### PR TITLE
Nginx Plus API plugin

### PR DESCRIPTION
**Pull request by Bugagazavr**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

Added Nginx Plus API input plugin https://github.com/influxdata/telegraf/issues/3867

* This plugin doesn't process *downstart*, *selected* fields for upstreams API because, nginx currently has invalid documentation for this fields

### CODE REVIEW

**Comment by glinton** [comment]
Before we review this pr, how is this plugin different from the current [nginx_plus](https://github.com/influxdata/telegraf/tree/1.8.1/plugins/inputs/nginx_plus) plugin, and can your changes be feasibly merged into that plugin?

**Comment by Bugagazavr** [comment]
@glinton 

Nginx Plus plugin collects metrics from `/status` endpoint which returns all possible data and deprecated ( https://www.nginx.com/blog/transitioning-to-nginx-plus-api-configuration-monitoring/ ).

This plugin uses many API endpoints and collects ( currently ) similar data. In future this plugin allow to collect more metrics from API.

Also changed [measurement names](https://github.com/influxdata/telegraf/blob/821b706c816771bf9d2a339862e638767bbaa3b7/plugins/inputs/nginx_plus_api/README.md#migration-from-nginx-plus-status-input-plugin)

Currently data models are similar ( except downstart, selected fields ) and possible to migrate data from Nginx Plus to this plugin.

**Comment by Bugagazavr** [comment]
@glinton Answer on your question about merge, yes this is possible. But i prefer to not do this, because, in future some API responses can be changed ( more fields, field type changes ).

**Comment by Bugagazavr** [comment]
@danielnelson done

**Comment by glinton** [comment]
Thanks, looks great!

**Pull request merged**
