### PR TITLE
Automatically generate field names for HAProxy from columns in stats CSV

### PR DESCRIPTION
**Pull request by G-regL**
Automatically generate  field names for HAProxy from columns in stats CSV, instead of manually looping through to find metrics.

This will allow newly added metrics in the stats page to be sent through Telegraf without changing anything.

Is follow-up to #1179.

### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sparrc** [comment]
Actually I'm just going to close this PR because I can see that it's still a breaking change. Unfortunately I don't think that this adds enough to justify breaking all current users of the plugin. If there are missing metrics then they will have to be added manuyally.

**Comment by G-regL** [comment]
While I agree this in it's current form, this is a breaking change, but would you accept it if I returned the field names to match the existing format?

The primary reason for this PR is to expand on the list of metrics that this plugin collects, as those currently being gathered seemed to have been cherry-picked from the large number available in the stats pages. 

The renaming of the metrics was done for simplicity and to stay in line with the vendors own stats names, but I'm not married to the idea and if keeping the existing name for metrics already being collected will mean this gets accepted then I'm fine with that. I'll just do a search/replace on the first row (field names) to keep them the same.

**Comment by sparrc** [comment]
yes, in order to be accepted you need to:

1. write a README explaining all metrics gathered
2. document the aggregated metrics that you are counting up and explain what they are and why you are aggregating them
3. keep existing metric names the same

**Comment by G-regL** [comment]
Given the discussion in #2318, what do you want to do with this PR? Do you plan to merge this one, or that one? Or neither?

**Comment by sparrc** [comment]
most likely #2323

**Comment by G-regL** [comment]
Looking over it, I agree that it's a more comprehensive PR. I'll submit a separate PR for the aggregated server status counters from here once that one gets merged.

**Pull request closed without merging**
