### PR TITLE
chore(log): Restructure and cleanup logging code

### LINKED ISSUE #10212: Adjust telegraf.Logger to be easy to use in whole codebase
## Feature Request

- Adjust `telegraf.Logger` to be easy to use in whole codebase, not only inside `plugins` (`aggregators`, `inputs`, `outputs`, `parsers` and `processors`).
- Moreover, `telegraf.Logger` should be also injected for `plugins/serializers` (as it is for other type of plugins).
- https://github.com/influxdata/telegraf/blob/master/docs/developers/LOGGING.md will need to be adjusted to reflect implemented changes.
- Forbids using `"log"` in whole codebase (by remove rule in `.golangci.yml` introduced in https://github.com/influxdata/telegraf/pull/10191 )

### LINKED ISSUE #14144: windows: As a service, telegraf logs do not capture error message on failure
### Relevant telegraf.conf

```toml
[[inputs.nvidia_smi]]
  bin_path = "C:\\Windows\\System32\\nvidia-smi.exe"
```

### Logs from Telegraf

```text
2023-10-19T06:31:47Z I! Starting Telegraf 1.28.2 brought to you by InfluxData the makers of InfluxDB
2023-10-19T06:31:47Z I! Available plugins: 240 inputs, 9 aggregators, 29 processors, 24 parsers, 59 outputs, 5 secret-stores
2023-10-19T06:31:47Z I! Loaded inputs: mem nvidia_smi system tail win_perf_counters
2023-10-19T06:31:47Z I! Loaded aggregators: 
2023-10-19T06:31:47Z I! Loaded processors: 
2023-10-19T06:31:47Z I! Loaded secretstores: 
2023-10-19T06:31:47Z I! Loaded outputs: influxdb
2023-10-19T06:31:47Z I! Tags enabled: redacted
2023-10-19T06:31:47Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"redacted", Flush Interval:10s
2023-10-19T06:31:47Z D! [agent] Initializing plugins
```

### System info

Telegraf 1.28.2, Windows 11

### Docker

_No response_

### Steps to reproduce

1. Install telegraf as service and configure telegraf.conf with [[inputs.nvidia_smi]] enabled.
2. On non-Nvidia equipped machines (w/o the nvidia-smi.exe file), start the telegraf service.
3. Attempt to stop the telegraf service.

### Expected behavior

With the inputs.nvidia_smi enabled in the config:

- For nvidia equipped system it should start and collects metrics normally.

- For non-nvidia equipped system, the nvidia-smi.exe is not found and the plugin should fail.
- Telegraf service should write error in the log file, indicating nvidia-smi.exe is not found and the plugin failed to load.
- Telegraf service should continue with other plugins and collects and sends metrics.
- Telegraf service should stop normally and logs relevant info when instructed to stop.

### Actual behavior

- For non-nvidia equipped system and the nvidia-smi.exe is not found.
- Telegraf service does not write error in the log file.
- With debug turned off, last entry in log is: _I! [agent] Config: Interval:10s, Quiet:false, Hostname:"<hostname>", Flush Interval:10s_
- With debug turned on, last entry in log is: _D! [agent] Initializing plugins._ No additional log entries are written.
- No metrics is collected or sent.
- When attempting to stop Telegraf service, an error is shown "_Windows could not stop the Telegraf Data Collector Service service on <host>. Error 1067: The process terminated unexpectedly._
- No additional stopping log entries are written.

### Additional info

We use the same config files and deploy to all workstations, some with nvidia cards, some don't. Previously with telegraf 1.17, this is fine for both type of workstations. Ones without a nvidia card will simply error on the plugin but still collects metrics. But since we've upgraded to 1.26 (and also tested latest 1.28), workstations without a nvidia card will show as if the telegraf has started without error (no error in log), but the actual service is hung and no metrics are collected/sent.

If a nvidia-smi.exe file is dropped into the c:\windows\system32\ location, the 1.2x telegraf service will runs, collects, sends, and stops normally (with error logged), just the same as 1.17 behaved. Even if the nvidia-smi.exe is a dummy 0 byte file. It appears telegraf can handle errors from plugins gracefully, but unable to handle file-not-found situation gracefully.

Also, with 1.2x, running telegraf from command line (with or without --debug): telegraf.exe --config 'c:\program files\telegraf\telegraf.conf', the log will correctly show "_E! [telegraf] Error running agent: could not initialize input inputs.nvidia_smi: nvidia-smi not found in "C:\\Windows\\System32\\nvidia-smi.exe" and not in PATH; please make sure nvidia-smi is installed and/or is in PATH_". But other plugins and metrics are still not collected/sent.

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

This PR moves all logging code into the `logger` package and simplifies the code. It also exposes all required functions in the `telegraf.Logger` interface to provide an abstraction for changing the underlying logging implementation. This is in preparation to provide more fine-grained logging as requested in #6584 or adding structured logging as requested in #8815.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #10212

### CODE REVIEW

**Comment by powersj** [comment]
FYI I accidently hit submit on the previous comment too soon, but I have updated it.

For the goshim test, I grabed https://github.com/ssoroka/rand and added some logging:

```diff
diff --git plugins/inputs/rand/rand.go plugins/inputs/rand/rand.go
index b5f6847..b3cf571 100644
--- plugins/inputs/rand/rand.go
+++ plugins/inputs/rand/rand.go
@@ -54,6 +54,10 @@ func (r *RandomNumberGenerator) Description() string {
 }
 
 func (r *RandomNumberGenerator) Gather(a telegraf.Accumulator) error {
+       r.Log.Error("error message")
+       r.Log.Warn("warn message")
+       r.Log.Info("info message")
+       r.Log.Debug("debug message")
        r.sendMetric(a)
        return nil
```

Build the plugin and used this config:

```toml
[agent]
  debug = true
  omit_hostname = true

[[inputs.execd]]
  command = ["/home/powersj/rand/rand", "--config", "/home/powersj/rand/plugin.conf"]
  signal = "none"

[[outputs.file]]
```

Which produced:

```
2024-04-26T16:30:17Z I! [inputs.execd] Starting process: /home/powersj/rand/rand [--config /home/powersj/rand/plugin.conf]
2024-04-26T16:30:18Z E! [inputs.execd] stderr: "2024/04/26 10:30:18 E! error message"
2024-04-26T16:30:18Z E! [inputs.execd] stderr: "2024/04/26 10:30:18 W! warn message"
2024-04-26T16:30:18Z E! [inputs.execd] stderr: "2024/04/26 10:30:18 I! info message"
2024-04-26T16:30:18Z E! [inputs.execd] stderr: "2024/04/26 10:30:18 D! debug message"
...
random value=7i 1714149026350162901
2024-04-26T16:30:27Z D! [outputs.file]  Wrote batch of 9 metrics in 64.99µs
2024-04-26T16:30:27Z D! [outputs.file]  Buffer fullness: 0 / 10000 metrics
```

This is the same as what I see from master currently.

**Comment by powersj** [comment]
Built and installed it as a service and still looks good.

Thanks!

**Comment by srebhan** [comment]
@powersj can you confirm that the last log line is now present in the eventlog?

**Comment by srebhan** [comment]
@DStrand1 I remove the RFFR label for now until @powersj had a chance to test the "last line is in eventlog" thing... Will let you know once this is good to finally go.

**Comment by powersj** [comment]
Here is my updated config:

```
[agent]
    debug = true
    logtarget = "eventlog"
    
[[inputs.cpu]]
[[outputs.file]]
```

Then in an admin powershell:

```powershell
> .\telegraf.exe --service install --config .\config.toml
> net stat telegraf
The Telegraf Data Collector Service service is starting.
The Telegraf Data Collector Service service was started successfully.

```

This is what I see in the Event Viewer:

image

I get the same with your branch or master.

## Executable By Hand

If I run the executable by hand with that same config, now all the messages go to the event log:

image

And this is the final message:

image

## Invalid Config

If I do the same with an invalid config, nothing new shows up in the event viewer and I get this message on the CLI:

```
PS C:\Users\Josh Powers\telegraf-srebhan> .\telegraf.exe --config .\config.toml
2024-05-08T20:47:04Z I! Loading config: .\config.toml
2024-05-08T20:47:04Z E! error loading config file .\config.toml: error parsing outpts, undefined but requested input: outpts
```

## Error in output

If I update the config like that in #14144 with:

```toml
[agent]
    debug = true
    logtarget = "eventlog"
    
[[inputs.cpu]]
[[outputs.file]]
[[inputs.nvidia_smi]]
  bin_path = "C:\\Windows\\System32\\nvidia-smi.exe"
```

The last message is:

image

As opposed to the expected:

```s
2024-05-08T20:50:08Z E! [telegraf] Error running agent: could not initialize input inputs.nvidia_smi: nvidia-smi not found in "C:\\Windows\\System32\\nvidia-smi.exe" and not in PATH; please make sure nvidia-smi is installed and/or is in PATH
```

Thoughts?

**Comment by srebhan** [comment]
@powersj I will remove the reference to #14144 then and need to investigate the issue further. Are you still good with the PR otherwise?

**Comment by powersj** [comment]
Yes!

**Review by DStrand1 — APPROVED** [review]
Looks great! Excited to see how this turns out

**Pull request merged**
