### PR TITLE
feat: dmesg regex collector

### PR DESCRIPTION
**Pull request by johnseekins**
- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary) (e.g. feat: or fix:)

This is a new plugin that lets us run regex matches against `dmesg` output and track the resultant counts. The idea here is a way to track the occurrence of particular messages in `dmesg`.

For example, if I wanted to know the number of times an OOM occurred in my system, I could look for a pattern like `.*oom_reaper.*|.*Out of memory.*` and count the results found in the ring buffer.

All values returned are, for all intents, counters.

Note: Currently, the regexp filters are compiled on every run of `Gather`, which seems inefficient to me, but I couldn't find any documentation on how to execute the compilation on initialization only.

### CODE REVIEW

**Comment by srebhan** [comment]
@johnseekins monitoring dmesg is a good idea. The question is only if we should have an own plugin for this or use the existing [`exec` plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/exec). There you can either get the real messages when using the [`grok` parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/grok) or write a small shell script that does the filtering.
Let's ask the core-developers what they think... @reimda, @powersj and thoughts?

**Comment by johnseekins** [comment]
> @johnseekins monitoring dmesg is a good idea. The question is only if we should have an own plugin for this or use the existing [`exec` plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/exec). There you can either get the real messages when using the [`grok` parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/grok) or write a small shell script that does the filtering. Let's ask the core-developers what they think... @reimda, @powersj and thoughts?

We actually currently do this with an `exec` plugin at work. And it works fine. But I thought it might be nice to make this into a built-in because it would reduce forking in the app and simplify config for others who might want to comb dmesg for data...

**Comment by srebhan** [comment]
@johnseekins I see. Let's see what InfluxData people have to say. :-)

**Comment by srebhan** [comment]
After thinking a bit more on the issue... How about you use [tail](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/tail) to monitor `/proc/kmsg` and use the [grok parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/grok) to extract the lines you want and then derive the count using the [basicstats aggregator](https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/basicstats)...

I know it sounds a bit complex at first, but my fear is a bit that after adding a `dmesg` input plugin people will request new features like get a rate of the events or the exact message or a part of the message etc duplicating the functionality already there...

**Comment by srebhan** [comment]
Hey @johnseekins I was talking to the Influx people recently and they are fine to add a separate dmesg plugin. However, I would like to broaden the scope of your implementation a bit and like to ask you for the following:

1. Directly read `/dev/kmsg` instead of calling the `dmesg` binary.
2. Maybe use [this library](https://pkg.go.dev/github.com/cirocosta/dmesg_exporter/kmsg#Parse) (or a similar one) to parse the lines.
3. Add optional `include_message`/`exclude_message` options to filter those messages (e.g. by the regexp you need).
4. Output all information such as (facility, severity, sequence number, message text, etc.) as metric tags/fields.

This allows everybody to handle and process those messages as they want. If you are only interested in the counts, you may want to use an aggregator or later aggregate in your database.

**Comment by johnseekins** [comment]
> Hey @johnseekins I was talking to the Influx people recently and they are fine to add a separate dmesg plugin. However, I would like to broaden the scope of your implementation a bit and like to ask you for the following:
> 
>     1. Directly read `/dev/kmsg` instead of calling the `dmesg` binary.
> 
>     2. Maybe use [this library](https://pkg.go.dev/github.com/cirocosta/dmesg_exporter/kmsg#Parse) (or a similar one) to parse the lines.
> 
>     3. Add optional `include_message`/`exclude_message` options to filter those messages (e.g. by the regexp you need).
> 
>     4. Output all information such as (facility, severity, sequence number, message text, etc.) as metric tags/fields.
> 
> 
> This allows everybody to handle and process those messages as they want. If you are only interested in the counts, you may want to use an aggregator or later aggregate in your database.
> 
> Does that sound OK for you?

That seems reasonable, but I'm not certain I'm going to have much time soon to work on this PR any more. If y'all have some ideas about how to improve it/make it more generic, that's great! But I don't have the expertise or time to really forge ahead with that work.

**Comment by srebhan** [comment]
@johnseekins sorry to hear... :-( Anyway, thanks for letting us know! Whenever you find some time to work on this, please feel free to reopen the PR or submit a new one...

**Pull request closed without merging**
