### PR TITLE
fix(inputs.opcua): add support for opcua datetime values

### LINKED ISSUE #12006: OPCUA should support DateTime values
### Use Case

I've discovered that the opcua plugin successfully collects datetime values, but these values fail to be serialized in `metric/metric.go`, and so are discarded.

Adding the following to `convertField` causes the values to be properly parsed (verifying with `--test`)
```go
	case time.Time:
		return v.String()
```

I'm happy to submit a PR or follow this work forward-- however I'm not sure why this is happening in the first place. I've configured the OPCUA values to be parsed as the string type in my telegraf.yaml:

```yaml
# Redacted snippet from config file. We have several 'nodes' configured and those all work just fine. 
[inputs.opcua]
  ...
  nodes = [
  {name="TimeValue", namespace="4", identifier_type="s", identifier="Path.To.Time"},
  ]
```

We're using influxdb as the output, but i've been testing from the repo tip using `--test` and can replicate that the datetime values are never returned, even thought the metric itself is 'OK' and the other values are being parsed. Output from the relevant section of the `--test` command (again, redacted.. happy to provide more details):

```
> MyHost,host=MyHostName,id=ns\=4;s\=Path.To.Time Quality="OK (0x0)" 1665621052000000000
> MyHost,host=MyHostName,id=ns\=4;s\=Path.To.Numerical.Value Numerical.Value=2.0999999046325684,Quality="OK (0x0)" 1665621052000000000
```

### Expected behavior

I expect it to forward the datetime values (perhaps as strings) to the outputs.

### Actual behavior

The values are never forwarded to the outputs.

### Additional info

It's possible this should be a bug report instead, my apologies for submitting it as a feature request if so.

### PR DESCRIPTION
**Pull request by vsinha**
Resolves #12006

This PR adds support for returning OPCUA DateTime values via the opc-ua input plugin. Prior to this PR, we silently drop those values.

## Details 
The `gopcua` library returns these values as the time.Time type, which telegraf doesn't handle in `metric.go:convertField`. To make the smallest change possible, we simply convert the datetime value to a string in the default golang format before returning the updated value.

## Example
Example telegraf.toml
```yaml
[inputs.opcua]
  # Authentication details redacted
  nodes = [
  {name="TimeEnded", namespace="4", identifier_type="s", identifier="TimeEnded"},
  ]
```

### Before: 
Notice the TimeEnded value has `Quality=OK` but the time value itself has failed to parse or be returned. This is because it falls into the `default` case in `metric.go:convertField`
```sh
❯ go run ./cmd/telegraf --config ~/telegraf-config-file.toml --test
...
2022-10-14T17:42:28Z D! [agent] Starting service inputs
> MACHINE123,host=HOST123,id=ns\=4;s\=TimeEnded Quality="OK (0x0)" 1665769360000000000
2022-10-14T17:42:40Z D! [agent] Stopping service inputs
2022-10-14T17:42:40Z D! [agent] Input channel closed
2022-10-14T17:42:40Z D! [agent] Stopped Successfully
```

### After:
We return the time as a string as intended
```sh
❯ go run ./cmd/telegraf --config ~/telegraf-config-file.toml --test
...
2022-10-14T17:46:49Z D! [agent] Starting service inputs
> MACHINE123,host=HOST123,id=ns\=4;s\=TimeEnded="2022-10-18 02:13:29.222 +0000 UTC",Quality="OK (0x0)" 1665769610000000000
2022-10-14T17:46:50Z D! [agent] Stopping service inputs
2022-10-14T17:46:50Z D! [agent] Input channel closed
2022-10-14T17:46:50Z D! [agent] Stopped Successfully
```

### CODE REVIEW

**Comment by MyaLongmire** [comment]
Thanks so much for this pr! I have 2 comments.

1. Will these new metrics cause backward compatibility issues for some users? 
2. Please sign the CLA

**Comment by R290** [comment]
I'm not sure how I can request changes without being a reviewer, so I'll just link to my commit here: https://github.com/R290/telegraf/commit/1b6bd07d020f0d6b97f73d9c7b60ec0db59a3632. 

Things I changed:
1. You can directly check for the `ua.TypeIDDateTime`
2. The `String()` method is meant for debugging, so I used `Format(time.RFC3339Nano)` to match the format commonly used by InfluxData. See also: https://pkg.go.dev/time#Time.String
3. Added a test case

@MyaLongmire previously all datetime tags would fail silently, even with debugging enabled. As far as I can see the impact is limited to some tags suddenly showing up. To be on the safe side, we can add a workaround flag which enables the datetime to string conversion.

**Comment by vsinha** [comment]
@R290 I added a commit with the changes you suggested.`make test` still passes.

**Review by MyaLongmire — APPROVED** [review]
Thanks for this pr! and thanks @R290 for your help :)

**Comment by vsinha** [comment]
Great! I'm still working on getting the CLA signed :) Will update here once that's taken care of

**Comment by vsinha** [comment]
!signed-cla

**Comment by vsinha** [comment]
@MyaLongmire is there something special i have to do to make the circleci pipeline succeed? 
image

**Comment by MyaLongmire** [comment]
I will try closing and reopening the pr as sometimes that can retrigger the ci.

**Comment by vsinha** [comment]
Doesn't look like that worked :(

**Comment by LarsStegman** [comment]
Because of my merged PR, there is a conflict. The logic for reading new values has been moved [here](https://github.com/influxdata/telegraf/blob/master/plugins/common/opcua/input/input_client.go#L351)

**Comment by MyaLongmire** [comment]
@vsinha It says it couldn't find a yaml file but all the ci tests ran. I have no idea why this is happening but will look into it.

**Comment by vsinha** [comment]
I can open a new PR on top of @LarsStegman's refactored plugin if that would be easier? (congrats on getting that merged btw Lars)

**Comment by vsinha** [comment]
Uh oh i shouldn't've merged

**Comment by vsinha** [comment]
@MyaLongmire i just reopened the PR in #12101

**Pull request closed without merging**
