### PR TITLE
Detect changes to config and reload telegraf (copy of pr #8529)

### LINKED ISSUE #7187: Telegraf watch and restart with new configuration file
## Feature Request

Telegraf should watch and restart with new configuration file

### Proposal:

Telegraf watch and restart with new configuration file

### Current behavior:
If a new config file is placed in the same place where telegraf is running, the only way of picking up the changes is either to restart the process or sending SIGHUP signal

### Desired behavior:

Telegraf making a md5 checksum of the whole config file once it's fully templated out and then trying to template it out every 10/30/60 seconds to see if something changed. If the md5 checksum has changed, then trigger a restart 

### Use case: 

This would be very useful in a container environment because config files can be updated very often and it would be. and it's very easy to run hundreds/thousands of telegraf so the more automation we have the better

### PR DESCRIPTION
**Pull request by sspaink**
resolves #7187

This feature was thought to be already supported, but has now made clear that it isn't and is required for another project effort. To help get this pull request ready quicker I've taken it over to resolve merge conflicts and use the latest [influxdata/tail](https://github.com/influxdata/tail) now that the fix has been merged. This pr still needs to be tested and reviewed to make sure this is the best approach. I also didn't copy over the windows specific changes because it wasn't obvious why they were necessary, see the original pull request #8529 for more details.

Lots of kudos to @vlastahajek for the original pr and the [fix to the tail repo](https://github.com/influxdata/tail/pull/9).

### CODE REVIEW

**Comment by sspaink** [comment]
@wojciechka, @ssoroka Are you able to take the artifacts posted by the Telegraf Tiger and see if this works for you? I am not entirely sure what the best way to test it would be. If you can provide some steps on how to test it, I'd be happy to do it as well.

**Comment by wojciechka** [comment]
> @wojciechka, @ssoroka Are you able to take the artifacts posted by the Telegraf Tiger and see if this works for you? I am not entirely sure what the best way to test it would be. If you can provide some steps on how to test it, I'd be happy to do it as well.

Unfortunately this does not work inside Kubernetes pods that have their configurations mounted as secrets.

This is because the secrets are handled as symlinks to symlinks and this logic may not be detecting all of the underlying changes.

I can confirm that just using `--watch-config poll` or `--watch-config inotify` works in the simple case of this being a file, but not when this is a Kubernetes secret.

I have tried to reproduce it outside of Kubernetes, but could not reproduce the case where it does not work, it may be that the mounts are handled by Kubernetes.

Would it be possible to implement it by periodically reading the config file and comparing its contents and/or checksum? This could be something like `--compare-config 1m` to indicate the check should be made every minute.

**Comment by wojciechka** [comment]
After spending more time and testing both modes, I have verified that `--watch-config inotify` is working well with `telegraf-operator` - where `telegraf` is run inside Kubernetes and has its config mounted as a Kubernetes secret.


I have verified this in `kind` and a GKE cluster, so I am optimistic that it will run in any Kubernetes cluster.

**Review by ssoroka — APPROVED** [review]

**Comment by pszlazak** [comment]
Is there any plan to support remote config (over http)? If I try this option I get:
```
2021-12-07T14:40:53Z W! Cannot watch config http://xx.xx.xx.xx:8086/api/v2/telegrafs/aaaaaaaa: stat http://xx.xx.xx.xx:8086/api/v2/telegrafs/aaaaaaaa: no such file or directory
```

**Pull request merged**
