### PR TITLE
Phemmer snmp2

### PR DESCRIPTION
**Pull request by sparrc**

### CODE REVIEW

**Comment by sparrc** [comment]
@phemmer are you available to chat on Slack or Google hangouts?

**Comment by phemmer** [comment]
I could be. irc (freenode) is also an option.

**Comment by sparrc** [comment]
can you email me at cameron@influxdb.com and we can setup a time?

**Comment by sparrc** [comment]
or if you sign-in to Gopher Slack, I've already pinged you there

**Pull request closed without merging**
