### PR TITLE
Add Linux mips build

### PR DESCRIPTION
**Pull request by danielnelson**
https://github.com/influxdata/telegraf/issues/3096#issuecomment-513554121

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@broizter Can you this build and verify if it is working?
- [telegraf-1.12.0~f8d2d09c_linux_mips.tar.gz](https://37116-33258973-gh.circle-artifacts.com/0/build/linux/mips/telegraf-1.12.0~f8d2d09c_linux_mips.tar.gz)

**Comment by broizter** [comment]
@danielnelson Runs perfectly on my EdgeRouter 4!

**Comment by pekindenis** [comment]
> @broizter Can you this build and verify if it is working?
> 
> * [telegraf-1.12.0~f8d2d09c_linux_mips.tar.gz](https://37116-33258973-gh.circle-artifacts.com/0/build/linux/mips/telegraf-1.12.0~f8d2d09c_linux_mips.tar.gz)

@danielnelson , it is not working for me, i use "Asus RT-N-10U" router.
 I'm seeing this error: telegraf: line 1: syntax error: unexpected "("

my /proc/cpuinfo details:

- system type             : Broadcom BCM5357 chip rev 2 pkg 8
- processor               : 0
- cpu model               : MIPS 74K V4.9
- BogoMIPS                : 149.91
- wait instruction        : no
- microsecond timers      : yes
- tlb_entries             : 64
- extra interrupt vector  : no
- hardware watchpoint     : yes
- ASEs implemented        : mips16 dsp
- shadow register sets    : 1
- VCED exceptions         : not available
- VCEI exceptions         : not available
- unaligned_instructions  : 0
- dcache hits             : 2147483648
- dcache misses           : 0
- icache hits             : 2147483648
- icache misses           : 0
- instructions            : 2147483648

**Comment by danielnelson** [comment]
Have you tried both the latest mips and the mipsel builds on the releases page? 
https://github.com/influxdata/telegraf/releases/tag/1.12.4

**Comment by pekindenis** [comment]
> Have you tried both the latest mips and the mipsel builds on the releases page?
> https://github.com/influxdata/telegraf/releases/tag/1.12.4

@danielnelson Runs perfectly, i used the mipsel build instead mips. Thank you ! 👍

**Comment by neofit999** [comment]
@danielnelson I tried execute the telegraf-1.12.5_linux_mipsel.tar.gz build and caught error.

I use "D-link dir-320 router"  device
Proc info:
```
~ # cat /proc/cpuinfo
system type             : Ralink SoC
processor               : 0
cpu model               : MIPS 24K V4.12
BogoMIPS                : 238.59
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes
ASEs implemented        : mips16 dsp
VCED exceptions         : not available
VCEI exceptions         : not available
```

Error:

```
futexwakeup addr=0x4080454 returned -89
futexwakeup addr=0x4093258 returned -89
futexwakeup addr=0x4093258 returned -89
futexwakeup addr=0x4080454 returned -89
futexwakeup addr=0x4093258 returned -89
fatal error: unexpected signal during runtime execution
futexwakeup addr=0x4093258 returned -89
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
futexwakeup addr=0x4093258 returned -89
futexwakeup addr=0x4093258 returned -89
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violationfutexwakeup addr=0x4093258 returned -89
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x449a0]

runtime stack:
runtime.throw(0x239468e, 0x2a)
        /usr/local/go/src/runtime/panic.go:617 +0x60
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x5a8
runtime.futexwakeup(0x4093258, 0x1)
        /usr/local/go/src/runtime/os_linux.go:81 +0x8c
runtime.unlock(0x4093258)
        /usr/local/go/src/runtime/lock_futex.go:112 +0xcc
runtime.printunlock()
        /usr/local/go/src/runtime/print.go:80 +0x70
runtime.dopanic_m(0x44007e0, 0x47084, 0x445fe60, 0x47cf4)
        /usr/local/go/src/runtime/panic.go:794 +0xa8
runtime.fatalthrow.func1()
        /usr/local/go/src/runtime/panic.go:672 +0x6c
runtime.fatalthrow()
        /usr/local/go/src/runtime/panic.go:669 +0x48
runtime.throw(0x239468e, 0x2a)
        /usr/local/go/src/runtime/panic.go:617 +0x60
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x5a8
runtime.futexwakeup(0x4093258, 0x1)
        /usr/local/go/src/runtime/os_linux.go:81 +0x8c
runtime.unlock(0x4093258)
        /usr/local/go/src/runtime/lock_futex.go:112 +0xcc
runtime.printunlock()
        /usr/local/go/src/runtime/print.go:80 +0x70
runtime.throw.func1()
        /usr/local/go/src/runtime/panic.go:611 +0x88
runtime.throw(0x239468e, 0x2a)
        /usr/local/go/src/runtime/panic.go:610 +0x40
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x5a8
runtime.futexwakeup(0x4093258, 0x1)
        /usr/local/go/src/runtime/os_linux.go:81 +0x8c
runtime.unlock(0x4093258)
        /usr/local/go/src/runtime/lock_futex.go:112 +0xcc
runtime.printunlock()
futexwakeup addr=0x4093258 returned -89
fatal error: unexpected signal during runtime execution
stack trace unavailable
```
How to fix this error ?

**Comment by neofit999** [comment]
> @danielnelson I tried execute the telegraf-1.12.5_linux_mipsel.tar.gz build and caught error.
> 
> I use "D-link dir-320 router" device
> Proc info:
> 
> ```
> ~ # cat /proc/cpuinfo
> system type             : Ralink SoC
> processor               : 0
> cpu model               : MIPS 24K V4.12
> BogoMIPS                : 238.59
> wait instruction        : yes
> microsecond timers      : yes
> tlb_entries             : 32
> extra interrupt vector  : yes
> hardware watchpoint     : yes
> ASEs implemented        : mips16 dsp
> VCED exceptions         : not available
> VCEI exceptions         : not available
> ```
> 
> Error:
> 
> ```
> futexwakeup addr=0x4080454 returned -89
> futexwakeup addr=0x4093258 returned -89
> futexwakeup addr=0x4093258 returned -89
> futexwakeup addr=0x4080454 returned -89
> futexwakeup addr=0x4093258 returned -89
> fatal error: unexpected signal during runtime execution
> futexwakeup addr=0x4093258 returned -89
> fatal error: unexpected signal during runtime execution
> fatal error: unexpected signal during runtime execution
> futexwakeup addr=0x4093258 returned -89
> futexwakeup addr=0x4093258 returned -89
> fatal error: unexpected signal during runtime execution
> [signal SIGSEGV: segmentation violationfutexwakeup addr=0x4093258 returned -89
> fatal error: unexpected signal during runtime execution
> panic during panic
> [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x449a0]
> 
> runtime stack:
> runtime.throw(0x239468e, 0x2a)
>         /usr/local/go/src/runtime/panic.go:617 +0x60
> runtime.sigpanic()
>         /usr/local/go/src/runtime/signal_unix.go:374 +0x5a8
> runtime.futexwakeup(0x4093258, 0x1)
>         /usr/local/go/src/runtime/os_linux.go:81 +0x8c
> runtime.unlock(0x4093258)
>         /usr/local/go/src/runtime/lock_futex.go:112 +0xcc
> runtime.printunlock()
>         /usr/local/go/src/runtime/print.go:80 +0x70
> runtime.dopanic_m(0x44007e0, 0x47084, 0x445fe60, 0x47cf4)
>         /usr/local/go/src/runtime/panic.go:794 +0xa8
> runtime.fatalthrow.func1()
>         /usr/local/go/src/runtime/panic.go:672 +0x6c
> runtime.fatalthrow()
>         /usr/local/go/src/runtime/panic.go:669 +0x48
> runtime.throw(0x239468e, 0x2a)
>         /usr/local/go/src/runtime/panic.go:617 +0x60
> runtime.sigpanic()
>         /usr/local/go/src/runtime/signal_unix.go:374 +0x5a8
> runtime.futexwakeup(0x4093258, 0x1)
>         /usr/local/go/src/runtime/os_linux.go:81 +0x8c
> runtime.unlock(0x4093258)
>         /usr/local/go/src/runtime/lock_futex.go:112 +0xcc
> runtime.printunlock()
>         /usr/local/go/src/runtime/print.go:80 +0x70
> runtime.throw.func1()
>         /usr/local/go/src/runtime/panic.go:611 +0x88
> runtime.throw(0x239468e, 0x2a)
>         /usr/local/go/src/runtime/panic.go:610 +0x40
> runtime.sigpanic()
>         /usr/local/go/src/runtime/signal_unix.go:374 +0x5a8
> runtime.futexwakeup(0x4093258, 0x1)
>         /usr/local/go/src/runtime/os_linux.go:81 +0x8c
> runtime.unlock(0x4093258)
>         /usr/local/go/src/runtime/lock_futex.go:112 +0xcc
> runtime.printunlock()
> futexwakeup addr=0x4093258 returned -89
> fatal error: unexpected signal during runtime execution
> stack trace unavailable
> ```
> 
> How to fix this error ?

I solved it ! )) 
I updated firmware my router on openwrt last version and it works !!!

**Pull request merged**
