### PR TITLE
Fixed SQL Server Plugin issues #881

### PR DESCRIPTION
**Pull request by VasuBalakrishnan**

### CODE REVIEW

**Comment by sparrc** [comment]
LGTM, thanks @VasuBalakrishnan! Can you update the CHANGELOG too?

**Comment by sparrc** [comment]
thanks @VasuBalakrishnan!

**Comment by VasuBalakrishnan** [comment]
What is the ETA for 0.11.2 release? Would like to use this fix for a project that I'm working on

thanks

**Comment by sparrc** [comment]
0.11.1 was just released a few days ago so it will be a few weeks yet.

But there is also a nightly build repo, if you follow these instructions: https://docs.influxdata.com/influxdb/v0.10/introduction/installation/#ubuntu-debian you can set it up (just replace influxdb with telegraf, and stable with nightly)

**Comment by sparrc** [comment]
Sorry @VasuBalakrishnan but it appears that the nightly repo is out of date...I'll work with our support team and try to update it.

**Comment by VasuBalakrishnan** [comment]
thanks. 

Also is it possible for you to share the grafana dashboard that you've in the plugin's README file.

**Comment by sparrc** [comment]
Sorry I didn't write the plugin, you'd have to ask @zensqlmonitor for it

**Comment by VasuBalakrishnan** [comment]
Got it thanks

**Comment by VasuBalakrishnan** [comment]
Is the latest nightly build out there for me to download? - thanks

**Comment by sparrc** [comment]
yes, it's there now, use the instructions above, replacing "stable" with "nightly", and then you should be able to "apt-get update && apt-get install telegraf"

**Comment by VasuBalakrishnan** [comment]
I'm getting 403 errors when I try to download the nightly build. 

https://s3.amazonaws.com/telegraf/telegraf_nightly_amd64.deb

I can download the influxdb's nightly build, no issues there.

**Comment by sparrc** [comment]
OK, I know the repo is working so you could just use that, in the meantime please open an issue about the telegraf nightly deb links not working

**Pull request merged**
