### PR TITLE
Adding output plugin for Splunk

### PR DESCRIPTION
**Pull request by tmartin14**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

This output plugin will forward enable forwarding of metrics to Splunk.

### CODE REVIEW

**Comment by tmartin14** [comment]
will fix and resubmit.

**Comment by danielnelson** [comment]
closes #3176

**Comment by tmartin14** [comment]
would love to get a little help here.   The circleci tests continue to FAIL for a number of plugins.  Is this normal?     

Also, for this particular output plugin, I am getting the following error:
--- FAIL: TestSplunk (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x71356e]

Is there any known solution for this?   

Any assistance would be greatly appreciated.

**Comment by danielnelson** [comment]
Can you rebase or merge master?  There have been a lot of changes since you branched.

**Comment by tmartin14** [comment]
I got everything worked out, but yes I can rebase and pull down the latest master.    I'll close this PR and open a new one when I get to that point.

**Comment by tmartin14** [comment]
Updated with new pull request:  https://github.com/influxdata/telegraf/pull/4185

**Pull request closed without merging**
