### PR TITLE
optimizations to statsd plugin

### PR DESCRIPTION
**Pull request by agnivade**
- The buffer was being held longer than required. Releasing it immediately
after its used now.
- Replaced strings.Prefix check with simply checking the first index. Same
with strings.Contains

Microbenchmarks show good improvements:
```go
func BenchmarkPrefix(b *testing.B) {
  str := "-somerandomstring"
  for n := 0; n < b.N; n++ {
    // strings.HasPrefix(str, "-")
    _ = str[0] == '-'
  }
}
```
```
name      old time/op    new time/op    delta
Prefix-4    5.07ns ± 0%    0.40ns ±13%  -92.14%  (p=0.008 n=5+5)

name      old alloc/op   new alloc/op   delta
Prefix-4     0.00B          0.00B          ~     (all equal)

name      old allocs/op  new allocs/op  delta
Prefix-4      0.00           0.00          ~     (all equal)
```
- Optimized parseKeyValue function to replaced strings.Split() check
with a strings.IndexByte() and then using the strings from the index.

Microbenchmarks show good improvements:
```go
func BenchmarkSplitEqual(b *testing.B) {
  str := "key=value"
  for n := 0; n < b.N; n++ {
    // splitted := strings.Split(str, "=")
    // _ = splitted[0]
    // _ = splitted[1]
    ind := strings.IndexByte(str, '=')
    _ = str[:ind]
    _ = str[ind+1:]
  }
}
```
```
name          old time/op    new time/op    delta
SplitEqual-4     112ns ± 1%       5ns ± 0%   -95.92%  (p=0.000 n=5+4)

name          old alloc/op   new alloc/op   delta
SplitEqual-4     32.0B ± 0%      0.0B       -100.00%  (p=0.008 n=5+5)

name          old allocs/op  new allocs/op  delta
SplitEqual-4      1.00 ± 0%      0.00       -100.00%  (p=0.008 n=5+5)
```

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
~- [ ] Associated README.md updated.~
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by agnivade** [comment]
I am unable to see the logs of the circle ci failure. The spinner just keeps spinning.

**Comment by danielnelson** [comment]
The spinner is probably a temporary issue with circle, but I think you will need to rebase for the tests to pass due to an issue on the master branch that has been fixed.

**Comment by danielnelson** [comment]
What do the larger benchmarks show?

**Comment by agnivade** [comment]
Rebased latest master and pushed.

Larger benchmarks don't show any noticeable improvements. Most probably because the test runs several order of magnitude larger than the difference the improvements make.

```
name   old time/op    new time/op    delta
UDP-4     873ms ± 9%     850ms ± 5%   ~     (p=0.310 n=5+5)

name   old alloc/op   new alloc/op   delta
UDP-4     168MB ± 8%     165MB ± 6%   ~     (p=0.841 n=5+5)

name   old allocs/op  new allocs/op  delta
UDP-4     3.46M ± 9%     3.39M ± 7%   ~     (p=0.690 n=5+5)
```

Note: You can indeed see slight improvements. But because of the variance, the overall delta nullifies itself.

**Comment by danielnelson** [comment]
I don't want to bother with minor tweaks unless there is a noticeable improvement overall, since every change comes with the risk of introducing bugs.  I wonder if moving to a structure similar to socket_listener would be helpful?  @phemmer do you know how socket_listener compared to tcp/udp_listener?

**Comment by phemmer** [comment]
Performance wise? No, I never investigated.

**Comment by agnivade** [comment]
> I don't want to bother with minor tweaks unless there is a noticeable improvement overall, since every change comes with the risk of introducing bugs.

Aren't the unit tests written for this purpose ?

Bugs can and will always come. IMO that should not stop improvements to the code. Yes, the risk increases proportionally depending on the type of change. In this case, it's a couple of lines change which improves some string comparisons. We should add more tests and increase coverage if there are fears of introducing bugs.

At the end of the day, its an open source project. Feel free to close the PR.

**Comment by danielnelson** [comment]
> Aren't the unit tests written for this purpose ?

Yes, but realistically they are not and will never be sufficient to completely avoid bugs.  Also, many performance enhancements come at the expense of code readability, so I just want to be sure we are going to see a benefit.  Hope you understand in this case.

That said, I am going to apply the bufPool change from this PR.

**Comment by danielnelson** [comment]
4fab572b6bec4326d03d13c38095f89a44c02b53

**Pull request closed without merging**
