### PR TITLE
Redis input enhancement

### PR DESCRIPTION
**Pull request by burdandrei**
### Required for all PRs:

- [V] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [V] README.md updated (if adding a new plugin)

master_last_io_seconds_ago added
role tag renamed to replication_role

### CODE REVIEW

**Comment by burdandrei** [comment]
I propose to rename role tag to replication_role, cause now it just overwrites global role tag.
Example - i got environment in AWS with tags "AutoscalingGroup,app,role" meaning server role in application. I got "app=api, role=web", "app=api, role=cache". Chef is adding these tags as global tags. Means if i got couple of cache servers i receive now role=master and role=slave, but it's not what i need.


I think replication_role tag reflects the real redis related role.

**Comment by sparrc** [comment]
where exactly is your global "role" tag coming from? And would this problem affect other users?

**Comment by burdandrei** [comment]
My global role is coming from AWS tags,
i think other users are using role tag to tag their instances by role.

**Comment by kuchin** [comment]
+1

**Comment by l13t** [comment]
+1

**Comment by sparrc** [comment]
please rebase your changes and put a very clear `**Breaking Change**: redis input plugin` notice in the v1.0 changelog.

**Comment by burdandrei** [comment]
@sparrc done!

**Pull request merged**
