### PR TITLE
add support for pulling metrics from a dropwizard application

### PR DESCRIPTION
**Pull request by grange74**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
We have an open pull request for adding dropwizard as a parser, I think this is the best solution for dropwizard because it decouples the data format from the transport.  I encourage you to take a look at the pull request and comment on if it will work or any ideas you have:

https://github.com/influxdata/telegraf/pull/2846

I think the other half of this that we need is a http input plugin, similar to httpjson, but allowing any parser to be used:

https://github.com/influxdata/telegraf/issues/813
https://github.com/influxdata/telegraf/issues/1758#issuecomment-304418082

**Comment by grange74** [comment]
Ok, separating the data format from the transport makes a lot of sense.

I guess in the long term a lot of the input plugins could be converted into parsers as many of the ones I looked at to model off this off just pulled json (or xml) from a HTTP endpoint (e.g. influxdb, kapacitor, tomcat). 
Having a simple http input plugin that supports custom parsers and various forms of authentication would be nice.
Please let me know if there is anything that I can help with.

One feature that was implemented in this PR, was to skip Idle metrics. That doesn't sound like something that should go into a parser. Would you see this as a generic feature and if so where would it fit in?

**Comment by danielnelson** [comment]
For idle metrics, the best idea I have seen is the idea in #3388.

**Comment by danielnelson** [comment]
I'm not aware of anyone working on the generic http input plugin, it would probably be fairly similar to this pull request without the dropwizard code but using the Parser interface.  Would you be interested in helping with this?

**Comment by grange74** [comment]
Sure, i'd be happy to help with the "generic http input plugin". I had a quick look at some of the existing input plugins that implement the Parser interface (e.g. nsq_consumer) and they seem very straight forward. 

Given that there are already several http input plugins (i.e. http_listener, http_response, httpjson), what would you want this one called? just http or something else?

We can probably close this PR now and create a new issue to describe the new "generic http input plugin" to document the desired behaviour.

**Comment by danielnelson** [comment]
We can use https://github.com/influxdata/telegraf/issues/813 for tracking the issue.  I think we should just name it `http`.

**Pull request closed without merging**
