### PR TITLE
chore(inputs.modbus): Improve modbus error messages

### LINKED ISSUE #16112: feat(inputs.modbus) See Hosts on Errormessages
### Use Case

To get a meaningful errormessage I have to see which host generated an error on a modbus request.

### Expected behavior

Print the hostname if a request fails 

### Actual behavior

Only print the slaveID in the error message

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by SoeNorKle**
## Summary
If debugMode is off, I couldn't see which host the Error generated. Adding the hostname in the error messages makes thinks easier.

## Checklist
- [ x] No AI generated code was used in this PR

## Related issues

resolves #16112

### CODE REVIEW

**Comment by SoeNorKle** [comment]
!signed-cla

**Comment by DStrand1** [comment]
Thanks for the PR! Could you rename your first commit so that it passes the semantic checker? Thanks!

**Comment by SoeNorKle** [comment]
Hope it works now. First PR I'll do for telegraf :)

**Comment by SoeNorKle** [comment]
PR #16114 do what I want and has more messages enriched with controller-data

**Pull request closed without merging**
