### PR TITLE
Forwarded Records and Offline

### PR DESCRIPTION
**Pull request by tboggiano**
Corrected spelling of Forwarded Records and added correct state status of 6 for offline databses on permise

### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@tboggiano Can you remove the whitespace changes so that there will be less churn in the git history?

@m82labs Can you review?

**Comment by tboggiano** [comment]
I didn't take out the whitepsaces on purpose VSCode automatically removes them. I tried to manually put them back in already and it just removes them again.

**Comment by m82labs** [comment]
I ran all the queries and they all run fine. I would actually be fine with the whitespace changes if it's not a big deal. I confirmed the forwarded records metric returns values as well.

**Comment by m82labs** [comment]
@tboggiano are you able to build and test this on your system? I don't think the whitespace changes will cause trouble when the queries are actually ran through the plugin, but it would need to be tested. If you are unable to build, I can build it locally tonight and test it out.

**Comment by tboggiano** [comment]
@m82labs yes let me build it out and stick on a live server

**Comment by tboggiano** [comment]
Tested both and have data showing up in the dashboards.

**Comment by m82labs** [comment]
Thanks @tboggiano!

**Pull request merged**
