### PR TITLE
Output openTSDB HTTPS with basic auth

### PR DESCRIPTION
**Pull request by aarnaud**
### Required for all PRs:
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by aarnaud** [comment]
Hi,

Do you know why this pull request did not merged ?

**Comment by sparrc** [comment]
just haven't gotten to reviewing/merging it yet, I will try to slate it for the 1.3 release.

**Comment by sparrc** [comment]
thanks @aarnaud

**Comment by aarnaud** [comment]
thanks @sparrc ;-)

**Pull request merged**
