### PR TITLE
feat(inputs.diskio): Allow selecting devices by ID

### LINKED ISSUE #11685: diskio - specify disk not by dev but by id
### Use Case

`/dev/sda`-like devices are not persistent in linux, so after disk swapping in a bay gathered statistics can relate to completely another device.

It would be much smarter to use `/dev/disk/by-id` links, which persist, for example:

`/dev/disk/by-id/ata-ST3000VX010-2E4166_Z6A0D9N1`

### Expected behavior

```
[[inputs.diskio]]
  devices = ["/dev/disk/by-id/nvme-WDS100T1X0E-00AFY0_21086Q902252"]
```

### Actual behavior

```
[[inputs.diskio]]
  devices = ["nvme0n1"]
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by srebhan**
- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #11685 

This PR will try to resolve all given devices on Linux, i.e. follow the (potential) symlinks of each device to their native "name"/device file which is helpful when specifying disk-ids or uuids. Furthermore, the PR adds the WWID of disks as tag.

**Note:** All of the above will only work on Linux and only if there are **no wildcards** used!

### CODE REVIEW

**Comment by powersj** [comment]
I like it! What do we need to add the docs?

**Review by Hipska — APPROVED** [review]
Can this be tested somehow?

**Comment by powersj** [comment]
@srebhan I think all that is waiting is doc updates and now conflicts resolved

**Review by powersj — APPROVED** [review]
thanks!

**Pull request merged**
