### PR TITLE
Dont specify AWS credential chain, use default

### LINKED ISSUE #1078: AWS Cloudwatch Input Credentials
The credential chain being used for the AWS Cloudwatch input will cause issues for people when deploying on a EC2 instance.

Specifically, having the EC2RoleProvider be the first provide in the chain (https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cloudwatch/cloudwatch.go#L159) will force the credentials always use the IAM role when on EC2 with no ability to override the credentials by using the environment variables.

The Ec2RoleProvider should be the last role in the chain. This way, you simply do not provide the envvars and it will fall through to the IAM profile, but you can override it by supplying the proper environment variables.

### PR DESCRIPTION
**Pull request by sparrc**
closes #1078

### CODE REVIEW

**Comment by johnrengelman** [comment]
LGTM
any chance we could see a release for this soonish?

**Comment by sparrc** [comment]
0.13 will be released May 1st or 2nd, until then you can use the nightlies: https://influxdata.com/downloads/#telegraf

**Comment by johnrengelman** [comment]
Awesome. Just had another thought here too, we might want to allow for providing specific credentials for the plugin instead of relying on only the environment variables or IAM roles.

**Comment by sparrc** [comment]
we could do that, could you open a separate issue for that?

**Comment by johnrengelman** [comment]
Issue - https://github.com/influxdata/telegraf/issues/1085
PR - https://github.com/influxdata/telegraf/pull/1086

**Pull request merged**
