### PR TITLE
feat: add influx semantic commits checker, checks only last commit.

### PR DESCRIPTION
**Pull request by tysonkamp**
### Required for all PRs:

- [ N/A] Updated associated README.md.
- [ N/A] Wrote appropriate unit tests.
- [X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

This change unblocks https://github.com/influxdata/k8s-idpe/issues/5723

Introduce Influxdata semantic commit and PR text checker to allow removal of semantic-pull-requests github app.

### CODE REVIEW

**Review by reimda — CHANGES_REQUESTED** [review]
Hi @tysonkamp, thanks for working on CI for semantic commits across all the org repos.

We use semantic commit messages on master but we don't enforce them on PR branches, except to make sure that when we squash and merge, the commit to master has a semantic commit.

There are two cases to handle to make sure "squash and merge" makes a semantic commit on master. 1) If there are multiple commits in the branch, GH uses the PR title as the message of the squash commit, so we need to check that the PR title is a valid semantic commit message. 2) if there is only one commit in the PR, there is no squash needed, so when you "squash and merge" it doesn't actually squash. It ignores the PR title and just merges the single commit. In this case the PR commit message must be a semantic commit message.

Our community review process and branch management strategy drive the way we use semantic versioning. We're happy with our processes, so a replacement for our current CI step is going to need to work well with the existing process.

This PR needs some changes in order to work with the existing process. I don't think it does the two steps I described. I heard you and @powersj talked about this yesterday and you are planning to add an option to influxdata/validate-semantic-github-messages that does what we need.

If there's anything I can do to help, please let me know, here or on slack or zoom!

**Comment by tysonkamp** [comment]
@reimda thank you for the clear articulation of the domain.  Indeed I talked to @powersj and we distilled the requirement down to this, which I think is identical to your statement.  Can you please confirm and assuming we're aligned I will implement this strategy as a configuration option in the semantic validator.

Optional logic for Telegraf team:
If there is one commit, check only the commit message and not the PR title
If there is > 1 commit,  check only the PR title

**Comment by reimda** [comment]
> Optional logic for Telegraf team:
> If there is one commit, check only the commit message and not the PR title
> If there is > 1 commit, check only the PR title

That should do it.

Since this workflow is for PRs that target master, we should add an event filter. We don't want it to run, for example, on release branches. You can filter the pull_request event by using a 'branches' line:

```yaml
on:
  pull_request:
    branches:
      - master # branch the PR will be merged to
```

**Comment by powersj** [comment]
@tysonkamp looks like your semantic PR checker is happy with this PR. Are we good to review and merge?

**Comment by tysonkamp** [comment]
I'd be delighted if it was merged.  Let me know if there's anything I should do.

**Comment by tysonkamp** [comment]
Checked in the condition to run when merging to master only.  LG2M, semantics checker passed.  Others pending.

**Review by reimda — APPROVED** [review]

**Pull request merged**
