### PR TITLE
Update vendoring to dep from gdm

### PR DESCRIPTION
**Pull request by goller**
- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

Connect #3394

This PR changes Telegraf's vendoring from `gdm` to `dep`  Dep is getting closer and closer to be ready to go (see https://github.com/golang/dep#current-status) 

To generate the dep files (Gopkg.lock and .toml) I used deps automatic conversion from the `godep` vendoring solution.  

Gdm's Godep file is similar to godeps.  Here is a python program I wrote to convert gdm's Godep to godep's format:

```python
#!/usr/bin/env python
import json

with open('Godeps') as godeps:
    conversion = {
        "ImportPath": "github.com/tools/godep",
	"GoVersion": "go1.9",
	"GodepVersion": "v74",
	"Deps": []
    }
    deps = godeps.readlines()
    for dep in deps:
        package, sha = dep.split()
        conversion["Deps"].append({
            "ImportPath": package,
            "Rev": sha
        })

    print(json.dumps(conversion, indent=4))
```

... and the shell script ...

```sh
python convert.py > howdy
rm Godeps           # the godeps vendoring uses a Godeps directory
mkdir Godeps
mv howdy Godeps/Godeps.json
dep init -v         # initializes the vendoring directory using Godeps/Godeps.json
dep ensure          # ensures all files are in the vendor directory
dep status          # status of the vendoring... pretty interesting.
```

There are other details that this PR should have

- [ ] Probably update .gitignore to ignore vendor
- [ ] Possibly cache the vendoring for circle ( https://circleci.com/docs/1.0/how-cache-works/#what-is-cached )
- [ ] Understand why the Gopkg.toml has far far far fewer entries than the lock.

### CODE REVIEW

**Comment by crazy-canux** [comment]
Looks good.
Gdm will never make succeed.
When can I use dep?

**Comment by smyrman** [comment]
> Understand why the Gopkg.toml has far far far fewer entries than the lock.

This is normal. The Gopkg.toml gives _constrains_ to `dep ensure -u`, and nothing more. It doesn't need to contain a single entry if there is something that doesn't just work, e.g. something with breaking changes.

**Comment by goller** [comment]
@smyrman Do you have some links you could share about that?  I'd love to read up to make sure I understand.

**Comment by smyrman** [comment]
The statement above is based on us having used the tool for various projects for the last several months. Our `Gopkg.toml` files are always very short, and always hand-edited to contain the most basic constraints only. You can put more constraints if you wish, but it's not needed to generate a valid lockfile which is automatically kept up to date based on code changes. This separates it massively from other tools such as e.g. `glide`, and makes it a lot more convenient to use.

Please refer to the official documentation: https://golang.github.io/dep/docs/Gopkg.toml.html

**Pull request closed without merging**
