### PR TITLE
ipmi_sensor: allow @ symbol in password

### PR DESCRIPTION
**Pull request by vtg**
### Required for all PRs:

- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/)

### CODE REVIEW

**Comment by danielnelson** [comment]
Looks great, and special thanks for adding the unittest.  Can you sign the CLA and add this to changelog and we can merge.

**Comment by vtg** [comment]
No problem. Should be signed now

**Comment by danielnelson** [comment]
I still not seeing you in our CLA list, can you resign it?

**Comment by vtg** [comment]
done

**Comment by danielnelson** [comment]
Thanks!

**Pull request merged**
