### PR TITLE
Do not skip good quality nodes after a bad quality node is encountered

### LINKED ISSUE #8871: [inputs.opcua] Error in plugin: Get Data Failed: Status not OK:  Bad (0x80000000)
### Relevant telegraf.conf:
N/A
```toml

```

### System info:

Windows Server 2012 R2 - Telegraf 1.17

### Docker

N/A

### Steps to reproduce:

1. Using an OPCUA server (Kepware) on my side, create at least 2 variables. 
2. First, both with Good quality to check plugin works fine. 
3. After this check, force one of them to Bad quality.

### Expected behavior:

Point with Good quality should be read and stored in InfluxDB. Point with Bad quality, not.

### Actual behavior:

[inputs.opcua] Error in plugin: Get Data Failed: Status not OK:  Bad (0x80000000) 
Error in log file. 
None of configured points is stored in influxDB, at least, point with Good quality should be stored.

### Additional info:

[inputs.opcua] Error in plugin: Get Data Failed: Status not OK:  Bad (0x80000000)

### PR DESCRIPTION
**Pull request by R290**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.

Resolves #8871, relates to #9523 and #9524

Properly handles nodes with a bad quality. Instead of returning the error, it is now only passed to the logger. Any following good quality nodes are no longer skipped.

### CODE REVIEW

**Review by sspaink — APPROVED** [review]
lgtm!

**Review by helenosheaa — APPROVED** [review]
Looks good, thanks for the PR

**Comment by bingblackbean** [comment]
is there any update about this topic?
I have exact the same issue which is one bad status will prevent telegraf opc ua plugin to send all nodes even most of them are in good status.

**Comment by R290** [comment]
The PR has been merged, so you have the following options:

- Use a nightly build: https://github.com/influxdata/telegraf#nightly-builds
- Compile from source: https://github.com/influxdata/telegraf#from-source
- Wait for the next telegraf release

**Pull request merged**
