### PR TITLE
Adding Database IO Tempdb per Azure DB collection, Fixing PerfmonV2 collection for on-prem

### PR DESCRIPTION
**Pull request by denzilribeiro**
### Required for all PRs:

- [X ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [] Has appropriate unit tests.

Datababase IO changes
Today on Azure SQL DB there was a bug where left outer join from virtual file stats and database_files was only on file_id. Tempdb was exposed on virtual file stats, but not in Database files. On Azure SQL DB have to use tempdb.sys.database_files. In addition each Azure SQL DB has its own tempdb so needed to add Database_id/File ID to be able to distinguish so that reporting can be done by Logical Server + Azure DB + database_id.  If you just looked at tempdb for a logical server would get multiple tempdb's belonging to different Azure SQL DB's as the logical server construct is just that a placeholder logical server not actual physical server.
Also corrected bug introduced earlier

PerfmonV2 Fix for [#7164](https://github.com/influxdata/telegraf/issues/7164)

### CODE REVIEW

**Comment by denzilribeiro** [comment]
@Trovalo  overlapped with your PR [#7161](https://github.com/influxdata/telegraf/pull/7161) just submitted as I was in process of submitting didn't realize - can you take a look at this one and see if addresses issues as I also added additional logic to pull tempdb IO for Azure SQL so is a bit more than the bug fix

**Comment by Trovalo** [comment]
I will have a look at it in a few minutes.

But I found a bigger problem while testing the whole plugin on multiple versions earlier.
While testing on SQL 2012. SQL 2019 and Azure SQL DB, I get an error
>I! Invalid column name 'physical_database_name'.
E! [inputs.sqlserver] Error in plugin: mssql: Invalid column name 'physical_database_name'.

It is caused by the latest changes (January) made to the query and not yet published (in fact those are not in telegraf 1.13.4).
The field [physical_database_name] exists only in azure SQL DB and SQL Server 2019. Any other version will fail to gather the metrics due to a compile error.

I'm opening an issue now, the best solution probably is to add dynamic SQL, so it is not validated by SQL Server until it has to execute it

**Comment by denzilribeiro** [comment]
I will add the dynamic SQL and resubmit shortly

**Comment by denzilribeiro** [comment]
@Trovalo  - actually go ahead and open an issue for that as is in a different part not IO :) misunderstood

**Comment by Trovalo** [comment]
I did it few minutes ago
https://github.com/influxdata/telegraf/issues/7164

**Comment by denzilribeiro** [comment]
@Trovalo - one last validation - pushed commit for the Perfmon counters too

**Comment by Trovalo** [comment]
I will run the tests tomorrow morning and let you know

**Pull request merged**
