### PR TITLE
Bump prometheus dependency to v2.21.0

### PR DESCRIPTION
**Pull request by pmalek-sumo**
Bump Prometeus dependency to `v2.21.0`.

In order to achieve this the following `go get` was performed:

```
go get github.com/prometheus/prometheus@e83ef207b6c2398919b69cd87d2693cfc2fb4127
```

The reason for this is that Prometheus doesn't follow Go module semver conventions (its module should have a `/v2` suffix but there's no intention in doing this - https://github.com/prometheus/prometheus/issues/7991#issuecomment-701298893).

The remaining changes are coming from a change in PB files from `github.com/prometheus/prometheus/prompb` from [1] to [2] via [PR][3]

[1]: https://github.com/prometheus/prometheus/blame/375ad1185c128e947dbf75000024088c504a0b14/prompb/remote.pb.go#L24
[2]: https://github.com/prometheus/prometheus/blame/3ad25a6dc3d94d09f94de00fe3ef9e374007b131/prompb/remote.pb.go#L65
[3]: https://github.com/prometheus/prometheus/pull/5075

## Motivation

Apart from being up to date the motivation it will allow other projects to use telegraf package's e.g. `github.com/influxdata/telegraf/agent`.

The use case where I hit this was when I was trying to import `github.com/influxdata/telegraf/agent` from within https://github.com/open-telemetry/opentelemetry-collector-contrib which gave me the following errors:

```
GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/otelcontribcol_unstable_darwin_amd64 \
                -ldflags "-X github.com/open-telemetry/opentelemetry-collector-contrib/internal/version.GitHash=63b2f339 -X github.com/open-telemetry/opentelemetry-collector-contrib/internal/version.Version=v0.19.0 -X go.opentelemetry.io/collector/internal/version.BuildType=release" -tags enable_unstable ./cmd/otelcontribcol
go: finding module for package github.com/prometheus/prometheus/discovery/install
go: finding module for package github.com/Azure/azure-sdk-for-go/arm/compute
go: finding module for package github.com/Azure/azure-sdk-for-go/arm/network
../../../.gvm/pkgsets/go1.15.7/global/pkg/mod/github.com/prometheus/prometheus@v2.5.0+incompatible/discovery/azure/azure.go:24:2: module github.com/Azure/azure-sdk-for-go@latest found (v51.0.0+incompatible), but does not contain package github.com/Azure/azure-sdk-for-go/arm/compute
../../../.gvm/pkgsets/go1.15.7/global/pkg/mod/github.com/prometheus/prometheus@v2.5.0+incompatible/discovery/azure/azure.go:25:2: module github.com/Azure/azure-sdk-for-go@latest found (v51.0.0+incompatible), but does not contain package github.com/Azure/azure-sdk-for-go/arm/network
../../../.gvm/pkgsets/go1.15.7/global/pkg/mod/github.com/prometheus/prometheus@v2.5.0+incompatible/discovery/consul/consul.go:27:2: ambiguous import: found package github.com/hashicorp/consul/api in multiple modules:
        github.com/hashicorp/consul v1.2.1 (/Users/DUMMY/.gvm/pkgsets/go1.15.7/global/pkg/mod/github.com/hashicorp/consul@v1.2.1/api)
        github.com/hashicorp/consul/api v1.7.0 (/Users/DUMMY/.gvm/pkgsets/go1.15.7/global/pkg/mod/github.com/hashicorp/consul/api@v1.7.0)
../../../.gvm/pkgsets/go1.15.7/global/pkg/mod/go.opentelemetry.io/collector@v0.19.0/receiver/prometheusreceiver/factory.go:22:2: module github.com/prometheus/prometheus@latest found (v2.5.0+incompatible), but does not contain package github.com/prometheus/prometheus/discovery/install
```

Please note the `v2.5.0+incompatible` that is required as of now (which doesn't understand Go modules hence most of the problems listed above).

### CODE REVIEW

**Comment by pmalek-sumo** [comment]
Ok so unfortunately this makes the tests to fail because of an assertion in `google.golang.org/protobuf@v1.24.0`

https://github.com/protocolbuffers/protobuf-go/blob/v1.24.0/internal/impl/legacy_message.go#L136

```
panic: mismatching message name: got k8s.io.kubernetes.pkg.watch.versioned.Event, want github.com/ericchiang.k8s.watch.versioned.Event

goroutine 1 [running]:
google.golang.org/protobuf/internal/impl.legacyLoadMessageDesc(0x11cec20, 0x1043b60, 0x10ae672, 0x2f, 0x0, 0xa2b100)
	/go/pkg/mod/google.golang.org/protobuf@v1.24.0/internal/impl/legacy_message.go:136 +0xa38
google.golang.org/protobuf/internal/impl.legacyLoadMessageInfo(0x11cec20, 0x1043b60, 0x10ae672, 0x2f, 0xc0001b1e60)
	/go/pkg/mod/google.golang.org/protobuf@v1.24.0/internal/impl/legacy_message.go:48 +0xf3
google.golang.org/protobuf/internal/impl.Export.LegacyMessageTypeOf(0x11bbf40, 0x0, 0x10ae672, 0x2f, 0xc000224410, 0xc0002ac000)
	/go/pkg/mod/google.golang.org/protobuf@v1.24.0/internal/impl/legacy_export.go:33 +0xd6
github.com/golang/protobuf/proto.RegisterType(0x11bbf40, 0x0, 0x10ae672, 0x2f)
	/go/pkg/mod/github.com/golang/protobuf@v1.4.2/proto/registry.go:186 +0x6a
github.com/ericchiang/k8s/watch/versioned.init.0()
	/go/pkg/mod/github.com/ericchiang/k8s@v1.2.0/watch/versioned/generated.pb.go:70 +0x59
FAIL	github.com/influxdata/telegraf/plugins/inputs/prometheus	0.037s
```

**Comment by sspaink** [comment]
@pmalek-sumo Thank you for this pr, I've updated the Kubernetes go client in this pr #8937 so the failure in the tests you were getting should be resolvable now.

**Comment by pmalek-sumo** [comment]
Thanks @sspaink ! It seems the patch is now clean to apply.

**Review by sspaink — APPROVED** [review]
Looks good!

**Pull request merged**
