### PR TITLE
inputs: add syncthing

### PR DESCRIPTION
**Pull request by blockloop**
This adds an input for [Syncthing REST API](https://docs.syncthing.net/dev/rest.html).
It creates two measurements described in detail in the README. I would like to improve
on this over time as there is much more information that would be useful, but for now
I think this covers the major parts. We can identify if a device/folder is "Out of sync".

### syncthing_folder

Tags:
 * `id` - the folder ID
 * `label` - the label (name) you have assigned to the folder
 * `path` - the sync path on the local filesystem

Fields: 
 * `paused` - if the folder is paused
 * `needed` - how many files are needed to be in sync

### syncthing_device

Tags:
 * `device_id` - the device id that is connected
 * `name` - the name of the connected device 

Fields:
 * `address` - the IP address of the connected device
 * `client_version` - the version of Syncthing that the connected device is using
 * `connected` - if the device is connected
 * `crypto` - which version of TLS the device is using for encryption
 * `in_bytes_total` - how many bytes have been received by this device
 * `out_bytes_total` - how many bytes have been sent to this device
 * `paused` - if the device connection has been paused

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by mhall119** [comment]
Will the `syncthing_folder` measurement have a different `path` for every sync'd folder, including subfolders? Or just the top-level ones?  If it's every folder this may result in high cardinality in InfluxDB

**Comment by blockloop** [comment]
> Will the `syncthing_folder` measurement have a different `path` for every sync'd folder, including subfolders? Or just the top-level ones? If it's every folder this may result in high cardinality in InfluxDB

Only the top-level folder that is being synced [see more here](https://docs.syncthing.net/rest/system-config-get.html)

**Comment by blockloop** [comment]
@sjwang90 any chance of getting this merged?

**Comment by sjwang90** [comment]
@blockloop Thanks for the contribution and sorry for the delay! How does this compare to https://github.com/influxdata/telegraf/pull/7176? We had that PR open for awhile and were hoping to have it added to the [list of external plugins](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md).

Would this be a reasonable route for your Syncthing input plugin?

**Comment by blockloop** [comment]
> @blockloop Thanks for the contribution and sorry for the delay! How does this compare to #7176? We had that PR open for awhile and were hoping to have it added to the [list of external plugins](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md).
> 
> Would this be a reasonable route for your Syncthing input plugin?

Ah yes. I didn't know that was already opened :grimacing:

**Comment by blockloop** [comment]
Closing in favor of #7176

**Pull request closed without merging**
