### PR TITLE
Support for custom pool names

### PR DESCRIPTION
**Pull request by imaben**
### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sparrc** [comment]
why did you put the pool name at the end of an `@` at the end of the url? is this some sort of common pattern?

**Comment by imaben** [comment]
There are many times when you need to customize the pool name，Do you have any good advice？

**Comment by sparrc** [comment]
My question is about why you chose this particular way of configuring it. Please explain why you have decided to configure it in this way and give an example of it being configured this way elsewhere.

Putting an `@<string>` at the end of a URL seems odd to me.

**Comment by imaben** [comment]
No, I just think it can be compatible with the old version, and this is highly unlikely that the `@` in the URL.

**Comment by sparrc** [comment]
in that case you have two options:

1. if phpfpm has a customary way of representing the pool name in the URL, then use that (and link to documentation)
2. create a normal configuration option that would be applied to all URLs.

**Comment by imaben** [comment]
Got it, thank you！

**Pull request closed without merging**
