### PR TITLE
Add GCP Stackdriver output plugin

### PR DESCRIPTION
**Pull request by jamesmaidment**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

Adds Google Stackdriver as an output for telegraf metric data, saved as a custom metric in Stackdriver

### CODE REVIEW

**Comment by jamesmaidment** [comment]
@danielnelson having issues with the circleci build, seems like its running on the 1.0 circle instead of 2.0.. can you advise?

**Comment by danielnelson** [comment]
I'm not sure what is going on here... looks like a circleci bug.  I manually rebuilt the last 2.0 build, maybe that will unstick it.  Maybe try adding another commit `git commit --allow-empty` or such?

**Comment by jamesmaidment** [comment]
Sure thing will try that... for context I got this email from Circle CI about that time:
```
Hi James,

GitHub told us that you no longer have access to influxdata/telegraf. We mirror GitHub's permissions, so we've unfollowed you from the project on CircleCI. If you were the last follower on the project, then we may have stopped building!

This should only happen if you were removed as a collaborator on GitHub, but sometimes projects are erroneously revoked. If that's the case, you just need to refollow the project from https://circleci.com/gh/influxdata/telegraf.

Please let us know if you think your access was removed erroneously. We'll pass the info on to GitHub and improve our workarounds.
```

**Comment by danielnelson** [comment]
CircleCI is still being weird, let's try opening a new pull request.

**Pull request closed without merging**
