### PR TITLE
Fixes change in Kafka consumer input plugin

### PR DESCRIPTION
**Pull request by Tagnard**
This fixes an issue with kafka_consumer input plugin that broke due to a [change](https://github.com/wvanbergen/kafka/commit/45aaec2261212048bd6a66d91597e253119fbc7e) in [wvanbergen/kafka](https://github.com/wvanbergen/kafka).

### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by Tagnard** [comment]
This build fails because it doesn't check agains the master.

**Comment by sparrc** [comment]
why did you close this? you just need to change the commit hash in the `Godeps` file

**Comment by Tagnard** [comment]
Sorry, I am new to pull requests and I thought i did something wrong.

I updated the godeps.

**Comment by sparrc** [comment]
thanks @Tagnard

**Pull request merged**
