### PR TITLE
add activemq input plugin

### PR DESCRIPTION
**Pull request by luoxiaojun1992**
### Required for all PRs:

- [x] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sparrc** [comment]
@luoxiaojun1992 can you explain why the jolokia plugin would not work for activemq?

**Comment by luoxiaojun1992** [comment]
@sparrc It's not convenient. The restful api is more useful.

**Comment by sparrc** [comment]
please provide more details, what do you mean by "more useful"? What is lacking in the jolokia plugin?

**Comment by sparrc** [comment]
closing for lack of updates. AFAICT the jolokia plugin already has the capability to pull activemq metrics. If you reopen please provide a full description and reasoning for why we should accept this plugin and what features is provides that the jolokia plugin doesn't.

**Pull request closed without merging**
