### PR TITLE
Make input/docker work with windows

### PR DESCRIPTION
**Pull request by hoerup**
Fix: #4666
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
At one point we moved the version forward to 1.24, but it was pulled back to version 1.21 since it broke connections to the version of Docker included with Ubuntu 14. (#4434)  This version of Ubuntu, while somewhat old, is still on extended support until midway though 2022, so I'd still like to keep it working.

What would be ideal is if we can find a way to set the variable to work with both versions, perhaps using the api version negotation in the docker library.  If that is impossible, we could make this user configurable but I'd first like an attempt to be made to find a way where that is not required.

**Comment by hoerup** [comment]
I haven't tested it yet, but would it be possible to, even though non-versioned requests are deprecated, first do a version-less client lookup to dockers "/version" api endpoint to discover min/max supported version- and then use that to determine the right api version for the rest of the session ?

**Comment by danielnelson** [comment]
I think this would probably work, if not I imagine there is another way we can make this work with one of the version negotiation functions.  We should test any change against the version included with Ubuntu 14 before merging to be sure.

**Comment by hoerup** [comment]
@danielnelson what can I do get this moving along ? update PR to remove version pinning, so we rely on https://github.com/moby/moby/blob/master/client/client.go#L200

**Comment by danielnelson** [comment]
Could you research a solution that will work for both Windows and Ubuntu 14?  Remember it is important that it works even when querying across platforms: Windows -> Ubuntu 14

**Comment by erichiller** [comment]
Is there anything holding this PR up?

**Comment by hoerup** [comment]
Do this really still need Ubuntu 14 compability ??

**Comment by powersj** [comment]
Hi,

We merged the change for the client version already in a different PR. I am going to close this PR as it is conflicting and only adds some additional README changes. I would be happy to see those changes get added to the README, but no need to keep this open in the current state.

Thanks!

**Pull request closed without merging**
