### PR TITLE
Support string type for metric value

### PR DESCRIPTION
**Pull request by e11it**
Some input plugins write metrics in string format.
Added functionality to convert string value to int or float when option smart_strings is set to true in config file.
Converting to float type if value contains '.'  else to integer type.Plugin output to console error on failed to convert.

### CODE REVIEW

**Comment by sparrc** [comment]
@e11it which input plugins are writing metrics in string format when they should be float or int?

I think that is the real issue here

**Comment by e11it** [comment]
I've detected that not all metrics send to prometheus. Teleraf configured to send metrics to both influxdb and promehteus.

Error in console:
Prometheus output, unsupported type. key: system, type: string
...

Current(after patch) unsupported metric is system_uptime_format with value 23 days, 6:08.

**Comment by sparrc** [comment]
so system_uptime_format is not going to be able to convert to int or float, so I don't see how the change helps?

**Comment by sparrc** [comment]
I don't think we should be printing anything at all, if prometheus doesn't support strings then we should just ignore those metrics.

**Comment by e11it** [comment]
Can't agree with you.

Here is output of the telegraf prometheus plugin with my patch and without it(Telegraf - Version 0.11.1).

[without_path.txt](https://github.com/influxdata/telegraf/files/186233/without_path.txt)
[with_patch.txt](https://github.com/influxdata/telegraf/files/186234/with_patch.txt)

**Comment by sparrc** [comment]
there have been many recent changes to the prometheus output, try rebasing and rebuilding, this is what I get with the current master for the `system` plugin:

```
# HELP system_load1 Telegraf collected point 'system_load1'
# TYPE system_load1 untyped
system_load1{dc="us-west-1",host="tyrion"} 2.01
# HELP system_load15 Telegraf collected point 'system_load15'
# TYPE system_load15 untyped
system_load15{dc="us-west-1",host="tyrion"} 1.64
# HELP system_load5 Telegraf collected point 'system_load5'
# TYPE system_load5 untyped
system_load5{dc="us-west-1",host="tyrion"} 1.86
# HELP system_n_users Telegraf collected point 'system_n_users'
# TYPE system_n_users untyped
system_n_users{dc="us-west-1",host="tyrion"} 3
# HELP system_uptime Telegraf collected point 'system_uptime'
# TYPE system_uptime untyped
system_uptime{dc="us-west-1",host="tyrion"} 709294
```

**Comment by sparrc** [comment]
ie, the prometheus_client output was unfortunately completely broken in version 0.11.1 :(

**Comment by sparrc** [comment]
thank you for the contribution @e11it, but Telegraf should not in any situation be collecting numerical measurements as strings. There were some serious problems with the 0.11.1 version of prometheus_client, but I think that you'll find that if you build Telegraf from source, or use a nightly, you'll have a much better experience.

**Pull request closed without merging**
