### PR TITLE
output amqp: Add ssl support

### PR DESCRIPTION
**Pull request by ekini**
This commit adds ssl support for amqp output.

### CODE REVIEW

**Comment by sparrc** [comment]
:+1: thanks much

**Comment by pdyba** [comment]
I also really appreciate it ! Thank You !

**Comment by pdyba** [comment]
Hi,
we have problem with TSL authentication via AMQP.
We have a certificate that works with Python application and with GO it does not.
When GO have both Plain and external authentication turned on GO uses only plain. When switching to external only I get
Exception (403) Reason: "SASL could not negotiate a shared mechanism"

Does URI mus be somehow special for cert-based auth external in GO ?

How were you testing that especially:
1. What were your parameters for CA/server and cert/client cert ?
2. How does the final URI look like in telegraf config
3. What openssl version did You use on RMQ server and what on client ?
4. What version of  rabbit were You using ?
5. Does the certificates needs some special permissions ?
6. How is SSL configured (verify,verify_peer, fail_if_no_peer_cert, true_) in RMQ does it have any additional cyphers turned on ?
Thank You in advance !
Piotr

**Comment by ekini** [comment]
I haven't investigated it thoroughly, but there's an issue about this in Go amqp client: https://github.com/streadway/amqp/issues/171

**Pull request closed without merging**
