### PR TITLE
Increase ping timeout based on ping count and interval

### PR DESCRIPTION
**Pull request by kodek**
This should fix a bug where the ping command will time out when specifying ping count > 1 with a long interval. Feel free to rewrite and/or add tests if necessary.

### CODE REVIEW

**Comment by sparrc** [comment]
seems more like user-error to me, why don't you just increase the timeout?

I'd prefer the plugin to behave the same as the `ping` unix command.

**Comment by kodek** [comment]
The timeout parameter is used both for the -W argument in ping (a per-ping timeout, "time to wait for a response" from the man pages) and the total ping command exec timeout (via internal.CombinedOutputTimeout()). You can reproduce the bug by passing in the following parameters:

count = 4
ping_interval = 15.0
timeout = 1.0

It will fail due to "Command timed out."

The corresponding ping command does not time out when sent from a terminal:
$ ping -c 4 -n -s 16 -i 15 -W 1 google.com

**Comment by sparrc** [comment]
hmm I see. I think that this plugin was meant to be using the `-w` flag instead of `-W`. I'm not sure whether we should change that to `-w` or patch the current behavior to use `-w`

**Comment by sparrc** [comment]
could you just run `go fmt ./...` on the code? it's a standard Go practice and needs to be done before tests can run

**Comment by sparrc** [comment]
closing for #1359

**Pull request closed without merging**
