### PR TITLE
feat(input.intel_pmt): Add pci_bdf tag to uniquely identify GPUs and other peripherals

### LINKED ISSUE #14003: In input.intel_pmt add pci_bdf tag to uniquely identify GPUs and other peripherals
### Use Case

In the current intel_pmt plugin, the `numa_node` of the intel_pmt device is used as a way to uniquely identify which CPU socket the sample belongs to. However, with GPUs and other future peripherals, an additional tag is needed to uniquely identify samples.

### Expected behavior

Add the parent of intel_pmt's device PCI Bus:Device.Function (BDF) as the tag `pci_bdf` for example 

```
pci_bdf=0000:e7:03.1
```

### Actual behavior

Nothing but the `numa_node` tag is used to uniquely identify a sample in intel_pmt, when there are multiple devices of the same GUID.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by bensallen**
In the current intel_pmt plugin, the `numa_node` of the intel_pmt device is used as a way to uniquely identify which CPU socket the sample belongs to. However, with GPUs and other future peripherals, an additional tag is needed to uniquely identify samples.

Thus add the parent of intel_pmt's device PCI Bus:Device.Function (BDF) as the tag `pci_bdf`. We find the PCI BDF by traversing up from `telemDeviceSymlink` and taking it's basename. Equivalent example in bash:

```
$ basename $(realpath /sys/class/intel_pmt/telem10/device/..)
0000:e7:03.1
```

All intel_pmt parent devices appear to be PCI devices, so we shouldn't need to special-case this tag between CPUs and other peripherals.

Sample including pci_bdf:

```
> intel_pmt,datatype_idref=ttemperature,guid=0x9956f43f,host=node001,numa_node=0,pci_bdf=0000:e7:03.1,sample_group=TEMPERATURE[4],sample_name=CORE_TEMP value=36.4140625 1695671600000000000
```

# Required for all PRs

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #14003

### CODE REVIEW

**Comment by powersj** [comment]
Thanks again for another issue + PR, I'll ask @p-zak and the other intel folks for a review as well, but two questions:

> However, with GPUs and other future peripherals, an additional tag is needed to uniquely identify samples.

Is there an example we can add as a test that includes a non-CPU device?

Is the PCI Bus:Device.Function coarse enough for future devices as well?

**Comment by bensallen** [comment]
> Is there an example we can add as a test that includes a non-CPU device?

There doesn't appear to be anything that is unique about PMT devices for non-CPUs compared to CPUs, other than different GUIDs and thus referencing other XML entries. Generally this is the whole idea behind Intel PMT, providing a common interface to telemetry. The Intel folks might have better idea if there's addition test cases that'd provide better coverage.

> Is the PCI Bus:Device.Function coarse enough for future devices as well?

I believe so yes. I've also not found other discoverable attributes about a intel_pmt or intel_vsec device that we could use as a tag to help uniquely identify components.

**Comment by bensallen** [comment]
Tagging @jakubsikorski for review as well in-case he hasn't seen this. Thanks Kuba!

**Review by jakubsikorski — APPROVED** [review]

**Review by p-zak — APPROVED** [review]
LGTM!

@bensallen Thanks for PR!

**Review by srebhan — APPROVED** [review]
Thanks @bensallen for your contribution!

**Pull request merged**
