### PR TITLE
Collect sys.dm_db_resource_stats with Azure Managed Instance

### PR DESCRIPTION
**Pull request by Eivissa**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@denzilribeiro Can you review?

**Comment by denzilribeiro** [comment]
Db resource stats doesn't make sense for managed instance should be collecting sys.resource_stats instead as managed instance is about instance level not DB level, there aren't limits per DB.
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-resource-stats-azure-sql-database?view=azuresqldb-current

**Comment by danielnelson** [comment]
Sorry for the dumb question, but what is the difference between "Azure SQL DB" and "Managed Instance"?

**Comment by denzilribeiro** [comment]
No dumb question :) -- Azure SQL has couple  [flavors](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-technical-overview) - one is a Single database so you don't get access to anything but a single database and all the limits are applicable to this one database, one is [managed instance](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance) (which can have many databases within the instance and also comes with SQL Agent a scheduling agent)  In this case limits are at the instance level.

**Comment by Eivissa** [comment]
@denzilribeiro  I understand you mean that sys.dm_db_resource_stats is not for Instance level monitoring as Managed Instance. Could we add more metric sys.server_resource_stats instead?

		[avg_cpu_percent],
		[io_requests],
		[io_bytes_read],
		[io_bytes_written]

**Comment by Eivissa** [comment]
> No dumb question :) -- Azure SQL has couple [flavors](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-technical-overview) - one is a Single database so you don't get access to anything but a single database and all the limits are applicable to this one database, one is [managed instance](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance) (which can have many databases within the instance and also comes with SQL Agent a scheduling agent) In this case limits are at the instance level.

I understand you mean that sys.dm_db_resource_stats is not for Instance level monitoring as Managed Instance. Could we add more metric sys.server_resource_stats instead?
	
[avg_cpu_percent],
[io_requests],
[io_bytes_read],
[io_bytes_written]

**Comment by denzilribeiro** [comment]
Yes should add sys.server_resource stats as a PR. I won't get to it till this weekend or next week so feel free to submit a PR with that if needed sooner

**Pull request closed without merging**
