### PR TITLE
A new input plugin for system usage.

### PR DESCRIPTION
**Pull request by neoliv**
### Required for all PRs:

- [x] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by neoliv** [comment]
My first github pull request. Hope it will work as intended and sorry for any noob mistake.

This new plugin should improve on what procstat is able to provide.
Take a look at the README.md. You will find the full description of the plugin capabilities and sample code.
You will also find a grafana procfilter.json with dashboards based on procfilter plugin and the corresponding telegraf configuration.
Hope you will find it useful. (We already use it in production to monitor our servers).
Cheers.

**Comment by sparrc** [comment]
Hi @neoliv, thank you for the contribution, but this is a massive plugin and rather esoteric as well. I understand that this might have come in as useful for your personal or work use-case, but it doesn't really fit in as a generally usable plugin that we would merge into telegraf.

We are currently working on a framework for supporting "external" plugins which don't live within the telegraf repo but still adhere to telegraf's plugin interface. This plugin would be a good example of a plugin that fits better as an external plugin.

**Comment by neoliv** [comment]
Hi and thank you for taking time to consider the PR.
Sorry to learn that your first impression of the plugin was "esoteric" 
and "too big".
Maybe a side-effect of my clumsy non-native English or bloated 
documentation?
Please take a couple more minutes to read these few lines and consider 
it a bit further before a final rejection.

My use-case and why I choose to write a new plugin:
5000+ linux servers and 2 sets of users for the data gathered by telegraf.
1 - sysadmins wanting to find quickly what is the root cause of a 
performance issue on a server (what process or user is hogging the system)
2 - architects doing capacity management and searching for 
trends/anomalies in application resource usage.

I tried to do that using procstat + influxQL CQs with mixed results. The 
most obvious issue is that procstat is outputting too much unfiltered 
data. You have to send all the processes stats to be able to aggregate 
them later on. Sending data about thousands of processes on every server 
is not a sound design (bandwidth, database size, ...)

To help sysadmins, you can use filters to send only data regarding the 
top most consuming processes.
top(cpu,5) will give you the 5 most CPU intensive processes.
top(rss,by(user)) will give you aggregated stats about the 5 most memory 
intensive users.

To make capacity management easier you can describe workloads 
aggregating stats about a set of processes.
children(cmd('apache'))
will give you all apache processes (even those forked by).
and(user('roor'), not(cmd('tws)))
will give you all root processes excluding 'tws' (probably handled in 
another workload)

Once you get your sets of processes you can emit stats one line per 
process or aggregate them.
field(rss,cpu) <- pack(user('joe'))
This will give you one output line with the sum of RSS and CPU for all 
processes belonging to joe (instead of hundreds of lines for an active 
user.)

BTW: This plugin is less CPU intensive than procstat because any syscall 
needed to get information about a process is performed in a lazy way 
(done only if the data is needed at output time). The profiling agreed 
on this.

Hope these examples show why this is far more easy to use and resource 
friendly than what is already available.

In the procfilter.conf you will find a real world configuration (and 
result dashboards) that has proven very useful for us. I'm quite sure it 
would also be a great help for a lot of sysadmin floating around telegraf!

Regarding the size of the plugin, I agree that it is one of the biggest 
in the input/ repo but it is not alone. See sizes of the source found 
with: .../inputs$ for p in *; do n=$(cat $p/*.go |wc -c); echo $n $p; 
done | sort -n
   ...
   54085  statsd
   62457  system
   77350  procfilter <--- here
   79992  http_listener
175024  sqlserver

Most of the bulk of the code is in the parser that I choose to keep 
simple (but not compact) to be easily maintained/extended. I followed 
advice from https://blog.gopheracademy.com/advent-2014/parsers-lexers/
No 'esoteric' yacc inside!

I'm "able" (read "payed") to maintain this plugin even if it stays 
outside the main telegraf repo but I strongly feel that it fills a gap 
in what the current plugins are providing and I'm confident that there 
are quite a lot of users with similar needs. Having this plugin bundled 
in the default rpm/deb will make for happy sysadmins!
Thank you for reading thus far.
Cheers.

     Olivier

**Comment by sparrc** [comment]
I don't disagree that it can be useful, I just don't think telegraf is the place for a custom DSL metric scripting language. You're free to maintain a fork for now and I can guarantee that there will be a way to maintain it as an external plugin.

**Comment by neoliv** [comment]
OK and thanks again.
I will wait for your external plugin framework.
BTW: In the meanwhile could you send me the .spec you use to build your 
rpms to rollout my own (internal) version?

    Olivier

**Comment by sparrc** [comment]
we dont use a .spec, we use `fpm`, see scripts/build.py

**Pull request closed without merging**
