### PR TITLE
Fixing #4453 by disabling counter refresh by default

### PR DESCRIPTION
**Pull request by vlastahajek**
- disabled counter refreshing by default - fix for #4453 
- added debugging prints
- added other troubleshooting tip

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by vlastahajek** [comment]
I've fixed conflict and new commit made running tests again, with good result.

**Comment by danielnelson** [comment]
Am I correct that this would mean that, by default, only instances seen by the initial Gather would be seen by the plugin?  It seems like for dynamic types, such as process, this would be an issue.

**Comment by sjwang90** [comment]
@vlastahajek Thanks for your contribution. Could you address the above question and it will help us figure out how to proceed with this PR.

**Comment by vlastahajek** [comment]
@sjwang90, when disabling the counter refresh interval, counters for dynamic types will not work properly. 
After getting back to this issue after two years with a more objective view, it seems to me that this type of fix is not a good idea.
As an alternative to the intended fix,  it will be worth mentioning the workaround in common problems. 
As other changes in the PR are useful, I'm going to close this PR and create another one with logging and doc improvements.

**Comment by srebhan** [comment]
@vlastahajek cool thank you!

**Pull request closed without merging**
