### PR TITLE
Add SMCIPMITool input plugin

### PR DESCRIPTION
**Pull request by jhpope**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by sjwang90** [comment]
Would you be willing to submit this plugin as an [external plugin](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf? Telegraf users would be able to use the plugin sooner by having it as an external plugin since it wouldn't have to go through the typical review process. 

Here is some [information on external plugins](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) and using them with `execd`. Feel free to respond with any questions you may have.

**Comment by jhpope** [comment]
Sure I will look at the docs you provided. Should I update this PR or submit a new one when ready?

**Comment by sjwang90** [comment]
Submitting a new PR with the location and description and adding it to [this list](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md) would be best.

**Comment by Oggy512** [comment]
I read now for a couple if hours, but didn't got it.
How can I use this plugin with telegraf?
I would love to monitor my Supermicro board, but no way so far...

THX!

**Comment by jhpope** [comment]
I converted this to a python script that can be used with the `exec` input plugin. Check it out here, https://github.com/jhpope/smc_ipmi

/cc @Oggy512

**Comment by sjwang90** [comment]
Thanks @jhpope! Adding it to our list of external plugins: https://github.com/influxdata/telegraf/pull/8897

**Pull request closed without merging**
