### PR TITLE
feat(common.shim): Enable metric tracking within external plugins

### LINKED ISSUE #15572: Metric tracking within external plugins
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  debug = true
  logtarget = "stderr"
  logfile = ""

[[inputs.execd]]
  command = ["/etc/telegraf/extern_plugin/mqtt_consumer", "-config", "/etc/telegraf/extern_plugin/plugin.conf"]
  signal = "none"
  data_format = "influx"
  name_override = "device"
  tags = {device = "default_device"}

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "xxx"
  organization = "yyy"
  bucket = "zzz"
  tagexclude = ["device", "asset"]
  
  data_format = "json"
  
  [outputs.influxdb_v2.tagpass]
    device = ["default_device"]
```

### Logs from Telegraf

```text
telegraf | 2024-06-25T12:36:32Z D! [outputs.influxdb_v2] Wrote batch of 2 metrics in 13.371321ms
telegraf | 2024-06-25T12:36:32Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf | 2024-06-25T12:36:42Z D! [outputs.influxdb_v2] Wrote batch of 2 metrics in 5.369446ms
telegraf | 2024-06-25T12:36:42Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf | 2024-06-25T12:36:52Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf | 2024-06-25T12:37:02Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf | 2024-06-25T12:37:12Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf | 2024-06-25T12:37:22Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
...
```

### System info

Telegraf 1.31, Windows 10

### Docker

_No response_

### Steps to reproduce

Probably the easiest way to reproduce this:
1. Convert the input plugin mqtt_consumer into an external plugin

### Expected behavior

Receive feedback when a metric has been successfully written to stdout so that the plugin does not get stuck.

### Actual behavior

The maximum amount of processed messages will be equal to `max_undelivered_messages` because the metrics are never getting acknowledged.

### Additional info

I had already created a post about this in the community forum: https://community.influxdata.com/t/metric-tracking-with-external-plugin/34710

I think it is a serious bug that the methods for metric tracking in an external plugin do not work at all, because the accumulator is provided by shim and is processed by it as well. The metrics were simply neglected to be acknowledged under certain circumstances.

Hence my suggestion, to use the two methods `m.Drop()` and `m.Reject()` after the call in this line 
https://github.com/influxdata/telegraf/blob/v1.31.0/plugins/common/shim/goshim.go#L121

Yes, the functionality of metric tracking when used in an external plugin would then differ somewhat from the usual application, but it would still provide useful functionality under these circumstances.

### PR DESCRIPTION
**Pull request by Wimmelwaldi**
## Summary

 - This PR enables external plugins to use metric tracking within their isolated environment

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #15572

### CODE REVIEW

**Review by powersj — COMMENTED** [review]
Thanks for the PR @Wimmelwaldi I assume you were able to test this and confirmed it resolved your request as well?

**Comment by powersj** [comment]
@Wimmelwaldi could you confirm you were able to use the artifacts to resolve your issue?

**Comment by Wimmelwaldi** [comment]
@powersj Sorry for the late reply. I was on vacation. 

Yes, I can confirm that this has solved my issue.
I deliberately ignored inputs/shim here, as this is deprecated. If any parts of the code still have this dependency, they should rather be adapted.

**Review by srebhan — APPROVED** [review]
Approved with huge thank you @Wimmelwaldi!

**Pull request merged**
