### PR TITLE
feat(inputs.logstash): Record number of failures

### PR DESCRIPTION
**Pull request by bartigor**
- [X] Updated associated README.md.
- [X] Wrote appropriate unit tests.

added a metric for counting errors by plugins on logstash input plugin

resolves #

I added the collection of metrics for the number of failures in the Logstash Input Plugin

### CODE REVIEW

**Comment by bartigor** [comment]
!signed-cla

**Comment by bartigor** [comment]
!signed-cla

**Review by Jagularr — COMMENTED** [review]
Makes sense, just curious about adding it as a new metric with the same name vs adding a field to the existing metric, is that necessary?

**Comment by bartigor** [comment]
About adding a new field to the existing metric: where do you sugest to add it? 
I made a new metric becaus 'failues' are not on the same level in Logstash stats api https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#pipeline-stats

**Comment by sspaink** [comment]
@bartigor sorry you haven't received a response in a while, are you still interested in working on this pull request? I think having it in a separate metric will probably be fine. I was wondering how you were planning on using the number of failures, wouldn't you need more context around those failures to make them a useful metric?

**Comment by bartigor** [comment]
I use this metric in my production to detect microservices that have changed the log format. So far, just the number of failures is enough for me? and if they have grown sharply, then it means that it is correctly parsed. You can probably expand the context, but so far I have not thought about how to do it better.

**Comment by sspaink** [comment]
Thank you for the context, if you could rebase your pull request against the latest master branch to have CI run again that would be great.

**Comment by bartigor** [comment]
It didn’t work to automatically merge master, a long time passed, and the master went ahead. I'll fix it when the time comes.

**Review by sspaink — APPROVED** [review]

**Comment by sspaink** [comment]
@bartigor looks like the tests are failing due to some syntax issues, do you have time to resolve them?

**Comment by bartigor** [comment]
I fixed it, everything seems to compile and pass

**Comment by sspaink** [comment]
@bartigor sorry seems the unit tests didn't get triggered, I triggered them manually and they are failing with:
```
[ERROR] gofmt has found errors in the following files:
plugins/inputs/logstash/logstash.go

Run make fmt to fix them.
make: *** [Makefile:152: fmtcheck] Error 1
```

**Comment by bartigor** [comment]
fixed

**Review by reimda — APPROVED** [review]

**Pull request merged**
