### PR TITLE
feat: Add common expression language metric filtering

### PR DESCRIPTION
**Pull request by srebhan**
- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

`namepass`/`namedrop` and friends are quite limited in their ability to filter metrics when it comes to certain field values or time based filtering. However, for some use-cases you want to only keep newer metrics or filter-out metrics with bad values early on.

To do so, this PR implements a `metricpass` option that can be used in all plugins and allows to specify a filter expression in the ["Common Expression Language" (CEL)](https://github.com/google/cel-go).
This allows do setup complex filtering rules such as
```c
"source" in tags && fields.exists(f, type(fields[f]) in [int, uint, double] and fields[f] > 20.0) && time >= now() - duration("24h")
```
accepting all metrics that do have a `source` tag, at least one numeric field with a value greater than 20 and being not older than one day.

### CODE REVIEW

**Comment by mhoffm-aiven** [comment]
This could be really useful to block old metrics from file/tail/http inputs that write timestamps explicitly but are not regularly updated!

**Review by mhoffm-aiven — APPROVED** [review]
LGTM

**Review by powersj — COMMENTED** [review]
Done an initial pass and all is good. Re-ran the mac tests and CI is now passing.

I would like to play with this a bit more today and then we can +1

**Review by powersj — APPROVED** [review]

**Comment by Hipska** [comment]
This feature is lacking examples in the documentation..

**Comment by srebhan** [comment]
Feel free to add them!

**Comment by Hipska** [comment]
I was looking for docs, because I don't know how they work 😛

**Pull request merged**
