### PR TITLE
feat: #9725 add shift property to modify register value in modbus input plugin

### PR DESCRIPTION
**Pull request by TimurDela**
### Required for all PRs:

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

GitHub did not allow me to modify the origin branch of pull-request #11067 so I was forced to close that PR and open a new one. Sorry for the mess this causes.

adds new 'shift' property to add a constant to the register value see issue https://github.com/influxdata/telegraf/issues/9725

### CODE REVIEW

**Comment by sspaink** [comment]
@TimurDela is this still considered a draft or ready for review?

**Comment by TimurDela** [comment]
Yes, this is still a draft. I am waiting for #11106 to be merged so I can rebase this one and make it more consistent with the new syntax

**Comment by srebhan** [comment]
Any update @TimurDela? I really think we should not implement shifting in the modbus plugin but rather use a processor to manipulate the data.

**Comment by TimurDela** [comment]
Hello @srebhan 
I understand the point of trying to keep the Modbus plugin clean from signal processing but then I would argue for removing the scaling as well.
The problem, however, is that the starlark processor seems to slow down the data acquisition quite a bit. It works well when I use a powerful computer but when I use it on a relatively old laptop for one of my Modbus devices, then I am not able to acquire data as fast as required (40ms).

**Pull request closed without merging**
