### PR TITLE
DHT22 temperature and humidity sensor plugin

### PR DESCRIPTION
**Pull request by gdunstone**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [?] Has appropriate unit tests.

### CODE REVIEW

**Comment by nerzhul** [comment]
excellent ! i have the same setup at home on a RPI with a python script i develop recently :D 
one unacceptable thing on your PR is to make sensor writeable for everybody instead of just setting the good rights (for example, can you try a setup with telegraf in root group, or try to do priviledge escalation) ?

**Comment by gdunstone** [comment]
Originally that was what I was doing, create gpio group, add telegraf user to it and make /sys/class/gpio group writeable.
Im doing some more bughunting on it because there is some issue with the go-dht package that causes it to behave erratically when loaded as part of telegraf (I think it has to do with being run as a goroutine.
The original package used cgo to achieve fast enough reads.

I was also going to add a feature to support dht11 as well.

**Comment by gdunstone** [comment]
it looks like this person ran into the same problem I am running into:
https://groups.google.com/forum/#!topic/golang-nuts/KFNYywZtL_4

**Comment by gdunstone** [comment]
Due to issues with goroutines not being able to poll gpio at a sufficient rate, this PR (and my fork of go-dht) is fundamentally flawed.

It would be best to write a program with go-dht to output influx line protocol and use telegrafs exec plugin.

**Comment by danielnelson** [comment]
Too bad about the polling issue.  I guess if we had a build system that could handle cross compiling CGO, like in your original pull request, it would work?  I'm not 100% sure about the syscall not working comment on the golang-nuts forum either, I don't know enough to say.

**Comment by gdunstone** [comment]
I think its just a side effect the way that goroutines work. Its intended behaviour that other things are executed while waiting on io, but becomes a problem when you need something that is executed on a strict deadline.

**Comment by danielnelson** [comment]
It seems like they should have the same accuracy as other native user space code, at least within a single function call.  I thought they only swap out the running goroutine when a function call happens (might be out of date on this though).

**Comment by gdunstone** [comment]
there is a bunch of function calls within go-dht to read from the sensor so that might be it.

Ill revisit at a later date.

**Comment by gdunstone** [comment]
@nerzhul I have created a PR for go-dht that adds an example that outputs the data in influx line format:
https://github.com/d2r2/go-dht/pull/6

@danielnelson if the build system could cross compile cgo that would be great, all it really needs is 
`arm-linux-gnueabihf-gcc`, I think. I'm just installing it on my build system now.

**Pull request closed without merging**
