### PR TITLE
AppDynamics Output Plugin

### PR DESCRIPTION
**Pull request by kyle-lt**
### Required for all PRs:

- [X ] Signed [CLA](https://influxdata.com/community/cla/).
- [ X] Associated README.md updated.
- [ X] Has appropriate unit tests.

Submitting Pull Request to satisfy [AppDynamics Output Plugin Issue](https://github.com/influxdata/telegraf/issues/6616)

### CODE REVIEW

**Comment by kyle-lt** [comment]
Hello folks, just wanted to inquire as to the next step in this process, thanks!

**Comment by danielnelson** [comment]
Thanks for the pull request @kyle-lt, we will try to look at it as soon as we are able.  The current reality is that we have a pretty long backlog so it might take some time.

**Comment by kyle-lt** [comment]
Thanks for the confirmation @danielnelson , I'll sit tight.

**Comment by kyle-lt** [comment]
Hi @danielnelson , just checking in again.  It's been about a month since last checkpoint, so interested in an update, if possible.  Thanks!

**Comment by kyle-lt** [comment]
Hello @danielnelson , me again, just wondering about when this might get looked at, thanks!

**Comment by danielnelson** [comment]
I don't have much to update other than this plugin is not currently on our list for 1.14, sorry.

**Comment by sjwang90** [comment]
This output plugin actually looks like a great candidate for an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md). Would you be willing to submit this plugin as an [external plugin](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf? Telegraf users would be able to use the plugin sooner by having it as an external plugin since it wouldn't have to go through the typical review process. 

Feel free to respond with any questions you may have.

**Comment by sjwang90** [comment]
Due to inactivity I'm going to close the issue here for now, but we'd love to see this as an external plugin.

**Pull request closed without merging**
