### PR TITLE
chore: Fix linter findings for `revive:enforce-repeated-arg-type-style` in `plugins/outputs` and `plugins/parsers`

### PR DESCRIPTION
**Pull request by zak-pawel**
## Summary

Address findings for [revive:enforce-repeated-arg-type-style](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-repeated-arg-type-style) in `plugins/outputs` and `plugins/parsers`

As we agreed here https://github.com/influxdata/telegraf/issues/15811, we will fix the errors found by the following configuration:
```
      - name: enforce-repeated-arg-type-style
        arguments: ["short"]
```

It is only part of the bigger job.
After all findings of this type in whole project are handled, we can enable `revive:enforce-repeated-arg-type-style` rule in `golangci-lint`.

## Checklist

- [x] No AI generated code was used in this PR

### CODE REVIEW

**Review by Hipska — APPROVED** [review]

**Comment by zak-pawel** [comment]
@srebhan Could you elaborate on what you mean by "reflects the current state better"? 
I agree that for the `full` setting, there will be a bit less code to correct, but if you're asking me for an opinion, I prefer `short` (just like you and @DStrand1) 🙂

**Comment by srebhan** [comment]
I mean that most of the code currently uses the `full` style. I also realized that the `short` version is ugly for functions where the definition is wrapped into multiple lines like
```golang
func myfunc(
    param1 string,
    param 2 string,
    param3 int,
    ...
)
```
as with the `full` style you can easily see all parameters (as it's one per line) whereas with `full` it is more complicated. OTOH maybe those functions are bad anyway... No so sure anymore...

**Comment by zak-pawel** [comment]
@srebhan 

> I mean that most of the code currently uses the `full` style.

I would say that a bit more code uses the `full` style than the `short` style, not most of the code :)

> I also realized that the `short` version is ugly for functions where the definition is wrapped into multiple lines

Well, it's a matter of taste, I for example like this (because it often groups parameters of the same type in one line). 
Additionally, thanks to the change to `short`, some function definitions could be condensed into one line.

**Comment by srebhan** [comment]
Ok so let's keep short... Will continue reviews. ;-)

**Review by DStrand1 — APPROVED** [review]

**Pull request merged**
