### PR TITLE
New SNMP Plugin, deprecating old to snmp_legacy

### PR DESCRIPTION
**Pull request by sparrc**
### Required for all PRs:

- [ ] CHANGELOG.md updated
- [ ] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sparrc** [comment]
@phemmer I made some large refactors as I was concerned about some of the changes for a few reasons, as well as seeing some missing features:

1. The snmp concepts and names defined in the snmp input plugin should aim to act identically to the standard linux snmp CLI utilities (snmpget, snmpwalk, snmptable, etc.)
1. An snmptable is a very specific snmp concept, and it does not mean that any OID that can be walked from should be treated as a table. If we want to support an `snmptable` command in telegraf, that should first be implemented in the client library we're using (github.com/soniah/gosnmp).
1. All snmp operations should be based around a simple text OID. I'd prefer to avoid creating any sort of table or row objects to describe snmp objects, when we can simply use their OID and a hashmap.
1. OIDs should be translated the first time they are seen, then cached and re-used later. If we can't get their name, we should simply use the OID to store it. The reason behind this is that the OID/MIB name are the canonical way to refer to an snmp object.
1. When doing an snmpwalk (what was called an "snmp table" before), we cannot set a single field name. The nature of snmpwalk is that it will traverse all child OIDs, and thus setting a name can easily create the situation of overwritten measurements. (I realize there was a user-error involved here on my part, but it was very easy to shoot myself in the foot, which is not ideal for a general-use plugin).
1. The snmp plugin should be able to take a `root_oid` for an snmpwalk, from there and collecting all relevant metrics underneath that oid.

I've yet to work on unit tests or documentation, but the configuration of the plugin basically looks like this:

```toml
# Retrieves SNMP values from remote agents
[[inputs.snmp]]
  agents = ["127.0.0.1:161"]
  version = 2 # Values: 1, 2, or 3

  ## SNMPv1 & SNMPv2 parameters
  community = "public"

  ## SNMPv2 & SNMPv3 parameters
  max_repetitions = 50

  ## SNMPv3 parameters
  #sec_name = "myuser"
  #auth_protocol = "md5"         # Values: "MD5", "SHA", ""
  #auth_password = "password123"
  #sec_level = "authNoPriv"      # Values: "noAuthNoPriv", "authNoPriv", "authPriv"
  #context_name = ""
  #priv_protocol = ""            # Values: "DES", "AES", ""
  #priv_password = ""

  ## Each 'tag' is an "snmpget" request. Tags are inherited by snmp 'walk'
  ## and 'get' requests specified below. If a name for the tag is not provided,
  ## we will attempt to use snmptranslate on the OID to get the MIB name.
  [[inputs.snmp.tag]]
    name = "sys_name" # optional, tag name
    oid = ".1.3.6.1.2.1.1.5.0"
  [[inputs.snmp.tag]]
    name = "sys_location"
    oid = ".1.3.6.1.2.1.1.6.0"

  ## optional, name of the measurement that each 'get' field will be under.
  name = "snmp"
  ## Each 'get' is an "snmpget" request. If a name for the field is not provided,
  ## we will attempt to use snmptranslate on the OID to get the MIB name.
  [[inputs.snmp.get]]
    name = "snmp_in_packets" # optional, field name
    oid = ".1.3.6.1.2.1.11.1.0"
  [[inputs.snmp.get]]
    oid = ".1.3.6.1.2.1.11.2.0"

  ## An SNMP walk will do an "snmpwalk" from the given root OID.
  ## Each OID it encounters will be converted into a field on the measurement.
  ## We will attempt to use snmptranslate on the OID to get the MIB names for
  ## each field.
  [[inputs.snmp.walk]]
    ## optional, inherit_tags specifies which top-level tags to inherit.
    ## Globs are supported.
    inherit_tags = ["sys_*"]
    name = "snmp_metrics" # measurement name
    root_oid = ".1.3.6.1.2.1.11"

  [[inputs.snmp.walk]]
    ## optional, 'include' specifies MIB names to include in the walk.
    ## 'exclude' is also available, although they're mutually-exclusive.
    ## Globs are supported.
    include = ["if*"]
    name = "ifTable"
    root_oid = ".1.3.6.1.2.1.2.2"

  [[inputs.snmp.walk]]
    exclude = ["ifAlias"]
    name = "ifXTable"
    root_oid = ".1.3.6.1.2.1.31.1.1"
```

**Comment by sparrc** [comment]
cc @phemmer @kaey @Infiniverse @pauldix @titilambert Please review this iteration of the SNMP plugin. This one is based off of https://github.com/influxdata/telegraf/pull/1389, but some changes have been made for the reasons that I outlined in my comment above

**Comment by phemmer** [comment]
As the changes stand, I would not be able to use this plugin. Not don't want to, but can't.  
The main purpose of rewriting the plugin was to add real table support, more closely follow the design patterns of other tools, to allow near any use case, and simplify configuration. This version of the plugin breaks every single one of those reasons.

> The snmp concepts and names defined in the snmp input plugin should aim to act identically to the standard linux snmp CLI utilities (snmpget, snmpwalk, snmptable, etc.)

I disagree. Tools such as `snmpget`, `snmpwalk`, etc, are meant for manual usage and plumbing. It is not the job of those tools to organize the data into a format to be reported on.

&nbsp;

> If we want to support an snmptable command in telegraf, that should first be implemented in the client library we're using 

Also disagree for the same reason. It is not the responsibility of the library to do this. The library should provide the low level interface to interact with the device. It is up to the application using the library to organize and format the data.

&nbsp;

> An snmptable is a very specific snmp concept, and it does not mean that any OID that can be walked from should be treated as a table.

I agree. My version of the plugin did not do this, and that was done for a specific reason. Your version of the plugin changing and making it behave this way is one of the main reasons I cannot use it.

&nbsp;

> All snmp operations should be based around a simple text OID. I'd prefer to avoid creating any sort of table or row objects to describe snmp objects, when we can simply use their OID and a hashmap.

I'm not sure what you mean by this. My version of the plugin did use a text OID.

&nbsp;

> OIDs should be translated the first time they are seen, then cached and re-used later. If we can't get their name, we should simply use the OID to store it.

This is another reason I can't use the plugin. Manually specifying names for a field was done for a specific reason. Take the output from one of my devices:

```
# snmpbulkwalk -m all -v2c -c public 10.0.99.99 .1.3.6.1.4.1.3375.2.2.5.6.2.1.5
...
F5-BIGIP-LOCAL-MIB::ltmPoolMbrStatusAvailState."/Common/pricebot-stg.ecom.chewy.com-pool"."/Common/fll2gpbt01stg".9000 = INTEGER: green(1)
F5-BIGIP-LOCAL-MIB::ltmPoolMbrStatusAvailState."/Common/splunk-indexer-event-collector-pool"."/Common/fll2aspi01stg".8088 = INTEGER: green(1)
F5-BIGIP-LOCAL-MIB::ltmPoolMbrStatusAvailState."/Common/splunk-indexer-event-collector-pool"."/Common/fll2aspi02stg".8088 = INTEGER: green(1)
```

All these are part of the same field (column) of an SNMP table. As you can see, each of them has a different OID name. Thus it would be impossible to use this field in any sort of grouping. In influxdb, you wouldn't be able to `group by pool_mbr_status` for example.

Also the monitored SNMP agent might not have a published MIB. The user should not be expected to have to write an MIB file to be able to get meaningful names in influxdb.

&nbsp;

> When doing an snmpwalk (what was called an "snmp table" before), we cannot set a single field name. The nature of snmpwalk is that it will traverse all child OIDs, and thus setting a name can easily create the situation of overwritten measurements.

If you specify the same name for multiple fields, this is the user's problem. The plugin cannot be blamed for this.

&nbsp;

> The snmp plugin should be able to take a root_oid for an snmpwalk, walking from there and collecting all relevant metrics underneath the root.

No, it should not. You can have an SNMP table which spans several OID prefixes. For example, you might be monitoring a device with network ports, and in SNMP a port number might have 2 prefixes, one for throughput metrics (byte counters, line errors, etc), and another for higher level protocol metrics (ip, tcp, etc). Maybe I want to select individual fields from these 2 prefixes and present them as a single measurement to influxdb.

Also, I may not want the entire table in influxdb. Some devices can report dozens of OIDs under a table prefix, when I only want one or two. Influxdb should not be spammed with this data that I have no use for, both inflating influxdb, and making it harder to sift through this unwanted data.

----

I apologize if this review comes across as a bit heated, but these changes defeat every single reason the new plugin was written. Yes the plugin I wrote included extra features (such as the 'conversion' feature), but they weren't the reason for writing the plugin, they were just extra features. You might as well just port these extra features to the existing plugin if you are going to preserve it's behavior.  
Obviously you are the project maintainer, and so if the new plugin meets your specific use case, you are free to merge it as is. I am quite willing to break my plugin out as a standalone executable.

**Comment by toni-moreno** [comment]
Hi @phemmer perhaps you would like to test a standalone snmp agent that I have plans to get ready on next 2/3 months

https://github.com/toni-moreno/snmpcollector

It is based in the "influxsnmp" tool, that I've forked a couple of month ago becouse of  we need something more flexible and also user friendly. 

The main diference will be a web frontend   to configure the agent and  the devices and metric/measurements configuration will be on a sql database.( you can see at the toml_to_sql_migration branch ). 
Future users could be people who have been working with cacti and needs for something more.

Feel free to test and contribute if you need.

**Comment by schotlandzegtja** [comment]
I can only speak as a user, but I was excited about @phemmer's changes; what I read here is quite disappointing.

I am keen to put InfluxDB into use at my place of employment but the inflexibility surrounding existing SNMP collection agents is making it difficult to justify. Telegraf, CollectD and influxsnmp all come up short.

**Comment by lizaoreo** [comment]
I'm with @schotlandzegtja, I was really looking forward to using @phemmer's plugin for all of the above reasons.  I've already got some stuff sorta working with the current SNMP plugin, but have been holding off doing much more because it's a bit cumbersome and I much preferred the way @phemmer's plugin worked.

**Comment by sparrc** [comment]
@phemmer the `ifv` table was not using the OID as the key. This meant that OIDs could only be translated to MIBs from the original definition, not on the fly.

I understand the concern on the part of the snmptable, maybe it is not up to the client library, but there needs to be more protections in place if what it is reading is not actually a table field. The code simply walks and this makes it too easy to make mistakes. One of the main reasons we (ie, InfluxDB, maintainers) want to change the SNMP plugin is that supporting it has become an extremely onerous and time-consuming task. Any new plugin needs to be significantly more bullet-proof before we can merge it.

Removing the "conversion" option was not permanent, it's easy to add back I was just trying to hack together something of a simple mockup without too much extra code.

I also don't think that MIB lookup is an optional feature. Having to manually hack out OIDs is onerous. We are unfortunate not to have a client library in Go that supports MIB names natively, but I think forking out to snmptranslate is an OK substitute.

**Comment by sparrc** [comment]
And lastly would like some clarification on why the "snmp.table" feature of @phemmer's proposed plugin does not mirror the behavior of the `snmptable` CLI command.

**Comment by sparrc** [comment]
And a followup apology-- I didn't intend to devolve or heat up the conversation on this. In retrospect the PR came off as a bit forceful, but my intention was to better understand the newly proposed PR and propose some changes based on my understanding of SNMP monitoring. I'm fully aware when my understanding is off, so let's try to compromise on some features that I believe will make the plugin easier to support and easier to modify.

Telegraf has suffered from large plugins with undiscussed features in the past and I'm trying to avoid the same mistakes. We need to come to a consensus because frankly I can't depend on contributors to be available later on for help supporting and fixing issues with plugins.

**Comment by sparrc** [comment]
Closing this because it was obviously not well-received. Please be patient with getting the new SNMP plugin added. I'm well-aware that some of my assumptions here were misguided and will try to work with @phemmer to get https://github.com/influxdata/telegraf/pull/1389 merged.

please try to keep in mind that this project only has a single maintainer, and dealing with hundreds of pull requests is quite difficult. I am trying to do my best to merge PRs that are going to be easy-to-use for the general community, and when there is a knowledge gap I do my best to bridge it.

**Comment by schotlandzegtja** [comment]
Thanks to all involved :)

**Comment by phemmer** [comment]
> needs to be more protections in place if what it is reading is not actually a table field. The code simply walks and this makes it too easy to make mistakes. 

There is no way to get around this. If you tell the plugin anything under a certain OID is a table field, then it has to trust you. However, I did put a "feature" in my design of the plugin that if there is no tag for that row of the table (meaning the field OID index has no corresponding tag with the same OID index), then the plugin skips it. This was done so that you wouldn't end up with metrics in our output database that have no tags, and can't be filtered on.
Though I would like to see real world examples of the problem you describe. I have never heard of such a thing (unless the OID prefix given never really was a table in the first place).

&nbsp;

> I also don't think that MIB lookup is an optional feature. Having to manually hack out OIDs is onerous. We are unfortunate not to have a client library in Go that supports MIB names natively, but I think forking out to snmptranslate is an OK substitute.

I considered it optional as yes, it might make configuration more onerous, but it's still possible. My goal was to make it possible for the plugin handle all use cases first, then afterwards make it easier.
However I do not think it should be required to use OID translation to get the field name. A user should be able to manually specify it (for reasons given in my earlier comment).

&nbsp;

> And lastly would like some clarification on why the "snmp.table" feature of @phemmer's proposed plugin does not mirror the behavior of the snmptable CLI command.

It does.
With the example data at https://github.com/phemmer/telegraf/blob/16b65065ab29218de3c9c0bdb1523f838cace2a7/plugins/inputs/snmp2/README.md, and the MIB file at https://gist.github.com/phemmer/142839f6ebcc937d3fcfcf3754798b85, I get the following:

```
# ./snmptable -m all -M ./mibs/ -v 2c -c public 127.0.0.1:1161 TEST::testTable
SNMP table: TEST::testTable

 hostname tablefield1 tablefield2
    "foo"           1     "0.123"
    "bar"           2     "0.456"
        ?           ?     "9.999"
TEST::testTable: WARNING: More columns on agent than in MIB
```

**Comment by jcmartins** [comment]
I would like to use telegraf to monitor all my network equipment ( mikrotik, juniper, linux)
How I can configure telegraf snmp plugin to monitor multiple equipment in only one telegraf machine?

**Comment by mannymickey** [comment]
I am planning for the same as 'jcmartins'. Can someone provide a syntax for adding multiple SNMP devices as inputs to telegraf
Which one is the expected input syntax?
[[inputs.snmp]]
agents = [ "x.x.x.1:161", "x.x.x.2:161", etc... ]
or 
[[inputs.snmp]]
agents = [ "x.x.x.1:161" ]
timeout = "5s"
retries = 3
version = 2
community = "public"
max_repetitions = 10

[[inputs.snmp]]
agents = [ "x.x.x.2:161" ]
timeout = "5s"
retries = 3
version = 2
community = "public"
max_repetitions = 10

**Comment by danielnelson** [comment]
@mannymickey You can use the former unless you need different options for the agents.  If you need more general help please ask over at the [InfluxData Community](https://community.influxdata.com) site.

**Pull request closed without merging**
