### PR TITLE
feat: Add snow parameter to OpenWeathermap input plugin

### PR DESCRIPTION
**Pull request by nberardi**
# Required for all PRs

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

Add support for snow field in OpenWeatherMap input plugin

New fields: snow

### CODE REVIEW

**Comment by nberardi** [comment]
Apologies, I forgot to sign the CLA.  It is now done.

**Comment by Hipska** [comment]
You also need to update all other tests to include a zero snow field.

**Comment by srebhan** [comment]
!signed-cla

**Comment by nberardi** [comment]
> You also need to update all other tests to include a zero snow field.

Those aren’t required because the snow property isn’t returned if the field is zero. Same with the rain forecast.

**Comment by nberardi** [comment]
63F69CC4-0415-4243-A335-5AF132A1861B

I signed the CLA again.

**Comment by Hipska** [comment]
> > You also need to update all other tests to include a zero snow field.
> 
> Those aren’t required because the snow property isn’t returned if the field is zero. Same with the rain forecast.

Anyway, the tests are now failing. They need to be fixed in order to get this merged.

> I signed the CLA again.

Correct, and by running that command, the CLA test is re-run and now [succeeds](https://github.com/influxdata/telegraf/pull/12466/checks?check_run_id=10512840536).

**Comment by nberardi** [comment]
> Anyway, the tests are now failing. They need to be fixed in order to get this merged.

I will correct the tests. I didn’t see them failing previously when I ran the on my box. I probably missed the commit.

**Comment by nberardi** [comment]
The test server on windows appears to be failing. Hopefully that won’t be held against me. 😀

**Review by Hipska — APPROVED** [review]

**Review by powersj — APPROVED** [review]

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for your contribution @nberardi!

**Pull request merged**
