### PR TITLE
implement kairosdb telnet and http(s) protocols

### PR DESCRIPTION
**Pull request by ovesh**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by ovesh** [comment]
What's the process/timeline for getting PRs merged? I just want to set my expectations accordingly.

**Comment by russorat** [comment]
Hi @ovesh, thank you for your PR! As you can see, we have a large backlog of PRs to move through. We will add this one to the prioritization queue and consider it for a future release. It's always hard for us to get a sense of how many people would benefit from new plugins, so if you can provide your use case, and hopefully other users will add theirs, it would help us prioritize accordingly. Thanks!

**Comment by ovesh** [comment]
Thanks for your response! Yeah, I see you have quite the backlog of PRs.

> if you can provide your use case

I'm not completely sure what you mean, so tell me if not in the right direction. kairosdb is a tsdb implemented on top of Cassandra. The project has a decent following on github and is well maintained, and I used it in a project for storing metric data, with telegraf being the client (using the plugin I implemented).

**Comment by 0x6373** [comment]
Not sure if this helps but i also would love to see KairosDB as a supported output plugin.
I tried to use OpenTSDB but switched to KairosDB after several problems (unclear documentation, strange behaviour for salting, poor query performance).
I also forked telegraf and adapted the opentsdb output-plugin to send the data to KairosDB (https://github.com/nosolutions/telegraf).

**Comment by russorat** [comment]
@0x6373 you mentioned a few other features you needed in order to get the plugin to work. Could you review this PR and ensure they have the features you would need to switch to it?

**Comment by 0x6373** [comment]
@russorat Sure, i already looked at the code, it seems like it should work, but i will have to test it.
This PR also supports basic authenticaiton to the kairosdb backend (apparently optional) which is something that's missing in my attempt.
Will update when i had a chance to run/test it.

**Comment by 0x6373** [comment]
@russorat is there a better way to test this than copying the files from the web-gui?
The fork indeedeng/telegraf:kairosdb-output seems to have been deleted.

**Comment by danielnelson** [comment]
The fork is still around: https://github.com/indeedeng/telegraf/tree/kairosdb-output

**Comment by 0x6373** [comment]
Ok, sorry for the noise, long day yesterday.

I just failed to compile the fork, so i applied both commits and build packages.
There are some issues from what i saw:

1. configuration described in README.md is wrong (copied from opentsdb), you need to check SampleConfig() for the correct one
2. It's not possible to specify a prefix for the send metricnames (which is a dealbreaker for me since i have multiple platforms reporting into KairosDB, which should not be mixed up)
3. No possibility to define a maximum batch size to send (not sure if there is an upper limit from KairosDB, did not find anything in it's configuration so this would not be a dealbreaker)
4. No debug mode available like "debug = true" in the opentsdb plugin

So in the current state i cannot switch to this PR since no custom prefix is possible.

**Comment by 0x6373** [comment]
Would it be ok if i create a PR for my version of this plugin?

Since it's really based on the opentsdb plugin i just changed a few things:

- Changed all OpenTSDB strings to KairosDB (different variants with upper/lower case)
- Changed default for http_path from "/api/put" to "/api/v1/datapoints"
- Changed the property "metric" to "name" in the generated JSON
- Removed the gzip writter between the json encoder and the final buffer

**Comment by danielnelson** [comment]
> Would it be ok if i create a PR for my version of this plugin?

Sure, is your PR based on the `opentsdb` output or on this PR?

> No possibility to define a maximum batch size to send

This should be possible with the `metric_batch_size` option either in the agent section or per output.

> No debug mode available like "debug = true" in the opentsdb plugin

I'm generally not in favor of these anymore, usually we should just log at debug level.  If it's too expensive then we can discuss on a case by case basis.

**Comment by 0x6373** [comment]
> Sure, is your PR based on the `opentsdb` output or on this PR?

My PR is based on a copy of the 'opentsdb' output plugin, we are currently testing this plugin on ~1200 hosts for the last few days, i'm not aware of any issues there.

> This should be possible with the `metric_batch_size` option either in the agent section or per output.

Just looked it up, i think that i will remove this logic then since it is redundant.

> I'm generally not in favor of these anymore, usually we should just log at debug level. If it's too expensive then we can discuss on a case by case basis.

Also OK for me, i will remove this (making the code even easier).

One more questions:

Are there any preferences from your side as to the docker image needed for testing? From what i see there are only non-official docker images for KairosDB.

**Comment by danielnelson** [comment]
> Are there any preferences from your side as to the docker image needed for testing? From what i see there are only non-official docker images for KairosDB.

Using docker is optional, if there isn't a good image its probably best to skip it.  Sorry, the existing tests are probably not a great example, ideally the tests would use httptest and maybe just a socket bound to a random unused port `127.0.0.1:0` for the telnet protocol.

**Comment by raffraffraff** [comment]
Why does this disable gzip compression? That's actually the main reason I wanted to create a KairosDB plugin. The opentsdb plugin works fine over telnet, but http is totally broken.

**Comment by raffraffraff** [comment]
I'm using gzip compression on my fork and it works fine. The key is to use the header `Content-Type: application/gzip` and `Content-Encoding: identity`:
https://github.com/raffraffraff/telegraf/commit/cb0143d9e80962e10391c7efd65ed885aa228786#diff-ff9b9b3460ddc46931f796d4f0459cb6R138

**Comment by 0x6373** [comment]
I just implemented gzip compression and will now work on adding basic authentication (something that we need).

It's going forward, slowly.

**Comment by danielnelson** [comment]
@0x6373 Yes please.

**Comment by 0x6373** [comment]
PR #5827 has been opened

**Comment by srebhan** [comment]
@0x6373 are you still interested in working on this PR?

**Comment by srebhan** [comment]
@ovesh or @0x6373 are you still interested in working on this PR or is it superseeded by #5827?

**Comment by 0x6373** [comment]
> @ovesh or @0x6373 are you still interested in working on this PR or is it superseeded by #5827?

From my point of view this PR is relevant anymore, #5827 is the newer one.
Not sure what @ovesh wants.

**Comment by ovesh** [comment]
I'm ok with closing this in favor of #5827.

**Comment by srebhan** [comment]
Superseeded by #5827. Continuing there.

**Pull request closed without merging**
