### PR TITLE
support mips64le architecture.

### PR DESCRIPTION
**Pull request by houfangdong**
### Required for all PRs:

- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by houfangdong** [comment]
!signed-cla

**Review by srebhan — APPROVED** [review]
Looks good to me.

**Review by Jagularr — APPROVED** [review]

**Comment by ssoroka** [comment]
I'd like to hear from users who need this before we lengthen our build times.

**Comment by helenosheaa** [comment]
We haven't received any other requests for this and we don't think the user base is large enough to justify increasing our build times. If this changes in the future we are open to adding it if we can show a large enough user base

**Pull request closed without merging**
