### PR TITLE
Improve error from line protocol parser

### LINKED ISSUE #4743: Improve error strings from line protocol parser
## Feature Request

When sending batches of line protocol it is very difficult to parse the error messages because the entire batch is shown.

### Proposal:

Show only a section of the offending line and show the line number and column.

```
$ cat test
cpu,cpu=cpu0 usage_guest=0,usage_guest_nice=0,usage_idle=0,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=4.00,usage_steal=0,usage_system=96.00,usage_user=0 1537833474000000000 cpu,cpu=cpu0 usage_guest=0,usage_guest_nice=0,usage_idle=0,usage_iowait=0,usage_irq=0,usage_nice=invalid,usage_softirq=4.00,usage_steal=0,usage_system=96.00,usage_user=0 1537833474000000000
$ curl -v 'http://localhost:9999/write?db=telegraf' --data-binary @test
```

### Current behavior:

Only byte offset is given
```
metric parse error: expected field at offset 281: "cpu,cpu=cpu0 usage_guest=0,usage_guest_nice=0,usage_idle=0,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=4.00,usage_steal=0,usage_system=96.00,usage_user=0 1537833474000000000\ncpu,cpu=cpu0 usage_guest=0,usage_guest_nice=0,usage_idle=0,usage_iowait=0,usage_irq=0,usage_nice=invalid,usage_softirq=4.00,usage_steal=0,usage_system=96.00,usage_user=0 1537833474000000000\n\n"
```

### Desired behavior:

The error message contains line/column instead of offset.  Column is given as a codepoint(rune) offset.

```
metric parse error: expected field on line: 2, column: 98: "cpu,cpu=cpu0 usage_guest=0,usage_guest_nice=0,usage_idle=0,usage_iowait=0,usage_irq=0,usage_nice=invalid,usage_softirq=4.00,usage_steal=0,usage_system=96.00,usage_user=0 1537833474000000000"
```

### Use case:

Impossible to find cause of error with current format and common batch sizes.

### PR DESCRIPTION
**Pull request by glinton**
Resolves #4743

### CODE REVIEW

**Comment by danielnelson** [comment]
On this one we should implement the line counting in machine.go.rl.  I think we need to add two ints to the Machine, one for line and one for start of line, these get updated as the machine runs.

**Comment by glinton** [comment]
Wouldn't that slow down the whole parsing (counting everything all the time) vs just slowing the printing of an error due to counting at error print time?

**Comment by masterofcloud1** [comment]
What will happen if you can't open the metrices file? For example, if you are using scripts to generate metrices, and they are creating massive amount of them. The error message will be "found error in line 5000" and you can't look for line 5000...

**Comment by danielnelson** [comment]
See #5484

**Pull request closed without merging**
