### PR TITLE
Add stackdriver input plugin

### LINKED ISSUE #2099: Add Google Cloud Monitoring input (Stackdriver)
### Proposal:

Google [has made Stackdriver generally available](https://cloudplatform.googleblog.com/2016/10/Google-Stackdriver-Generally-Available.html), and has a [metrics API](https://cloud.google.com/monitoring/docs/apis).

Please add support for fetching metrics from Google Cloud Monitoring, similar to [AWS CloudWatch input](https://github.com/influxdata/telegraf/tree/5d3850c44e048f5619a04c14373c3324c2c9c407/plugins/inputs/cloudwatch).

### Use case

Google Cloud Platform is a major cloud provider nowadays, and I'd prefer pulling all metrics into a single backend source (InfluxDB, Prometheus) and manage alerting from there, instead of having to manage various alerting sources (in this case, Google Stackdriver along with my main monitoring/alerting backend).

### PR DESCRIPTION
**Pull request by danielnelson**
closes #2099
closes #4977

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
I am planning to change the distribution type to send cumulative buckets, I believe this will work better with existing query languages (flux, promql) and matches the way we send histograms (in the histogram aggregator).  It also feels misleading to use the `lt` tag for the buckets when the histogram is not a cumulative histogram.

**Comment by danielnelson** [comment]
@Legogris I'm not sure if you are using the Stackdriver input or only the output.  Either way it would be great to get your review if you have time.

**Comment by Legogris** [comment]
I have not, don't really have much to add to the discussion on how to treat these metrics in the other direction, other than that the SeriesGrouper looks suitable for #5404 as well

**Comment by danielnelson** [comment]
> SeriesGrouper looks suitable for #5404 as well

Almost, over there we need to group including the field.  Maybe we could extend it though to let you pick what components to group by... gears are turning in my head...

**Comment by sciurus** [comment]
@danielnelson I'm getting an error building this, although it appears to be unrelated to this PR. After checking out the WuHan0608-stackdriver branch and running `make docker-image`

```
Step 8/15 : RUN make go-install
 ---> Running in be6f5b11ebd7
go install -ldflags "-w -s  -X main.commit=bd5c18ea -X main.branch=WuHan0608-stackdriver" ./cmd/telegraf
# github.com/influxdata/telegraf/vendor/github.com/prometheus/client_golang/prometheus
vendor/github.com/prometheus/client_golang/prometheus/counter.go:58:7: cannot use opts.ConstLabels (type Labels) as type Labels in argument to NewDesc
vendor/github.com/prometheus/client_golang/prometheus/counter.go:96:7: cannot use opts.ConstLabels (type Labels) as type Labels in argument to NewDesc
vendor/github.com/prometheus/client_golang/prometheus/counter.go:170:7: cannot use opts.ConstLabels (type Labels) as type Labels in argument to NewDesc
vendor/github.com/prometheus/client_golang/prometheus/gauge.go:51:7: cannot use opts.ConstLabels (type Labels) as type Labels in argument to NewDesc
vendor/github.com/prometheus/client_golang/prometheus/gauge.go:72:7: cannot use opts.ConstLabels (type Labels) as type Labels in argument to NewDesc
vendor/github.com/prometheus/client_golang/prometheus/gauge.go:96:42: cannot use labels (type Labels) as type Labels in argument to m.MetricVec.GetMetricWith
vendor/github.com/prometheus/client_golang/prometheus/labels.go:32:6: Labels redeclared in this block
	previous declaration at vendor/github.com/prometheus/client_golang/prometheus/desc.go:44:6
vendor/github.com/prometheus/client_golang/prometheus/labels.go:36:7: reservedLabelPrefix redeclared in this block
	previous declaration at vendor/github.com/prometheus/client_golang/prometheus/desc.go:35:29
vendor/github.com/prometheus/client_golang/prometheus/labels.go:85:6: checkLabelName redeclared in this block
	previous declaration at vendor/github.com/prometheus/client_golang/prometheus/desc.go:202:31
vendor/github.com/prometheus/client_golang/prometheus/value.go:39:5: errInconsistentCardinality redeclared in this block
	previous declaration at vendor/github.com/prometheus/client_golang/prometheus/labels.go:38:5
vendor/github.com/prometheus/client_golang/prometheus/gauge.go:96:42: too many errors
```

**Comment by sciurus** [comment]
This is looking good to me so far!

**Pull request merged**
