### PR TITLE
adding cmdline procstat

### LINKED ISSUE #1873: get full process path via procstat as TAG
### System info:

[Include Telegraf version, operating system name, and other relevant details]
telegraf-1.0.0-1.x86_64
RHEL6
## Feature Request

include command_line as a field collected from procstat . 
### Proposal:

get the full command line from  /proc/*/cmdline . return the contents of this file as a tag.
### Current behavior:

returns only the short name for the process and pid as the identifier of the process. 
### Desired behavior:

list the full process path as tag so that you may identify which process is which 
### Use case: [Why is this important (helps with prioritizing requests)]

for example you run a java application, procstat current captures "java" as the process name. This is fine if your run one of something but it very common in enterprise architecture to run multiples of something with different configs file/arguments . Capturing only java make it impossible (or very hard) to differentiate between them for resource usage.

### PR DESCRIPTION
**Pull request by scottprichard**
closes #1873

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by scottprichard** [comment]
pulled master in...same thing as:
Added Cmdline to procstat #3131

**Comment by scottprichard** [comment]
ready to merge, would be nice to get someone with write access to review this and merge it in

**Comment by scottprichard** [comment]
@danielnelson :pray:

**Comment by danielnelson** [comment]
PR is good but I am a little nervous about this value due to the potential length and contents of this data.  Let's do as suggested in https://github.com/influxdata/telegraf/issues/1873#issuecomment-439895335 and add a new option that, when enabled, will add this data as a *tag*.  The option would be disabled by default.
```
## When true add the full cmdline as a tag.
# cmdline_tag = false
```

Also make sure to update the README to list the new item.

**Comment by scottprichard** [comment]
@danielnelson can you review ?

**Comment by danielnelson** [comment]
Great, thank you!

**Comment by scottprichard** [comment]
@danielnelson not in 1.10.3 ? when can I expect 1.11.0 to be cut ? or can this get put into the next minor ?

**Comment by danielnelson** [comment]
1.11 should be released near the beginning of June, this isn't something we would put into a patch release but it should be easy to create a [custom package with docker](https://github.com/influxdata/telegraf/wiki/Packaging) or you can use one of the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds)

**Pull request merged**
