### PR TITLE
fix!: Remove deprecated plugins

### PR DESCRIPTION
**Pull request by reimda**
Remove the plugins listed in #9478.  Since this breaks compatibility, it will not be merged until the next major release (2.0).

Telegraf will also need to tell upgrading users of these plugins to migrate. This PR is a draft because it doesn't handle migration yet.

### CODE REVIEW

**Comment by Hipska** [comment]
What about the `plugins/*/deprecations.go` files?

**Comment by reimda** [comment]
> What about the `plugins/*/deprecations.go` files?

This PR was from before we added deprecations.go. It definitely needs an update

**Comment by Hipska** [comment]
Oh, I see indeed..

**Comment by powersj** [comment]
Closing this to re-open without conflicts + add a change log message with breaking change.

**Pull request closed without merging**
