### PR TITLE
fix: Update SUSE install/remove flags

### PR DESCRIPTION
**Pull request by zmalone**
### Required for all PRs:

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary) (e.g. feat: or fix:)

The SUSE block is only valid for older SUSE releases, https://www.suse.com/support/kb/doc/?id=000019341 has some examples. This provides systemd install/remove steps for systems that identify as a modern SUSE variation.

### CODE REVIEW

**Comment by popey** [comment]
Thanks for the contribution @zmalone 
Looks good to me!

**Comment by powersj** [comment]
!signed-cla

**Comment by sspaink** [comment]
@zmalone can you sign the CLA please? Then we can merge it, thanks for the contribution!

**Comment by sspaink** [comment]
!signed-cla

**Comment by srebhan** [comment]
@zmalone do you still have interest in getting this merged?

**Pull request closed without merging**
