### PR TITLE
#2861 - sqlserver input plugin not working with Azure SQL

### PR DESCRIPTION
**Pull request by regevbr**
#2861 - sqlserver input plugin not working with Azure SQL

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

### CODE REVIEW

**Comment by deluxor** [comment]
I will test your PR later, and i'll post some feedback

**Comment by regevbr** [comment]
Thanks @deluxor

**Comment by regevbr** [comment]
Im still not done with the PR, please wait for me to let you know im done

**Comment by regevbr** [comment]
@deluxor Im done - added a param "disable_parallel" that iwll cause all queries within a server to run one by one - this is for some reason needed by Azure SQL. 
In addition, added a needed first simple query to sustain the session to the DB.
In addition, to save resources, each server will have a single connection open to it, instead of 1.
And finally, to resolve the missing sys views, added to the queries options to ignore those views if they don't exist

**Comment by deluxor** [comment]
Great, I'll give it a try and back to you soon.

**Comment by regevbr** [comment]
The reason I added the "SELECT @@VERSION" comes from https://github.com/denisenkom/go-mssqldb/issues/217
I replaces the mssql driver because of what @zensqlmonitor said in https://github.com/influxdata/telegraf/issues/2852

**Comment by regevbr** [comment]
The new plugin is running in my production env for a few hours now and it works prefect

**Comment by danielnelson** [comment]
Is this because we are recreating a new connection pool every gather?  We have an in progress PR to add this to postgres #2701, would this method work here?

**Comment by regevbr** [comment]
That was not the issue here, but it will make sense to implement the behavior here as well... 
There waa a misuse of the connection as it was created per query, which i fixed, but having a global connection will make it better, but I think it belongs to a different pull request

**Comment by danielnelson** [comment]
Okay, so previously we would create multiple new connections per Gather.  With this change we can use a single new connection per Gather?

I don't really want an option to control if queries are run in parallel.  I'm not experienced with the go sql library but it would make more sense to me to be able to configure the connection pool size that is used for the life of the plugin.

**Comment by regevbr** [comment]
Yes, single connection per connection string per gathering. Currently every run of the gather method, a new connection is being open, if we want one connection it ia a different request. 
As to the parallel queries, it is required to run the queries im sequential order for the DOS mechanism not to get triggered

**Comment by danielnelson** [comment]
I think adding this option as is leaks too much detail about the implementation.  What if we added an option called `max_connections`?  For now we could use a semaphore to limit the connections to this amount but in the future if we add support for a stored connection pool later it would still apply.

**Comment by regevbr** [comment]
Sounds good to me, I will fix the pull request

**Comment by danielnelson** [comment]
I believe this was addressed in #3618

**Pull request closed without merging**
