### PR TITLE
new input plugin: x509_crl - shamefully inspired from x509_cert

### PR DESCRIPTION
**Pull request by jcgonnard**
### Required for all PRs:

- [ x] Signed [CLA](https://influxdata.com/community/cla/).
- [ x] Associated README.md updated.
- [ x] Has appropriate unit tests.

### CODE REVIEW

**Comment by jcgonnard** [comment]
Hello

is there anything to do for the pull request to be merged into master ? 

Thanks

**Comment by sjwang90** [comment]
This plugin doesn't have a huge audience and is therefore lower in our priority to review. However, it would thus look like a great candidate for an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md). Would you be willing to submit this plugin as an [external plugin](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf? Telegraf users would be able to use the plugin sooner by having it as an external plugin since it wouldn't have to go through the typical review process. 

Feel free to respond with any questions you may have.

**Comment by sjwang90** [comment]
@jcgonnard Due to the low interest of the plugin we would really like this plugin as an external plugin as mentioned in the previous comment. Please submit it as an external plugin or else we will look to close this issue.

**Comment by jcgonnard** [comment]
Hi
Thanks for your reply, I'm trying to compile as an external module but I can't compile yet

My repository is there:
https://github.com/jcgonnard/telegraf-input-x590crl

I'm facing this issue while compiling:
```
$ go build -o x509crl cmd/main.go
go: finding github.com/jcgonnard/telegraf-input-x590crl latest
go: finding github.com/influxdata/telegraf/plugins/common latest
go: finding github.com/influxdata/telegraf/plugins/common/shim latest
go: finding github.com/influxdata/telegraf/plugins latest
build command-line-arguments: cannot load github.com/influxdata/telegraf/plugins/common/shim: no matching versions for query "latest"
```

**Comment by sjwang90** [comment]
@ssoroka Do you have any insights into why @jcgonnard might be running into their compiling problem?

**Pull request closed without merging**
