### PR TITLE
Flume input plugin

### PR DESCRIPTION
**Pull request by Icarus0xff**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Thanks for the pull request @hikkikuma1991, could you modify the HTTP client to use a non-default Transport and add SSL/TLS support?  A good example of this is in the nginx plugin: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/nginx/nginx.go#L63

Also, can you add some unit tests for the example JSON?  Again you could base it on the nginx tests: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/nginx/nginx_test.go

**Comment by AAbouZaid** [comment]
Well, I create [Flume plugin](https://github.com/AAbouZaid/telegraf/blob/flume_input_plugin/plugins/inputs/flume/flume.go) 2 weeks ago but didn't find time to push it :joy: 
But at least it's here now :tada: 

I will make some PR to @hikkikuma1991 repo to add some useful parts like:
- Multi urls/servers.
- Filtering.
- Numerical output (not string as they come from Flume metrics API).

@hikkikuma1991 I'd suggest default behavior to be collecting all metrics, and make option to filter them in case that needed, because in Flume the metrics could be extended with extra classes.

**Comment by AAbouZaid** [comment]
@danielnelson I have a question.
I do see the HTTP client part again and again in many plugins, shouldn't this be a library or so to make it easier to use it?

**Comment by danielnelson** [comment]
> I do see the HTTP client part again and again in many plugins, shouldn't this be a library or so to make it easier to use it?

Yes, likely.  I'll try to work something out soon.

**Comment by russorat** [comment]
@hikkikuma1991 looks like according to the flume docs, monitoring is still a work in progress: https://flume.apache.org/FlumeUserGuide.html#monitoring

We'll probably hold off merging this until more people are using it or the flume monitoring stabilizes.

**Comment by sjwang90** [comment]
Looks like monitoring for flume is still a work in progress. Considering it's been a couple years and still hasn't been updated may be better to have this as [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md).

**Comment by sjwang90** [comment]
Closing this issue due to inactivity and the low priority of this issue.

If you would still like this plugin, please submit it as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf.

**Pull request closed without merging**
