### PR TITLE
fix(outputs.nebius_cloud_monitoring): fx endpoint

### LINKED ISSUE #14134: outputs.nebius_cloud_monitoring: metadata endpoint has been changed in near future
### Relevant telegraf.conf

```toml
[[outputs.nebius_cloud_monitoring]]
```

### Logs from Telegraf

```text
Oct 17 15:01:03 telegraf-vm telegraf[724]: 2023-10-17T15:01:03Z I! Loaded inputs: cpu disk diskio kernel mem processes swap system
Oct 17 15:01:03 telegraf-vm telegraf[724]: 2023-10-17T15:01:03Z I! Loaded aggregators:
Oct 17 15:01:03 telegraf-vm telegraf[724]: 2023-10-17T15:01:03Z I! Loaded processors:
Oct 17 15:01:03 telegraf-vm telegraf[724]: 2023-10-17T15:01:03Z I! Loaded secretstores:
Oct 17 15:01:03 telegraf-vm telegraf[724]: 2023-10-17T15:01:03Z I! Loaded outputs: nebius_cloud_monitoring
Oct 17 15:01:03 telegraf-vm telegraf[724]: 2023-10-17T15:01:03Z I! Tags enabled: host=telegraf-vm
Oct 17 15:01:03 telegraf-vm telegraf[724]: 2023-10-17T15:01:03Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"telegraf-vm", Flush Int
erval:10s
Oct 17 15:01:03 telegraf-vm telegraf[724]: 2023-10-17T15:01:03Z I! [outputs.nebius_cloud_monitoring] Writing to Nebius.Cloud Monitoring URL: ht
tps://monitoring.api.il.nebius.cloud/monitoring/v2/data/write
Oct 17 15:01:03 telegraf-vm telegraf[724]: 2023-10-17T15:01:03Z I! [outputs.nebius_cloud_monitoring] FolderID: b48bnn3jtboj8vb5uv8n
Oct 17 15:01:03 telegraf-vm systemd[1]: Started Telegraf.
```

### System info

Telegraf 1.28.2 Ubuntu 22.04.3 LTS

### Docker

_No response_

### Steps to reproduce

Now it's works well

### Expected behavior

Endpoint URL must be changed due to rebranding.

### Actual behavior

Now it's working

### Additional info

Support team said to me that now metadata endpoint for fetchinf Folder ID will be changed to 
`http://169.254.169.254/computeMetadata/v1/instance/vendor/folder-id`

### PR DESCRIPTION
**Pull request by abrekhov**
# Required for all PRs

- [X] Updated associated README.md.
- [X] Wrote appropriate unit tests.
- [X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #14134 

New endpoint works like this:
```bash
curl -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/vendor/folder-id
b48bnn3jtboj8vb5uv8n
```

### CODE REVIEW

**Review by powersj — COMMENTED** [review]
Thanks for this. Do you have an ETA as to when this will change?

Additionally, will the previous URL work for anyone? like older running instances? If so would, we need to try both?

Thanks!

**Comment by abrekhov** [comment]
> Thanks for this. Do you have an ETA as to when this will change?
> 
> Additionally, will the previous URL work for anyone? like older running instances? If so would, we need to try both?
> 
> Thanks!

Here is answer from support on this. 

image

So some time they will work both.

**Review by powersj — APPROVED** [review]

**Comment by powersj** [comment]
Thanks for following up on those details!

**Review by srebhan — APPROVED** [review]
Thanks for the fix @abrekhov!

**Pull request merged**
