### PR TITLE
updated ZFS measurements for ZFS on Linux version 0.7.1

### PR DESCRIPTION
**Pull request by richardelling**
### Required for all PRs:

- [ x] Signed [CLA](https://influxdata.com/community/cla/).
- [ x] Associated README.md updated.
- [ x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
I know this has some overlap with #2623, @tomtastic can you review?

**Comment by tomtastic** [comment]
@danielnelson As this PR includes the zil stats collection, I'm happy for it to replace #2623, but the checks are failing, can't tell why from looking at the circleci details, @richardelling are all your unit tests OK ?

**Comment by richardelling** [comment]
@tomtastic my unit tests pass, but it seems the CI fails on pull from my repo?

IMHO, this PR can replace #2623 and there are more stats in the pipeline. I'll be happy to collaborate.

**Comment by tomtastic** [comment]
No need to collaborate @richardelling, unless you can fix my zpool unit tests for issue #2616? 😁

**Pull request merged**
