### PR TITLE
feat(inputs.knx_listener): support TCP as transport protocol

### PR DESCRIPTION
**Pull request by alexander-zimmermann**
- [x] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

### CODE REVIEW

**Comment by srebhan** [comment]
Thanks for your contribution @alexander-zimmermann! 
Can you please run `make tidy` to make CI tests happy? Furthermore, how about adding `"tunnel_tcp"` as service type instead of adding another option? This would also get rid of the combinatorics and eases error checking... What do you think?

**Comment by alexander-zimmermann** [comment]
- Should I combine `go mod tidy` output w/ the bump commit or do you prefer a dedicated commit?
- Regarding service type... you mean something like tunnel_udp, tunnel_tcp and router?

**Comment by srebhan** [comment]
> Should I combine go mod tidy output w/ the bump commit or do you prefer a dedicated commit?

You can do an extra commit. The PR is squashed on merge anyway...

> Regarding service type... you mean something like tunnel_udp, tunnel_tcp and router?

Yeah exactly. Please note we need to keep backward compatible so we can go with `tunnel` (i.e. `tunnel_tcp`), `router` and `tunnel_udp` or additionally add `tunnel_tcp` with `tunnel` being a synonym for it...

**Comment by alexander-zimmermann** [comment]
@srebhan The changes are ready. Unfortunately, I did my last PR on my master instead of a dedicated feature branch. AFAIS the update pull request feature from Github is only working w/ branches and not w/ master. The only option I see is to close this PR and create a new only. Am I right?

**Comment by srebhan** [comment]
Sure, please feel free to open a new one and drop me a note where to find it. You should then also close this one with a link to the follow up...

**Comment by alexander-zimmermann** [comment]
closed by https://github.com/influxdata/telegraf/pull/11783

**Pull request closed without merging**
