### PR TITLE
Adding sonic_telemetry input plugin

### PR DESCRIPTION
**Pull request by wililupy**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.
Details to this pull request can be found in Issue: [https://github.com/influxdata/telegraf/issues/7472](https://github.com/influxdata/telegraf/issues/7472)

### CODE REVIEW

**Comment by skg-net** [comment]
@danielnelson  can we get this merged?

**Comment by wililupy** [comment]
Merged dynamic tagging to sonic_telemetry input plugin. 

Also, what work needs to be done so that this can be merged with master?

**Comment by smackdabinthesquash** [comment]
This plugin is essential for those of us running telegraf in a SONiC environment. Can this please be merged as soon as possible? Thanks! @danielnelson

**Comment by skg-net** [comment]
@wililupy  can you please resolve the conflicts?

**Comment by wililupy** [comment]
> @wililupy can you please resolve the conflicts?

I have resolved the conflicts with exception to the MacDeps. This conflict is due to my account on CircleCI is a free account and does not have access to test on MacOS.

**Comment by srebhan** [comment]
@wililupy Maybe this is a stupid question, but what is the difference to the `inputs/gnmi` plugin? If there are differences, is it possible to handle this in the existing plugin? If no, why?

**Comment by wililupy** [comment]
> @wililupy Maybe this is a stupid question, but what is the difference to the `inputs/gnmi` plugin? If there are differences, is it possible to handle this in the existing plugin? If no, why?

We built this plugin based on the Cisco GNMI plugin, but had to modify it slightly to work with SONiC. I have not checked to see if the GNMI plugin in inputs works correctly or not.

We have also added some FRR functions into the SONiC telemetry plugin to be able to get FRR statistics on BGP.

**Comment by skg-net** [comment]
@danielnelson @wililupy @bewing @evanphx @ibspoof This PR for this sitting for more than 6 months. Can we get this merged? Whom we need to follow up with?
https://github.com/influxdata/telegraf/pull/7473

**Comment by sjwang90** [comment]
@wililupy Based off the reviews, this plugin is too close in functionality to `inputs.gnmi` for us to merge it in as it as it will result in two very similar plugins. 

Can you change your PR to add the additional features as backwards extensions to the existing `inputs.gnmi` plugin so people can optionally configure to retrieve the FRR statistics?

**Comment by wililupy** [comment]
> @wililupy Based off the reviews, this plugin is too close in functionality to `inputs.gnmi` for us to merge it in as it as it will result in two very similar plugins.
> 
> Can you change your PR to add the additional features as backwards extensions to the existing `inputs.gnmi` plugin so people can optionally configure to retrieve the FRR statistics?

@sjwang90 When I tried to merge my input with the inputs.gnmi, it doesn't pull the correct stats from the SONiC switch and fails. I fear that if I make these changes, then generic gnmi for other devices may fail, which is why I recommend keeping it separate. 
Let me discuss this internally with our teams to see if we should change our implementation of gnmi.

As for the FRR addins, those should be fine, but they are not using gnmi to pull these statistics, and instead are pulling them directly from FRR, and I don't think these would be a good fit. 

I can rename the input to just SONiC telemetry. Does that make sense?

**Comment by srebhan** [comment]
@wililupy I think the PR is two in one. How about having the FRR part as an own plugin (e.g. `inputs/sonic`) and try to merge the GNMI part to the `inputs/gnmi` plugin.

For the latter you maybe can add a `flavor` or `dialect` option to the existing plugin that fence the differences between the generic part and your specialized part. Does this make any sense?

**Comment by wililupy** [comment]
> @wililupy I think the PR is two in one. How about having the FRR part as an own plugin (e.g. `inputs/sonic`) and try to merge the GNMI part to the `inputs/gnmi` plugin.
> 
> For the latter you maybe can add a `flavor` or `dialect` option to the existing plugin that fences the differences between the generic part and your specialized part. Does this make any sense?

@srebhan We can test this and I will update the PR based on what we find.

Thanks!

**Comment by wililupy** [comment]
Hello,

So we found during our testing of the input/gnmi plugin that it doesn't work with attributes of type 64 bit integers. json_ietf encodes 64 bit integers as strings and this needs a conversion to work. So we are looking at creating a patch for the input/gnmi plugin to support this and then for the FRR pieces that we had in the inputs/sonic_telemetry plugin, we will remove them and create a generic FRR input. 

So what I can do if it makes sense is create 2 new PR's, one for the update to the inputs/gnmi plugin and create a new inputs/frr plugin. 

Does that sound like a good way to move forward?

/r Luke

**Comment by srebhan** [comment]
@wililupy that sounds perfect to me. If it's easier for you to reuse this PR for any of the two please feel free to do so. Whatever is more convenient for you.

**Comment by srebhan** [comment]
@wililupy any news on the matter?

**Pull request closed without merging**
