### PR TITLE
Handle process termination during read from /proc

### LINKED ISSUE #2815: inputs.processes fails with "no such process"
## Bug report

Our Telegraf installations occasionally produce error messages like the following:

    E! ERROR in input [inputs.processes]: read /proc/16314/stat: no such process

The error is triggered when a process is terminated while `readProcFile` (`plugins/inputs/system/processes.go`) is reading the process's `/proc/<pid>/stat` file.

### System info:

All versions including the current master.

### Steps to reproduce:

The bug is triggered by a race condition so it's quite hard to reproduce in Telegraf (we get 10-20 errors per day from 500+ hosts), but here's a little test program that uses a copy of `readProcFile` to demonstrate the issue.

```go
package main

import (
    "fmt"
    "io/ioutil"
    "log"
    "os"
    "os/exec"
)

type reproductionType int

// Copied from plugins/inputs/system/processes.go
func readProcFile(filename string) ([]byte, error) {
    data, err := ioutil.ReadFile(filename)
    if err != nil {
        if os.IsNotExist(err) {
            return nil, nil
        }

        return nil, err
    }

    return data, nil
}

func main() {
    // Start cat with an open stdin pipe to keep the process running.
    cat := exec.Command("cat")
    catStdin, err := cat.StdinPipe()
    if err != nil {
        log.Fatal(err)
    }

    err = cat.Start()
    if err != nil {
        log.Fatal(err)
    }

    // In the background, close cat's stdin to make it terminate and wait for
    // the process to exit.
    isOpen := true
    go func() {
        catStdin.Close()
        cat.Wait()
        isOpen = false
    }()

    // As long as cat hasn't been terminated, keep rereading its stat file
    // from /proc.
    for isOpen {
        _, err = readProcFile(fmt.Sprintf("/proc/%d/stat", cat.Process.Pid))
        if err != nil {
            log.Fatal(err)
        }
    }
}
```

Running the test program multiple times tends to cause at least one failure:

    $ for x in $(seq 10); do echo $x; ./proctest; done
    1
    2
    3
    4
    5
    2017/05/16 14:00:45 read /proc/22710/stat: no such process
    6
    2017/05/16 14:00:45 read /proc/22716/stat: no such process
    7
    8
    9
    10
    2017/05/16 14:00:45 read /proc/22740/stat: no such process

### Expected behavior:

Telegraf already checks for process termination between listing the `/proc/*/stat` files and reading them. Process termination between `open()` and `read()` should be handled the same way (i.e. without errors).

### Actual behavior:

    E! ERROR in input [inputs.processes]: read /proc/16314/stat: no such process

### PR DESCRIPTION
**Pull request by noidi**
Fixes #2815.

### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by phemmer** [comment]
This might be worth reporting upstream to GO that it should be handled by `os.IsNotExist()`. Yes `os.IsNotExist()` is typically only useful on `Open()`, but I think the semantics of the function apply here, as the ESRCH means that the file has disappeared.

**Comment by noidi** [comment]
Personally, I don't think `os.IsNotExist()` should check for `ESRCH`. Currently it only checks for `ENOENT` [1], which (at least on Linux) is reserved for path operations [2], so I think it's meant to detect errors caused by operations on non-existent paths. In this case the path does exist during `open()`, but the corresponding process is terminated while (or before) `read()` is being called on the opened file descriptor, causing something akin to an I/O error.

[1] https://github.com/golang/go/blob/964639cc338db650ccadeafb7424bc8ebb2c0f6c/src/os/error_unix.go#L18
[2] https://lkml.org/lkml/2012/12/23/75

**Comment by danielnelson** [comment]
Interesting issue, I always thought that if open succeeded you were good to read.  It sounds like this could occur with any file in `/proc/<pid>/`,  Are there any other files this could happen with?

**Comment by danielnelson** [comment]
Whoops, I forgot to ask you to add it the changelog, I'll add it

**Comment by noidi** [comment]
@danielnelson Thanks for the merge! I don't have much experience with `/proc/<pid>/` but I'd be surprised if the other files didn't work this way. I did some cursory grepping and I think this was the only place in the Telegraf source code where this could be a problem.

**Pull request merged**
