### PR TITLE
Added Cmdline to procstat

### LINKED ISSUE #1873: get full process path via procstat as TAG
### System info:

[Include Telegraf version, operating system name, and other relevant details]
telegraf-1.0.0-1.x86_64
RHEL6
## Feature Request

include command_line as a field collected from procstat . 
### Proposal:

get the full command line from  /proc/*/cmdline . return the contents of this file as a tag.
### Current behavior:

returns only the short name for the process and pid as the identifier of the process. 
### Desired behavior:

list the full process path as tag so that you may identify which process is which 
### Use case: [Why is this important (helps with prioritizing requests)]

for example you run a java application, procstat current captures "java" as the process name. This is fine if your run one of something but it very common in enterprise architecture to run multiples of something with different configs file/arguments . Capturing only java make it impossible (or very hard) to differentiate between them for resource usage.

### PR DESCRIPTION
**Pull request by akrus**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [X] Has appropriate unit tests.

As a first approach to #1873, this PR adds cmdline with full command line of process as field. Not sure what should be updated in README.md. Adding as a tag is easy, but needs test change, so I'm afraid I need some assistance there.

### CODE REVIEW

**Comment by scottprichard** [comment]
it looks like the unit tests didn't even run, some docker image was not found.. any ideas? I for one would like to see this feature in telegraf as I have have had to push out a bunch of procstat config that will be completely unnecessary once this is in. So far I have only used it in test and would like to avoid pushing all that config into prod in favor of this.. Thanks for anyone who is working on this, you guys rock.

**Comment by glinton** [comment]
image

Apparently circle won't be able to build this until this branch gets updated with master.

**Comment by scottprichard** [comment]
hey @akrus looks like you need to pull master in and re-kick the build as @glinton mentioned. If you could that would be awesome, if not let us know and I'll fork it and sign that CLA and attempt to re-kick with your changes. Hopefully should be an easy merge if you haven't touched it since, which seems to be the case with your forked repo.

**Comment by glinton** [comment]
Closing in favor of #5681

**Pull request closed without merging**
