### PR TITLE
Add option for explicitly including queries in sqlserver input plugin.

### PR DESCRIPTION
**Pull request by HarshitOnGitHub**
Fixes: #6979.
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Try using [NewIncludeExcludeFilter](https://github.com/influxdata/telegraf/blob/master/filter/filter.go#L86), we use this in other plugins and it should give the expected behavior.

**Comment by HarshitOnGitHub** [comment]
Yeah makes sense, updated! :)

**Comment by HarshitOnGitHub** [comment]
@danielnelson Further, can you point me to some small issues that I can try my hands on? :)

**Comment by danielnelson** [comment]
Thanks for the offer to help.  The best issues to look at are the ones with the [ready label](https://github.com/influxdata/telegraf/labels/ready).  Ignore any that have an assignee, the rest are available but add a comment before you get in too deep so others will know you are looking into it.  You can also check issues with the [bug label](https://github.com/influxdata/telegraf/labels/bug).

**Pull request merged**
