### PR TITLE
feat: changelog generation

### PR DESCRIPTION
**Pull request by sspaink**
Adding a way to generate the changelog by running: `make changelog` 

benefit are: 
- moves this logic out of internal tooling, now anyone can see the potential changelog anytime
- entirely written in Go
- supports conventional commit messages
- auto-detect scope if missing (e.g. inputs.docker)

originally I was looking into using https://github.com/git-chglog/git-chglog,  but the project doesn't seem that active so maybe we can re-consider it in the future. We only need a subset of its features so I re-implemented a smaller version that we can use. The first few comments on this PR are related to this initial implementation using git-chglog.

Example updated CHANGELOG.md to include v1.22.0 with current implementation:
https://gist.github.com/sspaink/14b6893aad8419d1bbee8dab71a95072

Maybe in the future we can have the bot maintain a github gist (or something similar) every time master is updated and have it linked in the readme.

### CODE REVIEW

**Comment by sjwang90** [comment]
Nice! Here's some feedback based off the structure of existing changelog. Just focused on the 1.22.0 section. 

- Group dependencies updates together
- Group and highlight new plugins (New Inputs, New Outputs...)
  - @ the author for these new plugins
- Having the plugin (`inputs.`) at the beginning of each bullet that the feature/bug fix impacted was really nice to have
- There seem to be a lot of "update etc/telegraf.conf and etc/telegraf_windows.conf" PRs. I don't know if it's specific to recent work or this is continuous work that is done. Either way, I don't think this stuff needs to be included in the changelog.

**Comment by sspaink** [comment]
@sjwang90 responses for your feedback, made some changes to the changelog as well: https://github.com/influxdata/telegraf/blob/changeloggen/CHANGELOG.md

- Grouping dependency updates is possible by just sorting alphabetically. Pushed a change to show how that would look like.
- Grouping and highlighting new plugins is tricky, there isn't anything to distinct a new plugin I could add a regex to grab titles with (New .* Plugin) but that isn't going to guarantee anything. Maybe we can enforce a scope for new plugins (e.g. `feat(new): adding new plugin`).
   - For @ authors, we do get the username from git but it isn't guaranteed to be the github username. Proposal is to maybe just have a list of every name bellow the section thanking anyone who made a commit? I pushed a change showing how that would like as well.
- So that is already happening, IF the commit message included a scope (e.g. `feat(inputs.docker): blah blah`) I think we will need to enforce this within the commit message before merging PR's
- Agreed, "update etc/telegraf.conf and etc/telegraf_windows.conf" is made by the tiger bot I updated the template to ignore them and set it up in a way to add other commits to ignore as well

**Comment by sspaink** [comment]
Notes for next steps, We could run the following command: `git-chglog --next-tag v1.22.0 -o CHANGELOG.md v1.22.0..` and then that will only generate the section for the next release and then write a separate tool to append the existing changelog with the newly generated list so that we don't have to worry about the existing changelogs format. Then we can edit the generated changelog in case it needs some human refinement before commit it. And then the next time we run the tool it won't overwrite anything.

I know people are interested in seeing what will be included in the next release, so keeping the changelog updated frequently is probably a good idea. Maybe we can update it weekly?

**Comment by sspaink** [comment]
Example updated CHANGELOG.md to include v1.22.0 with current implementation running:
[CHANGELOG.md](https://github.com/influxdata/telegraf/files/8212044/CHANGELOG.md)

**Comment by Hipska** [comment]
Sounds good, could you re-add a current generated CHANGELOG.md, so we also can see what the latest results would be?

**Comment by Hipska** [comment]
Okay, still seems to have some minor issues then:
image

**Pull request closed without merging**
