### PR TITLE
feat: run govulncheck nightly on master branch

### PR DESCRIPTION
**Pull request by powersj**
Add additional method for scanning the project for possible known vulnerabilities. Run nightly to see if anything known has come up. See the following URL for a full breakdown on the tooling:

https://go.dev/security/vuln/

### CODE REVIEW

**Comment by powersj** [comment]
The version of go used matters. For example, when I ran with go1.19.1 I found a number of issues I'll link below, but as soon as I upgraded to go1.19.2 I got no vulnerabilities found.

```
Scanning for dependencies with known vulnerabilities...
Found 2 known vulnerabilities.

Vulnerability #1: GO-2022-1037
  Reader.Read does not set a limit on the maximum size of file
  headers. A maliciously crafted archive could cause Read to
  allocate unbounded amounts of memory, potentially causing
  resource exhaustion or panics. After fix, Reader.Read limits the
  maximum size of header blocks to 1 MiB.

  Call stacks in your code:
      config/config.go:330:22: github.com/influxdata/telegraf/config.Config.LoadDirectory calls path/filepath.Walk, which eventually calls archive/tar.Writer.WriteHeader
      plugins/outputs/cloud_pubsub/topic_gcp.go:31:15: github.com/influxdata/telegraf/plugins/outputs/cloud_pubsub.topicWrapper.Stop calls cloud.google.com/go/pubsub.Topic.Stop, which eventually calls archive/tar.Reader.Next

  Found in: archive/tar@go1.19.1
  Fixed in: archive/tar@go1.19.2
  More info: https://pkg.go.dev/vuln/GO-2022-1037

Vulnerability #2: GO-2022-1039
  Programs which compile regular expressions from untrusted
  sources may be vulnerable to memory exhaustion or denial of
  service. The parsed regexp representation is linear in the size
  of the input, but in some cases the constant factor can be as
  high as 40,000, making relatively small regexps consume much
  larger amounts of memory. After fix, each regexp being parsed is
  limited to a 256 MB memory footprint. Regular expressions whose
  representation would use more space than that are rejected.
  Normal use of regular expressions is unaffected.

  Call stacks in your code:
      plugins/inputs/directory_monitor/directory_monitor.go:406:31: github.com/influxdata/telegraf/plugins/inputs/directory_monitor.DirectoryMonitor.Init calls regexp.Compile, which eventually calls regexp/syntax.Parse

  Found in: regexp/syntax@go1.19.1
  Fixed in: regexp/syntax@go1.19.2
  More info: https://pkg.go.dev/vuln/GO-2022-1039

=== Informational ===

The vulnerabilities below are in packages that you import, but your code
doesn't appear to call any vulnerable functions. You may not need to take any
action. See https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
for details.

Vulnerability #1: GO-2022-1038
  Requests forwarded by ReverseProxy include the raw query parameters from
  the inbound request, including unparseable parameters rejected by net/http.
  This could permit query parameter smuggling when a Go proxy forwards a
  parameter with an unparseable value.

  After fix, ReverseProxy sanitizes the query parameters in the forwarded
  query when the outbound request's Form field is set after the ReverseProxy.
  Director function returns, indicating that the proxy has parsed the query
  parameters. Proxies which do not parse query parameters continue to forward
  the original query parameters unchanged.

  Found in: net/http/httputil@go1.19.1
  Fixed in: net/http/httputil@go1.19.2
  More info: https://pkg.go.dev/vuln/GO-2022-1038
```

**Comment by zak-pawel** [comment]
I run it locally using `1.19.1` for `master` and few old branches (which for sure have some vulnerabilities). 

For every case `govulncheck` ate all available cores and memory on my VM (8 cores, 16GB of memory), found nothing and got killed:
```
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Scanning for dependencies with known vulnerabilities...
[1]    30975 killed     govulncheck ./...
```

**Comment by zak-pawel** [comment]
> The version of go used matters. For example, when I ran with go1.19.1 I found a number of issues I'll link below, but as soon as I upgraded to go1.19.2 I got no vulnerabilities found.

@powersj 
I believe that all these vulnerabilities found for `1.19.1` were fixed in `1.19.2` so that's why for `1.19.2` there aren't any ;)

> ```
>   Found in: archive/tar@go1.19.1
>   Fixed in: archive/tar@go1.19.2
> 
>   Found in: regexp/syntax@go1.19.1
>   Fixed in: regexp/syntax@go1.19.2
> 
>   Found in: net/http/httputil@go1.19.1
>   Fixed in: net/http/httputil@go1.19.2
> ```

**Comment by zak-pawel** [comment]
@powersj And it makes a lot of sense, because these goversion-specific vulnerabilities at the end land in Telegraf binary.

Before every release, we need to be sure that we use latest-greatest version of `go` to build packages (which will also land in docker images).

**Review by MyaLongmire — APPROVED** [review]

**Pull request merged**
