### PR TITLE
Fix metric creation when node is offline in jenkins input

### LINKED ISSUE #6578: jenkins node doesnt appear as offline
### Relevant telegraf.conf:

```toml
[[inputs.jenkins]]
  ## The Jenkins URL
  url = "https://some-url"
  username = "username"
  password = "password"
  ## Set response_timeout
  response_timeout = "10s"
```

### System info:

Telegraf Version: 1.11.4
Jenkins Version: 2.89.4

### Steps to reproduce:

1. Add Docker node to Jenkins
2. Shutdown the node
3. Execute telegraf to test the config _telegraf --test --config=config.conf_

### Expected behavior:
The Jenkins plugin in telegraf should get the node as offline
`jenkins_node,arch=Linux\ (amd64),disk_path=/home/jenkins,node_name=displayName,status=offline, ....`

### Actual behavior:
The Jenkins plugin shows the error:
`Error in plugin: empty monitor data, please check your permission`

### Additional info:
The same user is used by the plugin and to get the the following response snippet of the API which is called by the plugin
```json
      {
         "_class":"hudson.slaves.SlaveComputer",
         "actions":[
            {

            },
            {

            },
            {

            }
         ],
         "description":"",
         "displayName":"displayName",
         "executors":[
            {

            }
         ],
         "icon":"computer-x.png",
         "iconClassName":"icon-computer-x",
         "idle":true,
         "jnlpAgent":false,
         "launchSupported":true,
         "loadStatistics":{
            "_class":"hudson.model.Label$1"
         },
         "manualLaunchAllowed":true,
         "monitorData":{
            "hudson.node_monitors.SwapSpaceMonitor":null,
            "hudson.node_monitors.TemporarySpaceMonitor":null,
            "hudson.node_monitors.DiskSpaceMonitor":null,
            "hudson.node_monitors.ArchitectureMonitor":null,
            "hudson.node_monitors.ResponseTimeMonitor":{
               "_class":"hudson.node_monitors.ResponseTimeMonitor$Data",
               "timestamp":1571985314769,
               "average":5000
            },
            "hudson.node_monitors.ClockMonitor":null
         },
         "numExecutors":1,
         "offline":true,
         "offlineCause":{
            "_class":"hudson.node_monitors.ResponseTimeMonitor$Data"
         },
         "offlineCauseReason":"5 mal keine Antwort",
         "oneOffExecutors":[

         ],
         "temporarilyOffline":false
      }
```

The error from the plugin is thrown because is _hudson.node_monitors.ArchitectureMonitor_ is _null_.

### PR DESCRIPTION
**Pull request by danielnelson**
closes #6578 

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@ctNb Would you be able to test out this fix with your offline node?  My Jenkins setup only has a single node right now.  Here are some builds, let me know if you need a different one:

- [telegraf-1.13.0~c2ee8640_linux_amd64.tar.gz](https://43107-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.13.0~c2ee8640_linux_amd64.tar.gz)
- [telegraf_1.13.0~c2ee8640-0_amd64.deb](https://43107-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.13.0~c2ee8640-0_amd64.deb)
- [telegraf-1.13.0~c2ee8640-0.x86_64.rpm](https://43107-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.13.0~c2ee8640-0.x86_64.rpm)

**Comment by ctNb** [comment]
i just tested the telegraf client on ubuntu and it seems not to work as expected. The offline node still doesn't show up.
I don't know how the accumulator exactly works, but is it possible that a metric is not getting listed when no fields are added? Because "status" is a tag and all other fields are in my case null (the API snippet in the issue shows this).
I am still testing some cases to be sure there is no error on my side

**Comment by danielnelson** [comment]
This is true, metrics without any fields are completely removed as they pass through Telegraf.  I was expecting that the `response_time` field would still remain though.  Let me know if you figure anything out and in the meantime I'll work on getting a better Jenkins test environment together.

**Comment by ctNb** [comment]
i am also setting up a clean test environment. I've installed the latest jenkins docker image and just added a node, which is not even existing. Jenkins shows this node in the GUI and API also as offline. When running now telegraf the node is also not shown.
Maybe the solution is to add something like in the "http_response" plugin, which contains a "result" tag and a "result_code" as a field.

**Comment by danielnelson** [comment]
Here is my output from an offline slave, so it seems that the response time monitor doesn't stick around for long, or maybe it stays only after some failures.
```json
{
	"_class": "hudson.slaves.SlaveComputer",
	"absoluteRemotePath": null,
	"actions": [
		{}
	],
	"assignedLabels": [
		{
			"name": "slave"
		}
	],
	"description": "",
	"displayName": "slave",
	"executors": [
		{}
	],
	"icon": "computer-x.png",
	"iconClassName": "icon-computer-x",
	"idle": true,
	"jnlpAgent": false,
	"launchSupported": true,
	"loadStatistics": {
		"_class": "hudson.model.Label$1"
	},
	"manualLaunchAllowed": true,
	"monitorData": {
		"hudson.node_monitors.ArchitectureMonitor": null,
		"hudson.node_monitors.ClockMonitor": null,
		"hudson.node_monitors.DiskSpaceMonitor": null,
		"hudson.node_monitors.ResponseTimeMonitor": null,
		"hudson.node_monitors.SwapSpaceMonitor": null,
		"hudson.node_monitors.TemporarySpaceMonitor": null
	},
	"numExecutors": 1,
	"offline": true,
	"offlineCause": {
		"_class": "hudson.slaves.OfflineCause$LaunchFailed"
	},
	"offlineCauseReason": "This agent is offline because Jenkins failed to launch the agent process on it.",
	"oneOffExecutors": [],
	"temporarilyOffline": true
}
```

Adding another field will do the trick. I think for now the safest change, just to address the issue, is to add the `numExecutors` field.  We could think about other fields in the context of a feature request.

**Comment by danielnelson** [comment]
Example output:
```
> jenkins_node,arch=Linux\ (amd64),disk_path=/var/lib/jenkins,node_name=master,status=online,temp_path=/tmp disk_available=517427200,memory_available=1216356352,memory_total=2101669888,num_executors=2i,response_time=0i,swap_available=0,swap_total=0,temp_available=517427200 1573546293000000000
> jenkins_node,node_name=slave,status=offline num_executors=1i 1573546293000000000
```

Updated builds:
- [telegraf-1.13.0~303518b2-0.x86_64.rpm](https://43490-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.13.0~303518b2-0.x86_64.rpm)
- [telegraf-1.13.0~303518b2_linux_amd64.tar.gz](https://43490-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.13.0~303518b2_linux_amd64.tar.gz)
- [telegraf_1.13.0~303518b2-0_amd64.deb](https://43490-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.13.0~303518b2-0_amd64.deb)

**Pull request merged**
