### PR TITLE
Avoid loop creation in second processor pass

### LINKED ISSUE #3629: Telegraf stops publishing metrics to InfluxDB; All plugins take too long to collect
## Bug report

After a seemingly random amount of time, Telegraf stops publishing metrics to InfluxDB over UDP. I have been experiencing this issue since Nov 2016 on both Telegraf 1.3.x and 1.4.4 on FreeBSD, on three separate servers. In the telegraf log, **all** collectors start to fail with 

    Error in plugin [inputs.$name]: took longer to collect than collection interval (10s)

I can't see anything unusual or interesting published from the Telegraf internal metrics.

This same issue has been reported in #3318, #2183, #2919, #2780 and #2870 but all those issues are either abandoned by the requestor, or confused with several separate issues; I am pening a new issue for my specific problem but if it's a duplicate (#3318 seems to be the closest) then please feel free to close
 
### Relevant telegraf.conf:

[telegraf.conf](https://gist.github.com/jgitlin-bt/a240ef53d4a8c2f6fab9b086066228a5)

### System info:

`Telegraf v1.4.4 (git: unknown unknown)` running on FreeBSD 10.3-RELEASE-p24

### Steps to reproduce:

1. `service telegraf start`
2. wait `$random` time period

### Expected behavior:

Telegraf publishes metrics to InfluxDB server over UDP

### Actual behavior:

Telegraf stops publishing metrics seemingly randomly, all input plugins start to fail with:

```
2018-01-02T17:16:50Z E! Error in plugin [inputs.processes]: took longer to collect than collection interval (10s)
2018-01-02T17:16:51Z E! Error in plugin [inputs.apache]: took longer to collect than collection interval (10s)
2018-01-02T17:16:51Z E! Error in plugin [inputs.mem]: took longer to collect than collection interval (10s)
2018-01-02T17:16:51Z E! Error in plugin [inputs.internal]: took longer to collect than collection interval (10s)
2018-01-02T17:16:51Z E! Error in plugin [inputs.system]: took longer to collect than collection interval (10s)
2018-01-02T17:16:51Z E! Error in plugin [inputs.swap]: took longer to collect than collection interval (10s)
2018-01-02T17:16:52Z E! Error in plugin [inputs.cpu]: took longer to collect than collection interval (10s)
2018-01-02T17:16:58Z E! Error: statsd message queue full. We have dropped 1 messages so far. You may want to increase allowed_pending_messages in the config
2018-01-02T17:17:00Z E! Error in plugin [inputs.phpfpm]: took longer to collect than collection interval (10s)
2018-01-02T17:17:00Z E! Error in plugin [inputs.statsd]: took longer to collect than collection interval (10s)
```

### Additional info:

[Full logs and stack trace](https://gist.github.com/jgitlin-bt/9381ba39ccea5e194b016b076ffe4281)

[Earlier occurrence](https://gist.github.com/jgitlin-bt/3d3bc92e841b4a29dacc7efdf80e352e)

[Grafana snapshot of Internal Telegraf metrics](https://snapshot.raintank.io/dashboard/snapshot/Kc2S3qBas1LZJSbGevPeRbNMG6Db6o9D?orgId=2)

### PR DESCRIPTION
**Pull request by danielnelson**
I think this will fix the deadlock when using an aggregator.

closes #3629

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@jgitlin-bt Can you try to reproduce the issue with this patch applied?

**Comment by jgitlin-bt** [comment]
Sure. I will try and work on that tomorrow @danielnelson

**Comment by jgitlin-bt** [comment]
Having some trouble getting this to build under FreeBSD, will update when I have my build issues resolved. I think I have an incompatible version of make installed

```
[jgitlin@tinman telegraf]$ nice make
make: "/usr/home/jgitlin/go/src/github.com/influxdata/telegraf/Makefile" line 5: Need an operator
make: "/usr/home/jgitlin/go/src/github.com/influxdata/telegraf/Makefile" line 7: Need an operator
make: Unknown modifier ','
make: Unknown modifier ','
make: "/usr/home/jgitlin/go/src/github.com/influxdata/telegraf/Makefile" line 9: Need an operator
make: "/usr/home/jgitlin/go/src/github.com/influxdata/telegraf/Makefile" line 14: Need an operator
make: "/usr/home/jgitlin/go/src/github.com/influxdata/telegraf/Makefile" line 16: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/home/jgitlin/go/src/github.com/influxdata/telegraf
```

**Comment by danielnelson** [comment]
@jgitlin-bt You will need GNU Make, or just run the command by hand, or I can build you a snapshot if you like.

**Comment by jgitlin-bt** [comment]
Thanks @danielnelson yeah I think that automake on my team's FreeBSD build server isn't really as "GNU Make compatible" as the manpage says it is ;)

That gets me building, I'll report back if I have any difficulties.

**Comment by jgitlin-bt** [comment]
OK @danielnelson Telegraf v1.6.0~6560edfa (git: aggregator-loop-deadlock 6560edfa) built from this branch is now running on one of our three servers, with the aggregator re-enabled. I'll let you know what happens!

**Comment by jgitlin-bt** [comment]
Almost 48 hours later and Telegraf built from this branch is still going strong! `\o/`

**Pull request merged**
