### PR TITLE
Feature/support pgbouncer

### PR DESCRIPTION
**Pull request by jsvisa**
- [x] CHANGELOG.md updated
- [x] README.md updated

### CODE REVIEW

**Comment by sparrc** [comment]
what does this add that the regular postgres plugin isn't able to provide?

**Comment by sparrc** [comment]
closing for lack of updates

**Comment by jsvisa** [comment]
@sparrc Sorry for the delay.

Yes, the postgres plugin can provide the detail. 

For PgBouncer, all statistics are stored in one database, default as 'pgbouncer', and the backend databases' information are stored in it as regular records. See more from [PgBouncer usage](https://pgbouncer.github.io/usage.html). 

For [telegraf/postgresql.go at master · influxdata/telegraf](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/postgresql/postgresql.go), the command not applied, 

and for [telegraf/postgresql_extensible.go at master · influxdata/telegraf](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/postgresql_extensible/postgresql_extensible.go), it always need `version` information

**Comment by sparrc** [comment]
> For telegraf/postgresql.go at master · influxdata/telegraf, the command not applied,

what does that mean exactly? can you add "the command" to that plugin?

> and for telegraf/postgresql_extensible.go at master · influxdata/telegraf, it always need version information

please also explain more, what do you mean that it always needs version information? why is pgbouncer not compatible with "version information"?

**Comment by jsvisa** [comment]
Sorry for my rudeness. First of all, [pgbouncer/pgbouncer: PgBouncer development](https://github.com/pgbouncer/pgbouncer) is a
> Lightweight connection pooler for PostgreSQL. 

Pgbouncer always store the stat info inside it's own datebase, not in PostgreSQL's side. 
The [stat of PostgreSQL](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/postgresql/postgresql.go#L76-L81) not applied to pgbouncer. 

And in postgresql_extensible.go, we need to fetch the PostgreSQL's version first, then execute the specified query string, but the [version query](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/postgresql_extensible/postgresql_extensible.go#L137)

>query = `select substring(setting from 1 for 3) as version from pg_settings where name='server_version_num'`

is not available in the special administration database **pgbouncer** , which only support below commands:

>  SHOW [HELP|CONFIG|DATABASES|FDS|POOLS|CLIENTS|SERVERS|SOCKETS|LISTS|VERSION]
  SET key = arg
  RELOAD
  PAUSE
  SUSPEND
  RESUME
  SHUTDOWN

So I think we need add the pgbouncer plugin along with postgresql and postgresql_extension.

**Comment by sparrc** [comment]
okay, fair enough, thanks for the clarification

**Comment by jsvisa** [comment]
May I reopen this PR?

**Comment by sparrc** [comment]
yes, sorry, I meant to do that with the last comment

**Comment by jsvisa** [comment]
@sparrc thanks, rebased

**Comment by sparrc** [comment]
Can you explain why you've used your own docker image for the tests? From googling there appears to be some others that are more common/popular. I ask because I've had contributors add docker images that have gone defunct.

**Comment by jsvisa** [comment]
Mine is based on alpine as base image, which is smaller(only 16MB), and seems the others use Ubuntu, which size almost is 98MB.

**Pull request closed without merging**
