### PR TITLE
WIP: smart: Gather S.M.A.R.T. information from storage devices

### PR DESCRIPTION
**Pull request by rickard-von-essen**
This adds a new input plugin which uses the `smartctl` utility from the
smartmontools package to gather metrics from S.M.A.R.T. storage devices.

Signed-off-by: Rickard von Essen <rickard.von.essen@gmail.com>

### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
I'll do some verification of this and come back when I think it's tested.

**Comment by sparrc** [comment]
@rickard-von-essen there is already a PR for this feature: #2319

feel free to re-open if your PR adds any additional functionality and you think we should use yours instead.

**Comment by rickard-von-essen** [comment]
Damn, #2319 must have been opened just after I started. I'll review and test that and comment there.

**Comment by rickard-von-essen** [comment]
@sparrc I think we should reopen this and compare the basic structure of the code with #2319.

**Comment by rickard-von-essen** [comment]
TODO:

- [ ] Properly handle exit codes
- [ ] Run gathering of metrics concurrently
- [ ] Split metrics into `smart_drive` and `smart_attribute`.
- [ ] Handle versions 5.41, 5.42, 6.[0-6]
- [ ] Update README.md

**Comment by rickard-von-essen** [comment]
@sparrc I think we should reopen this (only collaborators/owners can do that).

I have updated this with more documentation, concurrent metrics gathering, different metrics structure, verified against version 5.41, 5.42, 5.43, 6.0, 6.1, 6.2, 6.3, 6.4, and 6.5.

@sebito91 It would be awesome if you would help testing this by testing the performance on your 96-disk system and verify that this would also cover your use case.

**Pull request closed without merging**
