### PR TITLE
add support for linux/ppc64le

### PR DESCRIPTION
**Pull request by aklyachkin**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

Issue #8431

### CODE REVIEW

**Review by zak-pawel — COMMENTED** [review]
Shouldn't `ppc64le` also be added to `scripts/release.sh`? And what about link to nightly build in `README.md`?

@reimda @ssoroka ?

**Comment by reimda** [comment]
It looks like scripts/release.sh and the readme will need to be updated.

Also, don't debian-based distributions call it ppc64el?  We will want to name the packages whatever is customary for the distribution.
https://wiki.ubuntu.com/ppc64el
https://wiki.debian.org/ppc64el

**Comment by aklyachkin** [comment]
Hi, @zak-pawel and @reimda I added the changes. Now it should produce the ppc64el_deb for Debian, I added nightly build link into README.md and ppc64le into release.sh. Please check, if it is ok.

**Comment by zak-pawel** [comment]
LGTM!

@ssoroka ?

**Review by ssoroka — APPROVED** [review]

**Pull request merged**
