### PR TITLE
Add connection info per process to procstat

### PR DESCRIPTION
**Pull request by adrianlzt**
Only added where gopsutil supports returning connections by PID: linux,
freebsd and darwin.

Add these new fields, following the same naming as netstat:
tcp_close
tcp_close_wait
tcp_closing
tcp_established
tcp_fin_wait1
tcp_fin_wait2
tcp_last_ack
tcp_listen
tcp_none
tcp_syn_recv
tcp_syn_sent
tcp_time_wait
udp_socket

### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
I think we need to begin adding monitoring components to this plugin, to allow users to be able to skip collection of metrics they are not interested in.  How about we add a new option:
```
metrics_include = ["connections"]
```

If the option is unset then we collect only the current items.

**Comment by adrianlzt** [comment]
We can do the same with:
```
fielddrop = ["tcp_*", "udp_socket"]]

**Comment by danielnelson** [comment]
I more concerned about slowing down the collection speed as we parse more files.

**Comment by adrianlzt** [comment]
Superseded by #8755

**Pull request closed without merging**
