### PR TITLE
Add NATS Streaming System Server input plugin (#3842)

### LINKED ISSUE #3842: Add NATS Streaming Input
### Proposal:
Add the ability to read messages from the NATS streaming server. https://github.com/nats-io/go-nats-streaming

### PR DESCRIPTION
**Pull request by ishiev**
Resolves #3842

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Thanks for the pull request @ishiev , we will review as soon as we can but a few quick questions/observations:
- Why is it required to exclude freebsd?
- I see quite a few changes to the Gopkg.lock, can you double check all of these new dependencies are required?

**Comment by ishiev** [comment]
Hello, @danielnelson, here are the answers:
* The reason is the same as commit 1b0a4e49cdf30cd0ae4984253549c443520c11ca.
* New dependencies were required by the package github.com/nats-io/nats-streaming-server/server, which is used by the plugin.

**Comment by z400hero** [comment]
@ishiev isn;t this just the status of the Nats server as streaming data, instead of the actual data as the input?

**Comment by ishiev** [comment]
@z400hero this is only the status data of the Nats Streaming Server, as described on https://github.com/nats-io/nats-streaming-server#monitoring

**Comment by ishiev** [comment]
Я отсутствую на работе до 21.07.2019.

Если вопрос срочный, пожалуйста, отправьте сообщение на WhatsApp.


Примечание. Это автоматический ответ на ваше сообщение  "Re:
[influxdata/telegraf] Add NATS Streaming System Server input plugin (#3842)
(#4407)" отправлено 18.7.2019 10:30:06.

Это единственное уведомление, которое будет получено в случае отсутствия
этого пользователя.

**Comment by davidq2q** [comment]
Why is this not merged yet?

**Comment by sjwang90** [comment]
This plugin looks like a good candidate for an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf? Telegraf users would be able to use the plugin sooner by having it as an external plugin since it wouldn't have to go through the typical review process.

**Comment by srebhan** [comment]
@ishiev are you still interested in this PR?

**Comment by srebhan** [comment]
If someone wants to continue this one, please step-up and let me know!

**Comment by sjwang90** [comment]
Closing this PR due to inactivity.

If you would still like this plugin, please submit it as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf.

**Pull request closed without merging**
