### PR TITLE
Providing option to disable labels in prometheus output for string fields

### PR DESCRIPTION
**Pull request by shaheed121**
#3350 introduced a change where all string fields are turned to labels. However in certain cases where string value changes, it introduces a new metric due to the change in label value.

Hence this will provide an option to disable as well as enable only for certain string values. The default behavior doesn't change with this commit.

### CODE REVIEW

**Comment by danielnelson** [comment]
What about using the [measurement filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering) options to provide this using taginclude/tagexclude and fielddrop/fieldpass.

**Comment by shaheed121** [comment]
@danielnelson Yes, I could do that. But I would have to know the list or patterns of tags beforehand. Instead if I disable converting string fields to labels globally, then I don't have to fiddle with all input plugins.

So what do you think about having atleast an option to disable this feature like how we had before 1.5.0 release?

**Comment by danielnelson** [comment]
That makes sense, could you provide this in a similar way to how we we do it in the docker plugin with `docker_label_include` and `docker_label_exclude`?  Maybe we call it `string_label_include` and `string_label_exclude`.

**Comment by shaheed121** [comment]
@danielnelson To keep it consistent across output plugins, I thought of doing something like `string_as_state` in Riemann output plugin. So have added `string_as_label` and set default as `true` to make sure that it exhibits the current behavior. 
The reason I didn't go ahead with `string_label_include` and `string_label_exclude` because it would be redundant since it can be managed using Measurement filtering like you said.

**Pull request merged**
