### PR TITLE
feat: Update the Aliyun Metrics Exporter functionality

### PR DESCRIPTION
**Pull request by ZPascal**
## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #

### CODE REVIEW

**Comment by powersj** [comment]
@ZPascal - Is this a PR you plan to work on further? Looks like you were working on adding support for `acs_polardb`?

**Comment by ZPascal** [comment]
> Is this a PR you plan to work on further? Looks like you were working on adding support for `acs_polardb`?

@powersj Yes, that's correct and I'll add support for it. I'm currently testing/ debugging it.

**Comment by powersj** [comment]
Happy to see a PR with updates! We do try to keep the open PR list to things ready for review. Let me know if you push updates and we can reopen as needed. Thanks!

**Comment by ZPascal** [comment]
@powersj I've adapted the feature branch and adjusted the scope. I've added now rds performance support! Should I open a new PR or should we handle it here?

**Comment by ZPascal** [comment]
> > I've added now rds performance support! Should I open a new PR or should we handle it here?
> 
> We generally prefer smaller PRs with a narrow focus, so if it is easily done could you split them out?

Sure, I'll open a new PR with a dedicated focus on the RDS performance metrics.

**Pull request closed without merging**
