### PR TITLE
[wip] Add exec output plugin

### PR DESCRIPTION
**Pull request by ewbankkit**
### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

Very much a Work In Progress but I have it working with an "external" plugin I wrote: https://github.com/ewbankkit/telegraf-signalfx-output.
Much of the code is copied from https://github.com/influxdata/telegraf/blob/master/plugins/inputs/exec/exec.go and much could/should be shared.

TODO: Tests 😄.

Addresses https://github.com/influxdata/telegraf/issues/544.
Relates to https://github.com/influxdata/telegraf/issues/1717.

Let me know if you want me continue working on this.

### CODE REVIEW

**Comment by danielnelson** [comment]
@ewbankkit Sorry about lack of response, I think this would be a useful output plugin and if you are still interested in working on it I can help you get it merged.

**Comment by ewbankkit** [comment]
@danielnelson I haven't been following progress on Telegraf for a bit but am certainly interested in seeing this merged - Let me bring myself back up to speed.

**Comment by ewbankkit** [comment]
@danielnelson I have no cycles to work on this any more.

**Comment by danielnelson** [comment]
@ewbankkit Okay, no problem, thanks for letting us know.  Can you leave this pull request open for now and I'll close it once I have time to finish it up.

**Comment by russorat** [comment]
closing due to inactivity. if you are interested in this, please comment.

**Comment by Jaeyo** [comment]
@ewbankkit can i go forward with this?

**Comment by ewbankkit** [comment]
@Jaeyo Yes, please do.
My focus has switched to other projects.
Thanks.

**Pull request closed without merging**
