### PR TITLE
Add field key length output by field type in schema_sizing Starlark script

### PR DESCRIPTION
**Pull request by samhld**
### Required for all PRs:

- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Review by Jagularr — APPROVED** [review]

**Comment by helenosheaa** [comment]
Hey @samhld can you address the merge conflict

**Comment by samhld** [comment]
@helenosheaa Hmm I'm not sure how to interpret what the problem is, to be honest.  Maybe I can borrow you or whoever has a minute to help me interpret?

**Comment by helenosheaa** [comment]
@samhld yes just sent me a slack when it's good and we can hop on a zoom

**Comment by samhld** [comment]
Thanks, @helenosheaa!

**Review by helenosheaa — APPROVED** [review]

**Pull request merged**
