### PR TITLE
WIP : db_extensible plugin

### PR DESCRIPTION
**Pull request by menardorama**
Hi,

I've forked the postgresql_extensible plugin in order to add more databases.

For now it's just a WIP, I wanted to have feedbacks on it.

I've just added mysql in the loop for now, but had to comment the sanitize function (need to work with the ParseDSN) for now.

Feedbacks are welcome.

### CODE REVIEW

**Comment by JulienChampseix** [comment]
@menardorama if you need beta tester, dont hesitate for MySQL part ;)

**Comment by JulienChampseix** [comment]
@bakl what are the next step for merge those commit into the master ?

**Comment by JulienChampseix** [comment]
@sparrc any idea when this feature will be integrated ? @bakl approuved changes
thanks again @menardorama

**Comment by JulienChampseix** [comment]
@sparrc @bakl any update about this PR ?

**Comment by stemwinder** [comment]
@menardorama any plans for SQLite support?

**Comment by lucadistefano** [comment]
@menardorama  can you check if this pull can cover your needs ?https://github.com/influxdata/telegraf/pull/2785
I tried it on oracle,postgres,mssql,mysql and added sqlite support but I don't know if there are missing features.

**Comment by russorat** [comment]
Closing this in favor of #2785 .

**Pull request closed without merging**
