### PR TITLE
Remove warning if parse empty content

### PR DESCRIPTION
**Pull request by jeremydenoun**
Related to my issue #2448, I propose to hide warning if empty content should be passed especially with input.exec plugin

### Required for all PRs:

- [X] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by sparrc** [comment]
seems reasonable, but please add a unit test for it,

what do you think @danielnelson?

**Comment by jeremydenoun** [comment]
ok I add an unit test for it

**Comment by jeremydenoun** [comment]
done

**Comment by danielnelson** [comment]
Looks good, @jeremydenoun can you update the changelog?

**Comment by jeremydenoun** [comment]
done

**Pull request merged**
