### PR TITLE
Tail input plugin

### PR DESCRIPTION
**Pull request by sparrc**
WIP, todo:

- [x] parse and add each log message to the accumulator
- [x] support glob file matching, as in the filestat plugin
- [x] unit tests
- [x] update changelog & readme
- [x] write a plugin readme

### CODE REVIEW

**Comment by panda87** [comment]
Looks great @sparrc 
Im wondering if kakfa output supports routing to a different topics by the tag or anything else.
Another question if it supports listening to docker.sock to retrieve docker containers logs (stdout,stderr)

**Comment by sparrc** [comment]
thanks @panda87, not sure what you mean about kafka, but I can look into support for tailing sockets

**Comment by sparrc** [comment]
looks like the "tail" doesn't work on unix sockets, I think that would need to be a separate plugin, more similar to the tcp_listener and udp_listener plugins

**Comment by panda87** [comment]
@sparrc I meant that, im using kafka as output plugin, and I think that be able to route logs (files) per kafka topic can be great advantage.
For example, syslog will go to one topic and application log to another.

**Comment by sparrc** [comment]
OK, still not sure I fully understand, if you could open a separate feature request with more details and specific examples, that would be great.

Did you know that telegraf supports measurement filtering? I think this could be used to accomplish what you need. https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering

**Pull request merged**
