### PR TITLE
Update http_response.go

### PR DESCRIPTION
**Pull request by dannybeeckman**
Because the URL is only available in the full url format in the database, I am not able to select (group/filter) a specific hostname in the http_response plugin. 

**AS IS:**
`http_response,result=success,server=https://www.google.com:443/search/,status_code=200 http_response_code=200i,response_time=0.00778448,result_code=0i,result_type="success" 1536565736000000000`

**TO BE:**
`http_response,host=www.google.com,method=GET,path=/search/,port=443,protocol=https,result=success,server=https://www.google.com:443/search/,status_code=200 http_response_code=200i,response_time=0.00778448,result_code=0i,result_type="success" 1536565736000000000`

I wrote a simple improvement.

### CODE REVIEW

**Comment by dannybeeckman** [comment]
Ok, changed the code to use source instead of domain, @danielnelson .

I applied the gofmt and it seemed to change indentation, is it correct as it should be,  @glinton ?

**Comment by glinton** [comment]
It's still failing the tests, saying to run `make fmt`. Which version of go are you using?

**Comment by dannybeeckman** [comment]
> It's still failing the tests, saying to run `make fmt`. Which version of go are you using?

go version go1.11 linux/amd64

**Comment by danielnelson** [comment]
Looks like the code in the commit is space indented, go fmt should convert to use tabs instead.

**Comment by glinton** [comment]
@dannybeeckman can you run `make fmt` again and commit the changes?

**Comment by dannybeeckman** [comment]
@glinton I tried but I can't find what I did wrong. Maybe it is because I develop in my own repo instead of a branch?

**Comment by danielnelson** [comment]
There are conflict markers in http_response.go, but once those are solved you will need to use gofmt with Go 1.10 for now, we will change this soon but right now the tests are looking for the 1.10 format.

**Comment by glinton** [comment]
@dannybeeckman are you using go 1.10? Also you'll need to undo the last commit where you pasted the terminal output to the end of the file. `make fmt` updates the file in place so you won't need to paste anything.

**Comment by sjwang90** [comment]
Closing due to inactivity. Please feel free to re-open if you would like to continue this work.

**Pull request closed without merging**
