### PR TITLE
(feat) Final version of Wireless Network plugin

### PR DESCRIPTION
**Pull request by davidgs**
### Required for all PRs:
Final version of the Wireless Network Interface monitoring plugin. Works for Linux or OS X (darwin), exits with error on other platforms. 

- [X ] Signed [CLA](https://influxdata.com/community/cla/).
- [ X] Associated README.md updated.
- [ X] Has appropriate unit tests.

### CODE REVIEW

**Comment by srebhan** [comment]
@davidgs any update here? Will you be able to find some time to work on this PR?

**Comment by powersj** [comment]
Hi,

This PR has not been touched in a while and as a result I am going to close it. We are happy to review again once someone picks this back up with the suggested changes and rebased on master.

Thanks!

**Comment by davidgs** [comment]
I have rebased on master and fixed a bunch of stuff. I’ll submit as a new PR.

**Comment by srebhan** [comment]
@davidgs please drop me a note once you have the new PR (or assign me to it).

**Pull request closed without merging**
