### PR TITLE
add HTTP basic auth support to the http_listener input plugin

### PR DESCRIPTION
**Pull request by 3van**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

Does what it says on the tin. Needed it for a specific use case, and saw no reason for it to not be there, so here we are.

### CODE REVIEW

**Comment by 3van** [comment]
@danielnelson any chance this could land in a release sometime soon? I’d love to get our build process off of my fork.

**Comment by danielnelson** [comment]
I will try to review for 1.6.

**Comment by danielnelson** [comment]
Looks good but can you remove the HTTPS test code, I don't think it is necessary to test that for this code.

**Comment by 3van** [comment]
Ugh, sorry, I totally forgot about this. HTTPS tests removed now!

**Pull request merged**
