### PR TITLE
fix(inputs.http_response): fix the use of hostnames + interface

### PR DESCRIPTION
**Pull request by Mic92**
## Checklist

- [x] No AI generated code was used in this PR

## Related issues

~~resolves~~

### CODE REVIEW

**Review by powersj — COMMENTED** [review]
Hi @Mic92 - can you please file an issue with some background as to why this change needs to occur and justify the TODO as well please?

**Comment by powersj** [comment]
Hi,

Would be happy to circle around to this PR once you file an issue and remove the TODO. Thanks!

**Comment by Mic92** [comment]
2 weeks is a bit short for a timeout, i.e. if you go on holiday.

**Comment by powersj** [comment]
> 2 weeks is a bit short for a timeout, i.e. if you go on holiday.

Which is why we are perfectly fine re-opening this PR if you came back around to it or if you communicated you are out ;)

**Comment by Mic92** [comment]
I don't have permissions to re-open a PR and all previous reviews are missing in the new pull request.

**Pull request closed without merging**
