### PR TITLE
feat(outputs): Add framework to retry on startup errors

### LINKED ISSUE #9778: Two more Kafka input failures that break all other plugins
There are 2 failures that we see in Telegraf 1.20-rc0 just in the Kafka plugin, despite https://github.com/influxdata/telegraf/pull/9051 that was supposed to fix this plugin:

**1. If the Kafka  backends are just down**

Use this config to test:
```
[agent]
  interval = "1s"
  flush_interval = "1s"
  omit_hostname = true
  collection_jitter = "0s"
  flush_jitter = "0s"

[[outputs.kafka]]
  brokers = ["server1:9092","server2:9092","server3:9092"]
  topic = "xx"
  client_id = "telegraf-metrics-foo"
  version = "2.4.0"
  routing_tag = "host"
  required_acks = 1
  max_retry = 100
  sasl_mechanism = "SCRAM-SHA-256"
  sasl_username = "foo"
  sasl_password = "bar"
  exclude_topic_tag = true
  compression_codec = 4
  data_format = "msgpack"

[[inputs.cpu]]

[[outputs.file]]
  files = ["stdout"]
```

Make sure the client cant talk to server[1-3]; we did ip route add x via 127.0.0.1 to null route it but you could use a firewall or just point it to IPs that are not running Kafka.

What we expect:
- Kafka output fails and tries to reconnect 100 times
- I can still see the CPU input plugin sending data to stdout
- Once Kafka manages to connect then I see the data there as well

What actually happens:

- Kafka tries to connect a couple of times
- CPU input plugin data is never passed to the stdout
- After kafka fails, Telegraf exits with an error

**2. If the Kafka sasl_password  is wrong and SASL auth enabled**

This is trivial to reproduce - just change the sasl_password  for a working config.

What we expect:
- Kafka output fails and tries to reconnect X times
- Everything else works fine

What actually happens:
- Telegraf immediately fails to start with this error (process exits):

```
[root@x ~]# /usr/local/telegraf/bin/telegraf -config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/conf.d
2021-09-16T11:23:51Z I! Starting Telegraf build-50
...
2021-09-16T11:23:51Z E! [agent] Failed to connect to [outputs.kafka], retrying in 15s, error was 'kafka server: SASL Authentication failed.'
```

### LINKED ISSUE #14803: Generic handling to ignore errors on startup
### Use Case

In numerous feature requests, users are asking for a way to ignore errors on start up. It would be nice to have a high-level generic method to add this to input plugins.

### Expected behavior

Agent level setting to set this behavior for all input plugins.

### Actual behavior

Currently users will see Telegraf throw an error during start up if an input plugin cannot start. There are a couple exceptions to this where a configuration option is present to avoid these:

```s
  ## Behavior when we fail to connect to the endpoint on initialization. Valid options are:
  ##     "error": throw an error and exits Telegraf
  ##     "ignore": ignore this plugin if errors are encountered
  # connect_fail_behavior = "error"
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

A frequently requested feature is to retry startup for plugins in case of error e.g. if the connection to a remote machine fails.

Instead of implementing the logic for retrying in each plugin, this PR provides a framework **for output-plugins** to use if they wish to support retries. As an example, the Kafka output plugin is converted to use the new framework

More details can be found in the [TSD-006 specification](https://github.com/influxdata/telegraf/blob/master/docs/specs/tsd-006-startup-error-behavior.md).

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #14803
resolves #9778

### CODE REVIEW

**Review by powersj — COMMENTED** [review]
I really like this. 

In general, all outputs are connecting to something or creating a server for something to connect to with the exception file? And I don't think we would want to change anything for file.

What do you think are the next steps?

**Review by powersj — APPROVED** [review]
Thank you for this! Did you want to look at the ~wavefront~ graphite output in this or as a second PR?

**Comment by srebhan** [comment]
@powersj here are my findings regarding the graphite output... The current behavior of graphite is to always succeed on startup even though no server can be connected. The plugin will then try to connect to the given servers in each `Gather()` cycle. If at least one server was connected successfully, the data is written. This is done unconditionally and corresponds to the `retry` strategy in the new framework with potentially partial startup. _Additionally_, servers are _reconnected_ if they are found to be unconnected. This is also tried in each `Gather()` cycle.

Regarding the framework, the conversion of the graphite output has some drawbacks:
1. To keep the current behavior, we would need to set `startup_error_behavior` to `retry` by default. This is difficult and can only be done with a special handling in the config code.
2. The "reconnect disconnected servers" behavior currently implemented in the plugin is currently not covered by the framework code.

So given the challenges above and the little gain in terms of code-removal I suggest to not convert the graphite output for now, at least until we also handle the reconnect case in the framework...

**Comment by powersj** [comment]
@DStrand1 all yours to do a final review.

**Review by DStrand1 — APPROVED** [review]

**Pull request merged**
