### PR TITLE
Add date offset option to date processor

### PR DESCRIPTION
**Pull request by danielnelson**
closes: #6877

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Uh oh, it appears we have been setting the tag based on the local system time instead of using UTC to match the metric timestamps.  I will fix this but it will not be fully backwards compatible.

**Comment by Crashtein** [comment]
> Uh oh, it appears we have been setting the tag based on the local system time instead of using UTC to match the metric timestamps. I will fix this but it will not be fully backwards compatible.

Are you sure it is correct? Most people use this plugin to put tag offset appropiate to their timezone. 
My machines are time synced and timezone has been set. Also there is a seasonal time change +/-1h in my country. When I put my point into DB through telegraf processors plugin it reads the same time stample as it has in origin machine.
So assume I want an offset -6.00h to change tag at 6:00AM local time. You want to base tag on UTC time, so finally the offset is UTC time + offset. In described case it will be -5.00h. Am I correct? Could you explain your point of view?

**Comment by danielnelson** [comment]
I believe your calculation is correct.  My line of thinking here is that metrics are always reported in UTC, and adding a tag with a 0 offset should match the timestamp in the database, no matter the timezone of the system who collected it.

> Most people use this plugin to put tag offset appropiate to their timezone.

I don't have a good way to judge this.  I suspect the primary use of this plugin is to insert day of the week or month of the year, and it is possible that many users haven't noticed the discrepancy.  This would be a change of behavior though, so at the very least we should add this to the release notes.

**Comment by Crashtein** [comment]
Ok, now I understand it. One more thing I can add to this discussion is a RTC time - reference time which may be used on linux with i.e. timezonectl. It lets you set hardware time to UTC or local. You may also consider to put an information about that and let the user choose the best solution for use.

**Comment by danielnelson** [comment]
Rebased on master due to CHANGLOG.md conflict.

Added new `timezone` option to allow control over the time zone used.  Added release note about breaking change.

**Pull request merged**
