### PR TITLE
Add option to amqp output to publish persistent messages

### LINKED ISSUE #3526: Telegraf AMQP Output - Persistent messages
### Proposal:
Please allow the option to set messages to be persistent on the amqp output plugin.

### Current behavior:
Messages are not persistent and are lost when a broker restarts

### Desired behavior:
Messages are retained on the broker until they are processed

### Use case: [Why is this important (helps with prioritizing requests)]
When batch loading large amounts of messages (logparser messages to be precise), the messages are very large and take a while to process.  On occasion, the broker will run out of memory and crash.  All messages are lost and have to be reprocessed.

### PR DESCRIPTION
**Pull request by danielnelson**
closes #3526 

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@hanej Would you be able to test this patch?  I can you link you to a build from CircleCI if you tell me which package you prefer.

**Comment by hanej** [comment]
Absolutely.  Thank you.  We're running on RHEL 6/7 x86_64.

**Comment by danielnelson** [comment]
https://9007-33258973-gh.circle-artifacts.com/0/tmp/circle-artifacts.B0Y0kPB/build/linux/amd64/telegraf-1.5.0%257E9cfec13f-0.x86_64.rpm

**Comment by danielnelson** [comment]
@hanej I'm hoping to tag 1.5.0-rc1 tomorrow morning, if you can test before then we can squeeze this in.

**Comment by hanej** [comment]
It works perfectly.  Thank you very much.  The messages get persisted after broker restart.

**Pull request merged**
