### PR TITLE
fix: typo in influx line protocol parser docs

### PR DESCRIPTION
**Pull request by kapsh**
### Required for all PRs:

- [x] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

`parser_type` is actually used when reading configuration.

### CODE REVIEW

**Comment by kapsh** [comment]
!signed-cla

**Comment by kapsh** [comment]
Documented one doesn't work 
> plugin inputs.file: line 12: configuration specified the fields ["influx_parser_version"], but they weren't used

and parsers registry and every other input use `parser_type` wording.

**Comment by kapsh** [comment]
Unit tests task unchecked as I got no clue how to test readme.

**Review by powersj — APPROVED** [review]
wow thank you for this... I think I was too focused on the influxdb listeners, where it is different.

**Pull request merged**
