### PR TITLE
Add Starlark script for outputting Line Protocol shape...for sizing

### PR DESCRIPTION
**Pull request by samhld**
### Required for all PRs:

- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by srebhan** [comment]
@samhld how is this PR different from #8675?

**Comment by samhld** [comment]
@srebhan should be good to go now!

**Review by srebhan — COMMENTED** [review]
Please remove the commented code.

Furthermore, you drop the original metric, is this correct?

**Comment by samhld** [comment]
@srebhan Removed commented code.  The intention was to drop the original metric, yes.  That's up for debate currently, however :).  For now, it's fine.

**Comment by srebhan** [comment]
@samhld please add at least a comment in the example that the original metric is dropped. Furthermore, your expected values and the actual output of the script diverge. Please check what's going on here and fix one or the other.

**Comment by samhld** [comment]
Ugh, they didn't use to.  I'll have to investigate why this happened.

**Comment by samhld** [comment]
I know why -- will re-commit fix shortly!

**Comment by samhld** [comment]
@srebhan Ok gtg

**Review by srebhan — APPROVED** [review]
Fine with me.

**Pull request merged**
