### PR TITLE
Respect path prefix in influx output uri

### PR DESCRIPTION
**Pull request by dimrozakis**
Fixes issues:
- #2568
- #2750 

Duplicate of PR #2751, attempts to address https://github.com/influxdata/telegraf/pull/2751#issuecomment-306721832

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Can you also add a unittest?

**Comment by dimrozakis** [comment]
@danielnelson I wasn't sure what kind of new unittest to add in order to properly test the path prefix support, so I chose running the `TestHTTPClient_Write` and `TestHTTPClient_Query` tests twice, with and without a path prefix. Are we ok with that?

**Comment by danielnelson** [comment]
I would write a new testcase that only tests the path handling, it can do both the write and query operations.  The handler just needs to test that the path is correct and that's it.

**Comment by dimrozakis** [comment]
@danielnelson I changed the tests as requested

**Pull request merged**
