### PR TITLE
fix(inputs.upsd): Add additional fields to upsd from NUT

### PR DESCRIPTION
**Pull request by masterwishx**
adding more values to upsd input from NUT .
also will be cool to have it automaticly  :)

### CODE REVIEW

**Comment by masterwishx** [comment]
!signed-cla

**Comment by srebhan** [comment]
@masterwishx can you please run `make fmt` on the code to fix CI tests!?

**Comment by masterwishx** [comment]
Help is needed, some values not passing the test.

**Comment by srebhan** [comment]
@masterwishx the tests fail because you define the wrong type in the tests. NOTE: All fields defined in `floatValues` will be exported as `float64`.

**Comment by masterwishx** [comment]
as i saw in example of privios pr , some values defined as float then int in test

image
image

and from test isee some values not as they defined :  
expected: string but actual: bool ?
image

**Comment by srebhan** [comment]
@masterwishx first of all thank you for all your work! I took the liberty to rework your PR a bit to be able to specify the fields you want to have in the metric using a filter. This way you can simply say `additional_fields = ["*"]` to get all the information your UPS provides.
I also added the test-cases framework to be able to add new test-cases quickly. I would appreciate if you could add a test-case for your UPS. To get the `variables.dev` and `types.dev` you can simply adapt and use the following config
```toml
[[inputs.upsd]]
  server = "127.0.0.1"
  port = 3493
  username = "xxx"
  password = "xxx"

  additional_fields = ["*"]
  dump_raw_variables = true
```
and run `telegraf --config <the file above> --test --debug`. This will output the required information in a debug message...

**Comment by srebhan** [comment]
@masterwishx let me know if you agree with the changes and if the code works as you intended!

**Comment by masterwishx** [comment]
> first of all thank you for all your work! I took the liberty to rework your PR a bit to be able to specify the fields you want to have in the metric using a filter. This way you can simply say `additional_fields = ["*"]` to get all the information your UPS provides.
> I also added the test-cases framework to be able to add new test-cases quickly. I would appreciate if you could add a test-case for your UPS. To get the `variables.dev` and `types.dev` you can simply adapt and use the following config

Thanks for your help, sorry i dont have much expirience , so had test issues ...

**Comment by srebhan** [comment]
@masterwishx I don't think there is a docker image available for PRs... However, you can download the [linux-amd64 static binary](https://output.circle-artifacts.com/output/job/cd6022e1-4aa0-4061-a852-daf6259650f2/artifacts/0/build/dist/telegraf-1.30.0~9be194e9_linux_amd64.tar.gz) provided by [Tigerbot](https://github.com/influxdata/telegraf/pull/14447#issuecomment-1874376840) and run this on the host for testing!? It is only one single binary without further dependencies...

**Comment by masterwishx** [comment]
> @masterwishx I don't think there is a docker image available for PRs... However, you can download the [linux-amd64 static binary](https://output.circle-artifacts.com/output/job/cd6022e1-4aa0-4061-a852-daf6259650f2/artifacts/0/build/dist/telegraf-1.30.0~9be194e9_linux_amd64.tar.gz) provided by [Tigerbot](https://github.com/influxdata/telegraf/pull/14447#issuecomment-1874376840) and run this on the host for testing!? It is only one single binary without further dependencies...

OK, i will try to check it

**Comment by masterwishx** [comment]
@srebhan All working Fine ,i runned in Windows from my main PC and have all values from telegraf  `telegraf --config <the file above> --test --debug`:  
```
battery.capacity: 7
battery.charge: 100
battery.charge.low: 20
battery.charge.restart: 0
battery.protection: yes
battery.runtime: 3799
battery.runtime.low: 180
battery.type: 
device.mfr: Eaton
device.model: unknown 2000
device.type: ups
driver.debug: 0
driver.flag.allow_killpower: 0
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.synchronous: auto
driver.state: quiet
driver.version: 2.8.1
driver.version.data: MGE HID 1.46
driver.version.internal: 0.52
driver.version.usb: libusb-1.0.26 (API: 0x1000108)
input.bypass.frequency: 49.9
input.bypass.voltage: 233
input.frequency: 49.9
input.frequency.nominal: 50
input.transfer.high: 300
input.transfer.low: 100
input.voltage: 232
input.voltage.nominal: 230
outlet.1.status: on
outlet.desc: Main Outlet
outlet.id: 0
outlet.switchable: no
output.current: 1.7
output.frequency: 49.9
output.frequency.nominal: 50
output.voltage: 229
output.voltage.nominal: 230
ups.beeper.status: true
ups.delay.shutdown: 20
ups.delay.start: 30
ups.firmware: 
ups.load: 19
ups.load.high: 105
ups.mfr: Eaton
ups.model: unknown 2000
ups.power: 397
ups.power.nominal: 2000
ups.productid: ffff
ups.realpower: 264
ups.realpower.nominal: 1600
ups.shutdown: true
ups.start.auto: yes
ups.start.battery: yes
ups.start.reboot: yes
ups.status: OL
ups.temperature: 24.9
ups.test.interval: 604800
ups.test.result: Done and passed
ups.timer.shutdown: -1
ups.timer.start: -1
ups.type: online
ups.vendorid: 463
```
as from NUT plugin for Unraid  but have some difference in some values, not a big problem but still :  

image

image

image

image

also some values integer instead float :  

image

**Comment by srebhan** [comment]
@masterwishx the differences you see are most likely due to the different data-handling of the plugins. The upstream `upsd` plugin respects the value-type delivered by NUT by default. You can use `force_float` to force all values to float. The `enabled` vs `true` comes from the upstream go-package which detects the string and converts the value to a float. If you need to map it back, you can use the [enum processor](https://github.com/influxdata/telegraf/blob/master/plugins/processors/enum)...

**Comment by masterwishx** [comment]
> @masterwishx the differences you see are most likely due to the different data-handling of the plugins. The upstream `upsd` plugin respects the value-type delivered by NUT by default. You can use `force_float` to force all values to float. The `enabled` vs `true` comes from the upstream go-package which detects the string and converts the value to a float. If you need to map it back, you can use the [enum processor](https://github.com/influxdata/telegraf/blob/master/plugins/processors/enum)...

Thanks, got it.

**Review by powersj — APPROVED** [review]
Thanks - my biggest concern was not changing the types by default, but that logic all looks the same.

**Comment by masterwishx** [comment]
@powersj 
Hi ,updated Telegraf config on Server in Docker and have some issues and values still as integer .

From log:
image

From influxDB:
image

**Comment by masterwishx** [comment]
image

**Comment by masterwishx** [comment]
Also tested in Windows with force_float=true :

image

**Comment by masterwishx** [comment]
Also checked in Windows with `telegraf --config <the file above> --test --debug `  + `force_float = true`  

but getting integer values :  
image
image

image

**Comment by powersj** [comment]
@masterwishx 

That original error message says that the value in InfluxDB is an integer, but telegraf is sending it as a float. As Sven was mentioning there may be differences between the previous plugin you were using and the telegraf plugin. I would certainly expect a percentage to be delivered as a float.

**Comment by masterwishx** [comment]
> That original error message says that the value in InfluxDB is an integer, but telegraf is sending it as a float. As Sven was mentioning there may be differences between the previous plugin you were using and the telegraf plugin. I would certainly expect a percentage to be delivered as a float.

Sorry, but I can't get float values with force_float from two examples above

**Comment by powersj** [comment]
> Sorry, but I can't get float values with force_float from two examples above

Which 2?

Please use the `[[outputs.file]]` output to provide the metrics you are seeing as well.

Thanks!

**Comment by masterwishx** [comment]
> Please use the `[[outputs.file]]` output to provide the metrics you are seeing as well.
> 
> Thanks!

I will try to check but in example in docker also not working with output to influxdbv2

**Pull request merged**
