### PR TITLE
Add support for Graphite 1.1.x protocol

### PR DESCRIPTION
**Pull request by R4scal**
Hi
This PR will add support for Graphite 1.1.x protocol (with tags support) http://graphite.readthedocs.io/en/latest/tags.html#graphite-tag-support 

This is a concept that working for me. Any feedback is welcomed

### CODE REVIEW

**Comment by danielnelson** [comment]
Thanks for the PR, would it be possible for you to add the new functionality into the old graphite serializer and add an option `graphite_tag_support`?  I think this will cut down on duplicate logic.

**Comment by R4scal** [comment]
@danielnelson Done. I was add `graphite_tag_support` option to original graphite oputput

**Comment by R4scal** [comment]
`name` as tag name is reserved for graphite metric and will be replaced with `_name` in last commit,  because graphite server silently drop this tag from metrics

**Comment by danielnelson** [comment]
closes #3830

**Pull request merged**
