### PR TITLE
x509 certs authentication now supported for Prometheus input plugin

### PR DESCRIPTION
**Pull request by victorgp**
Some popular tools like ETCD works with x509 certs authentication, this PR make this plugin supports that.

### CODE REVIEW

**Comment by sparrc** [comment]
@victorgp we have a general way of handling these: https://github.com/influxdata/telegraf/blob/master/plugins/outputs/influxdb/influxdb.go#L91

and

https://github.com/influxdata/telegraf/blob/master/plugins/outputs/influxdb/influxdb.go#L71

Please make your change look more like that

**Comment by sparrc** [comment]
also see #1398

**Comment by victorgp** [comment]
Done! Much simpler!

**Comment by sparrc** [comment]
thanks @victorgp !

**Pull request merged**
