### PR TITLE
Add Message Max bytes configuration

### PR DESCRIPTION
**Pull request by otherpirate**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
What happens if the message is over the max, does `err := k.producer.SendMessages(msgs)` return an error?

**Comment by otherpirate** [comment]
When message is bigger than MessageMaxBytes config this error occurs:
`2018-08-09T15:47:24Z E! Error writing to output [kafka]: kafka: Failed to produce message to topic <topic>: kafka server: Message was too large, server rejected it to avoid allocation error.`

It's the same error with default value(without configuration)

**Comment by danielnelson** [comment]
It seems like short term we ought to drop these messages, after logging, because otherwise the output plugin will just be stuck trying to send with no potential to send successfully.  I don't think this needs to be done in the PR though.

Long term, I would like to add a max size limitation to the Serializer interface.  This way we could attempt to split the messages, similar to how we can currently limit single lines in the influx serializer.  We would have to consider what this means for each serializer and ultimately it still may impossible to write some metrics in the allotted space.

**Comment by danielnelson** [comment]
cherry-picked to master 61513c64b85b2cb325a49b930f5ae6ff44af4091

**Pull request merged**
