### PR TITLE
HTTP Response Input: Add pre-request scripts and environment variable reference.

### LINKED ISSUE #9596: HTTP Response Input: Support pre-request script to add dynamic headers.
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior: Currently, the headers are hard-coded in configurations

```conf
  # HTTP Request Headers (all values must be strings)
    [inputs.http_response.headers]
      Signature = "MySignature"
```

### Desired behavior: Use scripts(not necessarily JS) to calculate headers in runtime.

```conf
  # Pre-request Scripts
    [inputs.http_response]
      scripts = "timestamp = (Date.now()/1000).toFixed()"

  # Export the variable to environment variable
    [inputs.http_response.script_set_env]
      TIMESTAMP= "timestamp"

  # HTTP Request Headers
  # Reference environment variable using ${TIMESTAMP} notation
    [inputs.http_response.headers]
      x-timestamp = "${TIMESTAMP}"
```

### Use case: 

Some HTTP request needs pre-scripts to generate signatures or tokens in headers. This feature will enable this plugin to support this use case.

### PR DESCRIPTION
**Pull request by KEVISONG**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #9596, #9672

### CODE REVIEW

**Comment by srebhan** [comment]
@KEVISONG we use the Starlark interpreter in `processors/starlark`, so we should move the interpreter setup etc. to a common place (e.g. `plugins/common/starlark` or similar).
I think we should discuss (maybe on Slack) the question if we want this as a general feature or if those dynamics should be reflected in an own plugin implementing those API requirements. Here we would also need to involve the core developers from InfluxData...

**Comment by KEVISONG** [comment]
> @KEVISONG we use the Starlark interpreter in `processors/starlark`, so we should move the interpreter setup etc. to a common place (e.g. `plugins/common/starlark` or similar). I think we should discuss (maybe on Slack) the question if we want this as a general feature or if those dynamics should be reflected in an own plugin implementing those API requirements. Here we would also need to involve the core developers from InfluxData...

Hi @srebhan 

The pre-request script is switched to starlark implementation in commit 2bd5ece.

The newly added builtin functions are included in builtins.go.

**Comment by srebhan** [comment]
@KEVISONG I chatted with the core-devs and we are still having difficulties to understand the use-case of this PR...

From your example I understand that you want to add some header-values to a request to implement an (not yet available) authentication mechanism, so why not implementing this in the plugin code?
The underlying concern is that people either have difficulties to manage the new complexity _or_ misuse the option to implement whole protocols instead of doing them in plugins.

Can you comment a bit more on why you need to do it as a _config_ option instead of implementing it in the _plugin code_!?

**Comment by KEVISONG** [comment]
> @KEVISONG I chatted with the core-devs and we are still having difficulties to understand the use-case of this PR...
> 
> From your example I understand that you want to add some header-values to a request to implement an (not yet available) authentication mechanism, so why not implementing this in the plugin code? The underlying concern is that people either have difficulties to manage the new complexity _or_ misuse the option to implement whole protocols instead of doing them in plugins.
> 
> Can you comment a bit more on why you need to do it as a _config_ option instead of implementing it in the _plugin code_!?

Hi @srebhan 

The reason to implement it(dynamically generated header) in the _config_ file is each HTTP api server may have different authentication mechanism. Below is an example

In `HTTP API Server A` we may have a signature added to the header for each api call calculated as below:

```starlark
token = 'my_token'
key = 'my_key'
nonce = rand()
timestamp = now()
signature = sha256(token+key+nonce+timestamp)
```

In `HTTP API Server B` we may have:

```starlark
secret= 'my_secret'
nonce = rand()
timestamp = now()
signature = md5(nonce+timestamp+secret)
```

So it would be flexible if people can do it in the config using starlark script instead of hardcode these logic in the plugin code.

**Comment by srebhan** [comment]
@KEVISONG well this doesn't convince me yet. Here is why...

Both of your example have a `some_hash_function(<some static secret><some random value><some timestamp>)` structure which can be parameterized as
```toml
    authentication = "KEVISONG_sha256" or "KEVISONG_md5"
    secret = "what a nice secret we have"
```
and the code can be added to the http code. Anyway, who does still _invent_ "cool, new, non-standard" authentication mechanisms, nowadays instead of using JWT and friends? Do you foresee more than a handful of cases?

This would only make sense if we cannot _know_ those algorithm in advance and it will then also require every _user_ of telegraf to implement this "authentication" instead of just configuring it...

**Comment by KEVISONG** [comment]
> @KEVISONG well this doesn't convince me yet. Here is why...
> 
> Both of your example have a `some_hash_function(<some static secret><some random value><some timestamp>)` structure which can be parameterized as
> 
> ```toml
>     authentication = "KEVISONG_sha256" or "KEVISONG_md5"
>     secret = "what a nice secret we have"
> ```
> 
> and the code can be added to the http code. Anyway, who does still _invent_ "cool, new, non-standard" authentication mechanisms, nowadays instead of using JWT and friends? Do you foresee more than a handful of cases?
> 
> This would only make sense if we cannot _know_ those algorithm in advance and it will then also require every _user_ of telegraf to implement this "authentication" instead of just configuring it...

The point is not about the algorithm. It's about the concatenated string passed to the algorithm, which is unpredictable. It's not a self-invented auth mechanism but the way the signature is generated that differs. Let me use a better example that both HTTP server uses SHA256 to generate the signature.

In `HTTP API Server A`

```starlark
key = 'my_key'
nonce = rand()
timestamp = now()
signature = sha256(key+nonce+timestamp)
```

In `HTTP API Server B`

```starlark
key = 'my_key'
nonce = rand()
timestamp = now()
signature = sha256(nonce+timestamp+key) // The way the input string is concatenated is different from Server A
```

Above two HTTP Server have different concatenated string to generate the signature. This differs from app to app, which IMO is not suitable to be hard coded in the plugin code.

**Comment by srebhan** [comment]
@KEVISONG given you have a well known superset of information used to construct the signature, why don't you add an option saying
```toml
# For server A
signature="key,nonce,timestamp"

# or for server B
signature="nonce,timestamp,key"
```

**Pull request closed without merging**
