### PR TITLE
Make rabbitmq_queue gathering be configurable

### PR DESCRIPTION
**Pull request by ildarsv**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [ ] Has appropriate unit tests.

PR for the #3701

### CODE REVIEW

**Comment by danielnelson** [comment]
I'm somewhat adverse to adding new boolean options, as they don't scale up very well and become confusing especially if they become dependent on other options.  What I'd like to do is something similar to our other filter options and have an include and exclude list that supports globs:
```
queues_exclude = ["*"]
```

There is a good example of this in the docker input with `container_name_include` and `container_name_exclude`.

**Comment by ildarsv** [comment]
@danielnelson 
Yes, It is not the best solution, but in case you have 1000+ queues (some of them can be temporary) and you don't want to gather `rabbitmq_queue` at all, you can apply `queues_exclude = ["*"]`. But the telegraf will make request to the RabbitMQ API to grab all these queues stats anyway. ~1Mb will be requested in every collecting interval, it causes timeouts from time to time and overloads network. Not only I have faced this issue, @kerams seems to have faced this issue as well (see #3701).

**Comment by kerams** [comment]
@ildarsv Why not just check if `queues_exclude` is `*` and then decide whether it is necessary to gather them at all?

**Comment by ildarsv** [comment]
Alright, I like this way too, let me do it

**Comment by ildarsv** [comment]
@danielnelson I will appreciate if you make some comment/review for this PR when you have time.

**Pull request merged**
