### PR TITLE
feat(agent): Let all types of plugins be able to set a SNMP translator

### PR DESCRIPTION
**Pull request by Hipska**
# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

Although, this functionality should have better fit into the respective `Config.add*` methods..

Currently, only input plugins are supported.

### CODE REVIEW

**Comment by Hipska** [comment]
Or should new plugins use "gosmi" by default (and always)? Since the value for setting translator to "netsnmp" is deprecated and there is no other translator.

**Comment by srebhan** [comment]
@Hipska I think this is a bit over-engineered as only a _very_ small fraction of the plugins deal with snmp. So how about either deprecating the global setting and move it to the plugins _OR_ setting a global variable in `internal` for now?

**Comment by Hipska** [comment]
It was done like this as for example the inputs.snmp could have thousands of instances. It could indeed be a global variable, but what do you think of my idea to move these instructions to `func (c *Config) addInput` and the others?

**Comment by srebhan** [comment]
> It could indeed be a global variable, but what do you think of my idea to move these instructions to func (c *Config) addInput and the others?

The "translation" option is very specific and I don't think adding this infrastructure is appropriate given that only a hand-full of plugins use the translator. So I'm in favor of the global variable.

**Comment by Hipska** [comment]
It has been decided to let `gosmi` be the default snmp translator for new plugins, so this additions aren't needed for now.

**Comment by Hipska** [comment]
It has been decided to let new plugins only use gosmi for now, so this isn't needed.

**Pull request closed without merging**
