### PR TITLE
adding the tags in the graylog output plugin

### PR DESCRIPTION
**Pull request by edieship**
### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

This is just to include the metric tags as well in the graylog output plugin, at the moment only metric values are included.

### CODE REVIEW

**Comment by sparrc** [comment]
@vanillahsu can you review this please?

@edieship I'm not very familiar with graylog, but are there users who might not want tags in their graylog metrics? What sort of query capability does this add?

**Comment by sparrc** [comment]
are there any drawbacks to adding the tags?

@jamescarr can you review as well?

**Comment by edieship** [comment]
The reason I want to add the tags is because almost all the metrics come with different tags to better differentiate them. For example, for the docker container metrics, the container name is one tag, without the tags in the metric output, it'a very difficult to tell which container are the metrics for.

**Comment by sparrc** [comment]
@edieship, it makes sense, TBH I'm surprised that the metrics were useful at all without the tags. I just want to make sure that current users of the plugin won't get negatively affected by this.

**Comment by jamescarr** [comment]
Yeah this is useful because I also hit this problem. The tags are useful for filtering in graylog (for example, I commonly want to look at logs for a particular zone).

**Comment by sparrc** [comment]
OK, @edieship you can update the changelog and I'll merge

**Comment by sparrc** [comment]
cherry-picked the commits and made some tweaks to avoid some unnecessary allocations in the hash map: https://github.com/influxdata/telegraf/pull/1865

**Pull request closed without merging**
