### PR TITLE
fix: Reenable OpenBSD modbus support

### PR DESCRIPTION
**Pull request by geowiwi**
This is a follow-up to: https://github.com/influxdata/telegraf/pull/10047

- update modules for serial and modbus
- reenable modbus support on OpenBSD
- update wireguard/wgctrl for OpenBSD/arm64 support

YMMV on go.mod line 371, in my case the workaround was not necessary anymore.

### CODE REVIEW

**Comment by geowiwi** [comment]
!signed-cla

**Comment by reimda** [comment]
Hi @geowiwi, thanks for the PR! It will be nice to have modbus working on OpenBSD again. The PR doesn't build on linux or windows. Will you fix the imports for those platforms so CI will pass, then we'll get this reviewed and merged?

**Comment by geowiwi** [comment]
@reimda: please note wireguard/wgctrl update is only related to OpenBSD/arm64 support

**Review by srebhan — APPROVED** [review]
Awesome work @geowiwi. Looks good to me.

**Review by powersj — APPROVED** [review]

**Comment by geowiwi** [comment]
I noticed the bits related to wgctrl already made it to 1.21.4 in https://github.com/influxdata/telegraf/commit/fda08c5d43743b9be8eeed17e79beeb6c5fd8060.

Will the serial-x update make 1.21.5 or is this scheduled for a later release?

**Comment by powersj** [comment]
This PR will go out in v1.22.0 this week.

**Pull request merged**
