### PR TITLE
Provide a way to set socket permissions for unix/dgram sockets

### PR DESCRIPTION
**Pull request by gentstr**
#3239

* Defaults to world-writable by default (777)
* New configuration option file_mode allows for custom permissions

### Required for all PRs:
- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Thanks for the PR.  Can you make it so the default is not to chmod, so that the umask settings take effect, and also see if you can move the chmod code after the switch statement so you can share that code (alternately use a function).  Finally don't forget to gofmt.

**Comment by phemmer** [comment]
Also relying on permissions of the socket file for security is not a good practice. It works on linux, but it might be a good idea to toss in a warning in the docs:

http://man7.org/linux/man-pages/man7/unix.7.html
>       On Linux, connecting to a stream socket object requires write permis‐
>       sion on that socket; sending a datagram to a datagram socket likewise
>       requires write permission on that socket.  POSIX does not make any
>       statement about the effect of the permissions on a socket file, and
>       on some systems (e.g., older BSDs), the socket permissions are
>       ignored.  Portable programs should not rely on this feature for secu‐
>       rity.

Using `chmod` for security is also racy. Because the socket is created with different permissions at first, a client can connect before they have been adjusted.

The best practice for permissions on unix sockets is to either set the permissions on the directory, or to use [`SCM_CREDENTIALS`](http://man7.org/linux/man-pages/man7/unix.7.html)

**Comment by danielnelson** [comment]
> either set the permissions on the directory...

This seems like something that should be done outside of Telegraf.  Before starting the plugin the user would create a directory with posix acls or setgid or another method to ensure the socket created inside has the right permissions.  I imagine this would work today with no changes.

> to use SCM_CREDENTIALS

I'm new to this, but it looks like this sends us the uid, gid of the connecting user.  At that point we would  verify that it matches our selected user/group in Telegraf application code?

**Comment by phemmer** [comment]
> This seems like something that should be done outside of Telegraf

Yes, sorry. I wasn't proposing that telegraf do this :-)

> I'm new to this, but it looks like this sends us the uid, gid of the connecting user.

Something along those lines. Note that it only sends their primary GID, not their supplementary groups. So you'd have to do a name service lookup on the UID to get all the other groups the user is in.

**Comment by danielnelson** [comment]
Okay, this makes sense to me.  I'm going to close this pull request, we should do the SCM_CREDENTIALS instead.

**Comment by danielnelson** [comment]
It is possible to use this feature to either restrict or loosen permissions to a socket.  Creating a parent directory with tighter permissions and `SCM_CREDENTIALS` are good ways to tighten the permissions.  However, I suspect most actually want the opposite; to allow processes not in the `telegraf` group to write to the socket.

It seems that before `SCM_CREDENTIALS` can be used, you need filesystem access to be able to connect to the socket permissions, so they aren't helpful for loosening permissions.  Instead, it seems that the only methods are by using chmod after socket creation or changing the process umask.

If we wanted to change the umask, we would need to lock any file creation operations to avoid creating files with the wrong permissions.  This isn't undoable but would be a bit of work and a possible source of bugs.

That leaves us with chmod.  Considering only the case where we make the socket more permissive the race between creations and chmod will result in a moment where the the socket exists but connection will result in permission denied.  It does not appear that this can be avoided, but seems like something a client could take in consideration and since the permissions are being loosened it doesn't seem like a security issue.

In the chmod solution where the permissions are being tightened it is a security issue, but as pointed out the socket should already be put into a directory with restrictive permissions instead of relying on the socket perms.

This makes me think we should resurrect this pull request, and add some additional guidance to the sample config and README.

**Comment by danielnelson** [comment]
Closed in #5760

**Pull request closed without merging**
