### PR TITLE
Add support for self-signed certs to RabbitMQ input plugin

### PR DESCRIPTION
**Pull request by mattyjones**
### Required for all PRs:

- [x] CHANGELOG.md updated
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

This adds initial support for using self-signed certs. It will default to false to preserve existing functionality but can be set to `true` if desired. It also adds godoc strings where need to prevent my linter from going haywire.

screen shot 2016-07-17 at 5 52 19 pm

There are still outstanding golint issues that could be resolved. I will leave it up to the maintainers if this should be done. I would refactor it just to make the linter pass but the code that's present is more readable so I am leaving it in place.

The code changes here are functionality identical to `curl -k` for reference.

At some point it would be nice to have this folded into agent as this is implemented in several plugins already and could be written in a standard manner for all plugins to use.

### CODE REVIEW

**Comment by sparrc** [comment]
@mattyjones there is a generic internal helper function for fully supporting self-signed certs. See the httpjson.go plugin for an example.

**Comment by mattyjones** [comment]
@sparrc Thanks for the tip, refactored it and we are light and bright.

**Comment by mattyjones** [comment]
@sparrc  This is complete from my point of view, if you guys have further feedback let me know. If I need anything else I will open up additional PR's to keep things clean.

**Comment by sparrc** [comment]
thanks @mattyjones!

**Pull request merged**
