### PR TITLE
Update docker plugin

### PR DESCRIPTION
**Pull request by danielnelson**
### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
closes #2457

**Comment by danielnelson** [comment]
@georgyturevich @eesprit I have done a few improvements to the docker plugin here, and decided to bring in the unix and windows helper functions in order for us to behave more like the docker cli.  This should also fix the reporting of unset stats on Windows.  It would be great if both of you could double check that everything is still working as expected.

**Comment by georgyturevich** [comment]
@danielnelson 

Hi Daniel, the code looks good to me, but I am not a big expert in Golang. If you already have some compiled binaries, I can try to test it on my environment.

**Comment by eesprit** [comment]
@danielnelson the new docker client code seems to break when using the regular Unix Socket :

> juil. 26 13:08:40 vp909doc1003 telegraf[170236]: 2017-07-26T11:08:40Z E! Error in plugin [inputs.docker]: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/containers/json?limit=0: dial tcp: lookup /var/run/docker.sock: invalid domain name
> juil. 26 13:08:40 vp909doc1003 telegraf[170236]: 2017-07-26T11:08:40Z E! Error in plugin [inputs.docker]: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/info: dial tcp: lookup /var/run/docker.sock: invalid domain name

**Comment by eesprit** [comment]
Might be due to creating an httpClient and passing it to NewClient().
For Unix Socket, the httpClient should be nil so the socket type is correctly configured (just a guess though) : https://github.com/moby/moby/blob/master/client/client.go#L173 which leads to https://github.com/docker/go-connections/blob/master/sockets/sockets.go#L21

That was the case when it was working (httpClient was nil) so I think that is the actual problem with the TLS patch.

A solution would be to parse the host string like it is done here : https://github.com/moby/moby/blob/master/client/client.go#L162
And then check the proto to test if unix or tcp and create le Client depending on that.

**Comment by danielnelson** [comment]
@eesprit Thanks for catching that, would be pretty bad if I totally broke the docker plugin.  I don't see a good way to pass just the `tls.Config` in without a client and transport, so I pulled the call to `sockets.ConfigureTransport` up into Telegraf.

**Comment by danielnelson** [comment]
@georgyturevich Here is a [Windows amd64 build](https://7676-33258973-gh.circle-artifacts.com/0/tmp/circle-artifacts.wCJLiId/build/windows/amd64/telegraf-0a83a27307451565c406ef3cefb2133e0de0ccff%257E0a83a27_windows_amd64.zip) for testing with.

**Comment by eesprit** [comment]
@danielnelson Works fine here, and metrics are corrects even with offline CPUs. 
I didn't test test in tcp mode and TLS, as I don't have a docker daemon configured in that mode on hand. I will see if I can take the time to setup one for testing though.

**Comment by danielnelson** [comment]
@eesprit I'm splitting the tls off into it's own pull request, I'll mention you when I open it.

**Pull request merged**
