### PR TITLE
feat(outputs.azure_data_explorer): Set user agent string

### LINKED ISSUE #14046: Add user agent headers to Azure Data Explorer
### Use Case

To troubleshoot issues when customers are using the Azure Data Explorer plugin, add a set of additional headers that contain information on IngestiontType used and if TablePerMetric options are used

### Expected behavior

Given a cluster URI, we can find the IngestionType and TablePerMetric types and look at the telemetry data coming in for troubleshooting

### Actual behavior

This feature does not exist. We have to go to the Customer to get these details to start troubeshooting

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ag-ramachandran**
# Required for all PRs

- [X] Updated associated README.md. - No changes applicable, hence not updated
- [X] Wrote appropriate unit tests. - No test changes are applicable (this is server side telemetry)
- [X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #14046

<!-- Finally, include a summary of the code change itself. This
description should tell reviewers how the issues were resolved.

Add headers in the connection string for telemetry (azure_data_explorer). When customers ask for support, this will help us determine options used

### CODE REVIEW

**Review by powersj — CHANGES_REQUESTED** [review]
Thanks for the PR.

In general, I do not see an issue with setting user-agent like settings and sharing them with the endpoint. I would even ask you set the version correctly using [ProductToken](https://github.com/influxdata/telegraf/blob/dd7449940ef8e670be5480fb8c8ab71c054de1b4/internal/internal.go#L71) instead of the hard-coded 1.0.0.

I understand the value in knowing these details when supporting users. However, I am less inclined to allow you to start sharing user's config details for the purpose of telemetry, without their permissions. Sharing those details should be opt-in.

**Comment by ag-ramachandran** [comment]
> feat(outputs.azure_data_explorer): add telemetry headers and options to connection string for troubleshooting



> Thanks for the PR.
> 
> In general, I do not see an issue with setting user-agent like settings and sharing them with the endpoint. I would even ask you set the version correctly using [ProductToken](https://github.com/influxdata/telegraf/blob/dd7449940ef8e670be5480fb8c8ab71c054de1b4/internal/internal.go#L71) instead of the hard-coded 1.0.0.
> 
> I understand the value in knowing these details when supporting users. However, I am less inclined to allow you to start sharing user's config details for the purpose of telemetry, without their permissions. Sharing those details should be opt-in.

Sure @powersj, I have removed config specific options. Right now only version of telegraf is passed in so there is no user config that is passed.

Does this look good

**Review by powersj — APPROVED** [review]
Thank you!

**Review by srebhan — APPROVED** [review]
Thanks for your contribution @ag-ramachandran!

**Pull request merged**
