### PR TITLE
feature(kubernetes plugin): Adds support for a kuberentes plugin

### LINKED ISSUE #569: kubernetes input plugin
It would be nice to see telegraf support kuberentes deployments. This means decorating metrics with appropriate pod labels (pod name, namespace, container name, etc..). 

I'll try and take a stab at this soon as I would like to use telegraf instead of cadvisor for collecting metrics on my k8s cluster.

### PR DESCRIPTION
**Pull request by jchauncey**
fixes #569
This commit also refactors the existing docker plugin so that the
kubernetes plugin can gather metrics from the docker system.

### CODE REVIEW

**Comment by jchauncey** [comment]
ok not sure why its failing on building the binary. The kubernetes dep was downloaded it seems.

**Comment by jchauncey** [comment]
@sparrc im not sure whats going on here. Does `gdm` actually download the repo? Or just attempt to checkout the revision?

**Comment by jchauncey** [comment]
so I think the test failures are because it hasnt fully downloaded the kubernetes repo and its trying to go ahead and build the telegraf client. Not sure how to proceed

**Comment by sparrc** [comment]
@jchauncey I'll checkout your changes and take a look

**Comment by sparrc** [comment]
I get this error:

```
% go get ./...
# k8s.io/kubernetes/pkg/util/parsers
../../../k8s.io/kubernetes/pkg/util/parsers/parsers.go:30: undefined: parsers.ParseRepositoryTag
```

it seems like there are dependency issues here....tip of master docker parsers doesn't have that function: https://github.com/docker/docker/blob/master/pkg/parsers/parsers.go

**Comment by jchauncey** [comment]
Yeah you need the sha that is pinned for the docker/docker repo in go deps

**Comment by sparrc** [comment]
Is adding 14 new dependencies really the _only_ way to get the kubernetes tags? Isn't there some kind of simple API to get the same information without all of these huge client libraries? 

Adding this PR will also require hand-editing the Godeps file from now on

**Comment by jchauncey** [comment]
No this is the crappy thing about talking to the kube api. We've been
dealing with this in every deis project and it sucks. That's why I was
asking about using glide earlier. With the vendor directory and a glide
lock file it helps relieve so of the issues with pulling down the
kubernetes deps.

**Comment by jchauncey** [comment]
Sorry I didn't answer your question. Yes this is really the only way to talk to the kube api without using kubectl

**Comment by sparrc** [comment]
It built fine for me on OSX, but this change also increases the size of the binary by 63% (from 32M to 52M). I'm really not sure this is something that I want part of the Telegraf repo, I'll have to think on it.

unfortunate that the kubernetes api is so cumbersome, given the circumstances I wouldn't be opposed to having this plugin require the kubectl binary

**Comment by jchauncey** [comment]
@sparrc going to give the repo at the bottom of this issue a try tomorrow https://github.com/kubernetes/kubernetes/issues/11606

**Comment by jchauncey** [comment]
https://github.com/golang/build/blob/master/kubernetes/client.go

**Comment by sparrc** [comment]
interesting that the Go authors are maintaining a Kubernetes api library, hopefully it has enough capabilities for this plugin :+1:

**Comment by jchauncey** [comment]
So we have decided we are going to spend some time and see if we can build a light weight kubernetes api for people to use. Seems like the right thing to do since a lot of people are needing one. I'll update the PR when we get it done.

**Comment by sparrc** [comment]
great! :100:

closing this PR for the time being then

**Comment by Raffo** [comment]
@jchauncey Any chance we can collaborate on that? I was about to do the same, starting from the link you posted...

**Comment by jchauncey** [comment]
I think it might be fruitless now that I've spent a few days on it. If you
want a feature complete client you basically need what they have in the
main kubernetes repo. I have managed to reduce the deps on that repo to 13
but I can't go any further.

If influx doesn't want to increase the size of the binary then I'll just
maintain my own fork that includes the plugin.

**Comment by Raffo** [comment]
Ok, this means that problem must be addressed again in the kubernetes repo. It's not reasonable to have clients of Kubernetes that are that big. Thanks for the reply, anyway.

**Comment by sparrc** [comment]
@jchauncey what about the golang kubernetes library (https://godoc.org/golang.org/x/build/kubernetes)? Does that not have the ability to get kubernetes tags?

**Comment by jchauncey** [comment]
It can get the labels but using it within an existing kube cluster is a
little more difficult. You need to authenticate to talk to the kubeapi from
within a pod. It lacks this capability and adding it would require me to
basically pull in the deps that the main kube client already has. I'm not
sure it would reduce the size in the end.

**Pull request closed without merging**
