### PR TITLE
feat(inputs.gnmi): Rework plugin

### LINKED ISSUE #14044: GNMI / Got empty metric-name for response /
### Relevant telegraf.conf

```toml
[[inputs.gnmi]]
  addresses = ['${addresses}']
  username = "xxx"
  password = "xxx"
  redial = "60s"
  encoding = "json_ietf"
  [[inputs.gnmi.subscription]]
    name = "ifdesc"
    origin = "openconfig-interfaces"
    path = '/interfaces/interface[name=FourHundredGigE*]/state/description'
    subscription_mode = "sample"
    sample_interval = "60s"
  [[inputs.gnmi.subscription]]
    name = "temperature"
    origin = "openconfig-platform"
    path = '/components/component[name=FourHundredGigE*]/state/temperature/avg'
    subscription_mode = "target_defined"
  [[inputs.gnmi.subscription]]
    name = "Cisco-optics-lanes"
    origin = "Cisco-IOS-XR-controller-optics-oper"
    path = '/optics-oper/optics-ports/optics-port[name=Optics0/2/0/*]/optics-lanes/optics-lane'
    subscription_mode = "target_defined"
  [[inputs.gnmi.subscription]]
    name = "Cisco-optics-info"
    origin = "Cisco-IOS-XR-controller-optics-oper"
    path = '/optics-oper/optics-ports/optics-port[name=Optics0/2/0/*]/optics-info'
    subscription_mode = "target_defined"
  [[inputs.gnmi.subscription]]
    name="Cisco-controller-otu"
    origin = "Cisco-IOS-XR-controller-otu-oper"
    path = '/otu/controllers/controller[controller-name=CoherentDSP0/2/0/*]/info'
    subscription_mode = "target_defined"
```

### Logs from Telegraf

```text
023-10-03T09:08:02Z D! [inputs.gnmi] Connection to gNMI device 10.44.250.93:12346 established
2023-10-03T09:08:02Z W! [inputs.gnmi] Got empty metric-name for response, usually indicating
configuration issues as the response cannot be related to any subscription.
Please open an issue on https://github.com/influxdata/telegraf including your
device model and the following response data:
timestamp:1696324083211000000 prefix:{origin:"openconfig-interfaces"} update:{path:{elem:{name:"interfaces"} elem:{name:"interface" key:{key:"name" value:"FourHundredGigE0/2/0/3"}} elem:{name:"state"}} val:{json_ietf_val:"{\"description\":\"REDACTED \"}"}}
This message is only printed once.
```

### System info

Telegraf 1.28.1 / Cisco ASR 9922

### Docker

_No response_

### Steps to reproduce

1. Regroup all subscription under 1 input
2. Telegraf will start but will emit the initial error message and "Could not serialize metric: invalid name" 

### Expected behavior

Telegraf doesn't create any error and we expect to get the desired data from the openconfig-interfaces. 

### Actual behavior

Telegraf display an error at startup, and we don't get the desired data from the openconfig-interfaces. 
Moreover, we get lots of errors like this :
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name

### Additional info

The workaround we use is define 2 inputs gnmi like this :
```
[[inputs.gnmi]]
  addresses = [${addresses}]
  username = "xxx"
  password = "xxx"
  redial = "60s"
  encoding = "json_ietf"
  name_override = "Cisco"
  [[inputs.gnmi.subscription]]
    name = "ifdesc"
    origin = "openconfig-interfaces"
    path = '/interfaces/interface[name=FourHundredGigE*]/state/description'
    subscription_mode = "sample"
    sample_interval = "60s"
  [[inputs.gnmi.subscription]]
    name = "temperature"
    origin = "openconfig-platform"
    path = '/components/component[name=FourHundredGigE*]/state/temperature/avg'
    subscription_mode = "target_defined"
 
[[inputs.gnmi]]
  addresses = [${addresses}]
  username = "xxx"
  password = "xxx"
  redial = "60s"
  encoding = "json_ietf"
  [[inputs.gnmi.subscription]]
    name = "Cisco-optics-lanes"
    origin = "Cisco-IOS-XR-controller-optics-oper"
    path = '/optics-oper/optics-ports/optics-port[name=Optics0/2/0/*]/optics-lanes/optics-lane'
    subscription_mode = "target_defined"
  [[inputs.gnmi.subscription]]
    name = "Cisco-optics-info"
    origin = "Cisco-IOS-XR-controller-optics-oper"
    path = '/optics-oper/optics-ports/optics-port[name=Optics0/2/0/*]/optics-info'
    subscription_mode = "target_defined"
  [[inputs.gnmi.subscription]]
    name="Cisco-controller-otu"
    origin = "Cisco-IOS-XR-controller-otu-oper"
    path = '/otu/controllers/controller[controller-name=CoherentDSP0/2/0/*]/info'
    subscription_mode = "target_defined"
 ```

### LINKED ISSUE #14063: inputs.gnmi fails when metric-name is empty
### Relevant telegraf.conf

```toml
# Ciena gNMI
[agent]
  interval = "5m"

[[inputs.gnmi]]
  alias = "ciena-gnmi"
  addresses = ["10.144.248.3:6702"]
  username = "XXXXXXXXXXXXXXXXXXXX"
  password = "XXXXXXXXXXXXXXXXXXXX"
  encoding = "proto"
  redial = "10s"
  enable_tls = true
  insecure_skip_verify = true
  tls_ca = "/etc/telegraf/ciena-ca.cert.pem"
  tls_cert = "/etc/telegraf/ciena-client.cert.pem"
  tls_key = "/etc/telegraf/ciena-client.key.pem"
  name_override = "saos10xgnmi"
  updates_only = true

  fieldpass = ["path","source",
               "Ciena:/oc_if:interfaces/oc_if:interface/oc_if:state/oc_if:countersCiena:/in_crc_error_pkts",
               "Ciena:/oc_if:interfaces/oc_if:interface/oc_if:state/oc_if:countersCiena:/in_discards",
               "Ciena:/oc_if:interfaces/oc_if:interface/oc_if:state/oc_if:countersCiena:/in_errors",
               "Ciena:/oc_if:interfaces/oc_if:interface/oc_if:state/oc_if:countersCiena:/in_octets",
               "Ciena:/oc_if:interfaces/oc_if:interface/oc_if:state/oc_if:countersCiena:/name",
               "Ciena:/oc_if:interfaces/oc_if:interface/oc_if:state/oc_if:countersCiena:/out_errors",
               "Ciena:/oc_if:interfaces/oc_if:interface/oc_if:state/oc_if:countersCiena:/out_octets"]

  tagexclude = ["path","name"]

  [[inputs.gnmi.subscription]]
     name = "ifcounters"
     origin = "openconfig-interfaces"
     path = "/oc-if:interfaces/oc-if:interface/oc-if:state/oc-if:counters"
     subscription_mode = "sample"
     sample_interval = "30s"
```

### Logs from Telegraf

```text
telegraf  | 2023-10-06T18:41:35Z W! [inputs.gnmi::ciena-gnmi] Got empty metric-name for response, usually indicating
telegraf  | configuration issues as the response cannot be related to any subscription.
telegraf  | Please open an issue on https://github.com/influxdata/telegraf including your
telegraf  | device model and the following response data:
telegraf  | timestamp:1696617695101000000 prefix:{origin:"Ciena" elem:{name:"oc-if:interfaces"} elem:{name:"oc-if:interface"} elem:{name:"oc-if:state"} elem:{name:"oc-if:counters"}} update:{path:{origin:"Ciena" elem:{name:"in-1024-to-1518-octet-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-128-to-255-octet-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-1519-to-2047-octet-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-2048-to-4095-octet-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-256-to-511-octet-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-4096-to-9216-octet-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-512-to-1023-octet-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-64-octet-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-65-to-127-octet-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-broadcast-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-crc-error-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-discards"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-discards-octets"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-dropped-octets"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-dropped-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-errors"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-jabber-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-multicast-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-octets"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-oversize-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-undersize-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"in-unicast-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"last-clear"}} val:{uint_val:1691859140059797458}} update:{path:{origin:"Ciena" elem:{name:"link-flap-events"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"name"}} val:{string_val:"\"1\""}} update:{path:{origin:"Ciena" elem:{name:"out-1519-to-2047-octet-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"out-2048-to-4095-octet-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"out-4096-to-9216-octet-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"out-broadcast-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"out-errors"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"out-multicast-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"out-octets"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"out-pkts"}} val:{uint_val:0}} update:{path:{origin:"Ciena" elem:{name:"out-unicast-pkts"}} val:{uint_val:0}}
telegraf  | This message is only printed once.
```

### System info

Telegraf 1.28.2, Debian 11, Docker 20.10.5

### Docker

_No response_

### Steps to reproduce

1. Run under telegraf > 1.26.2
2. Any Ciena router (SAOS 10.8) fails
3.
...

### Expected behavior

It was working fine under 1.26.2 once this message was made a warning (instead of an error). But, now anything newer than 1.26.2 fails.

### Actual behavior

The data just isn't output, presumable because it isn't parseable. Removing the origin parameter in the config yields the erorr message but still no data output.

### Additional info

I've opened a previous issue on this and it was fixed in 1.25 but now it's broken again . . .

### PR DESCRIPTION
**Pull request by srebhan**
- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #14044
resolves #14063

This PR reworks the GNMI input plugin to untangle the functions and get a clearer structure. The new code is easier to follow and has a better modularity.
In the course of restructuring issue #14044 is fixed and a unit-test for the issue was added. Furthermore, we can now guess the path tag for strange devices (as e.g. reported in #14044) that do not provide prefix information.

### CODE REVIEW

**Comment by whizkidTRW** [comment]
Yes, that works! And I think this formatting of the field names by default is much better.

I almost didn't think it was working but in simplifying the config for testing, I found the problem. The ```fieldpass``` config I had been using all along was blocking it with this new ```1.29.0``` binary as the returned field names have changed vs. previous versions.

For anyone else interested in the details, the fields were coming through as (up through ```1.26.3```):
```
Ciena:/oc_if:interfaces/oc_if:interface/oc_if:state/oc_if:countersCiena:/out_octets=330249284806i
```

but now with this new code, they are:
```
out_octets=35445208113i
```

And, apparently, this was also changed starting in ```1.27.0``` as now those versions work too just as long as the ```fieldpass``` is updated accordingly. My apologies in not catching it earlier! From ```1.27.0``` to the latest (```1.28.2```), the fields come through as this: (notice the lack of ```Ciena``` on the end of ```oc_if:counters```)
```
Ciena:/oc_if:interfaces/oc_if:interface/oc_if:state/oc_if:counters/out_octets=35457943306i
```

And, to clarify, for versions ```1.27.0``` thru ```1.28.2```, setting ```origin = "Ciena"``` causes the above (```1.29.0```) shortened behavior to occur as well. Versions prior to ```1.27.0``` have a bug where the field comes through like this if ```origin = "Ciena"```:

```
iena:/out_octets=330286427762i
```

**Comment by srebhan** [comment]
@whizkidTRW there is also a `canonical_field_names` option which should bring back the long field names... Just in case you like cryptic names... ;-P

**Comment by whizkidTRW** [comment]
LOL That's good to know, but I'm good. I was already overriding them to something sensical, very close to the new output . . .

Thanks!

**Review by powersj — APPROVED** [review]
wow - thank you for improving this plugin.

**Comment by powersj** [comment]
@srebhan 2 conflicts to address, then feel free to land it

**Pull request merged**
