### PR TITLE
feat(http): support aws prometheus

### PR DESCRIPTION
**Pull request by baloo**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

This adds support to write to Amazon Managed Service for Prometheus.
Writing to AWS Prometheus requires queries to be signed with AWS v4 signatures, this PR adds support for that.

### CODE REVIEW

**Comment by baloo** [comment]
Individual CLA signed, Corporate CLA should have been amended to include me yesterday.

**Comment by sspaink** [comment]
!signed-cla

**Review by sspaink — APPROVED** [review]

**Comment by sspaink** [comment]
@baloo feature looks good to me, there is a minor linter issue that needs to be resolved before this can be merged.

**Comment by baloo** [comment]
@sspaink last lint error is currently in master afaict. Do you want me to fix this here?

**Comment by sspaink** [comment]
Looks like it has been fixed in master already with this PR: https://github.com/influxdata/telegraf/pull/10159, you will have to rebase this pr on master.

**Review by powersj — APPROVED** [review]

**Pull request merged**
