### PR TITLE
Replace hardcoded metrics name with a variable.

### LINKED ISSUE #14944: Replace hardcoded string with a variable for acc.AddFields() call in win_eventlog input plugin.
### Use Case

In our department several teams share the same telegraf service, and also share the same input plugin win_eventlog. To differentiate the metrics, we expect the metrics with different names corresponding to team name.
By importing the win_eventlog package and wrapping Gather() function, we can create different plugins for each team. 
The problem is that,  although metrics are collected through different plugins, all metrics name are "win_eventlog", because it is hardcoded.
https://github.com/influxdata/telegraf/blob/9a9bb16c08adab133f2d995d6e26bdad130999ef/plugins/inputs/win_eventlog/win_eventlog.go#L247

### Expected behavior

We can customize the name in metrics.

### Actual behavior

All the metircs with the same hardcoded name "win_eventlog".

### Additional info

Possible solution:
Add PluginName to WinEventLog:
```
type WinEventLog struct {
	PluginName string ``toml: plugin_name`
	...
}
```
And initialize the variable at init():
```
func init() {
	inputs.Add("win_eventlog", func() telegraf.Input {
		return &WinEventLog{
			PluginName:        "win_eventlog",
...
}
```
at Gather(), just replace the hardcoded string with the variable:
```
			acc.AddFields(w.PluginName, fields, tags, timeStamp)
```

After the change, we can import the win_eventlog package and customize the metrics name during init(), such as "win_eventlog_teamA"

### PR DESCRIPTION
**Pull request by nonpolarity**
## Checklist

- [ ] No AI generated code was used in this PR

## Related issues

resolves #14944

### CODE REVIEW

**Review by srebhan — CHANGES_REQUESTED** [review]
Is there a reason not to use the global `name_override` option (see [documentation](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-plugins))?

**Comment by nonpolarity** [comment]
> Is there a reason not to use the global `name_override` option (see [documentation](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-plugins))?

for example, we expect two names "win_eventlog_teamA" and "win_eventlog_teamB", so we add two input plugins and import the package "github.com/influxdata/telegraf/plugins/inputs/win_eventlog". The effect is that both plugin generate metric with name "win_eventlog".  The name_override will not help. It is not plugin level, it is metric level.

**Comment by srebhan** [comment]
@nonpolarity the `name_override`**IS** per plugin!

**Comment by nonpolarity** [comment]
> @nonpolarity the `name_override`**IS** per plugin!

Sorry I don't mean the `name_override` feature, I mean the name issue. The plugins names are correct, but the metric name is wrong. Since it is hardcoded, it is impossible to get different names.

**Comment by srebhan** [comment]
@nonpolarity please try

```toml
[[input.win_eventlog]]
  name_override = "win_eventlog_teamA"
  ...

[[input.win_eventlog]]
  name_override = "win_eventlog_teamB"
  ...
```
it will do _exactly_ what you are trying to do in this PR and thus duplicate functionality!

**Comment by nonpolarity** [comment]
> ```toml
> [[input.win_eventlog]]
>   name_override = "win_eventlog_teamA"
>   ...
> 
> [[input.win_eventlog]]
>   name_override = "win_eventlog_teamB"
> ```

You are right, this feature can solve the problem. 

To make it clean, the config should be like this:
```
[[input.win_eventlog_teamA]]
  name_override = "win_eventlog_teamA"
  ...

[[input.win_eventlog_teamB]]
  name_override = "win_eventlog_teamB"
  ```

**Pull request closed without merging**
