### PR TITLE
feat: adding sudo entry (#11352)

### PR DESCRIPTION
**Pull request by Tulux**
### Required for all PRs:

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

### CODE REVIEW

**Comment by reimda** [comment]
Hi @Tulux, thanks for the PR.

It may make sense for procstat to have a use_sudo setting, but it doesn't currently have that setting. This PR changes the to documentation to add use_sudo but it doesn't change the code to add it. Are you planning to update this PR and add use_sudo to the code?

**Comment by Tulux** [comment]
> Hi @Tulux, thanks for the PR.
> 
> It may make sense for procstat to have a use_sudo setting, but it doesn't currently have that setting. This PR changes the to documentation to add use_sudo but it doesn't change the code to add it. Are you planning to update this PR and add use_sudo to the code?

Hi @reimda,

@powersj just replied ;) We are discussing about it in #11352.

Florent

**Comment by reimda** [comment]
Since you're still working on the design, I'm going to make this a draft for now. When it's ready, you can switch it back

**Comment by MyaLongmire** [comment]
@Tulux any update on this?

**Comment by Tulux** [comment]
@MyaLongmire As per #11352 I am not able to go further on this, therefore I close this pull request

**Pull request closed without merging**
