### PR TITLE
additional fields in procstat plugin

### PR DESCRIPTION
**Pull request by rubycut**
Sponsored by ControlUP.com

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by rubycut** [comment]
Hi @danielnelson , what is the usual time frame for pull requests?

**Comment by russorat** [comment]
i don't think i see it in this PR, but would it be possible to add uptime here to support #2203?

**Comment by rubycut** [comment]
@russorat uptime is already present, https://github.com/influxdata/telegraf/blob/ec47cab950cb733cb56b10ba50313f0d167fff01/plugins/inputs/system/system.go#L56

**Comment by bmagistro** [comment]
@rubycut I believe @russorat (and ourselves) are interested in a processes uptime which is different than the general system uptime.  On a linux system this can be pulled from `/proc/<pid>/stat` (field 22 -- starttime) but takes some massaging to get back to seconds.

**Comment by rubycut** [comment]
Hi @bmagistro as you can see, this pull request is open for almost 4 months and still not merged. I am not willing to contribute anymore code until owners start promptly merging pull requests.

**Comment by danielnelson** [comment]
@glinton I accidentally closed this by deleting the target branch, reopening against master.  You might need to push the branch again.

**Comment by sjwang90** [comment]
Closed due to inactivity. Feel free to re-open if this is something you would like to continue working on.

**Pull request closed without merging**
