### PR TITLE
fix(kubernetes): Only initialize RoundTripper once

### LINKED ISSUE #1933: Kuberentes plugin leaking connections
## Bug report
The kubernetes plugin is leaking connections which is also leaking memory. 

[Include Telegraf version, operating system name, and other relevant details]
Version: master telegraf 
OS: ubuntu docker image

### Steps to reproduce:
Enable kubernetes plugin and wait

### Expected behavior:
Should close connections responsibly 

### Actual behavior:
Never closes opened connections

### PR DESCRIPTION
**Pull request by jchauncey**
fixes #1933

### CODE REVIEW

**Comment by jchauncey** [comment]
@sparrc Since the kubernetes plugin hadn't been released yet I didnt add this bug fix to the changelog. Do you still want me to do that?

**Comment by sparrc** [comment]
that's alright, can you rebase your changes so the CircleCI tests pass? Have you tested that this fixes the issue?

**Comment by jchauncey** [comment]
Yeah we tested that this fixes the issue. I'll rebase in just a bit.

**Comment by jchauncey** [comment]
We should probably open an issue to audit the other plugins that reach out over http and make sure they are following the same pattern.

**Comment by sparrc** [comment]
thanks @jchauncey, I opened #1954

**Pull request merged**
