### PR TITLE
Added support for a TLS-enabled Docker daemon

### PR DESCRIPTION
**Pull request by AntonBazhal**

### CODE REVIEW

**Comment by sparrc** [comment]
thanks @AntonBazhal for the contribution. We've had some permissions issues with the current docker client library so I'm going to wait for #645 to get fixed before merging this.

**Comment by sparrc** [comment]
Hi @AntonBazhal, I'm closing this PR because it will need to be refactored for the new docker plugin, which uses docker's official libraries to gather stats rather than the 3rd-party library that we were using before.

**Comment by sparrc** [comment]
ps: I would be happy to merge if you can refactor to use the new library

**Comment by AntonBazhal** [comment]
@sparrc, problem with the new library is that it does not have corresponding NewTLSClient class, thus it is not possible to refactor.

**Comment by tripledes** [comment]
@AntonBazhal the newclient() method from the new docker library takes an http.Client as a parameter, so you need to configure the transport layer to use TLS. So it should be possible to refactor your PR. Let me know if I could be of any help.

https://godoc.org/github.com/docker/engine-api/client#NewClient

**Pull request closed without merging**
