### PR TITLE
Add tcp/udp check connection input plugin

### PR DESCRIPTION
**Pull request by titilambert**
Rebased PR of #476

### CODE REVIEW

**Comment by titilambert** [comment]
@sparrc Thanks ! I fixed the sample config ;)

**Comment by sparrc** [comment]
could you write a README in the format of https://github.com/influxdata/telegraf/blob/master/plugins/inputs/EXAMPLE_README.md?

**Comment by sparrc** [comment]
since we can specify multiple `[[input.connection]]` entries, can you change config to look more like this:

```
[[inputs.connection]]
  # must be either "tcp" or "udp"
  type = "tcp"
  # Server address (default IP localhost)
  address = "github.com:80"
  # Set timeout (default 1.0)
  timeout = 1.0
  # Set read timeout (default 1.0)
  read_timeout = 1.0
  # String sent to the server
  send = "ssh"
  # Expected string in answer
  expect = "ssh"
```

**Comment by titilambert** [comment]
@sparrc Done !

**Comment by gianarb** [comment]
Awesome!! A good way to decrease the latency.. :+1: Thanks

**Comment by sparrc** [comment]
This looks good @titilambert, the only problem I have is that I feel like the name `connection` is a bit vague.

But, I'm also having trouble coming up with a good name, maybe just `response_time` would be  a better name? or `net_response`?

**Comment by titilambert** [comment]
@sparrc I had the same feeling when I choose the name ... 
Nagios equivalent plugins are `check_tcp` and `check_udp`...
I think I like `net_response`, but I would suggest some others: `net_connection`, `tcpudp_connection`, `port_check`.
What do you think ?

**Comment by sparrc** [comment]
I like `net_response` or `net_connection`, with a slight preference for `net_response` since it describes the data that you get out of the plugin (response time)

I'm leaning away from `tcpudp` because at some point I think we could add `http` response times to this plugin as well.

**Comment by titilambert** [comment]
@sparrc let's go for `net_response` !
I'm currently doing a input plugin for kubernetes, once finished, I will make this change.

**Comment by sparrc** [comment]
OK, but someone has already tried to do that: https://github.com/influxdata/telegraf/pull/665

I rejected the PR because it seems that the kubernetes client library is very tied up with their entire repo, and adding it requires adding 10-12 huge dependencies to Telegraf that almost doubled the binary size.

Although there's also the option of requiring kubernetes-cli or some external executable as a dependency of the plugin

**Comment by titilambert** [comment]
@sparrc I do not use kubernetes client lib :)
I use "/metrics" endpoints which show data with prometheus format :) So just you prometheus client lib.
I'm currently adding a new parser in plugins/parsers folder.

**Comment by titilambert** [comment]
@sparrc changes done !

**Comment by sparrc** [comment]
great, thanks for another contribution @titilambert

**Comment by sparrc** [comment]
@titilambert I sent you an email for some swag ~2 weeks ago, did you receive it?

**Comment by titilambert** [comment]
@sparrc no I didn't anything. Could you PM me on twitter ?

**Comment by sparrc** [comment]
@titilambert sure, will do

**Pull request closed without merging**
