### PR TITLE
fix: install after useradd

### PR DESCRIPTION
**Pull request by powersj**
fixes: #3833

### CODE REVIEW

**Comment by Snelius30** [comment]
Why did not merged?

**Comment by powersj** [comment]
> Why it has not been merged?

If you look at my last comment on the issue that reported this, you will find that no one confirmed the fix or continued responding: https://github.com/influxdata/telegraf/issues/3833#issuecomment-1609735948

**Comment by Snelius30** [comment]
> > Why it has not been merged?
> 
> If you look at my last comment on the issue that reported this, you will find that no one confirmed the fix or continued responding: [#3833 (comment)](https://github.com/influxdata/telegraf/issues/3833#issuecomment-1609735948)

Ok. I have tested with this Makefile changes. It works very well for SuSe 15.4. I think we should include the patches cause the problem exists and u have fixed it.

**Comment by powersj** [comment]
@Snelius30 thanks I do appreciate the feedback - I'll put the PR up again.

**Pull request closed without merging**
