### PR TITLE
Change node_name to be a tag in aerospike input

### LINKED ISSUE #2917: Incorrect aerospike metrics export to prometheus with more than 1 node in aerospike cluster
### Relevant telegraf.conf:

```
[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  hostname = ""


[[outputs.prometheus_client]]
  listen = "192.168.1.18:9126"

[[inputs.aerospike]]
  servers = ["localhost:3000"]
```

### System info:

```
Telegraf v1.3.1 (git: release-1.3 f93615672b02a41d9bc867bd92bf31c1d777989b)
Linux dev01 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### Steps to reproduce:

1. Generate config```telegraf -input-filter aerospike -output-filter prometheus_client config```
2. Get metrics from telegraf ``` telegraf --config telegraf.conf -test```
3. Get metrics from prometheus_client output ```curl 192.168.1.18:9126/metrics```. Do it few times.
4. Compare metrics that didn't change (device_used_bytes maybe) with what you got from curl.

### Expected behavior:

prometheus_client should provide aerospike metrics from the host where telegraf is running.

### Actual behavior:

prometheus_client may provide metrics from any host in your aerospike cluster.

### Additional info:

If you do telegraf -test, it will give you aerospike_node and aerospike_namespace X times, where X is the node count in your aerospike cluster. Then if you query prometheus_client output with curl on :9126/metrics you will get 1 set of metrics, which should be from the host where telegraf is running. But actually it gives you metrics from any of your aerospike hosts and host may change every collection interval. It results in a lot of spikes on dashboards even for metrics than didn't actually change.
In previous version 1.2.1 it always get metrics from the same one host, but it is not necessary the right host.

### PR DESCRIPTION
**Pull request by danielnelson**
Without this all nodes would create conflicting series.

fixes #2917

### Required for all PRs:

- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@popov-ilya Can you test this change? Here is the [amd64 build](https://7172-33258973-gh.circle-artifacts.com/0/tmp/circle-artifacts.x1MBq4c/telegraf.gz).

**Comment by popov-ilya** [comment]
```
ilya-popov@dev01:~$ curl 192.168.1.18:9127/metrics | grep aerospike_node_objects
# HELP aerospike_node_objects Telegraf collected metric
# TYPE aerospike_node_objects untyped
aerospike_node_objects{aerospike_host="localhost:3000",host="dev01",node_name="BB92F7E6C005452"} 7919
aerospike_node_objects{aerospike_host="localhost:3000",host="dev01",node_name="BB947F50D005452"} 7532
aerospike_node_objects{aerospike_host="localhost:3000",host="dev01",node_name="BB9B84A3B005452"} 7367
aerospike_node_objects{aerospike_host="localhost:3000",host="dev01",node_name="BB9F1EA1A005452"} 7144
```
Now it gives 4 times more series, but i can finally get correct data. Thank you!

**Comment by danielnelson** [comment]
I didn't see a way to determine which node is the "local" one using aerospike-client-go, though I didn't look too deeply.  If we did have a way we could potentially add an option to allow switching between full cluster and local node only mode, similar to what we have for elasticsearch.

This is technically a breaking change, but I think it must be done since otherwise this input is totally unusable with multiple nodes.

**Comment by popov-ilya** [comment]
Don't know about other outputs, but in prometheus i can drop unnecessary series when pulling it from telegraf.

**Comment by danielnelson** [comment]
Great, it is also possible for any output/input to use the tagpass/tagdrop options to prevent some of the series from being output.

**Comment by kportertx** [comment]
> I didn't see a way to determine which node is the "local" one using aerospike-client-go, though I didn't look too deeply. 

@danielnelson You cold use [RequesInfo()](https://godoc.org/github.com/aerospike/aerospike-client-go#RequestInfo) and pass a connection to localhost (or another target address).

**Comment by doingitbigdata** [comment]
@kportertx I'm trying to use RequestInfo() as you suggested but I'm not sure how to create the connection object.

When I run the following,
conn, err := as.NewConnection("localhost:3000", 5000)

I get this error,
dial tcp: i/o timeout

I've tried using 127.0.0.1 or the hostname for the address but get a similar error.

**Pull request merged**
