### PR TITLE
fix: Timestream plugin to work with customer provided endpoint_url

### PR DESCRIPTION
**Pull request by zhihaoli**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

Updating credentials file to not use endpoint_url parameter, and letting timestream client to use endpoint_url

### Context
- AWS Telegraf plugin fails to start, when trying to fetch AssumeRole credentials from STS, with the error
```
2022-03-10T02:03:00Z E! [agent] Failed to connect to [outputs.timestream], retrying in 15s, error was 'operation error - Timestream Write: DescribeDatabase, failed to sign request: failed to retrieve credentials: operation error STS: AssumeRole, https response error StatusCode: 404, RequestID: OAZPKXHJS7QXUVFPAMG2OB6MAU, api error UnknownError: UnknownError'
```
- This happens when we specify `endpoint_url` option in config file
- When the Telegraf plugin is executed inside a VPC setting, a customer may wish to specify Timestream endpoint. See https://aws.amazon.com/blogs/database/use-vpc-endpoints-with-amazon-timestream/
- The above failure is blocking customers to use Telegraf and Timesteam inside a VPC setup

### Issue
- The `endpoint_url` parameter is being incorrectly used when fetching STS credentials, during Timestream client initialization  https://github.com/influxdata/telegraf/blob/master/config/aws/credentials.go
- The supplied `endpoint_url` is for a specific AWS service like Timestream, Cloudwatch, etc.. But in the current code, it is being used to initialize STS to fetch AssumeRole credentials, which causes a 404 error.
- STS supports global and regionalized endpoints. AWS recommends that the IAM policy should control access to resources by region.
- see https://github.com/boto/botocore/issues/2124
- also see https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials
- As per the AWS Go SDK docs, endpoint is NOT specified for STS, when using [AssumeRoleOptions and CredentialCache](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials/stscreds#hdr-Assume_Role)
  - See doc - https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#specifying-credentials

### Changes
- Updated the credentials.go file to NOT use `endpoint_url` parameter
- Modified the [initial endpoint_url changes](https://code.amazon.com/reviews/CR-64783519) to re-use credentials and override endpoints for timestream service
- Added Unit test for timestream
- Updated Readme to specify use of STS global endpoints
- Updated Timestream and Cloudwatch_log to use EndpointResolver for client creation

### Testing
- Telegraf plugin is able to start with these changes
- Verified that Timestream Endpoint has access control via Security Policy for VPC Endpoint
```
2022-03-15T21:48:26Z I! [outputs.timestream] Constructing Timestream client for 'multi-table' mode
2022-03-15T21:48:26Z I! [outputs.timestream] Describing database 'telegraf-dev3' in region 'us-east-1'
2022-03-15T21:50:07Z I! Starting Telegraf 1.22.0-4fcff21c
2022-03-15T21:50:07Z I! Loaded inputs: http_listener
2022-03-15T21:50:07Z I! Loaded aggregators: 
2022-03-15T21:50:07Z I! Loaded processors: 
2022-03-15T21:50:07Z I! Loaded outputs: timestream (2x)
2022-03-15T21:50:07Z I! Tags enabled: availability_zone=$AZ environment=dev1 host=ip-172-31-50-238.us-west-2.compute.internal pod=1 region=us-west-2 regpod=uw2-1 role=telegraf
2022-03-15T21:50:07Z W! Deprecated inputs: 1 and 0 options
2022-03-15T21:50:07Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ip-172-31-50-238.us-west-2.compute.internal", Flush Interval:10s
2022-03-15T21:50:07Z I! [outputs.timestream] Constructing Timestream client for 'multi-table' mode
2022-03-15T21:50:07Z I! [outputs.timestream] Describing database 'telegraf-dev2' in region 'us-east-1'
2022-03-15T21:50:08Z I! [outputs.timestream] Describe database 'telegraf-dev2' returned: '&{%!s(*types.Database=&{0xc0008c2260 0xc0008cc0c0 0xc0008c2270 0xc0008c2280 0xc0008cc0d8 159 {}}) {map[{}:%!s(time.Duration=-1191305013) {}:%!s(*http.Response=&{0xc000ff2630}) {}:EAOPLDQQYFWAHVJKBPONQUX2WA {}:{%!s(uint64=13872318735012271413) %!s(int64=1011682118) %!s(*time.Location=&{ [] []  0 0 <nil>})} {}:{%!s(uint64=0) %!s(int64=63782977807) %!s(*time.Location=<nil>)} {}:{[{<nil> %!s(bool=false) %!s(bool=false) {map[{}:%!s(time.Duration=-1191305013) {}:%!s(*http.Response=&{0xc000ff2630}) {}:EAOPLDQQYFWAHVJKBPONQUX2WA {}:{%!s(uint64=13872318735012271413) %!s(int64=1011682118) %!s(*time.Location=&{ [] []  0 0 <nil>})} {}:{%!s(uint64=0) %!s(int64=63782977807) %!s(*time.Location=<nil>)}]}}]}]} {}}'.
```

Fixes: #10265

### CODE REVIEW

**Comment by zhihaoli** [comment]
anything else required to merge this PR?

**Comment by powersj** [comment]
We had one community member, @nathleeuk, who was interested in this and I was hoping they would report back if it resolved their issues.

**Comment by nathleeuk** [comment]
Hi @zhihaoli - would it be possible to view the configuration file you've used using testing to get this working?

I've updated our test telegraf instance to use Telegraf 1.22.0-33267232 (git: pull/10841 33267232) but i'm unsure if the telegraf.conf file needs to change.

I'm currently using endpoint_url = "https://ingest-cell1.timestream.eu-west-1.amazonaws.com" but i'm still not having much success.

Cheers,

Nath

**Comment by nathleeuk** [comment]
my config file is:
[[outputs.timestream]]
  ## Amazon Region
  region = "eu-west-1"
  ## Amazon Credentials
  access_key = "REVOKED"
  secret_key = "REVOKED"
  endpoint_url = "ingest-cell1.timestream.eu-west-1.amazonaws.com"
  database_name = "Celerity_Test_Timestream"
  describe_database_on_start = false
  mapping_mode = "multi-table"
  create_table_if_not_exists = true
  create_table_magnetic_store_retention_period_in_days = 365
  create_table_memory_store_retention_period_in_hours = 24

and we're still seeing this in the logs:

2022-04-13T08:17:41Z E! [outputs.timestream] Failed to write to Timestream database 'Celerity_Test_Timestream' table 'system'. Skipping metric! Error: 'operation error Timestream Write: WriteRecords, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post "https://ingest.timestream.eu-west-1.amazonaws.com/": dial tcp 54.76.10.207:443: i/o timeout'

**Comment by zhihaoli** [comment]
Hi @nathleeuk 

this is the config we tested with:
[[outputs.timestream]]
  region = "us-west-2"
  database_name = "telegraf-dev2"
  describe_database_on_start = true
  mapping_mode = "multi-table"
  create_table_if_not_exists = true
  create_table_magnetic_store_retention_period_in_days = 3650
  create_table_memory_store_retention_period_in_hours = 8760
  namedrop = ["capsule8*","linkerd*"]
  #replacement_char = "_"
  #max_write_go_routines = 500
  role_arn = "arn:aws:iam::322513308869:role/telegraf-test-ec2-role"
  endpoint_url = "https://ingest-cell1.timestream.us-west-2.amazonaws.com/"

The main difference I see is that the endpoint_url needs to be prefixed with 'https://' which I didn't see on the config you posted. Could you try with that and see if it fixes it?

**Comment by nathleeuk** [comment]
@zhihaoli thanks, Bruce

I'm now getting:

2022-04-19T10:32:03Z E! [agent] Failed to connect to [outputs.timestream], retrying in 15s, error was 'operation error Timestream Write: DescribeDatabase, failed to sign request: failed to retrieve credentials: operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: 2b7982ed-5256-439a-b476-458f26c11215, api error AccessDenied: User: arn:aws:iam::***:user/*** is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::***:user/***

Please could you share your IAM policy for your role arn:aws:iam::322513308869:role/telegraf-test-ec2-role

thanks again

**Comment by shrikanthn** [comment]
The use of `role_arn` is not mandatory. If you don't supply it, the code should fallback to use the default credentials you have set. 

IAM policy for the role used for our testing is as below
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "timestream:WriteRecords",
                "timestream:DescribeTable",
                "timestream:CreateTable"
            ],
            "Resource": "arn:aws:timestream:*:322513308869:database/*/table/*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "timestream:DescribeDatabase",
                "timestream:CreateDatabase"
            ],
            "Resource": "arn:aws:timestream:*:322513308869:database/*"
        }
    ]
}
```
Additionally, you need to provide Trust relationship for the user, on the above role. For eg.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::322513308869:role/AmazonSSMRoleForInstancesQuickSetup"
            },
            "Action": "sts:AssumeRole",
            "Condition": {}
        }
    ]
}
```

**Comment by nathleeuk** [comment]
Thanks, @zhihaoli 

Would it be possible to connect on slack as i'm struggling with this one still, unfortunately!

My creds i'm providing is full unrestricted admin of our aws account, so if I exclude the ARN I would expect this to have the correct perms like you mentioned

When I have a similar config to yours but without the ARN i'm getting:

2022-04-20T09:49:28Z E! [outputs.timestream] Couldn't describe database 'Celerity_Test_Timestream'. Check error, fix permissions, connectivity, create database.
2022-04-20T09:49:28Z E! [agent] Failed to connect to [outputs.timestream], retrying in 15s, error was 'operation error Timestream Write: DescribeDatabase, https response error StatusCode: 404, RequestID: 7a183c55-0952-456a-9b09-f7b48ad612f2, api error UnknownOperationException: UnknownError'

**Comment by nathleeuk** [comment]
Hi @zhihaoli - still struggling on this one

Are you in the InfluxDB community slack?

Cheers

**Comment by shrikanthn** [comment]
@nathleeuk can you point us to the slack channel so that we can connect

**Comment by nathleeuk** [comment]
Hi @shrikanthn could we connect using the influxdb community channel: influxcommunity.slack.com

**Comment by nathleeuk** [comment]
Hi @shrikanthn do you have access to the influxdb community channel?

**Comment by shrikanthn** [comment]
@nathleeuk No I dont have access to the channel. Can you add me to it

**Comment by shrikanthn** [comment]
Tested on the latest commit `d06559a486e5dc939bc373796ea98e5542eb0409 ` from master. It worked with the below setup

### Steps to test

*Please replace <aws_acct_id> with your AWS account-ID in the below steps*

- Created a VPC using [this template](https://aws-database-blog.s3.amazonaws.com/artifacts/DBBLOG-1533/demo_vpc.template.yml). The template is taken [from this blog](https://aws.amazon.com/blogs/database/use-vpc-endpoints-with-amazon-timestream/)
- Open Timestream on AWS console, there should be 2 endpoints created, one for query and one for ingestion
- create a timestream database, for eg DB=`telegraf-dev2`
- Navigate to VPC, on the AWS console, select "Endpoint" on the left menu
- Click the ingestion endpoint link
- navigate to `Policy` tab in the below section of the page and update the IAM policy to
	```
	{
		"Statement": [
			{
				"Principal": "*",
				"Effect": "Allow",
				"Action": [
					"timestream:write*",
					"timestream:describeTable*",
					"timestream:describeDatabase*",
					"timestream:createTable*"
				],
				"Resource": "*"
			}
		]
	}
	```
- Navigate to IAM service on AWS console
  - Create an IAM policy - `telegraf-testing-policy`
    ```
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "timestream:WriteRecords",
                    "timestream:DescribeTable",
                    "timestream:CreateTable"
                ],
                "Resource": "arn:aws:timestream:*:<aws_acct_id>:database/*/table/*"
            },
            {
                "Effect": "Allow",
                "Action": [
                    "timestream:DescribeDatabase",
                    "timestream:CreateDatabase"
                ],
                "Resource": "arn:aws:timestream:*:<aws_acct_id>:database/*"
            }
        ]
    }
    ```
  - Create an IAM user - `telegraf-test-user`
   - Assign the policy - `telegraf-testing-policy` to the user
  - Create an IAM role - `telegraf-testing-role-2`
    - attach permission - policy - `telegraf-testing-policy` to this role
    - under Trust relationship, add
	```
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "AWS": "arn:aws:iam::<aws_acct_id>:user/telegraf-test"
                    },
                    "Action": "sts:AssumeRole"
                }
            ]
        }
	```
- Create an EC2 instance and add it to in one of the `PublicSubnet` that gets created from the VPC template

- SSH onto the above EC2 instance, install `git` , `java`  and [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html)

- using AWS CLI ensure you can perform the operations —
   ```
   aws timestream-write describe-database --endpoint-url="https://ingest-cell1.timestream.us-west-2.amazonaws.com" --database-name telegraf-dev2
   ```
- Make sure to include the `--endpoint-url`  option when calling the AWS api. The endpoint is the one that gets created under VPC for timestream
- Also, when calling AWS APIs, use credentials of the previously created IAM user - `telegraf-test-user`

- Create telegraf configs under
  - `/etc/telegraf/telegraf.conf `
   ```
        [agent]
          interval = "10s"
          round_interval = true
          metric_batch_size = 15000
          metric_buffer_limit = 10000000
          flush_buffer_when_full = true
          collection_jitter = "0s"
          flush_interval = "10s"
          flush_jitter = "0s"
          debug = false
          quiet = false
          hostname = ""
          logfile  = "/tmp/telegraf"
        [global_tags]
          environment = "dev1"
          pod = "1"
          regpod = "uw2-1"
          region = "us-west-2"
          availability_zone = "$AZ"
   ```

  - `/etc/telegraf/telegraf.d/output-influxdb.conf `
```
        [[outputs.influxdb]]
          urls = ["http://44.229.42.112:8086"]
          database = "telegraf-dev2"
          precision = "s"
          timeout = "5s"
          user_agent = "telegraf"
          udp_payload = 512
          namepass = ["capsule8*"]
        [[outputs.influxdb]]
          urls = ["http://44.229.42.112:8086"]
          database = "telegraf-dev2"
          precision = "s"
          timeout = "5s"
          user_agent = "telegraf"
          udp_payload = 512
          namepass = ["linkerd*"]
        [[outputs.timestream]]
          region = "us-west-2"
          database_name = "telegraf-dev2"
          describe_database_on_start = true
          mapping_mode = "multi-table"
          create_table_if_not_exists = true
          create_table_magnetic_store_retention_period_in_days = 3650
          create_table_memory_store_retention_period_in_hours = 8760
          namedrop = ["capsule8*","linkerd*"]
          #replacement_char = "_"
          #max_write_go_routines = 500
          role_arn = "arn:aws:iam::<aws_acct_id>:role/telegraf-testing-role-2"
          endpoint_url = "https://ingest-cell1.timestream.us-west-2.amazonaws.com"
   ```

  - for `/etc/telegraf/telegraf.d/http_listener.conf`
   ```
   [[inputs.http_listener]]
     service_address = ":8094
   ```

- Clone the telegraf repo, make and execute
    ```
   git clone https://github.com/influxdata/telegraf.git

   git checkout -b timestream_endpoint

   git pull origin pull/10841/head

   make

   ./telegraf  -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
   ```

- tail the telegraf login on a different terminal 
   ```
   tail -f /tmp/telegraf
   ```


### expected startup logs
```
2022-06-23T23:48:41Z I! Starting Telegraf 1.24.0-b2f5d0c2
2022-06-23T23:48:41Z I! Loaded inputs: http_listener
2022-06-23T23:48:41Z I! Loaded aggregators: 
2022-06-23T23:48:41Z I! Loaded processors: 
2022-06-23T23:48:41Z I! Loaded outputs: influxdb (3x) timestream
2022-06-23T23:48:41Z I! Tags enabled: availability_zone=$AZ environment=dev1 host=ip-10-0-0-201.us-west-2.compute.internal pod=1 region=us-west-2 regpod=uw2-1
2022-06-23T23:48:41Z W! Deprecated inputs: 1 and 0 options
2022-06-23T23:48:41Z W! Deprecated outputs: 0 and 3 options
2022-06-23T23:48:41Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ip-10-0-0-201.us-west-2.compute.internal", Flush Interval:10s
2022-06-23T23:48:41Z I! [outputs.timestream] Constructing Timestream client for 'multi-table' mode
2022-06-23T23:48:41Z I! [outputs.timestream] Describing database 'telegraf-dev2' in region 'us-west-2'
2022-06-23T23:48:41Z I! [outputs.timestream] Describe database 'telegraf-dev2' returned: '&{%!s(*types.Database=&{0xc027542b10 0xc0275143d8 0xc027542b20 0xc027542b30 0xc0275143c0 146 {}}) {map[{}:%!s(time.Duration=-749463065) {}:%!s(*http.Response=&{0xc000d0c7e0}) {}:WNN4FTQHV5BLI3ZSCQIST2WMIA {}:{%!s(uint64=13881603502455383577) %!s(int64=302087305) %!s(*time.Location=&{ [] []  0 0 <nil>})} {}:{%!s(uint64=0) %!s(int64=63791624921) %!s(*time.Location=<nil>)} {}:{[{<nil> %!s(bool=false) %!s(bool=false) {map[{}:%!s(time.Duration=-749463065) {}:%!s(*http.Response=&{0xc000d0c7e0}) {}:WNN4FTQHV5BLI3ZSCQIST2WMIA {}:{%!s(uint64=13881603502455383577) %!s(int64=302087305) %!s(*time.Location=&{ [] []  0 0 <nil>})} {}:{%!s(uint64=0) %!s(int64=63791624921) %!s(*time.Location=<nil>)}]}}]}]} {}}'.
2022-06-23T23:48:41Z I! [inputs.http_listener] Started HTTP listener service on :8094
```


### sample ingestion logs
```
2022-06-23T23:49:01Z W! [agent] ["outputs.timestream"] did not complete within its flush interval
2022-06-23T23:49:11Z W! [agent] ["outputs.timestream"] did not complete within its flush interval
2022-06-23T23:49:14Z I! [outputs.timestream] ##WriteToTimestream - Metrics size: 5331 request size: 407 time(ms): 22580
2022-06-23T23:49:21Z W! [outputs.timestream] Failed to write to Timestream database 'telegraf-dev2' table 'interface:io_l5d_thriftNameInterpreter:bindingcache'. Error: 'ResourceNotFoundException: The table interface:io_l5d_thriftNameInterpreter:bindingcache does not exist.'
2022-06-23T23:49:21Z I! [outputs.timestream] Trying to create table 'interface:io_l5d_thriftNameInterpreter:bindingcache' in database 'telegraf-dev2', as 'CreateTableIfNotExists' config key is 'true'.
2022-06-23T23:49:21Z E! [outputs.timestream] Failed to create table 'interface:io_l5d_thriftNameInterpreter:bindingcache' in database 'telegraf-dev2': operation error Timestream Write: CreateTable, https response error StatusCode: 400, RequestID: KNCZEO6SCEKNNWER53L5LP7SDQ, ValidationException: . Skipping metric!
2022-06-23T23:49:21Z W! [outputs.timestream] Failed to write to Timestream database 'telegraf-dev2' table 'jvm:mem:current:Compressed_Class_Space'. Error: 'ResourceNotFoundException: The table jvm:mem:current:Compressed_Class_Space does not exist.'
```

**Comment by powersj** [comment]
@[nathleeuk](https://github.com/nathleeuk) were you able to get in touch with @[shrikanthn](https://github.com/shrikanthn)? If not are you able to test the instructions he posted?

**Comment by shrikanthn** [comment]
@powersj Can you merge the PR

**Comment by powersj** [comment]
> @powersj Can you merge the PR

This is on my list for review. Thanks!

**Review by powersj — APPROVED** [review]
Thank you all for working through this and providing a PR!

**Review by MyaLongmire — APPROVED** [review]

**Pull request merged**
