### PR TITLE
fix(secrets): Avoid returning negative number

### PR DESCRIPTION
**Pull request by powersj**
## Summary
This can return a negative value, which will make for a very unhappy unsigned int.

## Checklist

- [x] No AI generated code was used in this PR

### CODE REVIEW

**Comment by srebhan** [comment]
@powersj how can this number become negative?

**Comment by powersj** [comment]
See https://community.influxdata.com/t/secret-stores-os-loading-too-many-secrets/33525/7 for a config that reproduces

**Comment by powersj** [comment]
@srebhan - it is because the user is trying to use secret store on a config value that doesn't even support it. In this case snmp's community config option.

**Comment by srebhan** [comment]
@powersj I think we should simply prevent this number becoming negative in the first place... How about doing some tracing in the secret's `Destroy()` (`config/secret.go` line 161) and `init()`? Can we reproduce the issue?

**Comment by srebhan** [comment]
@powersj I can reproduce the underflow here and will try to find out where we do destroy the secret too often. :-)

**Pull request closed without merging**
