### PR TITLE
Add support for field/tag keys to strings processor

### LINKED ISSUE #5928: Support strings processor operating on tag/field keys
I may simply not be understanding but i am collection win perf counters Avg._Disk_Bytes/Write
I want to replace the / with _ in the resultant field name in influxdb
i have the following config but it is still coming as Avg._Disk_Bytes/Write and not Avg._Disk_Bytes_Write

[[processors.strings.replace]]
    field = ""
	old = "/"
	new = "_"

### PR DESCRIPTION
**Pull request by glinton**
Resolves #5928 

This enables the string processor to work on tag and field keys with the config additions of `tag_key` and `field_key`.

#### Example
**Config**
```toml
[[processors.strings]]
  [[processors.strings.lowercase]]
    tag_key = "URI-Stem"
  [[processors.strings.replace]]
    tag_key = "uri-stem"
    old = "-"
    new = "_"
```

**Input**
```
iis_log,URI-Stem=/API/HealthCheck http_version=1.1 1519652321000000000
```

**Output**
```
iis_log,uri_stem=/API/HealthCheck,URI-Stem=/API/HealthCheck http_version=1.1 1519652321000000000
```

Try it here:
<ul>
  <li><details><summary>linux/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf">telegraf</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.12.0%7Ef6226c6e-0.x86_64.rpm">telegraf-1.12.0~f6226c6e-0.x86_64.rpm</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.12.0%7Ef6226c6e_linux_amd64.tar.gz">telegraf-1.12.0~f6226c6e_linux_amd64.tar.gz</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.12.0%7Ef6226c6e-0_amd64.deb">telegraf_1.12.0~f6226c6e-0_amd64.deb</a></li>
    </li></ul></details>
    <li><details><summary>arm64</summary><ul>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf">telegraf</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.12.0%7Ef6226c6e-0.arm64.rpm">telegraf-1.12.0~f6226c6e-0.arm64.rpm</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.12.0%7Ef6226c6e_linux_arm64.tar.gz">telegraf-1.12.0~f6226c6e_linux_arm64.tar.gz</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf_1.12.0%7Ef6226c6e-0_arm64.deb">telegraf_1.12.0~f6226c6e-0_arm64.deb</a></li>
    </li></ul></details>
    <li><details><summary>armel</summary><ul>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf">telegraf</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf-1.12.0%7Ef6226c6e-0.armel.rpm">telegraf-1.12.0~f6226c6e-0.armel.rpm</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf-1.12.0%7Ef6226c6e_linux_armel.tar.gz">telegraf-1.12.0~f6226c6e_linux_armel.tar.gz</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf_1.12.0%7Ef6226c6e-0_armel.deb">telegraf_1.12.0~f6226c6e-0_armel.deb</a></li>
    </li></ul></details>
    <li><details><summary>armhf</summary><ul>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf">telegraf</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.12.0%7Ef6226c6e-0.armv6hl.rpm">telegraf-1.12.0~f6226c6e-0.armv6hl.rpm</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.12.0%7Ef6226c6e_linux_armhf.tar.gz">telegraf-1.12.0~f6226c6e_linux_armhf.tar.gz</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf_1.12.0%7Ef6226c6e-0_armhf.deb">telegraf_1.12.0~f6226c6e-0_armhf.deb</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf">telegraf</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf-1.12.0%7Ef6226c6e-0.i386.rpm">telegraf-1.12.0~f6226c6e-0.i386.rpm</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf-1.12.0%7Ef6226c6e_linux_i386.tar.gz">telegraf-1.12.0~f6226c6e_linux_i386.tar.gz</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf_1.12.0%7Ef6226c6e-0_i386.deb">telegraf_1.12.0~f6226c6e-0_i386.deb</a></li>
    </li></ul></details>
    <li><details><summary>mipsel</summary><ul>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf">telegraf</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf-1.12.0%7Ef6226c6e_linux_mipsel.tar.gz">telegraf-1.12.0~f6226c6e_linux_mipsel.tar.gz</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf_1.12.0%7Ef6226c6e-0_mipsel.deb">telegraf_1.12.0~f6226c6e-0_mipsel.deb</a></li>
    </li></ul></details>
    <li><details><summary>s390x</summary><ul>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf">telegraf</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf-1.12.0%7Ef6226c6e-0.s390x.rpm">telegraf-1.12.0~f6226c6e-0.s390x.rpm</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf-1.12.0%7Ef6226c6e_linux_s390x.tar.gz">telegraf-1.12.0~f6226c6e_linux_s390x.tar.gz</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf_1.12.0%7Ef6226c6e-0_s390x.deb">telegraf_1.12.0~f6226c6e-0_s390x.deb</a></li>
    </li></ul></details>
    <li><details><summary>static_amd64</summary><ul>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/static_amd64/telegraf">telegraf</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/static_amd64/telegraf-1.12.0%7Ef6226c6e-static_linux_amd64.tar.gz">telegraf-1.12.0~f6226c6e-static_linux_amd64.tar.gz</a></li>
    </li></ul></details>
  </li></ul></details>

  <li><details><summary>windows/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.12.0%7Ef6226c6e_windows_amd64.zip">telegraf-1.12.0~f6226c6e_windows_amd64.zip</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf.exe">telegraf.exe</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/windows/i386/telegraf-1.12.0%7Ef6226c6e_windows_i386.zip">telegraf-1.12.0~f6226c6e_windows_i386.zip</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/windows/i386/telegraf.exe">telegraf.exe</a></li>
    </li></ul></details>
  </li></ul></details>

  <li><details><summary>freebsd/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/freebsd/amd64/telegraf">telegraf</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/freebsd/amd64/telegraf-1.12.0%7Ef6226c6e_freebsd_amd64.tar.gz">telegraf-1.12.0~f6226c6e_freebsd_amd64.tar.gz</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/freebsd/i386/telegraf">telegraf</a></li>
      <li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/freebsd/i386/telegraf-1.12.0%7Ef6226c6e_freebsd_i386.tar.gz">telegraf-1.12.0~f6226c6e_freebsd_i386.tar.gz</a></li>
    </li></ul></details>
  </li></ul></details>

</ul>

### CODE REVIEW

**Comment by danielnelson** [comment]
I guess we should remove the old key after each modification?  I notice that `dest` doesn't really make sense with keys either, which is a little unfortunate.

**Comment by glinton** [comment]
Should we also remove the old key when `dest` is specified on regular `tag/field`? I didn't remove the old key after each modification in order to match the behavior of `dest`, but agree that the old key should be removed.

**Comment by danielnelson** [comment]
The dest operation is weird, perhaps we shouldn't include it in future processors and think about deprecating it.  Maybe a copy processor would make more sense?  Instead of using dest you use the copy processor, then you modify the copy.  I think it will be tough to model this until we add a real language.

Looks like there are a few examples that need updated and then this is good.

**Comment by glinton** [comment]
For tags and fields, if `dest` is specified, we could add a `metric.RemoveTag(key)` to [where we set `dest = c.Dest`](https://github.com/influxdata/telegraf/pull/6129/files#diff-b708d92e96c83b30874f6b0d4c77d687R108) to clean up the old keys, though now it seems it would need to be opt-in behavior.

**Comment by danielnelson** [comment]
I'm more inclined to move in the direction of deprecating the `dest` option, but let's think about it and not do anything more right now.

**Pull request merged**
