### PR TITLE
fix monitoring not working with rethinkdb 2.3.5 

### PR DESCRIPTION
**Pull request by vodolaz095**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by vodolaz095** [comment]
https://github.com/influxdata/telegraf/issues/2958

**Comment by danielnelson** [comment]
Thanks for the PR, looks good overall, but I think this will break compatibility with rethink < 2.3.

Could you change the password/username to have their own config settings and then if authkey is set also do this?  https://github.com/GoRethink/gorethink/blob/master/CHANGELOG.md#changed-10

**Comment by danielnelson** [comment]
Can you change the pull request to go into master?

**Comment by vodolaz095** [comment]
Please, ignore this PR - i made another one to master branch with fixes - #2963

**Pull request closed without merging**
