### PR TITLE
Worktable workfile stats

### PR DESCRIPTION
**Pull request by m82labs**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

This is a small PR to add some new stats to help in troubleshooting tempdb contention from sort/hash spills. I have added two new metrics to the `sqlServerPerformanceCounters` query:
- `Workfiles Created/sec`
- `Worktables Created/sec`

I also noticed some mertrics from the V2 query that seemed to be omitted when the queries were split out and added them back:
- `Distributed Query`
- `DTC calls`
- `Query Store CPU usage`

### CODE REVIEW

**Comment by m82labs** [comment]
I might need a review from @denzilribeiro on this one. I don't think the metrics above were removed on purpose, but I don't honestly know.

**Review by denzilribeiro — APPROVED** [review]
Mark, can you add these to the sqlAzureDBPerformanceCounters  and sqlAzureMIPerformanceCounters  as well?   Did these get dropped along the way?

**Comment by m82labs** [comment]
I'll add them. No the worktables/files stats were never there, but the Query Store CPU and the DTC related metrics were at one point.

**Comment by m82labs** [comment]
All set @denzilribeiro.

**Review by Jagularr — APPROVED** [review]

**Review by denzilribeiro — APPROVED** [review]

**Comment by m82labs** [comment]
I haven't contributed in a while, will this automatically get merged in at some point in the future or do I have to do something else? Thanks!

**Comment by m82labs** [comment]
@denzilribeiro I also noticed all the resource governor metrics were removed when the queries were split out. Do you know if the normal RG DMVs exist on all versions (Azure SQL DB, Managed instances, etc.)?

Specifically in the perf counter query I was inserting some "fake" metrics via a query: 
```SET  @SqlStatement = N'
SELECT
	 ''SQLServer:Workload Group Stats'' AS [object]
	,[counter]
	,[instance]
	,CAST(vs.[value] AS BIGINT) AS [value]
	,1
FROM
(
    SELECT
		 rgwg.name AS instance
		,rgwg.total_request_count AS [Request Count]
		,rgwg.total_queued_request_count AS [Queued Request Count]
		,rgwg.total_cpu_limit_violation_count AS [CPU Limit Violation Count]
		,rgwg.total_cpu_usage_ms AS [CPU Usage (time)]
		,rgwg.total_lock_wait_count AS [Lock Wait Count]
		,rgwg.total_lock_wait_time_ms AS [Lock Wait Time]
		,rgwg.total_reduced_memgrant_count AS [Reduced Memory Grant Count]
		' + @Columns + N'
	FROM sys.[dm_resource_governor_workload_groups] AS rgwg
	INNER JOIN sys.[dm_resource_governor_resource_pools] AS rgrp
		ON rgwg.[pool_id] = rgrp.[pool_id]
) AS rg
UNPIVOT (
    value FOR counter IN ( [Request Count], [Queued Request Count], [CPU Limit Violation Count], [CPU Usage (time)], [Lock Wait Count], [Lock Wait Time], [Reduced Memory Grant Count] ' + @PivotColumns + N')
) AS vs'

INSERT INTO @PCounters
EXEC( @SqlStatement )```

I can add it to this same PR unless there were compatibility issues.

**Comment by denzilribeiro** [comment]
@m82labs  semantics of RG are different on SQL DB (MI is the same as on-prem). 
Why don't you get what you can get from the actual counters rather than simulated? Aka perfmon Workload Group Stats Object ? It can be confusing otherwise right?
https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-workload-group-stats-object?view=sql-server-ver15 
If it is just for backward compat, then no need to add for MI.

**Review by denzilribeiro — CHANGES_REQUESTED** [review]
Can you remove these 2 from the SQL DB portion ( given no DTC support)- sorry I missed that

,'Distributed Query'
,'DTC calls'

**Comment by m82labs** [comment]
> @m82labs semantics of RG are different on SQL DB (MI is the same as on-prem).
> Why don't you get what you can get from the actual counters rather than simulated? Aka perfmon Workload Group Stats Object ? It can be confusing otherwise right?
> https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-workload-group-stats-object?view=sql-server-ver15
> If it is just for backward compat, then no need to add for MI.

You have made me re-evaluate how much I actually need the few extra metrics the DMVs provide, I don't think I need them. :)

**Comment by m82labs** [comment]
Is there anything I need to do to get these changes merged @Jagularr ?

**Review by denzilribeiro — APPROVED** [review]

**Review by sspaink — APPROVED** [review]
lgtm. @m82labs sorry for the slow response, thanks for waiting!

**Pull request merged**
