### PR TITLE
feat: Artifactory Webhook Receiver

### LINKED ISSUE #10376: Webhook listener to listen to webhooks from Jfrog Artifactory
## Feature Request

Webhook listener to listen to webhooks from Jfrog Artifactory.

### Proposal:

Create a webhook listener similar to the Github webhook listener that collects webhooks from Jfrog Artifactory.  I have already created this in a fork, but believe that others may benefit from the feature.

### Current behavior:

Can't receive webhooks from Artifactory.  

### Desired behavior:

Receive webhooks from Artifactory

### Use case: 

Currently we are looking to collect webhooks from our various CI/CD tools.  Since we already make use of the Github webhook listener, it makes sense to include our repository (Jfrog Artifactory) as well.

### PR DESCRIPTION
**Pull request by sammcadams-8451**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10376
https://github.com/influxdata/telegraf/issues/10376

Added a webhook receiver to receive webhooks from Jfrog Artifactory

### CODE REVIEW

**Comment by sspaink** [comment]
@sammcadams-8451 thank you for working on this, I think you will need to rebase to fix the windows CI test job so it uses the latest configuration.

**Comment by sammcadams-8451** [comment]
> @sammcadams-8451 thank you for working on this, I think you will need to rebase to fix the windows CI test job so it uses the latest configuration.

Yea sorry about that.  It should be good now i realized i had to fix a few linter issues as well

**Review by reimda — APPROVED** [review]

**Comment by reimda** [comment]
@sammcadams-8451 would you resolve the conflict and we'll merge this? Thanks!

**Comment by sammcadams-8451** [comment]
> 

Should be good now!

**Review by powersj — APPROVED** [review]
Thank you for the PR!

**Pull request merged**
