### PR TITLE
fix: doc interval setting for internet speed plugin

### PR DESCRIPTION
**Pull request by powersj**
Fixes: #11148

### CODE REVIEW

**Comment by srebhan** [comment]
@powersj isn't that comment only true in combination with `enable_file_download = true` (which is `false` by default)? It might be a bit misleading to users...

**Comment by powersj** [comment]
The `enable_file_download` does not control whether a file gets downloaded or not. It controls a setting in the speed test library as to the workload/weight of the download itself. When enabled, it is a hard-coded setting; without it, the library adjusts based on the latency to the server. Check it out [here](https://github.com/showwin/speedtest-go/blob/master/speedtest/request.go#L58).

The workload setting is the number of go threads to download something.

The weight is used to determine the size of MB to download:

```
var dlSizes = [...]int{350, 500, 750, 1000, 1500, 2000, 2500, 3000, 3500, 4000}
<snip>
reqMB := dlSizes[weight] * dlSizes[weight] * 2 / 1000 / 1000
```

**Comment by srebhan** [comment]
Oh so I always misinterpreted this one. Thanks for clarification!

**Review by srebhan — APPROVED** [review]
Looks good to me.

**Comment by powersj** [comment]
> Oh so I always misinterpreted this one. Thanks for clarification!

you are not alone :) I did the same and wasn't until I looked deeper into the library did it I realize the config value we have is really poorly named :(

**Pull request merged**
