### PR TITLE
feat(inputs.sqlserver): add @@SERVICENAME and SERVERPROPERTY(''IsClustered'') in measurement sqlserver_server_properties 

### PR DESCRIPTION
**Pull request by goswamisandeep**
# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

### CODE REVIEW

**Comment by srebhan** [comment]
@Trovalo do you have any thoughts on the PR?

**Comment by Trovalo** [comment]
I'll have a look at it in the following days

**Review by Trovalo — APPROVED** [review]

**Comment by Trovalo** [comment]
The PR is ok, I'm just curious to know about the use of @@SERVICENAME, what does it add compared to @@SERVERNAME?
@goswamisandeep

_I know the difference between the two, just curious about how that info will be used as they are strictly related_

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for adding this information @goswamisandeep!

**Comment by powersj** [comment]
I am ready to approve once we get some insight into:

> I'm just curious to know about the use of @@SERVICENAME, what does it add compared to @@ServerName

**Comment by goswamisandeep** [comment]
> I am ready to approve once we get some insight into:
> 
> > I'm just curious to know about the use of @@SERVICENAME, what does it add compared to @@ServerName

i think it was to identify if user installed multiple sqlservers on same host.

**Pull request merged**
