### PR TITLE
Added support for Amazon Linux distribution in post remove scripts

### PR DESCRIPTION
**Pull request by schebrolu**
### Required for all PRs:

- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sparrc** [comment]
I'm not sure that you've handed all cases here. What if the script is called in  "upgrade" mode on amazon linux? Why are you not detecting that? (see relevant if-statements for debian and rpm)

**Comment by schebrolu** [comment]
Thanks for review and feedback @sparrc 
Let me check Amazon equivalent for this check and put in so that only triggered in case of post package remove.

**Comment by schebrolu** [comment]
@sparrc - Please review the update and share feedback. Sorry I had to force push as I ran into issue with rebase from upstream.

Instead of going by the Linux distribution based conditional branching this revised script handle remove based on what packaging guidelines these distributions follow.
Looks like you have similar issue with InfluxDB too, if this is acceptable solution you can follow similar approach for InfluxDB as well.

**Comment by sparrc** [comment]
thnaks @schebrolu

**Comment by sparrc** [comment]
@schebrolu can you rebase your changes and re-push. Force pushing is totally fine, by the way.

**Comment by schebrolu** [comment]
Thank you @sparrc 
Rebased and pushed my changes, please review and merge.

**Comment by sparrc** [comment]
thanks @schebrolu

**Comment by schebrolu** [comment]
No merge :(

**Comment by sparrc** [comment]
oops! my mistake

**Pull request merged**
