### PR TITLE
Add hsperfdata Input Plugin

### PR DESCRIPTION
**Pull request by njwhite**
A new version of #2056 (as I can't re-open the PR with my new changes @sparrc?). I've re-written the binary parsing logic (it no longer uses the dependency go-hsperfdata) and so is about 200 lines longer. I've also expanded the test coverage with some interestingly-malformed hsperfdata files and other edge cases.

### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [X] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by njwhite** [comment]
Could I get a review for this PR? Thanks -

**Comment by sparrc** [comment]
@njwhite at the moment we don't have time to fully review all plugin requests we are receiving. This will likely need to become an "external" plugin first (https://github.com/influxdata/telegraf/issues/1717).

I wouldn't expect a full review for a few months.

**Comment by njwhite** [comment]
Thanks for the update @sparrc!

**Comment by njwhite** [comment]
Hi @sparrc - are there any docs on how to make this into an "external" plugin? Or can this PR be merged as an internal plugin? Thanks -

**Comment by danielnelson** [comment]
@njwhite Sorry, will have to wait awhile more before we have time to review for official inclusion.

**Comment by apexlir** [comment]
Shame, I would like to replace collectd/jmxtrans with telegraf and JVM monitoring is the only thing stopping me from migrating.

**Comment by danielnelson** [comment]
@apexlir Take a look at the collectd parser used with socket_listener and the jolokia input for JVM monitoring.

**Comment by nashtsai** [comment]
it's been almost a year for this PR, is anyone reviewing it?

**Comment by coxsim** [comment]
We have an interest in using a non-JMX means for monitoring the JVM from Telegraf (for a JVM where we're avoiding allocation of additional memory).  This looks like a great fit.  Is it likely to be included in a future version of Telegraf, or should it be included via the plugin framework?

**Comment by g10ck** [comment]
Hey guys, still waiting this plugin in master. When you will merge it?

**Comment by glinton** [comment]
Also, @njwhite please update your branch with master to remove the conflicts and refrain from force pushing your branch now that the review has been started, in order to facilitate speedy review updates.
Thanks for this

**Comment by njwhite** [comment]
Thanks for the review @glinton - however I raised this PR 2 1/2 years ago and now no longer need it. Happy for anyone else to take ownership -

**Comment by danielnelson** [comment]
Let's close the pull request for now and if someone is interested in adopting this plugin please create a new issue first.

**Pull request closed without merging**
