### PR TITLE
updated version of telegraf(1.7+) that supports OpenHardwareMonitor!

### PR DESCRIPTION
**Pull request by Suron12**
Please precompile an updated version of telegraf(1.7+) that supports OpenHardwareMonitor! I only run windows, and DEP doesn't have windows installers. I also have never had to use GO before. 
Thanks,

### CODE REVIEW

**Comment by danielnelson** [comment]
Try either the [curl installation](https://github.com/golang/dep#installation) or you can build from source, here is how I do it and this should place dep in your $GOPATH/bin directory:
```
go get -d github.com/golang/dep
cd src/github.com/golang/dep
git checkout -q v0.5.0
go install -ldflags="-X main.version=v0.5.0" ./cmd/dep
```

**Comment by iamsilvio** [comment]
@marianob85 are you able to create a updated pull request? I would love to use your plugin but I have to rely on the influxdata repo

**Comment by aumann** [comment]
Does this have a chance of being merged after the remaining issues are solved?

Compilation with this plugin seems to work without problems for us, even after rebasing locally.

We found this plugin to be really useful, as Windows is slow in adding support for newer sensors like temperature sensors or fan speed sensors. OpenHardwareMonitor has drivers for those sensors and is a great addition to the other plugins for newer hardware.

If we get a pointer as to what needs to be done to get this merged, we could try and solve the remaining issues.

**Comment by sjwang90** [comment]
Due to the level of interest in the plugin, I think it would be better suited as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf. @marianob85 would you be willing to submit your plugin as an external plugin?

**Comment by marianob85** [comment]
> Due to the level of interest in the plugin, I think it would be better suited as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf. @marianob85 would you be willing to submit your plugin as an external plugin?

Hi, I was made this plugin long time ago, but yes, I will try to rewrite it as an external plugin for telegraf.

**Comment by marianob85** [comment]
https://github.com/marianob85/open_hardware_monitor-telegraf-plugin

**Comment by sjwang90** [comment]
Added to list of [external plugins](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md)

**Pull request closed without merging**
