### PR TITLE
Adding support for Default Haproxy Stats Page

### PR DESCRIPTION
**Pull request by pasancario**
Related to https://github.com/influxdata/telegraf/issues/1019

### CODE REVIEW

**Comment by sparrc** [comment]
@pasancario you appear to have broke a unit test with this change and changed the default behavior. Can you explain why this was necessary?

**Comment by sparrc** [comment]
@pasancario I think I understand the problem now.

But how about we just change this to have users specify the full path? guessing and parsing URLs is a recipe for failure.

So rather than parsing, just have the servers list look like this:

```toml
servers = [
  "http://myhaproxy.com:1936/;csv",
  "http://anotherhaproxy.com:1936/haproxy?stats;csv"
]
```

**Comment by pasancario** [comment]
HI @sparrc , 

I just tried with this configuration: 
`
servers = [
 "http://myhaproxy.com:80/haproxy?stats",
"http://myhaproxy.com:80/haproxy?stats;csv"
]
`
But it doesn't work as your are appending ;csv in final petition: 
` fmt.Sprintf("%s://%s%s/;csv", u.Scheme, u.Host, u.Path), nil)`

I was only trying to give support to default haproxy configuration URI.

**Comment by sparrc** [comment]
@pasancario I can merge this if you make the changes to have users specify the full URL

**Comment by pasancario** [comment]
I changed it made user specify full URL, and also change default behaviour (with ;csv too)

**Comment by sparrc** [comment]
you need to run `go fmt ./...` on your code

**Comment by sparrc** [comment]
So what does this change for users exactly? Does the SampleConfig need to change?

Also please update the changelog

**Comment by sparrc** [comment]
@pasancario Thanks for the readme, but I meant the SampleConfig() function, this needs to change to return the correct URLs.

You'll also need to rebase because there was a separate PR for haproxy unix socket support.

**Comment by sparrc** [comment]
closing for lack of updates, @pasancario please feel free to open a new PR with your changes rebased off of master.

**Pull request closed without merging**
