### PR TITLE
Fix haproxy plugin to include missing slim metric

### PR DESCRIPTION
**Pull request by cabillman**
### Required for all PRs:

- [x] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Issue #2132

### CODE REVIEW

**Comment by sparrc** [comment]
looks fine but you need to fix your rebase/merge to not include all of these irrelevant commits. Also, your changelog update should be in 1.2 not 1.1

**Comment by cabillman** [comment]
@sparrc How does that look?

**Comment by krise3k** [comment]
It duplicates https://github.com/influxdata/telegraf/pull/1937

**Comment by sparrc** [comment]
oh, right, woops, this has already been fixed, see https://github.com/influxdata/telegraf/pull/1937

**Pull request closed without merging**
