### PR TITLE
Update paho.mqtt.golang

### LINKED ISSUE #6142: Telegraph writes 1 batch from MQTT to to InfluxDB and then restarts with memory error
### Relevant telegraf.conf:

```toml
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "5s"
  precision = ""
  debug = true
  quiet = false
  hostname = "telegraf"
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"] # required
  database = "telegraf" # default database
  retention_policy = ""
  namedrop = ["iot_*", "demo_*"]

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "iot"
  retention_policy = ""
  namepass = ["iot_*"]

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "demo" 
  retention_policy = ""
  namepass = ["demo_*"]


[[inputs.mqtt_consumer]]
  servers = ["ssl://hub:8883"]
  insecure_skip_verify = true   ## Use TLS but skip chain & host verification
  qos = 1
  topics = [
    "matrix/zenon/influx",
    "matrix/demo/influx"
  ]
  persistent_session = true
  client_id = "telegraf_matrix"
  username = "matrix"
  password = "..."
  data_format = "influx"
```

### System info:
Telegraf 1.10.4 in Docker version 18.06.1-ce, build e68fc7a
Ubuntu 18.04 LTS

### Steps to reproduce:

Start TICK stack, configure Telegraf to read from MQTT and write to Influx and see failures every 2-3 hours. It worked fine when traffic to MQTT was approx. 500 records/second, but then when MQTT traffic became 3000 records/seconds, telegraf started to fail constantly.
 
### Expected behavior:
Should read from MQTT and write to Influx without stops.

### Actual behavior:
Works 2-3 hours, than becomes unstable and constantly restarts. 
```
telegraf_1    | 2019-07-19T10:10:10Z I! Starting Telegraf 1.10.4
telegraf_1    | 2019-07-19T10:10:10Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf_1    | 2019-07-19T10:10:10Z I! Loaded inputs: mem diskio disk mqtt_consumer mqtt_consumer
telegraf_1    | 2019-07-19T10:10:10Z I! Loaded aggregators: 
telegraf_1    | 2019-07-19T10:10:10Z I! Loaded processors: 
telegraf_1    | 2019-07-19T10:10:10Z I! Loaded outputs: influxdb influxdb influxdb
telegraf_1    | 2019-07-19T10:10:10Z I! Tags enabled: host=telegraf
telegraf_1    | 2019-07-19T10:10:10Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
telegraf_1    | 2019-07-19T10:10:10Z D! [agent] Connecting outputs
telegraf_1    | 2019-07-19T10:10:10Z D! [agent] Attempting connection to output: influxdb
telegraf_1    | 2019-07-19T10:10:10Z D! [agent] Successfully connected to output: influxdb
telegraf_1    | 2019-07-19T10:10:10Z D! [agent] Attempting connection to output: influxdb
telegraf_1    | 2019-07-19T10:10:10Z D! [agent] Successfully connected to output: influxdb
telegraf_1    | 2019-07-19T10:10:10Z D! [agent] Attempting connection to output: influxdb
telegraf_1    | 2019-07-19T10:10:10Z D! [agent] Successfully connected to output: influxdb
telegraf_1    | 2019-07-19T10:10:10Z D! [agent] Starting service inputs
telegraf_1    | 2019-07-19T10:10:10Z I! [inputs.mqtt_consumer] Connected [ssl://hub:8883]
telegraf_1    | 2019-07-19T10:10:10Z I! [inputs.mqtt_consumer] Connected [ssl://hub:8883]
telegraf_1    | 2019-07-19T10:10:20Z D! [outputs.influxdb] wrote batch of 1000 metrics in 68.453001ms
telegraf_1    | 2019-07-19T10:10:20Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
telegraf_1    | panic: runtime error: invalid memory address or nil pointer dereference
telegraf_1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1247983]
telegraf_1    | 
telegraf_1    | goroutine 91 [running]:
telegraf_1    | github.com/influxdata/telegraf/vendor/github.com/eclipse/paho%2emqtt%2egolang.outgoing(0xc00040f500)
telegraf_1    |         /go/src/github.com/influxdata/telegraf/vendor/github.com/eclipse/paho.mqtt.golang/net.go:202 +0xb33
telegraf_1    | created by github.com/influxdata/telegraf/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
telegraf_1    |         /go/src/github.com/influxdata/telegraf/vendor/github.com/eclipse/paho.mqtt.golang/client.go:295 +0x6e7
telegraf_1    | 2019-07-19T10:11:20Z I! Starting Telegraf 1.10.4
telegraf_1    | 2019-07-19T10:11:20Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf_1    | 2019-07-19T10:11:20Z I! Loaded inputs: mqtt_consumer mqtt_consumer mem diskio disk
telegraf_1    | 2019-07-19T10:11:20Z I! Loaded aggregators: 
telegraf_1    | 2019-07-19T10:11:20Z I! Loaded processors: 
telegraf_1    | 2019-07-19T10:11:20Z I! Loaded outputs: influxdb influxdb influxdb
telegraf_1    | 2019-07-19T10:11:20Z I! Tags enabled: host=telegraf
telegraf_1    | 2019-07-19T10:11:20Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
telegraf_1    | 2019-07-19T10:11:20Z D! [agent] Connecting outputs
telegraf_1    | 2019-07-19T10:11:20Z D! [agent] Attempting connection to output: influxdb
telegraf_1    | 2019-07-19T10:11:20Z D! [agent] Successfully connected to output: influxdb
telegraf_1    | 2019-07-19T10:11:20Z D! [agent] Attempting connection to output: influxdb
telegraf_1    | 2019-07-19T10:11:20Z D! [agent] Successfully connected to output: influxdb
telegraf_1    | 2019-07-19T10:11:20Z D! [agent] Attempting connection to output: influxdb
telegraf_1    | 2019-07-19T10:11:20Z D! [agent] Successfully connected to output: influxdb
telegraf_1    | 2019-07-19T10:11:20Z D! [agent] Starting service inputs
telegraf_1    | 2019-07-19T10:11:20Z I! [inputs.mqtt_consumer] Connected [ssl://hub:8883]
telegraf_1    | 2019-07-19T10:11:20Z I! [inputs.mqtt_consumer] Connected [ssl://hub:8883]
telegraf_1    | 2019-07-19T10:11:30Z D! [outputs.influxdb] wrote batch of 1000 metrics in 25.164782ms
telegraf_1    | 2019-07-19T10:11:30Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
telegraf_1    | panic: runtime error: invalid memory address or nil pointer dereference
telegraf_1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1247983]
telegraf_1    | 
telegraf_1    | goroutine 70 [running]:
telegraf_1    | github.com/influxdata/telegraf/vendor/github.com/eclipse/paho%2emqtt%2egolang.outgoing(0xc000090700)
telegraf_1    |         /go/src/github.com/influxdata/telegraf/vendor/github.com/eclipse/paho.mqtt.golang/net.go:202 +0xb33
telegraf_1    | created by github.com/influxdata/telegraf/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
telegraf_1    |         /go/src/github.com/influxdata/telegraf/vendor/github.com/eclipse/paho.mqtt.golang/client.go:295 +0x6e7
```

### PR DESCRIPTION
**Pull request by glinton**
Resolves #6142

### CODE REVIEW

**Comment by glinton** [comment]
@dogada can you please test this with a nightly in the morning or one of the following builds:
<ul>
  <li><details><summary>freebsd/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/freebsd/amd64/telegraf">telegraf</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/freebsd/amd64/telegraf-1.12.0%7E38898341_freebsd_amd64.tar.gz">telegraf-1.12.0~38898341_freebsd_amd64.tar.gz</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/freebsd/i386/telegraf">telegraf</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/freebsd/i386/telegraf-1.12.0%7E38898341_freebsd_i386.tar.gz">telegraf-1.12.0~38898341_freebsd_i386.tar.gz</a></li>
    </li></ul></details>
  </li></ul></details>

  <li><details><summary>linux/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf">telegraf</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.12.0%7E38898341-0.x86_64.rpm">telegraf-1.12.0~38898341-0.x86_64.rpm</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.12.0%7E38898341_linux_amd64.tar.gz">telegraf-1.12.0~38898341_linux_amd64.tar.gz</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.12.0%7E38898341-0_amd64.deb">telegraf_1.12.0~38898341-0_amd64.deb</a></li>
    </li></ul></details>
    <li><details><summary>arm64</summary><ul>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf">telegraf</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.12.0%7E38898341-0.arm64.rpm">telegraf-1.12.0~38898341-0.arm64.rpm</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.12.0%7E38898341_linux_arm64.tar.gz">telegraf-1.12.0~38898341_linux_arm64.tar.gz</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf_1.12.0%7E38898341-0_arm64.deb">telegraf_1.12.0~38898341-0_arm64.deb</a></li>
    </li></ul></details>
    <li><details><summary>armel</summary><ul>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf">telegraf</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf-1.12.0%7E38898341-0.armel.rpm">telegraf-1.12.0~38898341-0.armel.rpm</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf-1.12.0%7E38898341_linux_armel.tar.gz">telegraf-1.12.0~38898341_linux_armel.tar.gz</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf_1.12.0%7E38898341-0_armel.deb">telegraf_1.12.0~38898341-0_armel.deb</a></li>
    </li></ul></details>
    <li><details><summary>armhf</summary><ul>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf">telegraf</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.12.0%7E38898341-0.armv6hl.rpm">telegraf-1.12.0~38898341-0.armv6hl.rpm</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.12.0%7E38898341_linux_armhf.tar.gz">telegraf-1.12.0~38898341_linux_armhf.tar.gz</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf_1.12.0%7E38898341-0_armhf.deb">telegraf_1.12.0~38898341-0_armhf.deb</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf">telegraf</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf-1.12.0%7E38898341-0.i386.rpm">telegraf-1.12.0~38898341-0.i386.rpm</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf-1.12.0%7E38898341_linux_i386.tar.gz">telegraf-1.12.0~38898341_linux_i386.tar.gz</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf_1.12.0%7E38898341-0_i386.deb">telegraf_1.12.0~38898341-0_i386.deb</a></li>
    </li></ul></details>
    <li><details><summary>mipsel</summary><ul>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf">telegraf</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf-1.12.0%7E38898341_linux_mipsel.tar.gz">telegraf-1.12.0~38898341_linux_mipsel.tar.gz</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/mipsel/telegraf_1.12.0%7E38898341-0_mipsel.deb">telegraf_1.12.0~38898341-0_mipsel.deb</a></li>
    </li></ul></details>
    <li><details><summary>s390x</summary><ul>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf">telegraf</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf-1.12.0%7E38898341-0.s390x.rpm">telegraf-1.12.0~38898341-0.s390x.rpm</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf-1.12.0%7E38898341_linux_s390x.tar.gz">telegraf-1.12.0~38898341_linux_s390x.tar.gz</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf_1.12.0%7E38898341-0_s390x.deb">telegraf_1.12.0~38898341-0_s390x.deb</a></li>
    </li></ul></details>
    <li><details><summary>static_amd64</summary><ul>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/static_amd64/telegraf">telegraf</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/linux/static_amd64/telegraf-1.12.0%7E38898341-static_linux_amd64.tar.gz">telegraf-1.12.0~38898341-static_linux_amd64.tar.gz</a></li>
    </li></ul></details>
  </li></ul></details>

  <li><details><summary>windows/</summary><ul>
    <li><details><summary>amd64</summary><ul>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.12.0%7E38898341_windows_amd64.zip">telegraf-1.12.0~38898341_windows_amd64.zip</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf.exe">telegraf.exe</a></li>
    </li></ul></details>
    <li><details><summary>i386</summary><ul>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/windows/i386/telegraf-1.12.0%7E38898341_windows_i386.zip">telegraf-1.12.0~38898341_windows_i386.zip</a></li>
      <li><a href="https://37049-33258973-gh.circle-artifacts.com/0/build/windows/i386/telegraf.exe">telegraf.exe</a></li>
    </li></ul></details>
  </li></ul></details>

</ul>

**Comment by dogada** [comment]
@glinton thanks for quick fix, do you have Docker image with night builds?

**Comment by glinton** [comment]
I don't believe we do have nightly docker images, but this should be in the [official nightly builds](https://github.com/influxdata/telegraf#nightly-builds) now.

It should be trivial to drop the new telegraf binary into a new docker image based on the official telegraf docker image.

**Comment by dogada** [comment]
We tested nightly builds in our environment and we don't see stack trace mentioned in #6142 but the problem still persists but with complete silence in logs now. Once per 3-4 days Telegraf just stops to receive data from MQTT broker (we use Mosqitto) and we don't see any diagnostic messages in the logs.

**Comment by danielnelson** [comment]
It's possible you are now running into #6232, which was an issue with persistent sessions.  We just released 1.12.0 which contains fixes for both issues, can you retry your testing with this?

**Pull request merged**
