### PR TITLE
chore(aggregators): Comment out default values in sample configs

### PR DESCRIPTION
**Pull request by Hipska**
## Summary

- Aligns all aggregator sample configs so they have commented out defaults for the common parameters.
- ~Adds a test to validate the sample config~

## Checklist

- [x] No AI generated code was used in this PR

### CODE REVIEW

**Comment by Hipska** [comment]
!retry-failed

**Comment by srebhan** [comment]
@Hipska please do not add the tests here. I would suggest to add a test to `config/config_test.go` iterating over all known plugins and do this. Maybe one test per plugin category would be the best. This way we do have the test in one place and do not need to stray the code across all plugins...

**Comment by Hipska** [comment]
We discussed this before when I introduced the `DefaultSampleConfig` testutil. I wanted to do something like that, but you were opposed to that since some plugins have special handling of the sample data and thus cannot be tested like you just requested..

**Comment by srebhan** [comment]
I said we should be careful with the test and add a whitelist for plugins we know are different.

**Comment by Hipska** [comment]
So, next actions: Remove the tests?

**Comment by srebhan** [comment]
Yes.

**Review by srebhan — APPROVED** [review]
Thanks a lot @Hipska!

**Review by DStrand1 — APPROVED** [review]

**Pull request merged**
