### PR TITLE
Fix nil pointer error in knx_listener

### PR DESCRIPTION
**Pull request by pheew**
### Required for all PRs:

- [ ] Updated associated README.md. 
  _(Don't think this is necessary but happy to make any changes if required)_
- [x] Wrote appropriate unit tests.

The KNX input plugin crashes with a nil pointer dereference error when receiving subsequent messages for an ignored group address:

```
2021-06-28T18:19:19Z I! [inputs.KNXListener] Ignoring message {Command:Write Source:1.1.5 Destination:1/0/0 Data:[0]} for unknown GA "1/0/0",
panic: runtime error: invalid memory address or nil pointer dereference,
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x19680b8],
goroutine 11 [running]:,
github.com/influxdata/telegraf/plugins/inputs/knx_listener.(*KNXListener).listen(0xc00050a630),
	/go/src/github.com/influxdata/telegraf/plugins/inputs/knx_listener/knx_listener.go:158 +0x418,
github.com/influxdata/telegraf/plugins/inputs/knx_listener.(*KNXListener).Start.func1(0xc00050a630),
	/go/src/github.com/influxdata/telegraf/plugins/inputs/knx_listener/knx_listener.go:133 +0x48,
created by github.com/influxdata/telegraf/plugins/inputs/knx_listener.(*KNXListener).Start,
	/go/src/github.com/influxdata/telegraf/plugins/inputs/knx_listener/knx_listener.go:131 +0x497,
```

I narrowed it down to a faulty boolean check which makes it still try to process an ignored KNX message. The included unit test fails without the changes made.

### CODE REVIEW

**Comment by pheew** [comment]
!signed-cla

**Review by srebhan — APPROVED** [review]
Looks good. Thanks for tracking this down!

**Review by srebhan — COMMENTED** [review]
Please fix the linter issue with the empty line at beginning of `TestRegularReceives_MultipleMessages()`.

**Review by srebhan — APPROVED** [review]
LGTM.

**Review by MyaLongmire — APPROVED** [review]

**Pull request merged**
