### PR TITLE
Vespa input plugin

### PR DESCRIPTION
**Pull request by olaaun**
This is an input plugin for Vespa, the open big data serving engine. See [vespa.ai](https://vespa.ai/) for more information. 

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Thanks for the pull request, we will check it out as soon as we can but we have quite the backlog right now so it may take some time.

**Comment by sjwang90** [comment]
Hey @olaaun! Would you be willing to submit this plugin as an external plugin that can be used with execd to run seamlessly with Telegraf? Telegraf users would be able to use the plugin sooner by having it as an external plugin since it wouldn't have to go through the typical review process.

Here is some information on external plugins and using them with execd. Feel free to respond with any questions you may have.

**Comment by olaaun** [comment]
Hi, @sjwang90! I'll take a look at the doc, and get back to you. Thanks!

**Comment by sjwang90** [comment]
@olaaun Is this still something you'd be interested in working on?

**Pull request closed without merging**
