### PR TITLE
feat: extend kube_inventory plugin to include resourcequota measurement and extend node and pod measurement

### PR DESCRIPTION
**Pull request by varunjain0606**
**Checks:**
- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format]

**Requirements:**
Requirements have been included in the link below
https://github.com/influxdata/telegraf/issues/9621

**Resolves**
Included some more metrics in kubernetes_node, kubernetes_pod_container measurement in kube_inventory plugin as that would enhance the monitoring of k8s. Also add a resource type "resourcequotas" for even better monitoring of quota management.

**Description:** 
Added these new metrics in kubernetes_node measurement within kube_inventory plugin.
1. count
2. status_condition
3. spec_schedulable

Added tags:
1. status
2. condition

Added these new metrics in kubernetes_pod_container measurement within kube_inventory plugin.
1. status_condition

Added tags:
1. status
2. condition

Added new kubernetes_resourcequota measurement and added these metrics
1. hard_cpu_cores_limit
2. hard_memory_bytes_limit
3. hard_pods_limit
4. used_cpu_cores
5. used_memory_bytes
6. used_pods

Added tags:
1. resource
2. namespace

**Example:** 
Output - 
kubernetes_node,host=vjain count=8i 1628918652000000000
kubernetes_node,condition=Ready,host=vjain,node_name=ip-172-17-0-2.internal,status=True status_condition=1i 1629177980000000000
kubernetes_node,cluster_namespace=tools,condition=Ready,host=vjain,node_name=ip-172-17-0-2.internal,status=True allocatable_cpu_cores=4i,allocatable_memory_bytes=7186567168i,allocatable_millicpu_cores=4000i,allocatable_pods=110i,capacity_cpu_cores=4i,capacity_memory_bytes=7291424768i,capacity_millicpu_cores=4000i,capacity_pods=110i,spec_unschedulable=0i,status_condition=1i 1628918652000000000
kubernetes_pod_container,condition=Ready,host=vjain,pod_name=uefi-5997f76f69-xzljt,status=True status_condition=1i 1629177981000000000
kubernetes_resourcequota,host=vjain,namespace=default,resource=pods-medium hard_cpu_cores=10i,hard_memory_bytes=21474836480i,hard_pods=10i,used_cpu_cores=0i,used_memory_bytes=0i,used_pods=0i 1629110393000000000

### CODE REVIEW

**Comment by sspaink** [comment]
@varunjain0606 thank you for contributing this pull request, it looks like there are some issues with the tests. Do you have time to continue working on this?

**Comment by varunjain0606** [comment]
@sspaink  I have fixed the test cases. This PR has a couple of changes that can be split into 2 or 3 PRs. Please let me know if you want me to split them. I have requirement for all of these changes along with some other changes that I can submit in the follow up PRs. These changes can be really helpful to monitor k8s infrastructure for everyone. Thanks

**Comment by sspaink** [comment]
@varunjain0606 it looks like there are two files `processor` and `test` that might have been added by mistake to this pull request, they seem like they are binaries? I think the changes you've made should be ok within just this pull request.

**Comment by varunjain0606** [comment]
> @varunjain0606 it looks like there are two files `processor` and `test` that might have been added by mistake to this pull request, they seem like they are binaries? I think the changes you've made should be ok within just this pull request.

Sorry for the unnecessary files in the PR. I have removed them now. Please have a look at the PR again @sspaink

**Comment by bougou** [comment]
#10147 just adds several new fields regarding of node condition status, no tags are added.

**Comment by bougou** [comment]
Kuberenetes node currently exposed several node conditions:

- Ready
- DiskPressure
- MemoryPressure
- NetworkUnavailable
- PIDPressure

The condition status value might be string value `False`, `True`,  or `Unkown`.

The #10147 PR just adds those conditions as new fields on `kubernetes_node` measurement with value converted to integer (0, 1, 2), with no tags are introduced.

```
kubernetes_node,tagname="foobar" condition_ready=0i condition_disk_pressure=1i condition_network_unavailable=1i condition_pid_pressure=1i condition_memory_pressure=1i 1547597616000000000
```

It seems that this PR (#9627) treats this part in way that:

Add a `status_condition` **field** with converted integer value, and adds the condition name in **tag** `condition`.

**Comment by powersj** [comment]
Hi @varunjain0606,

Sorry that no one ever got back to you on this PR. Are you still interested in seeing it land? If so, could I have you rebase on master and ensure tests pass?

Thanks!

**Comment by varunjain0606** [comment]
@powersj Can you please take a look at this updated PR. I have re-based and verified all tests are passing
https://github.com/influxdata/telegraf/pull/13040

**Pull request closed without merging**
