### PR TITLE
docs: override reported OpenSearch version

### PR DESCRIPTION
**Pull request by powersj**
Fixes: #9414

### CODE REVIEW

**Review by srebhan — COMMENTED** [review]
Looks good to me. Thanks @powersj!

**Comment by reimda** [comment]
Adding an override seems risky in that someone could put in the override version and forget it and then upgrade, or put in the wrong override version. Then things wouldn't work as intended. I would prefer the approach of detecting whether telegraf is connecting to opensearch or elasticsearch at runtime, then checking the version requirements based on that.

This relies on the ability to detect whether telegraf has connected to one or the other, which I'm not sure how to do.

**Comment by powersj** [comment]
How about we scrap the change and add a comment in the README about enabling compatibility mode in AWS OpenSearch service? Similar to [this comment](https://github.com/influxdata/telegraf/issues/9414).

To make matters worse, [AWS docs](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/rename.html#rename-upgrade) explain that they support a 6.x and a 7.x version and outline how you can make your cluster report the actual ES version used to support existing open source software that checks versions. Trying to determine what version of OpenSearch uses 6.x and 7.x is not clearly documented and only makes trying to add additional version checks even harder.

**Comment by powersj** [comment]
After talking to the team we agreed we prefer documenting how OpenSearch clusters can enable compatibility mode. This is AWS' provided solution for interfacing with existing ElasticSearch clients that need to know which version they are talking to.

**Review by MyaLongmire — APPROVED** [review]

**Review by Hipska — APPROVED** [review]

**Review by srebhan — APPROVED** [review]
Even better!

**Pull request merged**
