### PR TITLE
feat(inputs.gnmi): Add option to create more descriptive tags

### PR DESCRIPTION
**Pull request by srebhan**
## Summary

While investigating an [issue report](https://github.com/influxdata/telegraf/issues/12831#issuecomment-2089176830) I noticed that paths with multiple keys like
```
/openconfig-platform:components/component[name="LM-1"]/subcomponents/subcomponent[name="PORT-1-1"]/name
```
produce very bulky and undescriptive tags like `/openconfig-platform:components/component/subcomponents/subcomponent/name=PORT-1-1,name=LM-1` because key-keys are usually named `name`.

The new `prefix_tag_key_with_path` would produce more descriptive tags `component_name=LM-1,subcomponent_name=PORT-1-1` by prefixing the key with the path segment containing the key.

## Checklist

- [x] No AI generated code was used in this PR

### CODE REVIEW

**Review by powersj — APPROVED** [review]
Thanks! Out of curiosity, do we need the full 28k line JSON file or could a more limited version be used?

**Comment by srebhan** [comment]
Not necessarily. Should I shorten it?

**Comment by powersj** [comment]
> Not necessarily. Should I shorten it?

If it isn't straight forward, then we can keep as-is.

**Comment by srebhan** [comment]
@powersj shortened to ~1k lines...

**Comment by powersj** [comment]
Fantastic, thank you very much!

**Review by DStrand1 — APPROVED** [review]

**Pull request merged**
