### PR TITLE
nvidia-smi readme update - Support for Windows Powershell

### PR DESCRIPTION
**Pull request by gsxryan**
Added to readme for users that would like to use this plugin on windows / powershell

### Required for all PRs:

- [x ] Signed [CLA](https://influxdata.com/community/cla/).
- [x ] Associated README.md updated.
- [na ] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Thanks but I'm don't think this is required, it isn't different in Windows vs on other platforms.

**Comment by gsxryan** [comment]
It isn't required, but it sure would have helped me in my search, if it was there.  Windows does not have a bin path.  And telegraf directory formatting isn't using a standard that windows script users are used to.   (Requires quotes where the Linux path didn't, and used forwardslash instead of backslash)

**Comment by danielnelson** [comment]
The lack of quoting appears to actually be a bug in the example config, I'll fix that up real quick.

You can actually use backslashes here, the easiest way is to use single quotes:
```
bin_path = 'C:\Program Files\NVIDIA Corporation/NVSMI\nvidia-smi.exe'
```

**Comment by gsxryan** [comment]
Aha!  Nice.  Thanks for the fix!

**Pull request closed without merging**
