### PR TITLE
NATS output plugin

### LINKED ISSUE #1487: Feature Request : NATS output plugin
## Feature Request

Create a NATS (streaming ?) output plugin

### Desired behavior:
Being able to send metrics to a NATS Queue server, possibly using the streaming protocol
https://github.com/nats-io/nats-streaming-server/blob/master/README.md
http://site-nats-streaming-staging.zeppole.buffalo.im/

### Use case: 
When you have a large number of servers, you may want to use a broker in between the gathering client (telegraf) and the influx server.
NATS is a new queue system and is written in GO.
There already is an input plugin.

### PR DESCRIPTION
**Pull request by pires**
### Required for all PRs:

- [x] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

Fixes #1487

### CODE REVIEW

**Comment by sparrc** [comment]
looks good @pires, can you change the SSL handling to use the [internal.GetTLSConfig](https://github.com/influxdata/telegraf/blob/master/internal/internal.go#L108) function? You can see how the influxdb output plugin does it here: https://github.com/influxdata/telegraf/blob/master/plugins/outputs/influxdb/influxdb.go#L91

**Comment by pires** [comment]
@sparrc sure thing. On it!

**Comment by sparrc** [comment]
also you can update the changelog with this under the 1.1 section 👍

**Comment by pires** [comment]
@sparrc yep, was just waiting on your approval.

**Comment by pires** [comment]
@sparrc done, sir!

**Comment by m4ce** [comment]
Looks like if the NATS server happens to be unreachable and comes back at some point, telegraf never recovers:

```
2016/10/26 10:35:10 I! Output [nats] buffer fullness: 10045 / 10000 metrics. Total gathered metrics: 650575. Total dropped metrics: 9125.
2016/10/26 10:35:10 E! Error writing to output [nats]: FAILED to send NATS message: nats: connection closed
```

**Comment by sparrc** [comment]
@m4ce please open a proper issue, commenting on a closed PR is not productive

**Comment by pires** [comment]
@m4ce that shouldn't be the case since [by default NATS client will try to reconnect](https://github.com/nats-io/nats/blob/master/nats.go#L79).

If you happen to open an issue as correctly suggested by @sparrc, make sure you CC me.

**Comment by m4ce** [comment]
Sorry for writing this here. Thank you guys for looking into this.

**Pull request closed without merging**
