### PR TITLE
Update interrupts plugin to be consistent with cpu_usage (et al)

### PR DESCRIPTION
**Pull request by jdoupe**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Can you further explain the reasoning behind this change, I know we considered making cpu a tag but couldn't think of any queries that needed it.  Unless we have a very strong reason we shouldn't make this change since it will break queries.

**Comment by jdoupe** [comment]
It was mostly a consistency thing.  cpu.usage_* have cpu as a tag.  As a prometheus user, it seems odd to have CPUx be part of the series name.  

I can understand not wanting to change it at this point, but the consistency might be enough for people to understand the change and be willing to have it break any existing queries/dashboards.

A compromise might be to leave the "total" field in place, as that is likely the most widely used, while still removing the "CPUx" fields into tags.  (But that does go against my consistency argument to some extent.)

**Comment by danielnelson** [comment]
Thanks for the explanation.  I will try to keep the prometheus metric mangling in mind with future metric design, but I think we should stick with the current schema for now in this case.

**Comment by phemmer** [comment]
Just throwing out another way to think of this: The cpu measurement measures cpu usage, thus the cpu is a tag, and the different ways of how it is used are fields (idle, iowait, steal, etc). The interrupts measurement measures interrupt usage, thus the interrupt is a tag, and the different cpus that interrupt is used on are fields.

**Comment by jdoupe** [comment]
I don't disagree, however, since the number of CPU's in a system can fluctuate, I don't think it makes sense for them to be a part of the measurement/field.  If you create a query for interrupts by CPU, you have to know how many CPU's are in the system first?

**Pull request closed without merging**
