### PR TITLE
Fix udp metric splitting

### PR DESCRIPTION
**Pull request by danielnelson**
Another attempt at fixing #2862

This fixes several length checks and a state transition in metric reader and removes previous change to split in influxdb.go.  The reader bugs could cause the reader to enter the overflow and splitOverflow states unnecessarily.  These states will split metrics at positions that are illegal for udp.

In the influxdb udp client, I take advantage of the fact that the reader returns points one at a time to verify a full line was read and only send if this is true.  Only points that are longer than the udp payload size should be a problem.  They are logged and discarded.

A better fix would maybe be building this into the Reader, so that it is packet aware, or perhaps the Reader interface is just the wrong fit here.  Relying on the reader to return points one at a time is not a very robust solution.

cc @sebito91

### Required for all PRs:

- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by sebito91** [comment]
Sure, we can do that. If anything, let's add a crazy long testcase to the UDP endpoint no?

**Comment by sebito91** [comment]
Here's one for the tests...

```
[root@hostname ~]# telegraf --test --config /etc/telegraf/telegraf.conf --input-filter nstat
* Plugin: inputs.nstat, Collection 1
> nstat,bu=linux,cls=server,dc=cer,env=production,host=hostname,name=netstat,sr=database IpExtInBcastOctets=12570626154i,IpExtInBcastPkts=95541226i,IpExtInCEPkts=0i,IpExtInCsumErrors=0i,IpExtInECT0Pkts=55674i,IpExtInECT1Pkts=0i,IpExtInMcastOctets=5928296i,IpExtInMcastPkts=174365i,IpExtInNoECTPkts=17965863529i,IpExtInNoRoutes=20i,IpExtInOctets=3334866321815i,IpExtInTruncatedPkts=0i,IpExtOutBcastOctets=0i,IpExtOutBcastPkts=0i,IpExtOutMcastOctets=0i,IpExtOutMcastPkts=0i,IpExtOutOctets=31397892391399i,TcpExtArpFilter=0i,TcpExtBusyPollRxPackets=0i,TcpExtDelayedACKLocked=14094i,TcpExtDelayedACKLost=302083i,TcpExtDelayedACKs=55486507i,TcpExtEmbryonicRsts=11879i,TcpExtIPReversePathFilter=0i,TcpExtListenDrops=1736i,TcpExtListenOverflows=0i,TcpExtLockDroppedIcmps=0i,TcpExtOfoPruned=0i,TcpExtOutOfWindowIcmps=8i,TcpExtPAWSActive=0i,TcpExtPAWSEstab=974i,TcpExtPAWSPassive=0i,TcpExtPruneCalled=0i,TcpExtRcvPruned=0i,TcpExtSyncookiesFailed=12593i,TcpExtSyncookiesRecv=0i,TcpExtSyncookiesSent=0i,TcpExtTCPACKSkippedChallenge=0i,TcpExtTCPACKSkippedFinWait2=0i,TcpExtTCPACKSkippedPAWS=806i,TcpExtTCPACKSkippedSeq=519i,TcpExtTCPACKSkippedSynRecv=0i,TcpExtTCPACKSkippedTimeWait=0i,TcpExtTCPAbortFailed=0i,TcpExtTCPAbortOnClose=22i,TcpExtTCPAbortOnData=36593i,TcpExtTCPAbortOnLinger=0i,TcpExtTCPAbortOnMemory=0i,TcpExtTCPAbortOnTimeout=674i,TcpExtTCPAutoCorking=494253233i,TcpExtTCPBacklogDrop=0i,TcpExtTCPChallengeACK=281i,TcpExtTCPDSACKIgnoredNoUndo=93354i,TcpExtTCPDSACKIgnoredOld=336i,TcpExtTCPDSACKOfoRecv=0i,TcpExtTCPDSACKOfoSent=7i,TcpExtTCPDSACKOldSent=302073i,TcpExtTCPDSACKRecv=215884i,TcpExtTCPDSACKUndo=7633i,TcpExtTCPDeferAcceptDrop=0i,TcpExtTCPDirectCopyFromBacklog=0i,TcpExtTCPDirectCopyFromPrequeue=0i,TcpExtTCPFACKReorder=1320i,TcpExtTCPFastOpenActive=0i,TcpExtTCPFastOpenActiveFail=0i,TcpExtTCPFastOpenCookieReqd=0i,TcpExtTCPFastOpenListenOverflow=0i,TcpExtTCPFastOpenPassive=0i,TcpExtTCPFastOpenPassiveFail=0i,TcpExtTCPFastRetrans=350681i,TcpExtTCPForwardRetrans=142168i,TcpExtTCPFromZeroWindowAdv=4317i,TcpExtTCPFullUndo=29502i,TcpExtTCPHPAcks=10267073000i,TcpExtTCPHPHits=5629837098i,TcpExtTCPHPHitsToUser=0i,TcpExtTCPHystartDelayCwnd=285127i,TcpExtTCPHystartDelayDetect=12318i,TcpExtTCPHystartTrainCwnd=69160570i,TcpExtTCPHystartTrainDetect=3315799i,TcpExtTCPLossFailures=109i,TcpExtTCPLossProbeRecovery=110819i,TcpExtTCPLossProbes=233995i,TcpExtTCPLossUndo=5276i,TcpExtTCPLostRetransmit=397i,TcpExtTCPMD5NotFound=0i,TcpExtTCPMD5Unexpected=0i,TcpExtTCPMemoryPressures=0i,TcpExtTCPMinTTLDrop=0i,TcpExtTCPOFODrop=0i,TcpExtTCPOFOMerge=7i,TcpExtTCPOFOQueue=15196i,TcpExtTCPOrigDataSent=29055119435i,TcpExtTCPPartialUndo=21320i,TcpExtTCPPrequeueDropped=0i,TcpExtTCPPrequeued=0i,TcpExtTCPPureAcks=1236441827i,TcpExtTCPRcvCoalesce=225590473i,TcpExtTCPRcvCollapsed=0i,TcpExtTCPRenoFailures=0i,TcpExtTCPRenoRecovery=0i,TcpExtTCPRenoRecoveryFail=0i,TcpExtTCPRenoReorder=0i,TcpExtTCPReqQFullDoCookies=0i,TcpExtTCPReqQFullDrop=0i,TcpExtTCPRetransFail=41i,TcpExtTCPSACKDiscard=0i,TcpExtTCPSACKReneging=0i,TcpExtTCPSACKReorder=4307i,TcpExtTCPSYNChallenge=244i,TcpExtTCPSackFailures=1698i,TcpExtTCPSackMerged=184668i,TcpExtTCPSackRecovery=97369i,TcpExtTCPSackRecoveryFail=381i,TcpExtTCPSackShiftFallback=2697079i,TcpExtTCPSackShifted=760299i,TcpExtTCPSchedulerFailed=0i,TcpExtTCPSlowStartRetrans=9276i,TcpExtTCPSpuriousRTOs=959i,TcpExtTCPSpuriousRtxHostQueues=2973i,TcpExtTCPSynRetrans=200970i,TcpExtTCPTSReorder=15221i,TcpExtTCPTimeWaitOverflow=0i,TcpExtTCPTimeouts=70127i,TcpExtTCPToZeroWindowAdv=4317i,TcpExtTCPWantZeroWindowAdv=2133i,TcpExtTW=24809813i,TcpExtTWKilled=0i,TcpExtTWRecycled=0i 1496460785000000000
> nstat,bu=linux,cls=server,dc=cer,env=production,host=hostname,name=snmp,sr=database IcmpInAddrMaskReps=0i,IcmpInAddrMasks=90i,IcmpInCsumErrors=0i,IcmpInDestUnreachs=284401i,IcmpInEchoReps=9i,IcmpInEchos=1761912i,IcmpInErrors=407i,IcmpInMsgs=2047767i,IcmpInParmProbs=0i,IcmpInRedirects=0i,IcmpInSrcQuenchs=0i,IcmpInTimeExcds=46i,IcmpInTimestampReps=0i,IcmpInTimestamps=1309i,IcmpMsgInType0=9i,IcmpMsgInType11=46i,IcmpMsgInType13=1309i,IcmpMsgInType17=90i,IcmpMsgInType3=284401i,IcmpMsgInType8=1761912i,IcmpMsgOutType0=1761912i,IcmpMsgOutType14=1248i,IcmpMsgOutType3=108709i,IcmpMsgOutType8=9i,IcmpOutAddrMaskReps=0i,IcmpOutAddrMasks=0i,IcmpOutDestUnreachs=108709i,IcmpOutEchoReps=1761912i,IcmpOutEchos=9i,IcmpOutErrors=0i,IcmpOutMsgs=1871878i,IcmpOutParmProbs=0i,IcmpOutRedirects=0i,IcmpOutSrcQuenchs=0i,IcmpOutTimeExcds=0i,IcmpOutTimestampReps=1248i,IcmpOutTimestamps=0i,IpDefaultTTL=64i,IpForwDatagrams=0i,IpForwarding=2i,IpFragCreates=0i,IpFragFails=0i,IpFragOKs=0i,IpInAddrErrors=0i,IpInDelivers=17658795773i,IpInDiscards=0i,IpInHdrErrors=0i,IpInReceives=17659269339i,IpInUnknownProtos=0i,IpOutDiscards=236976i,IpOutNoRoutes=1009i,IpOutRequests=23466783734i,IpReasmFails=0i,IpReasmOKs=0i,IpReasmReqds=0i,IpReasmTimeout=0i,TcpActiveOpens=23308977i,TcpAttemptFails=3757543i,TcpCurrEstab=280i,TcpEstabResets=184792i,TcpInCsumErrors=0i,TcpInErrs=232i,TcpInSegs=17536573089i,TcpMaxConn=-1i,TcpOutRsts=4051451i,TcpOutSegs=29836254873i,TcpPassiveOpens=176546974i,TcpRetransSegs=878085i,TcpRtoAlgorithm=1i,TcpRtoMax=120000i,TcpRtoMin=200i,UdpInCsumErrors=0i,UdpInDatagrams=24441661i,UdpInErrors=0i,UdpLiteInCsumErrors=0i,UdpLiteInDatagrams=0i,UdpLiteInErrors=0i,UdpLiteNoPorts=0i,UdpLiteOutDatagrams=0i,UdpLiteRcvbufErrors=0i,UdpLiteSndbufErrors=0i,UdpNoPorts=17660i,UdpOutDatagrams=51807896i,UdpRcvbufErrors=0i,UdpSndbufErrors=236922i 1496460785000000000
```

**Comment by oplehto** [comment]
Deployed it on a test node and the drops that I saw previously are not to be seen. For checking the dops I'm generating a super-simple "heartbeat" metric and looking what comes out the other side: 
`$ for i in `seq 1 100` ; do echo "hb value=$i" > /dev/udp/localhost/8092 ; sleep 1 ; done`

The metrics look sane in tcpdump and none of the other parts of our metrics pipeline are reporting errors. I'll keep an eye on it though.

**Comment by keyboardfann** [comment]
Dear @danielnelson ,
I also meet the split problem, I use statsrelay -> telegraf statd input plugin. When metrics > 1000 may find the problem happen, I don't know it's telegraf issue or statsrelay issue. 

telegraf version: 1.3.2
statsrelay project: https://github.com/jjneely/statsrelay
Test script:
for i in $(seq 1 1000);do echo "deploys.test.myservice$i:1|c" | nc -w 1 -u 10.62.4.240 12000;done

telegraf.log

2017-06-19T14:20:00Z D! Output [riemann] wrote batch of 200 metrics in 21.181514ms
2017-06-19T14:20:00Z D! Output [riemann] wrote batch of 200 metrics in 19.413567ms
2017-06-19T14:20:00Z D! Output [riemann] wrote batch of 200 metrics in 22.65629ms
2017-06-19T14:20:00Z D! Output [riemann] wrote batch of 200 metrics in 20.937404ms
2017-06-19T14:20:00Z D! Output [riemann] wrote batch of 200 metrics in 23.934974ms
2017-06-19T14:20:00Z D! Output [riemann] buffer fullness: 18 / 1000000 metrics. 
2017-06-19T14:20:00Z D! Output [riemann] wrote batch of 18 metrics in 4.565389ms

Test script:
for i in $(seq 1 1400);do echo "deploys.test.myservice$i:1|c" | nc -w 1 -u 10.62.4.240 12000;done

telegraf.log

2017-06-19T14:15:44Z E! Error: splitting ':', Unable to parse metric: |c
2017-06-19T14:15:44Z E! Error: splitting ':', Unable to parse metric: |c
2017-06-19T14:15:44Z E! Error: splitting ':', Unable to parse metric: |c
2017-06-19T14:15:44Z E! Error: splitting ':', Unable to parse metric: |c
2017-06-19T14:15:44Z E! Error: splitting ':', Unable to parse metric: |c
2017-06-19T14:16:00Z D! Output [riemann] wrote batch of 200 metrics in 12.656706ms
2017-06-19T14:16:00Z D! Output [riemann] wrote batch of 200 metrics in 12.392982ms
2017-06-19T14:16:00Z D! Output [riemann] wrote batch of 200 metrics in 18.71846ms
2017-06-19T14:16:00Z D! Output [riemann] wrote batch of 200 metrics in 12.292245ms
2017-06-19T14:16:00Z D! Output [riemann] wrote batch of 200 metrics in 35.489108ms
2017-06-19T14:16:00Z D! Output [riemann] wrote batch of 200 metrics in 12.652427ms
2017-06-19T14:16:00Z D! Output [riemann] wrote batch of 200 metrics in 11.488574ms
2017-06-19T14:16:00Z D! Output [riemann] buffer fullness: 130 / 1000000 metrics. 
2017-06-19T14:16:00Z D! Output [riemann] wrote batch of 130 metrics in 12.944222ms

**Pull request merged**
