### PR TITLE
Add plugin warp10

### PR DESCRIPTION
**Pull request by aurrelhebert**
### Required for all PRs:

PR to add an output plugin for the [Warp 10 platform](www.warp10.io). I sign the SLA, and write a README. See #1452 

- [ ] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sparrc** [comment]
are you going to write unit tests?

**Comment by aurrelhebert** [comment]
I can try writing a test with docker

**Comment by aurrelhebert** [comment]
Unit test added but still get error when loading the docker image with circle Ci (image not found in docker.io). However when I manually run the test, it works (loading the image from Docker Hub).  
How can I correct it ?

**Comment by aurrelhebert** [comment]
Ok now the test looks OK. This may comes from a Tag issue with docker. I will close this PR for now and start clean with a new one.

**Pull request closed without merging**
