### PR TITLE
Attach the pod labels to the `kubernetes_pod_volume` & `kubernetes_pod_network` metrics.

### PR DESCRIPTION
**Pull request by LGDoor**
### Required for all PRs:

- [X] Updated associated README.md.
- [X] Wrote appropriate unit tests.

Resolves the issue that the pod labels are missing in the metrics `kubernetes_pod_volume` & `kubernetes_pod_network`.

### CODE REVIEW

**Comment by LGDoor** [comment]
!signed-cla

**Review by sspaink — APPROVED** [review]
Looks good to me, from the readme it does look like the pod labels should be added to every metric. @LGDoor was there an open issue that this pr resolves?

**Comment by LGDoor** [comment]
> Looks good to me, from the readme it does look like the pod labels should be added to every metric. @LGDoor was there an open issue that this pr resolves?

No. I didn't find any issue mention this.

**Review by helenosheaa — APPROVED** [review]
Looks good

**Pull request merged**
