### PR TITLE
Add twitter input plugin

### PR DESCRIPTION
**Pull request by ykzts**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@ykzts Thanks for opening the pull request.  Plugin looks good, but I don't think we would include it in Telegraf due to the amount of dependencies it requires, weighed against the number of users who I anticipate would be interested in running it.

We are looking into more ways we can allow plugins like this to be loaded at runtime, and I think that would be a better fit.

**Comment by ykzts** [comment]
> We are looking into more ways we can allow plugins like this to be loaded at runtime, and I think that would be a better fit.

👍

**Comment by ykzts** [comment]
move to https://github.com/inabagumi/twitter-telegraf-plugin

**Comment by danielnelson** [comment]
Very nice, would it be okay if we add your repo to the new list of [external plugins](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md)?

**Comment by ykzts** [comment]
This product is still WIP. I'm honored if it's still good.

**Comment by danielnelson** [comment]
That's okay, you are added

**Pull request closed without merging**
