### PR TITLE
config api

### PR DESCRIPTION
**Pull request by ssoroka**
config.api plugin

- adds http listener for incoming config requests which can load and unload Telegraf plugins without restarting
- adds storage plugins
- persist list of running plugins and their configuration across restarts
- makes agent the manager of running plugin list instead of config package.
- supports json-based config
- supports dynamically building a json description of plugin config from plugins
- supports dynamically assigning config from json

### CODE REVIEW

**Comment by reimda** [comment]
Hi Steven, Jess asked us to get config api reviewed through this PR.

Your last change here was Feb 12 and there are lots of merge conflicts. Is this your latest code and is it ready for review? I took a quick look at the conflicts and most of them are trivial, but agent/agent.go is more complex. It doesn't seem productive to do a review of it without the conflicts resolved. Would you resolve them?

We're going to need the test and once command line options to be working before this can be merged. Are they still disabled?

**Comment by reimda** [comment]
The agent tests don't pass for me. In master they load a test config file (config/testdata/telegraf-agent.toml) but don't start running the plugins. It looks like in this branch they run the plugins which causes the tests to fail because they can't connect to services. I've attached the output of ` test -short -race ./agent/ 2>&1 > configapi_agent_test.txt`

[configapi_agent_test.txt](https://github.com/influxdata/telegraf/files/6787246/configapi_agent_test.txt)

**Comment by ssoroka** [comment]
All tests are passing on the branch now. You won't see this in github because it's running it against master, not the local branch. Once you've had a pass-through we can look at updating it with the latest master branch.

**Comment by ssoroka** [comment]
this branch has been rebased with master and moved to https://github.com/influxdata/telegraf/pull/9546. this can be closed when the review is done or not using this branch anymore.

**Comment by sspaink** [comment]
Closing in favor of: #9546

**Pull request closed without merging**
