### PR TITLE
docs(inputs.snmp): Clarify the deprecation of agent tag setting

### PR DESCRIPTION
**Pull request by powersj**
## Summary
Provide some additional information about the change for users after user feedback was seen in #14111.

## Checklist

- [x] No AI generated code was used in this PR

### CODE REVIEW

**Comment by powersj** [comment]
@Hr0bar would this have helped provide some additional background to the snmp deprecation?

**Comment by Hr0bar** [comment]
Yes I think so. But now it seems almost like the deprecation is going to be
kept forever, is there a plan to actually remove it in some distant future?
Now it looks like a notice rather than deprecation that you should
proactively act upon.

**Comment by powersj** [comment]
> Now it looks like a notice rather than deprecation that you should
proactively act upon.

That was my intention as this would not be something we get rid of. Rather a gentle way of pushing users to use a more common value across metrics.

Does that work?

**Comment by Hr0bar** [comment]
Oh then if thats the intention its definitely more clear now. Up until now
I thought its a hard deprecation and migration will be mandatory in the
future. (We already migrated in dashboards, alerting in dependent systems
on this snmp plugin etc to "source" :D )

**Review by Hipska — APPROVED** [review]

**Pull request merged**
