### PR TITLE
procstat err if no pids found

### PR DESCRIPTION
**Pull request by arindamchoudhury**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
So this would change the procstat_lookup measurement to have a `lookup_error`?  I don't think this is wanted, the lookup succeeded with no matches.

**Comment by arindamchoudhury** [comment]
this helps to notify when a process dies.

**Comment by danielnelson** [comment]
What about the current `procstat_lookup` behavior, does it not work for you, why not?
```
procstat_lookup,exe=foo,pid_finder=pgrep,process_name=bar,result=success pid_count=0i,result_code=0i,running=0i 1556136150000000000
```

**Comment by arindamchoudhury** [comment]
now, it does not send any data if pid is not found. so we can not make a query to check status of a process.

**Comment by danielnelson** [comment]
Can you show your configuration and how to reproduce?  It should always emit the `procstat_lookup` measurement.

**Comment by danielnelson** [comment]
I'm closing but we can discuss further, want to make sure we have a solution that works for you.

**Pull request closed without merging**
