### PR TITLE
Update default value for Cloudwatch rate limit

### PR DESCRIPTION
**Pull request by AntoineAugusti**
Follow up of: https://github.com/influxdata/telegraf/issues/2298

New documentation: http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html

Rate limit is used for the `GetMetricStatistics` endpoint.

### Required for all PRs:

- [x] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sparrc** [comment]
PS: also please put that documentation like in the SampleConfig

**Comment by sparrc** [comment]
cc @johnrengelman

**Comment by AntoineAugusti** [comment]
@sparrc Done that and squashed. thanks!

**Comment by phemmer** [comment]
If we're saying cloudwatch has a limit of 400 requests per second, do we really want to default to telegraf using all of it? This means that if telegraf has it maxed out, and someone simply goes to the AWS dashboard and tries to pull up cloudwatch metrics, their browser is going to push it over the limit. Ditto if they have any other system which also uses cloudwatch metrics. Should we not choose a safer default, and let people increase it to the max if the default isn't enough?

**Comment by johnrengelman** [comment]
it's probably time revive this PR https://github.com/influxdata/telegraf/pull/1795 so that telegraf can pull multiple periods of data in 1 request thus saving the API limit.

**Comment by sparrc** [comment]
@phemmer makes a good point....@AntoineAugusti can you lower the default to ~200?

**Comment by AntoineAugusti** [comment]
@sparrc Sure, done

**Pull request merged**
