### PR TITLE
chore(deps): Bump github.com/signalfx/golib from 3.3.46 to 3.3.50

### PR DESCRIPTION
**Pull request by LukeWinikates**
this PR bumps `signalfx/golib` to ~~`v3.3.49`~~ `v3.3.50`

### CODE REVIEW

**Review by powersj — APPROVED** [review]
+1 - any reason not to go all the way to 3.3.50? Looking at [the diff](https://github.com/signalfx/golib/compare/v3.3.49...v3.3.50) it is largely changes due to the jump up to go1.19

**Comment by LukeWinikates** [comment]
@powersj thanks for spotting the even newer version. Looks like the released `3.3.50` just a couple of hours after I started looking at this.

Apologies for the force push after you added the `ready for final review` label!

**Review by powersj — APPROVED** [review]
Looks good with v3.3.50 as well and no worries :)

**Review by srebhan — APPROVED** [review]
Thanks @LukeWinikates!

**Comment by srebhan** [comment]
@LukeWinikates can you please resolve the conflict so we can merge this PR!?

**Comment by LukeWinikates** [comment]
@srebhan sure thing! rebased onto the master branch and re-ran `go mod tidy`.

**Pull request merged**
