### PR TITLE
feat(outputs.wavefront): use common/http to configure http client

### LINKED ISSUE #14090: Limit the number of HTTP connection using outputs.wavefront
### Use Case

Please add a feature request for the outputs.wavefront Telegraf output plugin which can control for the number of connections the plugin makes such that we can pin it to a specific value, like outputs.http does now.
This is to avoid the Wavefront plugin from making too many connection and overloading the proxies.

### Expected behavior

We set the number of HTTP connections (like outputs.http does now) to a certain value and it stays that way.

Example from outputs.http:

```
  ## MaxIdleConns controls the maximum number of idle (keep-alive)
  ## connections across all hosts. Zero means no limit.
  # max_idle_conn = 0

  ## MaxIdleConnsPerHost, if non-zero, controls the maximum idle
  ## (keep-alive) connections to keep per-host. If zero,
  ## DefaultMaxIdleConnsPerHost is used(2).
  # max_idle_conn_per_host = 2

  ## Idle (keep-alive) connection timeout.
  ## Maximum amount of time before idle connection is closed.
  ## Zero means no limit.
  # idle_conn_timeout = 0
```

### Actual behavior

This doesn't currently exist.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by LukeWinikates**
# Required for all PRs

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #14090

This PR adopts Telegraf's `common/http` struct to configure the `http.Client` used by the Wavefront output plugin. This should be a harmonious way of exposing a variety of HTTP client customizations and tuning parameters, including the idle connection settings requested in #14909.

I removed existing fields for TLS and HTTP Timeout configuration, because the HTTPClientConfig exposes the same fields.

`question`: I am not sure if the `init()` function needs to set a default `HTTPClientConfig`.
`note`: this is currently using a branch of the Wavefront SDK. I want to get feedback on the PR early. Prior to final review, we (the Wavefront Go SDK maintainers) will release a new SDK version, and I will update this PR accordingly.

### CODE REVIEW

**Review by srebhan — APPROVED** [review]
Thanks for the nice upgrade @LukeWinikates! The code looks good, just two comments/requests from my side:

1. Please update to the `github.com/wavefronthq/wavefront-sdk-go v0.14.1` package as soon as it is released. IIRC dependabot will not touch git-versions so we need to do this manually...
2. We now do have the possibility to include other configs in the `sample.conf` by creating a `sample.conf.in` and call the generator in the plugin file. Checkout the [http input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http) for an example on TLS parameters... It would be nice if we could include those parameters here to present all options to the user... This can be a separate PR though!

**Comment by LukeWinikates** [comment]
@srebhan @powersj thanks for the fast feedback!

@powersj yes, I would like to wait to merge this until we ship an updated Wavefront SDK release with the new configuration options exposed.

* I will get a new Wavefront SDK version released and update the PR with a proper released version
* I will update the docs and sample config.

I will circle back after that. Thanks again!

**Comment by LukeWinikates** [comment]
@srebhan @powersj just updated this branch to use the Wavefront SDK version released today, plus an update to the sample config.

Looking at @srebhan's comment about config file includes, I considered the possibility of extracting a config template that covers TLS options and idle connection settings, but I didn't take the plunge yet. The least complicated option would be to make a template that covers all of the `httpconfig.HTTPClientConfig` fields, using the content from the HTTP output plugin. Then everything that uses `httpconfig.HTTPClientConfig` could embed that too.

I like the idea of having a single source of truth about all the configuration options for `httpconfig.HTTPClientConfig`. I'd like to keep it out of scope for this PR.

**Review by srebhan — APPROVED** [review]

**Review by powersj — APPROVED** [review]
Thank you!

**Pull request merged**
