### PR TITLE
Add snmp table feature #540

### PR DESCRIPTION
**Pull request by titilambert**
@sparrc Hello !
It seems tests are failing because of number of entries in config files ???
```
telegraf -sample-config > testconfig.conf
telegraf -config  testconfig.conf

panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/naoina/toml.(*parseState).execute.func1(0xc8200b17f8)
	/home/tcohen/gits/go/src/github.com/naoina/toml/parse.go:47 +0xab
github.com/naoina/toml.(*tomlParser).Execute(0xc8200bf880)
	/home/tcohen/gits/go/src/github.com/naoina/toml/parse.peg.go:849 +0x3ca
github.com/naoina/toml.(*parseState).execute(0xc8200b18c0, 0x0, 0x0)
	/home/tcohen/gits/go/src/github.com/naoina/toml/parse.go:52 +0x63
github.com/naoina/toml.(*parseState).parse(0xc8200b18c0, 0x0, 0x0)
	/home/tcohen/gits/go/src/github.com/naoina/toml/parse.go:38 +0x1e4
github.com/naoina/toml.Parse(0xc8201b6000, 0x84dc, 0x86dc, 0x84dc, 0x0, 0x0)
	/home/tcohen/gits/go/src/github.com/naoina/toml/parse.go:15 +0xfd
github.com/influxdata/config.ParseFile(0x7ffc199b6417, 0xf, 0xc8200b1978, 0x0, 0x0)
	/home/tcohen/gits/go/src/github.com/influxdata/config/legacy.go:50 +0xaa
github.com/influxdata/telegraf/internal/config.(*Config).LoadConfig(0xc8204092d0, 0x7ffc199b6417, 0xf, 0x0, 0x0)
	/home/tcohen/gits/go/src/github.com/influxdata/telegraf/internal/config/config.go:328 +0x61
main.main()
	/home/tcohen/gits/go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:147 +0xd2e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 34 [chan send]:
github.com/naoina/toml.(*tokens16).Tokens.func1(0xc8200d3110, 0xc820080580)
	/home/tcohen/gits/go/src/github.com/naoina/toml/parse.peg.go:466 +0x134
created by github.com/naoina/toml.(*tokens16).Tokens
```

If I remove **4** entries in `testconfig.conf` file, I don't have any error ...

Is it a bug from toml ???

### CODE REVIEW

**Comment by sparrc** [comment]
yes, I ran into this recently too, can you paste in your entire config file and I can help? It seems like the toml parser doesn't like `###` or the large `Telegraf Config` section at the top

**Comment by titilambert** [comment]
here the config file: https://gist.github.com/titilambert/e5572dd1223a85c5d2af
Should we patch toml lib ?

**Comment by sparrc** [comment]
try replacing all of the `## ` with just `# `

**Comment by titilambert** [comment]
@sparrc It's working ! We should catch the error and print a better error message for users

**Comment by titilambert** [comment]
@sparrc It's NOT workgin (I load an other config file :/)

**Comment by titilambert** [comment]
@sparrc I just updated the gist

**Comment by sparrc** [comment]
what about:

```
#
#                                  OUTPUTS                                    #
#
```

to just

```
# OUTPUTS
```

**Comment by titilambert** [comment]
Still no :( (gist updated)

**Comment by sparrc** [comment]
try removing the trailing comment: https://gist.github.com/titilambert/e5572dd1223a85c5d2af#file-telegraf-conf-L830?

**Comment by titilambert** [comment]
Still no  :(
But I remove the 29 last lines (on both files):
* working https://gist.github.com/titilambert/3ff92ea9ca32c0a50fc4
* notworking https://gist.github.com/titilambert/bec4ed434349764e273a

The only diff is : in the working file I just commented the last line .... 
I don't get why !??

**Comment by titilambert** [comment]
@sparrc are we stuck with this parser ?
It seems dead since 08/2015... I saw taht all influxdata softs are using it but maybe you should consider to change the dependency to an other parser like https://github.com/pelletier/go-toml or https://github.com/kezhuw/toml

**Comment by sparrc** [comment]
I tried pelletier/go-toml but it doesn't provide the capability to unmarshal toml data onto an arbitrary interface. https://github.com/kezhuw/toml looks promising.

**Comment by titilambert** [comment]
@sparrc So what can I do ? :D

**Comment by sparrc** [comment]
I really don't know, sorry, just try to get the file to not panic :see_no_evil: :gun:

**Comment by titilambert** [comment]
:D oki, I will try something this evening :)

**Comment by titilambert** [comment]
@sparrc I made a "dirty workaround" which remove all comments from sample config file when you run `circle-test.sh` script

**Comment by titilambert** [comment]
@sparrc well, it's working, it's ugly ... this is workaround definition ...
What do you think ?

**Comment by sparrc** [comment]
:scream:! no! this is catching an actual bug, the -sample-config generated file should work out of the box. Try rebasing and running again (I made some changes to the config file format when merging a separate PR just now)

**Comment by titilambert** [comment]
@sparrc :D :D

**Comment by sparrc** [comment]
@titilambert I've merged all necessary external PRs and fixed dependencies for #745, please rebase and the config file panic should be fixed.

**Comment by titilambert** [comment]
@sparrc rebased !
Thanks !!

**Comment by sparrc** [comment]
OK, is this ready to go then? Could you update the README with an explanation of what these table features are exactly?

**Comment by titilambert** [comment]
@sparrc README added !
I think this is ready !

**Comment by sparrc** [comment]
in the README, can you put more explanation of the different config options? I'm not sure I understand the differences between `inputs.snmp.table` and `inputs.snmp.host.table`? And what is a `subtable`? Are these at all related to `snmptable`?

**Comment by titilambert** [comment]
@sparrc README updated ! Tell me if is OK now.
Please wait before merging, I just want to check something before

**Comment by titilambert** [comment]
#TODELETE stuff removed :)

@sparrc This PR is good for me !

**Pull request closed without merging**
