### PR TITLE
docs: URL updates for graylog 3

### PR DESCRIPTION
**Pull request by BenoitPoulet**
Update the URLs and port for Graylog 3, as Graylog 2 is very old.

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Review by ssoroka — CHANGES_REQUESTED** [review]
should there be a note about old ports? 
You also need to change plugins/inputs/graylog/graylog.go to match.

**Comment by sjwang90** [comment]
@BenoitPoulet Still interesting in working on this? Please address the comment from above. Thanks.

**Comment by BenoitPoulet** [comment]
I did the change in plugins/inputs/graylog/graylog.go

**Comment by srebhan** [comment]
@BenoitPoulet does it make sense to mention both ports (the old and the new one) at least in the Readme? If I get this, you _always_ have to set the `server` field... Is my understanding correct?

**Comment by BenoitPoulet** [comment]
Hello,

Now Graylog is in 4.2 ,  so i not convinced that many people still use Graylog 2 and the old port.
By the way the metrics list gathered by the plugin must be outdated too.
 
Yes, perhaps you can mention the old port in the Readme.

**Review by Hipska — APPROVED** [review]

**Comment by powersj** [comment]
I resolved the conflicts, but we need the linter happy and the CLA signed please:

```
/github/workspace/plugins/inputs/graylog/README.md:7:17 MD034/no-bare-urls Bare URL used [Context: "http://[graylog-server-ip"]
/github/workspace/plugins/inputs/graylog/README.md:8:17 MD034/no-bare-urls Bare URL used [Context: "http://[graylog-server-ip"]
/github/workspace/plugins/inputs/graylog/README.md:54:72 MD034/no-bare-urls Bare URL used [Context: "http://host:9000/api/api-brows..."]
```

**Comment by powersj** [comment]
!signed-cla

**Comment by powersj** [comment]
Appreciate you putting this up, but to get this landed, I am going to close this in favor of https://github.com/influxdata/telegraf/pull/10481

**Pull request closed without merging**
