### PR TITLE
Request aggregates plugin

### PR DESCRIPTION
**Pull request by danielgblanco**
As the the description of the plugin indicates, this plugin aggregates some information tailing a CSV file with results from requests before adding it to the accumulator. I've created the PR to master, but I'm not sure if that's the right branch. Thanks.

### CODE REVIEW

**Comment by sparrc** [comment]
you need to run `go fmt ./...` on your code

**Comment by danielgblanco** [comment]
Done, forgot to run it after my last changes...

**Comment by sparrc** [comment]
@danielgblanco what exactly is this csv file and where does it come from? this seems rather specific for a plugin in the general repo

**Comment by danielgblanco** [comment]
@sparrc this CSV file can be generated by test harness like JMeter or SoapUI or it can be an access log, providing the web server is configured to output the access log in CSV (pretty straight forward in NGinx). When load testing high frequency applications generating thousands of requests per second, or several applications in parallel, sending a data point for every request floods InfluxDB with writes. This is a solution to monitor requests in a server or test harness in real time, generating a constant number of data points independent of the requests/second the system under test is able to process.

Having said that, I understand your concerns. In case you consider this should not be part of the general repo, how would you recommend keep the rest of Telegraf up-to-date while being able to use this plugin? Is there a way to, let's say, download the Telegraf binaries and install the plugin separately on top?

Thanks.

**Comment by danielgblanco** [comment]
Hi @sparrc, after some testing I noticed that the last data points were not being stored. This is because when `Stop()` is called in the service input it flushes the remaining metrics to the accumulator, but at that time this accumulator has already been flushed to the outputs in `agent.go`. I've made a small modification to wait until all service inputs are stopped to flush metrics.

As I mentioned before, I believe this could be useful to monitor performance of an application or web server, but if you think this is not general enough for the public repo, should I move the change to the agent to a different PR? I believe that data points should be flushed after all service inputs have stopped not to miss any data points. What do you think?

**Comment by sparrc** [comment]
the agent change might have already inadvertently been fixed with #1235

Could you writeup more specifics in the readme? what does the csv file look like? where can it be configured to come from? how can it be configured?

**Comment by danielgblanco** [comment]
I've just added more info to the README. If you think this plugin can be merged to the public repo I'll rebase and check if #1235 fixes the flushing at shutdown issue. If not, I guess it's better to keep my fork at a certain release... Thanks!

**Comment by sparrc** [comment]
@danielgblanco Thanks for including more details, I'm sorry but I think that is indeed too specific for the general repo.

The best way to maintain this is to have a fork and pull in changes from upstream regularly. I would highly recommend _not_ making changes in your fork to the core codebase because this will only make rebasing more difficult.

The only file that you should have issues with is `plugins/inputs/all/all.go`, but you can get around this by adding a line like this to the .gitattributes file:

```
plugins/inputs/all/all.go merge=union
```

**Comment by danielgblanco** [comment]
Thanks @sparrc. I'll give 0.13.1 a go and see if it fixes the flushing of metrics on shutdown to flush after the services are stopped. In any case, I'll keep this plugin in our fork and try to contribute to the public repo with other (more useful for everyone) stuff.

**Pull request closed without merging**
