### PR TITLE
docs: Add generic secret store usage

### PR DESCRIPTION
**Pull request by powersj**
fixes: #13328
superseeds #13370

### CODE REVIEW

**Comment by powersj** [comment]
@knollet does this convey what you wanted in #13370?

**Review by srebhan — APPROVED** [review]

**Comment by srebhan** [comment]
@powersj assigning it back to you in case you want to wait for feedback...

**Comment by knollet** [comment]
Yes, it does, thank you very much. I'm sorry, I couldn't do it myself.

**Comment by powersj** [comment]
> Yes, it does, thank you very much. I'm sorry, I couldn't do it myself.

no need to apologize, thanks for bringing it up!

**Pull request merged**
