### PR TITLE
Fixing Windows CORE Issue

### PR DESCRIPTION
**Pull request by JeffAshton**
Switching from github.com/lxn/win to github.com/JeffAshton/win_pdh.  This is a fork of the original library, but containing only the performance counters wrappers.

### CODE REVIEW

**Comment by sparrc** [comment]
thanks @JeffAshton, can you change docs/LICENSE_OF_DEPENDENCIES as well?

**Comment by JeffAshton** [comment]
@sparrc : Docs have been updated Cameron.  Thanks for Telegraf.  :)

**Comment by sparrc** [comment]
No problem, I looked into your fork and noticed that it only represents ~400 lines of code. Could you actually just copy and paste that code directly here into a file within the same package as the plugin? For a dependency that small I prefer to just have it in-repo.

You can keep the license of the code the same, and paste it in here as well if you want.

**Comment by JeffAshton** [comment]
Hey @sparrc, I brought in the pdh library and appended the license and authors.  I think that should cover us legally.

**Comment by JeffAshton** [comment]
@sparrc, Is there anything else you need from me on this one?

**Comment by JeffAshton** [comment]
Hey @sparrc , I've rebased the changes.  Not sure why a CI build didn't kick off.  Can you kick one off for me?  Thanks

**Comment by sparrc** [comment]
we had a configuration issue with CircleCI that had builds from forks disabled. I've created a separate PR (https://github.com/influxdata/telegraf/pull/2180) to merge this change and close #1763

**Pull request closed without merging**
