### PR TITLE
Update to pgx 3.2.0

### LINKED ISSUE #3817: Configuration for location of certs of postgres in ssl with CA mode
Hi Team

I am trying to configure my postgres in ssl mode with client authentication
But In the telegraf configuration I am unable to see any setting which specify the location of the client cert key
Does the plugin support postgres in ssl mode with client authentication

### PR DESCRIPTION
**Pull request by danielnelson**
Includes TLS support among other things.

closes #3817 

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@suckatrash Are you able to test with one of these builds?:

- [telegraf-1.10.0%7E0d7f373a-0.x86_64.rpm](https://23326-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.10.0%7E0d7f373a-0.x86_64.rpm)
- [telegraf_1.10.0%7E0d7f373a-0_amd64.deb](https://23326-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.10.0%7E0d7f373a-0_amd64.deb)

**Comment by suckatrash** [comment]
Tested and I can confirm this is working now!  Thanks!!

**Comment by suckatrash** [comment]
@danielnelson - This is probably the wrong place to ask, but when is the estimated release date for telegraf 1.10?  Could the fix here be back-ported to 1.9.z?

**Comment by danielnelson** [comment]
This was already backported to 1.9.1, but let me know if you find any issues.

**Pull request merged**
