### PR TITLE
feat(inputs.http_response): Add cookie authentication

### LINKED ISSUE #11913: Allow cookie auth also in http_response plugin (like in http input plugin)
### Use Case

For monitoring some sites we need to authenticate via different auth URL and cookies are used to grant access.
This seems to be possible with http input plugin but not with http_response input plugin. At least it was merged in https://github.com/influxdata/telegraf/pull/9395 for http input plugin).

### Expected behavior

Have option to use cookie based auth in http_response plugin as well.

### Actual behavior

Does not work.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by DStrand1**
## Summary
Add http cookie auth to the http_response input plugin, similar to the http input plugin

## Checklist

- [X] No AI generated code was used in this PR

## Related issues

resolves #11913

### CODE REVIEW

**Review by powersj — APPROVED** [review]
Thank you! Did you ask the reporter to try this out? If not I would.

**Review by srebhan — APPROVED** [review]
Awesome job @DStrand1! Thanks!

**Comment by srebhan** [comment]
@powersj assigning it back to you in case you want to test it some more...

**Comment by DStrand1** [comment]
@space2man Are you available to test this fix for your issue #11913? Thanks in advance!

**Pull request merged**
