### PR TITLE
docs(outputs.mqtt): fix minor syntax typo

### PR DESCRIPTION
**Pull request by andoks**
# Required for all PRs

- [x] Updated associated README.md.  
       N/A
- [x] Wrote appropriate unit tests.  
       N/A
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [x] Sign CLA

resolves #

Correct the topic syntax description as go template ["Actions"](https://pkg.go.dev/text/template) ends with `}}` not `]]`

### CODE REVIEW

**Comment by andoks** [comment]
!signed-cla

**Comment by andoks** [comment]
Labels are wrong, I assume because I created the PR with wrong title initially. This is not a code fix, but a minor typo fix in the docs

**Comment by powersj** [comment]
> I assume because I created the PR with wrong title initially

yes the bot will parse your initial submission and try to apply some applicable tags

**Review by powersj — APPROVED** [review]
Thanks for the catch!

**Pull request merged**
