### PR TITLE
feat: add field key option to set event partition key

### PR DESCRIPTION
**Pull request by powersj**
Fixes: #10762

### CODE REVIEW

**Comment by jcorioland** [comment]
Hi @powersj - any reason why this PR has been closed without being merged? Supporting partitioning key in the Event Hubs output is something my team currently need for a customer who is using Telegraf. Thanks!

**Comment by powersj** [comment]
@jcorioland the original issue was closed as we did not get a response on whether this PR resolved the issue. I can reopen the PR and get some new artifacts if you are willing to test them out?

**Comment by plalwa** [comment]
@powersj, i will be happy to help, unfortunately i was not able to build from the branch, and also the build artifacts links seems not working. Can you have a look?

**Comment by plalwa** [comment]
> @powersj ok, understand. @plalwa can you confirm you will be able to test if we have a build from this branch?

sure!

**Comment by powersj** [comment]
Thank you both, please see #11076

**Pull request closed without merging**
