### PR TITLE
added linux/darwin min/max ping values to match windows plugin

### PR DESCRIPTION
**Pull request by hestonk**
I noticed that the Linux ping pluging was missing values for min and max. Wanted to capture that data since we already have it in the ping output.

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by hestonk** [comment]
can't figure out why circleci is complaining about the go format. When i run the command and go through the 2 files i've modified, nothing seems out-of go-lang code standards. Any advice?

**Comment by danielnelson** [comment]
Sorry the error message is not great in our circleci script.  Have you ran `go fmt ./...` on your code and what does it say?

**Comment by hestonk** [comment]
`$ go fmt ./...`
`plugins/inputs/ping/ping_test.go`
Could have sworn I ran that and got no output before. all good now.
Thanks @danielnelson ....would love to see this implemented in 1.4!

**Comment by danielnelson** [comment]
Thanks, it will be there.

**Pull request merged**
