### PR TITLE
introduce timestamps to file content and path

### PR DESCRIPTION
**Pull request by silverboots**
### Required for all PRs:

- [ ] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

new parameter to allow timestamp prefix to each line in file.  Also, add
ability to introduce time parameters in path and file name.  Will also
create missing directories if required.

### CODE REVIEW

**Comment by sparrc** [comment]
can you explain why this is necessary? most metric formats already include the timestamp so I'm not sure I see the utility.

**Comment by silverboots** [comment]
Hi, there are two changes here. The first to introduce a prefix time stamp. I couldn't see how to get a time stamp for system metrics like cpu in the output (perhaps you can tell me how) - the usage is to easily index data in splunk so can chart time series of metrics. The second change is to allow times to be used in file path and file name, this is so new logs / directories can be created when process starts - this makes archiving of old data logs easier and minimises data stored on local server. I also intend to introduce roll features so new files are created based on day and size.

**Comment by sparrc** [comment]
what data format are you outputting? the "influx" data format, for example, has a timestamp at the end.

**Comment by silverboots** [comment]
Hi, I am outputting influx data format and to be honest I didn't notice until you just mentioned it the date/time on the end (I am new to this project :) ) That said, I still believe its a valid option for a few reasons.  1 - It will work with any format or input type, 2 - the prefix added is human readable, so makes reviewing raw files easier and 3 - prefix can be used as a line break more easily for interpreting file i.e. where input data goes across multiple lines.  Out of interest do you know if the influx date time is UTC or local time?  I would like UTC.

**Comment by sparrc** [comment]
The timestamps are unix nano, which is always based off of UTC. 

Thank you for the PR, but I'm sorry I don't think I can accept your change. The whole point of the file output is for each line to be in a valid protocol format, adding the timestamp makes it no longer valid json/influx/graphite. it makes it more human readable, but less machine readable.

If you really needed it you could post-process the file, but I'd rather not have this part of telegraf, as I think it's unnecessary and encourages bad practices.

**Pull request closed without merging**
