### PR TITLE
docs(config): Clarify metric-routing example

### LINKED ISSUE #14990: tagpass, tagdrop does not remove tags
### Relevant telegraf.conf

```toml
Nope
```

### Logs from Telegraf

```text
Nope
```

### System info

any version

### Docker

_No response_

### Steps to reproduce

Nope

### Expected behavior

Removed tags in the output

### Actual behavior

Tags are present

### Additional info

In the [doc](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#routing-metrics-to-different-outputs-based-on-the-input) we have mention **"The tag is removed in the outputs before writing."** which awesome behaviour but actual it does not remove a tags and they are present in the output.

### PR DESCRIPTION
**Pull request by kklis**
## Summary

Clarify example description to avoid tagpass and tagdrop behavior misinterpretations.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #14990

### CODE REVIEW

**Review by srebhan — APPROVED** [review]
Thanks for the clarification @kklis!

**Comment by srebhan** [comment]
@kklis could you please sign the CLA!?!

**Comment by kklis** [comment]
!signed-cla

**Review by powersj — APPROVED** [review]
Thank you!

**Pull request merged**
