### PR TITLE
fix: Fix missing disks in container

### LINKED ISSUE #10297: Telegraf 1.21.1, input plugin `disk` doesn't report data for non-partitioned disks
### Relevent telegraf.conf

```toml
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
```

### System info

Telegraf 1.12.1 running in Docker 20.10.8

### Docker

```
services:
  telegraf:
    image: telegraf:1.21
    environment:
      HOST_PROC: /host/proc
      HOST_MOUNT_PREFIX: /host
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /:/host:ro
      - /sys:/host/sys:ro
```  

### Steps to reproduce

1. Update Telegraf to 1.21.1
2. Look at the `disk` metrics

### Expected behavior

All disks (`/dev/sda1` and `/dev/sdb`) should export data.

### Actual behavior

Only data for `/dev/sda1` is visible, `/dev/sdb` is missing.

### Additional info

The `diskio` input plugin still reports data for `/dev/sdb` after the update to 1.21.1, only `disk` is missing data. I've tried the [Troubleshooting](https://github.com/influxdata/telegraf/tree/v1.21.1/plugins/inputs/disk#troubleshooting) instructions and both expected disks (`/dev/sda1` and `/dev/sdb`) show up in the Docker container as a mount under `/host` with an `ext4` filesystem and `stat` succeeds for both.

Downgrading the Docker image to 1.20.4 fixes the issue and `/dev/sdb` has data again. There's no 1.21.0 image I could test with but data stopped being available after the upgrade from 1.21.0 to 1.21.1.

### PR DESCRIPTION
**Pull request by srebhan**
### Required for all PRs:
- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10297

This PR fixes the missing disks when trying to run telegraf from within a container.

### CODE REVIEW

**Review by powersj — APPROVED** [review]

**Comment by voiprodrigo** [comment]
After this change, logs are plagued with this type of messages:

2022-01-19T19:40:03Z D! [inputs.disk] [SystemPS] partition 0: {"device":"sysfs","mountpoint":"/sys","fstype":"sysfs","opts":["rw","nosuid","nodev","noexec","relatime"]}
2022-01-19T19:40:03Z D! [inputs.disk] [SystemPS] -> using mountpoint "/sys"...
2022-01-19T19:40:03Z D! [inputs.disk] [SystemPS] => kept...
2022-01-19T19:40:03Z D! [inputs.disk] [SystemPS] partition 1: {"device":"proc","mountpoint":"/proc","fstype":"proc","opts":["rw","nosuid","nodev","noexec","relatime"]}
2022-01-19T19:40:03Z D! [inputs.disk] [SystemPS] => dropped by filesystem-type filter
2022-01-19T19:40:03Z D! [inputs.disk] [SystemPS] partition 2: {"device":"devtmpfs","mountpoint":"/dev","fstype":"devtmpfs","opts":["rw","nosuid"]}
2022-01-19T19:40:03Z D! [inputs.disk] [SystemPS] => dropped by filesystem-type filter

**Comment by srebhan** [comment]
@voiprodrigo as you can see those are **debug** messages. Is there any reason you are running in debug mode?

**Comment by voiprodrigo** [comment]
@srebhan  I know they're debug. Still, I feel these look as "debug during development/bug fixing", not "debugging in production". Mostly because of the buffer messages, I like to keep an eye on those.

**Comment by srebhan** [comment]
@voiprodrigo can you please open an issue to discuss possible solutions there?

**Pull request merged**
