### PR TITLE
adding inputs.filebeat plugin

### PR DESCRIPTION
**Pull request by jgysel**
Hi,

Queries the filebeat statistics from the elasticsearch project (Lightweight Shipper for Logs).

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by russorat** [comment]
@jgysel thanks for the PR! My understanding is that using the `-httpprof` option is really only for debugging, and if you'd like to continuously monitor, you should use the `/stats` endpoint. https://github.com/elastic/beats/pull/3717

What are your thoughts?

**Comment by gl1ridae** [comment]
Hi! Is there any chance this plugin will be added in the nearest release? It'll be quite convenient to have inputs for all elastic-stack products.

**Comment by danielmotaleite** [comment]
probably obsolete by https://github.com/influxdata/telegraf/pull/4911

**Comment by sjwang90** [comment]
Closing in preference for #4911

**Pull request closed without merging**
