### PR TITLE
Add ~200 more Couchbase metrics via Buckets endpoint

### LINKED ISSUE #4152: Couchbase Plugin Enhancement
## Feature Request
Couchbase Plugin Enhancement to include key metrics to monitor couchbase bucket performance.

Opening a feature request kicks off a discussion.

### Proposal:
Few of the key metrics missing in the default couchbase plugin are
(Full list of requested metrics for Couchbase plugin - _edited Oct 27, 2020 by @sjwang90_):

```
curr_connections
vb_active_resident_items_ratio
ep_queue_size
ep_cache_miss_rate
ep_tmp_oom_errors
ep_dcp_xdcr_items_remaining
couch_docs_fragmentation
query-requests_1000ms

gets per seconds
sets per seconds
deletes per seconds
active resident ratio
inbound xdcr ops/sec
outbound xdcr mutations
docs fragmentation %
connections
cluster node count

couch_docs_actual_disk_size
ep_cache_miss_rate
couch_docs_fragmentation
ep_bg_fetched
vb_active_resident_items_ratio
ep_queue_size
vb_num_eject_replicas
ep_warmup_value_count
vb_active_curr_items
ep_cache_miss_rate
couch_docs_fragmentation
ep_queue_size
vb_active_resident_items_ratio
curr_connections
curr_items_tot
ep_bg_fetched
ep_diskqueue_drain
ep_diskqueue_fill
vb_replica_eject
ep_oom_errors
ep_queue_size
ep_tmp_oom_errors
[etc...]
```

References: 
https://blog.couchbase.com/monitoring-couchbase-cluster/

### Current behavior:
Only a handful of metrics are being monitored currently.
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/couchbase

Fields:
quota_percent_used (unit: percent, example: 68.85424936294555)
ops_per_sec (unit: count, example: 5686.789686789687)
disk_fetches (unit: count, example: 0.0)
item_count (unit: count, example: 943239752.0)
disk_used (unit: bytes, example: 409178772321.0)
data_used (unit: bytes, example: 212179309111.0)
mem_used (unit: bytes, example: 202156957464.0)

### Desired behavior:
Need additional metrics to effectively monitor Couchbase.

### Use case: [Why is this important (helps with prioritizing requests)]
There are heavy users of Couchbase growing rapidly. IT would be very helpful, if we can improve on this.

### PR DESCRIPTION
**Pull request by Jagularr**
The additional metrics are configurable as `detailed` metrics. 
Many of the stats being added correlate directly to graphs available on the Couchbase UI, you can hover them to see their metric 'name'.
Every gather of the `detailed` metrics will gather the latest Couchbase metrics (from the last possible second).

resolves #4152

### CODE REVIEW

**Comment by ssoroka** [comment]
I think we may want to consider adding `fields_included = []` and `fields_excluded = []` support to this as the field-set is getting really large.

**Comment by Jagularr** [comment]
> I think we may want to consider adding `fields_included = []` and `fields_excluded = []` support to this as the field-set is getting really large.

Done

**Review by helenosheaa — APPROVED** [review]
Looks good to me

**Review by ssoroka — APPROVED** [review]
this is probably fine, but I was thinking we needed fields_excluded, but maybe not?

**Comment by Jagularr** [comment]
> this is probably fine, but I was thinking we needed fields_excluded, but maybe not?

I guess my thinking was that if the user is handpicking every field they do want, they won't have much of a need for fields excluded?

**Comment by ssoroka** [comment]
It depends. if you want all fields except 1 or 2, but you also want to get any fields added from plugin updates, exclude would be a better fit. I'm not certain it matters that much for this, but that's the idea.

**Pull request merged**
