### PR TITLE
feature: introduces `diff` and `non_negative_diff` into BasicStats Aggregator plugin

### PR DESCRIPTION
**Pull request by m0**
post-processing counter metrics with influxdb's aggregate-functions leads to issues with grafana panels (e.g. see https://github.com/influxdata/influxdb/issues/6451#issuecomment-332994274, https://github.com/influxdata/influxdb/issues/8010). In many use cases only the aggregate/derivative data is of interest, therefore this PR makes the diff and non-negative-diff aggregate functions available in telegraf.

`diff`: provides the difference between last and current value
`non_non_negative_diff`: same as `diff`, but negative difference value is ignored

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by aurimasplu** [comment]
Any hopes if this will be in 1.11?

**Comment by otisg** [comment]
@danielnelson Any chance you could merge this?

**Comment by otisg** [comment]
@danielnelson Anything that anyone from the community could do to help get this merged?  AFAICT, this has all PR requirements satisfied and has 👍 x20 :)

**Comment by darinfisher** [comment]
See the [X.509 Certificate plugin](https://github.com/influxdata/telegraf/blob/release-1.15/plugins/inputs/x509_cert/README.md)

**Pull request merged**
