### PR TITLE
chore!: Exclude plugins not available on the target platform

### LINKED ISSUE #10162: By default telegraf.conf for Windows binaries contain Linux input plugin configurations
### Relevent telegraf.conf

```toml
# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states
  report_active = false


# Read metrics about disk usage by mount point
[[inputs.disk]]
  ## By default stats will be gathered for all mount points.
  ## Set mount_points will restrict the stats to only the specified mount points.
  # mount_points = ["/"]

  ## Ignore mount points by filesystem type.
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]


# Read metrics about disk IO by device
[[inputs.diskio]]
  ## By default, telegraf will gather stats for all devices including
  ## disk partitions.
  ## Setting devices will restrict the stats to the specified devices.
  # devices = ["sda", "sdb", "vd*"]
  ## Uncomment the following line if you need disk serial numbers.
  # skip_serial_number = false
  #
  ## On systems which support it, device metadata can be added in the form of
  ## tags.
  ## Currently only Linux is supported via udev properties. You can view
  ## available properties for a device by running:
  ## 'udevadm info -q property -n /dev/sda'
  ## Note: Most, but not all, udev properties can be accessed this way. Properties
  ## that are currently inaccessible include DEVTYPE, DEVNAME, and DEVPATH.
  # device_tags = ["ID_FS_TYPE", "ID_FS_USAGE"]
  #
  ## Using the same metadata source as device_tags, you can also customize the
  ## name of the device via templates.
  ## The 'name_templates' parameter is a list of templates to try and apply to
  ## the device. The template may contain variables in the form of '$PROPERTY' or
  ## '${PROPERTY}'. The first template which does not contain any variables not
  ## present for the device is used as the device name tag.
  ## The typical use case is for LVM volumes, to get the VG/LV name instead of
  ## the near-meaningless DM-0 name.
  # name_templates = ["$ID_FS_LABEL","$DM_VG_NAME/$DM_LV_NAME"]


# Get kernel statistics from /proc/stat
[[inputs.kernel]]
  # no configuration


# Read metrics about memory usage
[[inputs.mem]]
  # no configuration


# Get the number of processes and group them by status
[[inputs.processes]]
  # no configuration


# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration


# Read metrics about system load & uptime
[[inputs.system]]
  ## Uncomment to remove deprecated metrics.
  # fielddrop = ["uptime_format"]
```

### System info

1.20.4, Windows Server

### Docker

_No response_

### Steps to reproduce

1. download telegraf binaries from "https://dl.influxdata.com/telegraf/releases/telegraf-1.20.4_windows_amd64.zip" URL, which is mentioned on telegraf official documentation page, to Windows endpoint
2. extract files in the necessary location
3. open telegraf.conf file

### Expected behavior

By default "telegraf.conf" for Windows binaries should contain Windows input plugin configurations.

### Actual behavior

By default "telegraf.conf" for Windows binaries contain Linux input plugin configurations. they are mentioned in "Relevent telegraf.conf".

### Additional info

Till 1.20.x version, by default "telegraf.conf" for Windows binaries contained Windows input plugin configurations.

### PR DESCRIPTION
**Pull request by srebhan**
- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #10162 

This PR excludes plugins from being built if they are not available on the target platform (i.e OS and/or arch). This way, there will be no dysfunctional plugins (reporting errors at runtime) due to the platform, nor is the sample-config of those plugins included.

### CODE REVIEW

**Review by Hipska — APPROVED** [review]

**Comment by Hipska** [comment]
> ☺️ This pull request doesn't significantly change the Telegraf binary size (less than 1%)

Strange, I would have expected something. But I assume there will be a difference on the Windows build..

**Review by powersj — COMMENTED** [review]
I fundamentally agree, that builds of specific platforms should not have plugins that do not support those platforms. However, users who currently have `[[inputs.processes]]` and run on Windows currently get a warning that that plugin is not supported on their platform. Now, Telegraf will not start up and error out:

```s
# new behavior
$ ./telegraf.exe --config config.toml
2022-09-20T20:16:03Z E! [telegraf] Error running agent: Error loading config file config.toml: error parsing processes, Undefined but requested input: processes

# current behavior
$ ./telegraf.exe --config config.toml
2022-09-20T20:18:58Z I! Starting Telegraf 1.25.0-f803c6b4
2022-09-20T20:18:58Z I! Available plugins: 206 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2022-09-20T20:18:58Z I! Loaded inputs: processes
2022-09-20T20:18:58Z I! Loaded aggregators:
2022-09-20T20:18:58Z I! Loaded processors:
2022-09-20T20:18:58Z I! Loaded outputs: file
2022-09-20T20:18:58Z I! Tags enabled: host=DESKTOP-6BC121I
2022-09-20T20:18:58Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"DESKTOP-6BC121I", Flush Interval:10s
2022-09-20T20:18:58Z W! [inputs.processes] Current platform is not supported
2022-09-20T20:19:01Z I! [agent] Hang on, flushing any cached metrics before shutdown
2022-09-20T20:19:01Z I! [agent] Stopping running outputs
```

I have seen community members mention that they like having one config for Windows and Linux and that Telegraf just works with what is there, we seem to be in a bit of an inconstant state where that is the case in some places, but not all. For example, `ethtool`, `infiniband`, `processes`, `synproxy`, and `wireless` all have some warning with messages like this that would be removed.

We could merge this in a new minor release, not a patch release, with lots of docs about it, but I would still prefer this be a major version change.

**Comment by srebhan** [comment]
@powersj we could also provide a dummy hull in the `all/xyz.go` files, registering a dummy plugin with the warning . Furthermore, the users could use `--input-filter` to remove platform dependent plugins or we do not error out on unknown plugins but rather just print a warning in `config`...
Whatever we decide, it should a) be consistent and b) not force developers to write monkey-code. :-)

**Comment by powersj** [comment]
> we could also provide a dummy hull in the `all/xyz.go` files, registering a dummy plugin with the warning

I am good with this or we merge this for 2.0 only

> do not error out on unknown plugins but rather just print a warning in config...

This could lead to users missing a plugin not working due to a potential typo.

**Comment by srebhan** [comment]
Then I opt for the 2.0 pathway. ;-)

**Comment by powersj** [comment]
Per discussion closing this PR. Thanks for putting this up, but we agree the gain from this PR is limited, while possibly causing some breaking issues for users.

**Pull request closed without merging**
