### PR TITLE
Sudo support for ceph/varnish plugin && uint64 metrics

### PR DESCRIPTION
**Pull request by ljagiello**
In many default installations ceph and varnish binaries require root permissions or specific user permissions to actually gather metrics.

Although it's possible to instrumented system configuration to either run telegraf with root privileges or share the same user/permissions as measured software it's not a default setup.

In my opinion ability to run binary with `sudo` makes entire setup simpler without additional interaction.

My changes allow to use configuration like:
```
binary = "/usr/bin/sudo /usr/bin/varnishstat"
ceph_binary = "/usr/bin/sudo /usr/bin/ceph"
```

With a proper sudo configuration it will simplify amount of changes needed to collect metrics.

I've also changed type of varnish metrics. It was `int` but in varnish source code we can find all metrics are actually `uint64` (https://github.com/varnishcache/varnish-cache/blob/master/include/tbl/vsc_f_main.h)

I hit that issue with some metrics:
```
~# varnishstat -1 | grep -i MAIN.n_objectcore
MAIN.n_objectcore      18446744073709550877          .   objectcore structs made
```

### CODE REVIEW

**Comment by joshuaspence** [comment]
You don't need to run `varnishstat` as `root`... you just need the `telegraf` user to be in the `varnish` group.

**Comment by ljagiello** [comment]
That is true if you run varnish as non-privileged user.

**Comment by sparrc** [comment]
We need the uint64 change but I'm not sure about the sudo change. "sudo" is not exactly a part of the binary so it seems odd to put it there. If you're giving telegraf "sudo no password" privilege anyways, seems like you might as well run the entire service as sudo?

**Comment by ljagiello** [comment]
@sparrc you can limit access only for specific binaries - eg. only `/usr/bin/varnishstat` and you don't need to run entire telegraf process with `root` privileges. It's small flexible fix allow to run it that way if you want. Default is still the same as it was.

**Comment by sparrc** [comment]
it feels like a bit of a hack to me though because there are many other plugins where we fork off commands in telegraf, and this PR only deals with ceph & varnish.

Maybe you can give those binaries permission to execute using `setcap`?

**Pull request closed without merging**
