### PR TITLE
Update proxmox.go

### PR DESCRIPTION
**Pull request by er-pratyush**
### Required for all PRs:

- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Review by Jagularr — CHANGES_REQUESTED** [review]
The field 'Search' does not exist on the 'Data' struct. The field would need to be renamed from 'Searchdomain' for the build to succeed. however, can you add some context as to what this change is needed for?

**Comment by er-pratyush** [comment]
refer https://github.com/influxdata/telegraf/issues/8776
JSON data from Proxmox API returns key as data.search and the if condition in plugin was checking for Data.Searchdomain.
it seemed a quick fix and i made the change without looking at struct (mistake on my end). though later i realized that it was in line with data struct.

**Comment by easterism** [comment]
The call https://localhost:8006/api2/json/nodes/nodename/dns returns
 `{"data":{"search":"node.local","dns2":"8.8.8.8","dns1":"192.168.0.22"}}`
 Confirmed on PVE 6.2-4

**Comment by aantuness** [comment]
The call https://localhost:8006/api2/json/nodes/nodename/dns returns
{"data":{"search":"<name>.local","dns1":"8.8.8.8"}}
Confirmed on PVE 6.4-4

**Comment by connormckelvey** [comment]
I don't think there is anything wrong with the use of `Searchdomain` as it stands. if you look here: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/proxmox/structs.go#L65, Searchdomain has a JSON tag of `search`, which matches the JSON payload referenced above.

**Pull request closed without merging**
