### PR TITLE
feat(inputs.smart): Add additional SMART metrics that indicate/predict device failure

### PR DESCRIPTION
**Pull request by r4um**
Additional critical SMART metrics that are helpful in indicating/predicting device failure. From https://en.wikipedia.org/wiki/Self-Monitoring,_Analysis_and_Reporting_Technology#Known_ATA_S.M.A.R.T._attributes

### CODE REVIEW

**Comment by powersj** [comment]
I closed and re-opened the PR to get CI to kickoff

**Comment by powersj** [comment]
Thanks for the PR, looks like the tests will need an update for these additional fields.

**Comment by r4um** [comment]
> Thanks for the PR, looks like the tests will need an update for these additional fields.

Added. Thanks.

**Comment by powersj** [comment]
> CircleCI Pipeline — Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.

I heard back from CircleCI, namely, it sounds like this shows up when you have an account with CircleCI and either you are logged out if you use a username/password or if you have a GitHub OAuth login, need to disconnect and reconnect your account.

**Review by powersj — APPROVED** [review]

**Review by srebhan — APPROVED** [review]
Looks good to me. Nice work @r4um! Thanks for your contribution!

**Pull request merged**
