### PR TITLE
Add documentation on how to migrate to json_v2 parser

### PR DESCRIPTION
**Pull request by sspaink**
Added a section to the json_v2 README.md to help users understand the differences and move their old json parser configuration to the new json_v2 parser.

### CODE REVIEW

**Comment by sjwang90** [comment]
Here's an example of data that worked cleanly with v1 and its replacement with v2:

Baywheels bikshare data station status: https://gbfs.baywheels.com/gbfs/en/station_status.json

json v1:
```toml
[[inputs.http]]
  urls = ["https://gbfs.baywheels.com/gbfs/en/station_status.json"]
  data_format = "json"
  json_query = "data.stations"
  tag_keys = ["station_id"]
  json_string_fields = ["eightd_has_available_keys","legacy_id", "station_status"]
  json_time_key = "last_reported"
  json_time_format = "unix"
```

json v2:
```toml
[[inputs.http]]
    urls = ["https://gbfs.baywheels.com/gbfs/en/station_status.json"]
    data_format = "json_v2"
        [[inputs.http.json_v2]]
            [[inputs.http.json_v2.object]]
                path = "data.stations"
                tags = ["station_id"]
                timestamp_key = "last_reported"
                timestamp_format = "unix"
```

Both lead to this output (didn't include the whole thing)
```
http,host=MBP15-SWANG.local,station_id=548,url=https://gbfs.baywheels.com/gbfs/en/station_status.json eightd_has_available_keys=false,is_installed=1,is_renting=1,is_returning=1,legacy_id="548",num_bikes_available=19,num_bikes_disabled=0,num_docks_available=4,num_docks_disabled=0,num_ebikes_available=4,station_status="active" 1624633754000000000
http,host=MBP15-SWANG.local,station_id=549,url=https://gbfs.baywheels.com/gbfs/en/station_status.json eightd_has_available_keys=false,is_installed=1,is_renting=1,is_returning=1,legacy_id="549",num_bikes_available=21,num_bikes_disabled=0,num_docks_available=10,num_docks_disabled=0,num_ebikes_available=5,station_status="active" 1624635273000000000
```

**Comment by sjwang90** [comment]
i'll try to put togethers another example that requires processors to rename fields and convert data types in v1 but can be done really cleanly with v2

**Comment by sjwang90** [comment]
I'm thinking stuff is better for the blog I'm putting together: https://docs.google.com/document/d/1U_FdSkvN0quKLaNTGjH3b3AqZXNT9xQUcE9bN9F0p1A/edit?usp=sharing

@sspaink LMK know you think. I copied all your text in what I have so far.

**Comment by sspaink** [comment]
@sjwang90 I think adding this to a blog instead sounds like a good idea to me! looks good so far.

**Pull request closed without merging**
