### PR TITLE
Adding support for sourcetype in Splunkmetric serializer and standardizing tags for other metadata fields

### PR DESCRIPTION
**Pull request by dgshue**
### Required for all PRs:

[Bugfix/5503](https://github.com/influxdata/telegraf/issues/5503)

This will have impact on any previous config files as users will have to update their tags to reflect the new tag names.  Other than that it's pretty straight forward. Welcome any feedback, first time contributor so bare with me.

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
I think we should use the `sourcetype` tag but not rename any of the existing tags, this should fit in with the existing implementation without breaking anything.  Alternately, I could see these as being configurable options on the parser:
```
data_format = "splunkmetric"
splunkmetric_sourcetype_tag = "splunkmetric_sourcetype"
```

**Comment by ronnocol** [comment]
I'm with @danielnelson here, breaking the existing configuration syntax could be significantly painful for people who have large telegraf deployments. I think just adding sourcetype as an overridable field and generally adopting https://github.com/influxdata/telegraf/issues/3362 should be sufficient to resolve the issue without requiring config changes. 

There are Splunk based apps that are widely deployed that have the existing configuration schema included in them, I'm not saying it can't change, but it would first have to be deprecated before being removed.

**Comment by srebhan** [comment]
@dgshue any update?

**Comment by powersj** [comment]
Hi,

This PR has not been touched in a while and as a result I am going to close it. We are happy to review again once someone picks this back up with the suggested changes and rebased on master.

Thanks!

**Pull request closed without merging**
