### PR TITLE
[Docker Plugin] add server hostname for each docker measurements

### PR DESCRIPTION
**Pull request by aaronjheng**
### Required for all PRs:

- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by sparrc** [comment]
@aaronjheng I'm not sure this is a good idea. By default docker randomizes the name of the container, which means that every launched container will have a new name and the potential series cardinality is infinite.

When talking about influxdb, the database can't handle an infinite number of possible tag/value combinations.

You will need to workaround this using docker labels or other means.

**Comment by aaronjheng** [comment]
@sparrc Thanks for replying. What I want to record is the host of docker engine, not the container.

**Comment by sparrc** [comment]
I see, maybe I'm misunderstanding something then, is that different than the built-in telegraf `host` tag? Can you explain exactly what info.Name is? linking to some documentation would be extra helpful

**Comment by aaronjheng** [comment]
>  is that different than the built-in telegraf host tag?

Yes. In my use case, the telegraf program and the target docker-engine are in different servers. So the built-in telegraf host tag is not the docker-engine's host.

>  Can you explain exactly what info.Name is?

I can't find any specific description about this **Info** struct. But after digging some source code. I find this [https://github.com/docker/docker/blob/master/daemon/info.go](https://github.com/docker/docker/blob/master/daemon/info.go):
```
hostname := ""
if hn, err := os.Hostname(); err != nil {
    logrus.Warnf("Could not get hostname: %v", err)
} else {
    hostname = hn
}
v.Name = hostname
```
So, I assume that **info.Name** means the hostname of the docker engine's host.

**Comment by aaronjheng** [comment]
Ping

**Comment by sparrc** [comment]
Looks good to me, but can you make the tag more descriptive? I'd suggest `docker_engine_host` but I'll leave it up to your judgement

**Comment by aaronjheng** [comment]
Sounds great!  In docker context, `engine_host` is enough.

**Pull request merged**
