### PR TITLE
AWS SQS input plugin

### LINKED ISSUE #6115: Input plugin to subscribe to SQS for metrics
## Feature Request

Similar to the GCP pub/sub plugin that can receive metrics, a similar plugin for AWS SQS.  It should be able to work with any of the Telegraf input data formats.

### PR DESCRIPTION
**Pull request by gordonbondon**
Fixes #6115. 
An alternative approach to #7725 using service plugin.

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Review by ssoroka — APPROVED** [review]
all in all really solid. Thanks for this!

**Comment by ssoroka** [comment]
Would be good to have some unit tests on this to protect it from future breaking changes.

**Review by ssoroka — CHANGES_REQUESTED** [review]
going to change this to blocking until we get some unit tests

**Comment by sspaink** [comment]
@gordonbondon are you still interested on working on this PR? Will you be able to add some tests?

**Comment by gordonbondon** [comment]
@sspaink hi! Sorry, unfortunately won't be able to contribute further in near future.

**Comment by MyaLongmire** [comment]
@jacksgt are you interested in reopening your pr or giving this another go?

**Pull request closed without merging**
