### PR TITLE
Fix float32 negative value/ add validation for range limit

### PR DESCRIPTION
**Pull request by garciaolais**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

- Fix [7317](https://github.com/influxdata/telegraf/issues/7317)
- Add test for negative float32 values
- Updated Readme inside code

--------------------------------------

- Fix [7227](https://github.com/influxdata/telegraf/issues/7227)
- add validation for range limit

### CODE REVIEW

**Comment by sensor-freak** [comment]
The proposed change modifies the conversion of 16 bit values only, However, for 32 bit and 64 bit values the behaviour remains the opposite. This seems to me unexpected behaviour.

It would be better if all cases are handled equally.

**Comment by srebhan** [comment]
@garciaolais: Can you please resolve the merge conflict and also fix 32 and 64-bit versions!?

**Comment by garciaolais** [comment]
Hi @srebhan I need to verify the new terms, maybe this change its not valid anymore.

**Comment by srebhan** [comment]
@garciaolais: Sure. Just compared your code to what is in master and it looks _very_ similar. Just let me know on what you think!

**Comment by garciaolais** [comment]
@srebhan: in a few days I Will have free time, I hope check this issue very soon 👍

**Comment by srebhan** [comment]
@garciaolais any chance you find some time to look at this?

**Comment by garciaolais** [comment]
Hi @srebhan , Tomorrow I have a free weekend, I will working in this

**Comment by garciaolais** [comment]
Hi @srebhan  

Today I checked this and its seems that the https://github.com/influxdata/telegraf/pull/7869 solved the issue https://github.com/influxdata/telegraf/issues/7317 

For this reason, I will close this PR 

Thanks!

**Pull request closed without merging**
