### PR TITLE
Cleanup of Exec Inputs documentation - redux

### PR DESCRIPTION
**Pull request by marknmel**
Hi @sparrc

(Sorry for the noise - new pr)

Please find some improvements to readability including the \n for the exec/telegraf line-protocol input.

I hope you (and others) find it easier to read.

/Mark

### CODE REVIEW

**Comment by marknmel** [comment]
@sparrc  - circleci blew up here.  How can I kick this off again?

**Comment by sparrc** [comment]
You can do a dummy amend commit and force push to your branch

**Comment by sparrc** [comment]
@marknmel thanks but _amend_ was important, I didn't want a dummy commit, you should have done:

```
git commit --amend
<do nothing>
git push -f
```

can you now squash these two commits like this?

```
git rebase HEAD~2
git push -f origin patch-1
```

**Comment by marknmel** [comment]
Sorry @sparrc . I've never done this before (and apparently I suck at it) :-(
I've just tried again.  Feel free to tell me I'm a dolt and have buggered it up again.

**Comment by sparrc** [comment]
no problem @marknmel! It looks like now you've amended the 2nd commit, but you need to squash the two commits together, I think if you just run these commands it should do it:

git rebase HEAD~2
git push -f origin patch-1

ie, your PR should just have one commit in it

**Comment by marknmel** [comment]
I think I got there somehow... but I'm certainly not proficient.  Hopefully I can get better at this. Thanks for your patience @sparrc

**Comment by sparrc** [comment]
perfect, thanks!

**Pull request closed without merging**
