### PR TITLE
change uri scheme for default RavenDB configuration (#10765)

### PR DESCRIPTION
**Pull request by ml054**
Minor: Change default URI scheme from https to http. As default server uses http, not https. 

### Required for all PRs:

- [x] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

### CODE REVIEW

**Comment by powersj** [comment]
Can you please point to a document stating that they do not use https? I would be shocked if their cloud product did not use https. While their [docker image](https://hub.docker.com/r/ravendb/ravendb) may not use https by default I would prefer to keep this set to the more secure option.

**Comment by ml054** [comment]
Hi, @powersj 

We use 8080 by default for unsecured servers (see https://ravendb.net/docs/article-page/4.2/csharp/start/installation/setup-wizard#unsecure-setup)
and 4433 for https. 

I created this PR because currently we mix https with default http port (8080).

**Comment by powersj** [comment]
> Hi, @powersj
> 
> We use 8080 by default for unsecured servers (see https://ravendb.net/docs/article-page/4.2/csharp/start/installation/setup-wizard#unsecure-setup) and 4433 for https.
> 
> I created this PR because currently we mix https with default http port (8080).

Awesome - thanks for the response!

I would prefer that the docs show how to connect securely to a server by default (e.g. https + 443) and a  comment is added about using http for local development. Something like the following

```toml
    ## Node URL and port that RavenDB is listening on. By default,
    ## attempts to connect securely over HTTPS, however, if the user
    ## is running a local unsecure development cluster users can use
    ## HTTP via a URL like "http://localhost:8080"
    url = "https://localhost:443"
```

**Comment by ml054** [comment]
@powersj This is brilliant idea. Will implement your suggestions and push changes. Thanks for suggestion!

**Comment by ml054** [comment]
I'm ready for review - applied your suggestions

**Review by powersj — APPROVED** [review]

**Comment by powersj** [comment]
Thank you!

**Pull request merged**
