### PR TITLE
docs(processors.ifname): Document better agent tag name

### PR DESCRIPTION
**Pull request by Hipska**
# Required for all PRs

- [x] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

Related to #8011 and #4413

### CODE REVIEW

**Review by powersj — COMMENTED** [review]
@Hipska,

As you know the config should show the default, and you are essentially changing the default if someone takes the default config and modifies it. I don't think we want to do this. If you want to document (i.e. add a comment) about using "source" instead of agent, I think that is cool, but not changing the default.

Thoughts?

**Comment by Hipska** [comment]
Well, the default isn't actually changed (it is still `agent`), so current users aren't affected. But as discussed in the original #8011, that default doesn't make much sense as most (if not, all) users need to change it anyway.


FYI, I'm planning to make a new processor which will make the ifname processor deprecated as it will have the same functionality + more.

**Comment by powersj** [comment]
@Hipska,

This will create confusion. The sample config option no longer shows the default value. The uncommented value is not the default.

What I was trying to say above is that we do have users who use the `telegraf config` command and/or the sample config to generate their config. They would pick up this change unconsciously, they would not be aware of the change, and it would cause confusion.

**Comment by Hipska** [comment]
You prefer to have it the other way round? (having `example: ...` in the comments)

**Comment by powersj** [comment]
yes

**Review by powersj — APPROVED** [review]

**Review by srebhan — APPROVED** [review]
Thanks @Hipska!

**Pull request merged**
