### PR TITLE
Adapt the MySQL input plugin to handle specific MariaDB implementation of user statistics tables

### PR DESCRIPTION
**Pull request by etiennecarriere**
Linked to https://github.com/influxdata/telegraf/issues/2910
### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by etiennecarriere** [comment]
I have a test failure on something that is not related to mysql (udplistener). Could you relaunch the test ?

**Comment by danielnelson** [comment]
Now that I see the code changes, I think my original advice was bad and we should adjust the way we address this.

It looks like we have only a couple fields which are not shared, as well as a few types which are different.  What if we stick with the old `select *` query and when we Scan the rows we pull out the columns we know are there, and then try to pull the optional two columns one at a time.  If there is an error we ignore it.  We can change the target values to be pointers and if they are nil they won't be added as fields when you call AddFields.

The second problem is the types, we can't switch the type to a float because the type change will cause an error for users of Percona databases in InfluxDB.  Are we able to detect this when we Scan?  Maybe we can try to scan into an int and fallback to a float?

**Comment by HristoMohamed** [comment]
Any update on this?

**Comment by etiennecarriere** [comment]
I am not a Go expert and I don't know how to do it as @danielnelson says as i don't see how to get a column by its name and not by its position in the result of a request. 
So currently, on my production servers, I work with this patched version .

**Pull request closed without merging**
