### PR TITLE
Wavefront output plugin

### PR DESCRIPTION
**Pull request by puckpuck**
### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

This is a new output plugin for Wavefront.  Wavefront is a SaaS for metrics.  You can learn more about Wavefront on their website: https://www.wavefront.com  

We have been using this output plugin for multiple months with a few Wavefront customers yielding great results, and are ready to release it to the community so it can be part of the main telegraf package.

### CODE REVIEW

**Comment by mspinassi** [comment]
+1 for getting this plugin merged.

**Comment by connorgorman** [comment]
+1. Any traction on this PR?

**Comment by puckpuck** [comment]
Can we get an update on status on this PR, will it be a candidate for the next release?  I made a few small changes to resolve all outstanding conflicts.

**Comment by danielnelson** [comment]
@puckpuck I don't have this scheduled for the next release at this time.

**Comment by connorgorman** [comment]
@danielnelson Any reason why not to include it? Are you waiting for go plugins in 1.8?

**Comment by danielnelson** [comment]
It has more to do with the prioritization of issues and pull requests.

**Comment by connorgorman** [comment]
@puckpuck Can you add a silent mode for the wavefront plugin? Because wavefront only accepts numeric values, any plugin that sends a mixture of numeric values and non-numeric values ends up blowing up the log

**Comment by puckpuck** [comment]
Trying to get an understanding on what we need to do in order to get this PR included into 1.4?  Would closing it and resubmitting as a single commit help?

**Comment by danielnelson** [comment]
@puckpuck Don't worry about the number of commits, I always merge pull requests using "squash and merge".  I do think the test failure will clear up if you rebase against master.

@nhaugo Have we arranged for a wavefront account so we can test?

**Comment by puckpuck** [comment]
@danielnelson and @nhaugo I created a Wavefront trial account a while ago but it was never activated.  I can resend the link to the email we have.

As for rebasing, I tried, and I believe I may have entered git hell :(.  My original fork was based on another fork which has since diverged away from a full fork, and rebase from upstream keeps giving me errors that I need to merge, but merge is also not working o_O.  Another option is I throw away my current repo, and start anew with a fork from influxdata/telegraf instead, but that would require a new PR.

**Comment by danielnelson** [comment]
Rebasing might be easier if you just squash your branch into one commit, especially since there is very little overlapping code.  You can also force push a new branch so long as you use the same branch name on your remote.

**Comment by puckpuck** [comment]
@danielnelson I've tried, and get a bunch of merge conflicts, even on files I never touched.  It's not difficult for me to trash the repo and fork again, re-add my changes and submit a new PR

**Comment by danielnelson** [comment]
ok

**Pull request closed without merging**
