### PR TITLE
fix leap_status value in chrony input plugin

### PR DESCRIPTION
**Pull request by m4ce**
see #1982

### CODE REVIEW

**Comment by sparrc** [comment]
please fix the unit tests

**Comment by m4ce** [comment]
@sparrc, I must be missing something here but I don't see how my change would affect the output expected by the unit test? I see leap_status is expected to be set to "normal" and that's what it is set to. If you could point me out to the reason, I will be happy to fix it.

**Comment by sparrc** [comment]
@m4ce are you able to run the unit tests locally? your changes appear to be changing some exissting metrics, I don't have time to dig too deeply but I think if you can run the unit tests you can figure out what's changed

**Comment by m4ce** [comment]
@sparrc, no worries, I had a better look and the problem is the reference_id field. I've now commited a fix for it, let's wait for the unit test to finish.

**Comment by sparrc** [comment]
@m4ce can you add unit tests to verify that `Leap Status: Not synchronised` is getting represented properly now?

**Comment by m4ce** [comment]
@sparrc i've done that, i hope it looks good now.

**Pull request merged**
