### PR TITLE
Docker log track message offset

### PR DESCRIPTION
**Pull request by i-prudnikov**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

This PR comes from #7068, as discussed with @danielnelson, we agreed to split #7068 to smaller parts. This the second part - track message timestamps. This allows to resume from particular message, and prevent delivering messages that already delivered. This feature inspired by fluentd.

### CODE REVIEW

**Comment by i-prudnikov** [comment]
Hello @danielnelson, is there any progress with this? Could you please review proposed change?

**Comment by sjwang90** [comment]
Thanks @i-prudnikov! Sorry for the delay but we'll get someone to review this soon.

**Comment by i-prudnikov** [comment]
> Thanks @i-prudnikov! Sorry for the delay but we'll get someone to review this soon.

Sure, I can update the branch to resolve the conflicts, I guess the conflicts here is because I pushed changes almost 1 year ago.

**Comment by reimda** [comment]
Hi @i-prudnikov, thanks for the PR.  This is closely related to #8352.  There are a few other plugins that also need to store state when running and read state on startup. Because it's a common need, we'd eventually like to implement a lot of this in the telegraf agent itself, not individually in each plugin.  If each plugin stores its own state, the user would have multiple state files on disk. There would also be settings for each plugin like this PR's offset_storage_path, and the user would need to make sure to set all of them correctly.

Another difficulty is that users can start multiple instances of plugins.  If they start two instances of docker_log with the default offset_storage_path, both plugin instances will overwrite the same file.  The user will need to be careful to put unique values of offset_storage_path in each instance.  I'd like to have the agent take care of this for the plugins, but that requires a way to uniquely identify plugin instances, which is something telegraf doesn't have yet.

Let me bring this up with others in the dev team tomorrow.  I expect we'll either increase priority of implementing agent changes to save state plugins or decide to take this PR without much change and then plan to switch docker_log to save state through the agent in the future.

**Comment by i-prudnikov** [comment]
Hi @reimda, thank you very much for explanations. The issues you've mentioned especially about several instances of the plugin do make sense. I have another PR for this input that I'm going to push soon, should I mention you to review it?

**Comment by reimda** [comment]
Yes, I can review another docker_log PR and a mention is a good way to remind me.

**Comment by reimda** [comment]
> Let me bring this up with others in the dev team tomorrow. I expect we'll either increase priority of implementing agent changes to save state plugins or decide to take this PR without much change and then plan to switch docker_log to save state through the agent in the future.

Just an update: There are two ongoing efforts to add a state interface for plugins.  One is https://github.com/HRI-EU/telegraf/tree/state-persistance and the other isn't public yet.  When we choose one and merge it I expect #8352 will be closed.  To be notified when that happens, you can subscribe to notifications for that issue.

**Comment by jhychan** [comment]
any progress on this feature?

**Comment by powersj** [comment]
https://github.com/influxdata/telegraf/pull/9476 is getting some design work and attention. Because it will mean an overhaul to this PR and this PR is dependent on it getting landed I am going to close this PR for now. Thanks!

**Pull request closed without merging**
