### PR TITLE
Apstra AOS input plugin

### PR DESCRIPTION
**Pull request by huttmf**
The [AOS](https://www.apstra.com/products/aos-overview/) input plugin parses protobuf messages sent by the AOS server and formats them as time series database metrics, e.g., Influxdb. These messages contain telemetry data that AOS generates and consist of performance monitoring (perfmon), alerts and events.

### CODE REVIEW

**Comment by danielnelson** [comment]
I just flipped through this PR quickly, but these files will be an issue due to their license.
```
 // Copyright 2014-present, Apstra, Inc. All rights reserved.
￼ //
￼ // This source code is licensed under End User License Agreement found in the
￼ // LICENSE file at http://www.apstra.com/community/eula
```

All code used by Telegraf will need to be license compatible with the [MIT License](https://github.com/influxdata/telegraf/blob/master/LICENSE).

**Comment by huttmf** [comment]
Ok - I will look into removing the EULA license text.
Thanks,
Mike

**Comment by huttmf** [comment]
I have removed the EULA text and switched to the MIT license.

**Comment by Ragsboss** [comment]
Hi @danielnelson thank you for looking into this PR. Would you mind advising us on best possible way to merge this PR? We strongly believe in open data frameworks like Telegraf and chose this particular framework after evaluating few other choices. We'd like to merge this PR within the next 2 weeks, to align with [AOS](https://www.apstra.com/products/aos-overview/) release timelines. We'd greatly appreciate any input and help with PR review we can get.

**Comment by danielnelson** [comment]
@Ragsboss I don't have this scheduled for review that soon, I expect it will take longer than this unless we shift focus.  The next Telegraf feature release would be in December as well.  Let's get you in contact with @sjwang90 for scheduling.

**Comment by sjwang90** [comment]
@Ragsboss Our next feature release would be early December. Would an early March Telegraf feature release for this plugin fit in with your AOS release timeline?

**Comment by Ragsboss** [comment]
Hi Daniel and Samantha thank you for your response. The release we want on our side is targeted for Jan 6 2020 GA.

I'd request for this to go in before that if possible. It's a relatively small plugin. If this is not possible please advise our best alternative options?

Sent from my iPhone
Email maybe terse

On Nov 7, 2019, at 3:03 PM, Samantha Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


@Ragsboss<https://github.com/Ragsboss> Our next feature release would be early December. Would an early March Telegraf feature release for this plugin fit in with your AOS release timeline?

**Comment by sjwang90** [comment]
Good to know. We have our next feature release pretty full right now. I will prioritize it for 1.14 in the first quarter but let you know if we can get it in sooner or can figure out any other options.

**Comment by huttmf** [comment]
HI @sjwang90 we've made a few additions to this PR to support our latest release of AOS 3.2. Just wanted to see if this is still scheduled to be reviewed for the 1.14 release. Thx Mike

**Comment by sjwang90** [comment]
Hi @huttmf, sorry for the delay but we're going to have to push this to 1.15 due to other reviews and backlog items we are getting in for 1.14.  We will review this as soon as the work with 1.14 is complete. 
 Thanks for your patience.

**Comment by huttmf** [comment]
Ok. Please let us know if there's anything we can do on our end to ensure this gets into 1.15.
Thanks

**Comment by sjwang90** [comment]
Hi @huttmf and @Ragsboss, we have recently merged an [Execd Go Shim](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/execd/shim) to be used with the `inputs.execd` plugin.  We believe your Apstra AOS plugin would be a great use case for this. 

Would you mind taking a look at going down this route? This would really expedite the review and integration process of getting your plugin working with Telegraf sooner than later.

**Comment by huttmf** [comment]
Hi @sjwang90 this sounds interesting - we will take a look. Do you know if we can expect the same performance as building the plugin as part of telegraf itself?

**Comment by danielnelson** [comment]
There is a bit of overhead but it should be minor.

**Comment by sjwang90** [comment]
Removing the 1.15 milestone for now.  We are making some improvements on our execd Go shim and will let you know when you can try this out with the new improvements and any questions using this as an external plugin.

**Comment by huttmf** [comment]
Hi @sjwang90 I just wanted to check to see if the shim improvements were ready for testing yet?

**Comment by sjwang90** [comment]
The [execd Go shim](https://github.com/influxdata/telegraf/tree/master/plugins/common/shim) is ready for use.  Here is some more information about [external plugins](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md).

Please try it out and let us know if you have any questions.

**Comment by huttmf** [comment]
Hi - I'm testing our plugin using the execd input plugin. The aos plugin is a service plugin . Previously we were seeing data being processed continuously - i.e., the influx buffer_size was always > 0. Now it appears there is a 30s gap where the buffer_size is 0 - see attached image. I was hoping to get more insight into this 30s gap and if there is any way to reduce this. Thx.

image

**Comment by huttmf** [comment]
Hi @sjwang90 do you have any recommendations on the agent interval for external plugins. The values I'm currently testing with are

**Comment by sjwang90** [comment]
@ssoroka Do you think you could help out with potentially why @huttmf is getting a 30s gap from his external plugin

**Comment by sspaink** [comment]
Sounds like moving to an external plugin was the right decision for this plugin, closing as there doesn't seem to be any more work to be done here.

**Pull request closed without merging**
