### PR TITLE
docs(inputs.modbus): README changes regarding request.tags

### LINKED ISSUE #10965: inputs.modbus.request.tags give error cannot unmarshal TOML array table into map
### Relevant telegraf.conf

```toml
[[inputs.modbus]]

  name = "powermeter"

  slave_id = 1

  timeout = "1s"

  controller = "tcp://x.x.x.x:502"

  #interval = "1s"

  configuration_type = "request"

  [[inputs.modbus.request]]
    slave_id = 8
    byte_order = "ABCD"
    register = "holding"
    fields = [
      { address=19841, measurement= "Total positive active energy (kwh)", name="energy phase 1", type="UINT32", scale=1.0 },
      { address=21889, measurement= "Total positive active energy (kwh)", name="energy phase 2", type="UINT32", scale=1.0 },
      { address=23937, measurement= "Total positive active energy (kwh)", name="energy phase 3", type="UINT32", scale=1.0 },

      { address=18476, measurement= "Total active power (W)", name="power phase 1", type="INT32", scale=1.0},
      { address=20524, measurement= "Total active power (W)", name="power phase 2", type="INT32", scale=1.0 },
      { address=22572, measurement= "Total active power (W)", name="power phase 3", type="INT32", scale=1.0 }
    ]
    [[inputs.modbus.request.tags]]
       location = "floor 1"
```

### Logs from Telegraf

```text
[telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.d/input/input-main-busbars.conf: error parsing modbus, line 30: (modbus.requestDefinition.Tags) cannot unmarshal TOML array table into map[string]string (need slice)
```

### System info

Telegraf 1.22.1, modbus plugin

### Docker

_No response_

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

I expect Telegraf to send the tags in the output (for influxdb)

### Actual behavior

Error message below:

[telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.d/input/input-main-busbars.conf: error parsing modbus, line 30: (modbus.requestDefinition.Tags) cannot unmarshal TOML array table into map[string]string (need slice)

### Additional info

I use the Telegraf modbus plugin with the "Per request definition" (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/modbus).

It seems that the modbus plugin has trouble parsing the "tags" section of the config as specify in the doc.

### PR DESCRIPTION
**Pull request by mrxaxen**
# Required for all PRs

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

Just came across the same problem, hoping it'll save a couple of minutes for others in the future.
resolves #10965

### CODE REVIEW

**Review by srebhan — DISMISSED** [review]
Looks good to me. Thanks for fixing this @mrxaxen! Much appreciated!

**Review by srebhan — COMMENTED** [review]
Hey @mrxaxen thanks for fixing this issue. Can you please change the erroneous sections also in the `sample*.conf` and then run `make docs`!?

The background is that the `sample*.conf` files are embedded into the README.md which would override your changes...

**Comment by mrxaxen** [comment]
Hey @srebhan! Changed the configuration files (found 2, hoping that's all). Not sure about the CI runs, since's one's reporting on the first commit's message which was accepted last time, and one's reporting on `statsd` which i have not laid my hands on. Anyways, this is my very first PR here, i'm not really familiar with conventional commits either so pointers are appriciated.

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks @mrxaxen for the fix!

**Review by powersj — APPROVED** [review]

**Pull request merged**
