### PR TITLE
Make HAProxy metric gathering automatic

### PR DESCRIPTION
**Pull request by G-regL**
Let the fields of the CSV dictate which metrics are returned by the plugin.

Also, made the plugin aggregate the server statuses for active/backup up/down/maint/drain/other in their respective BACKEND line.

### CODE REVIEW

**Comment by G-regL** [comment]
@sparrc I deleted my other PR #1170 because I wasn't sure how to rebase. I re-forked the repo, made the changes again and run `go fmt ./...` in my local copy, but it doesn't seem to fix anything when I push the changes.

I'm new to GitHub so still learning the ropes, but any idea what I'm doing wrong here?

**Comment by sparrc** [comment]
It looks like you've changed some of the field names. You need to create a mapping of csv columns to field names to lookup for each csv column (such as `active_servers`, `backup_servers`, `http_response.1xx`, etc)

**Comment by G-regL** [comment]
@sparrc I have indeed changed some field names, but I'm not sure what you mean by having a mapping of CSV columns to field names. The field names *are* the CSV column names, which wasn't the case before (there's no column in the CSV called `active_servers`, or `backup_servers`).

**Comment by sparrc** [comment]
those columns were mapped to more user-friendly names.

you are changing the fields of the plugin, which will break queries for existing users of this plugin.

**Comment by G-regL** [comment]
Yes, but only a couple of columns had friendly names. The others still had relatively cryptic ones, as they have in the CSV.
Would it be better for me to restore the columns I changed and replace the rest of the column names with friendlies?

**Comment by sparrc** [comment]
I would say either keep the names the same as the current behavior, or change them all to friendly names.

If you are changing them all, you'll need to write up a release note and put it in the CHANGELOG.

**Comment by sparrc** [comment]
I'd also appreciate it a lot if you could writeup a README for this plugin :)

**Comment by G-regL** [comment]
Noted, I think I'll change them all, nesting related ones for easy grouping.

Sure, I think I can probably swing the README, in which I'll be able to add the CSV column <> field name mapping details.

**Comment by sparrc** [comment]
great, thanks!

**Comment by lunetics** [comment]
any update on this?

**Comment by sparrc** [comment]
closing for lack of updates, please feel free to open a new PR though

**Pull request closed without merging**
