### PR TITLE
chore: update influxdb-observability to fix statsd bug

### LINKED ISSUE #12363: opentelemetry plugin doesnt work with statsd timing type
### Relevant telegraf.conf

```toml
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Log at debug level.
  debug = true
  quiet = false
[[inputs.statsd]]
   protocol = "udp"
   max_tcp_connections = 250
   tcp_keep_alive = false
   service_address = ":8125"
   delete_gauges = true
   delete_counters = true
   delete_sets = true
   delete_timings = true
#   percentiles = [50.0, 90.0, 99.0, 99.9, 99.95, 100.0]
   metric_separator = "_"
#   parse_data_dog_tags = false
   allowed_pending_messages = 10000
   percentile_limit = 1000
[[outputs.opentelemetry]]
   service_address = "localhost:443"
   insecure_skip_verify = true
   compression = "gzip"
```

### Logs from Telegraf

```text
2022-12-08T20:35:01Z D! [outputs.opentelemetry] skipping unrecognized histogram field field="upper" value=%!q(float64=10)
2022-12-08T20:35:01Z D! [outputs.opentelemetry] skipping unrecognized histogram field field="lower" value=%!q(float64=10)
test_service_stage_metrics_biz_success_v4,host=povilas-thinkpad,hostname=$HOSTNAME,metric_type=timing,namespace=$NAMESPACE,nodename=$NODENAME,type=app sum=100,upper=10,lower=10,count=10i,mean=10,median=10,stddev=0 1670531700000000000
2022-12-08T20:35:01Z W! [outputs.opentelemetry] failed to add point: unsupported histogram count value type int64
2022-12-08T20:35:01Z D! [outputs.file] Wrote batch of 1 metrics in 213.753µs
```

### System info

Linux

### Docker

_No response_

### Steps to reproduce

1. Run telegraf with config
2. Test with ` echo "test.service.stage.metrics.biz.success_v4:10|ms|@0.1" | nc -w 1 -u localhost 8125`

### Expected behavior

sends all the data to opentelemetry endpoint

### Actual behavior

throws errors; debug logs indicate drops data.

### Additional info

I've investigate this issue and it's:

1. Statsd timings are aggregated wtih mean, median, sum, upper, lower, etc, and are set as `untyped` metric type
_>https://github.com/influxdata/telegraf/blob/master/plugins/inputs/statsd/statsd.go#L244-L265

2. Opentelemetry plugin when resolving the untyped metric sees that it has `count` field and assumes Prometheus Histogram

https://github.com/influxdata/influxdb-observability/blob/main/influx2otel/metrics_telegraf_prometheus_v1.go#L52-L56

Because timing type uses special `metric_type=timing` tag we can assume that it's timing summary and convert everything to gauges.

I've opened PR in the library -> https://github.com/influxdata/influxdb-observability/pull/136

### PR DESCRIPTION
**Pull request by jacobmarble**
fixes #12363

@povilasv can you confirm that this fixes #12363 ?

# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

### CODE REVIEW

**Comment by oded-dd** [comment]
Hey. Any update on that?

**Comment by jacobmarble** [comment]
I don't have permission to merge. I'll slack @powersj .

**Review by powersj — APPROVED** [review]

**Comment by sri-shetty** [comment]
@jacobmarble @powersj - It would be great to see a new build of a telegraf release with this statsd fix. Do we have an ETA?

**Comment by powersj** [comment]
You can use the nightly builds for now. v1.25.1 will come in the next week. Originally scheduled yesterday, but delayed due to some [CircleCI fall out](https://circleci.com/blog/january-4-2023-security-alert/)

**Comment by powersj** [comment]
The release is still pending some updates due to the CircleCI incident. I am hoping for early next week, but still uncertain.

**Comment by sri-shetty** [comment]
Thank you @powersj  @srebhan for the v1.25.1 release. The official helm chart (and the docker image) for v1.25.1 hasn't been made available. Looking at alpine, it still points to 1.25.0-alpine. (1) [Link to docker image](https://hub.docker.com/_/telegraf/tags?page=1&name=alpine) (2) [Link to helm chart](https://github.com/influxdata/helm-charts/tree/master/charts/telegraf). Could you please let us know when could we see the officially docker image and the helm charts.

**Comment by powersj** [comment]
We are waiting to release new docker images on some final updates on our backend and for https://github.com/influxdata/influxdata-docker/pull/666 to land. Once both of those things happen we will put up PRs for new DockerHub images. Once those are merged and available we can then update the helm charts.

I would suggest watching that PR above, and once you see it land things should roll from there.

**Comment by powersj** [comment]
Are you sure? This is the commit directly into the release-1.25 branch:

https://github.com/influxdata/telegraf/commit/345eb6930acc18071619e7c79526f5aa95877059

It is not in the release notes because it did not follow our automated format for deps.

**Pull request merged**
