### PR TITLE
first pass for adding more couchbase stats

### PR DESCRIPTION
**Pull request by iskrenpp**
This is first pass/attempt to start adding more couchbase input plugin stats.

@sparrc  please let me know if I can assist with anything else and thank you for your help. 
On average how soon do you think you can lend a hand?

 With PR change  I can compile but no stats are getting reported back

### CODE REVIEW

**Comment by iskrenpp** [comment]
@sparrc they exist as they are from a  monitoring best practices doc that Couchbase support has provided - some might be per node only some per bucket only - I will do some more digging on that if that helps

**Comment by sparrc** [comment]
I don't think these are part of the bucket stats, can you link to documentation?

**Comment by iskrenpp** [comment]
https://github.com/membase/ep-engine/blob/master/docs/stats.org

**Comment by sparrc** [comment]
that is for the couchbase ep-engine, it's not the same as a bucket stat.

I'm going to close this PR, but feel free to resubmit if you can figure out the necessary query to get those stats.

**Pull request closed without merging**
