### PR TITLE
Allow win_perf_counter input plugin to have no instances present. Fixes #7281

### LINKED ISSUE #7281: win_perf_counter input plugin - issue when instances are not always present
### Relevant telegraf.conf:

```toml
[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "RemoteFX Network"
    Instances = ["*"]
    Counters = [
      "Total Received Bytes",
    ]
    Measurement = "remotefx.network"
    IncludeTotal = false
```

### System info:

Any version of windows.
Any version of telegraf.

### Steps to reproduce:

1. Make sure there are no Remote Desktop connection active to the machine where telegraf is running.
2. Watch telegraf.log filling up with the errors about the missing data:
```
2020-04-02T13:05:05Z E! [inputs.win_perf_counters] Error in plugin: No data to return.
2020-04-02T13:05:10Z E! [inputs.win_perf_counters] Error in plugin: No data to return.
```
3. Once Remote Desktop session is started, logging stops.

### Expected behaviour:

I'd like to be able to ignore these symptoms. As that might not be desired for all users of the plugin, I'd like to make it configurable option.
The best would be have it as an option on the individual measurement level, but having it at plugin level would also work.

### Actual behaviour:

No way to ignore missing instances, configurable or not.

### Additional info:
The way I would like to have that configured:

```toml
[[inputs.win_perf_counters]]
  # Possible solution: have that as a configuration option on the plugin level, default to false.
  IgnoreMissingInstance = true
  [[inputs.win_perf_counters.object]]
    ObjectName = "RemoteFX Network"
    Instances = ["*"]
    Counters = [
      "Total Received Bytes",
    ]
    Measurement = "remotefx.network"
    IncludeTotal = false
    # Preferred solution: be able to configure that on the measurement level.
    IgnoreMissingInstance = true
```

I have PR ready that allows plugin-wide configuration (unfortunately, I couldn't figure out proper testing for it).

### PR DESCRIPTION
**Pull request by bielawb**
This pull request is my attempt to fix issue #7281 with plugin-wide configuration option.
I've tested that on the live system, but I couldn't create relevant unit tests - it looks to me that similar condition (PDH_NO_DATA) is handled, but in the different place.

I decided to share this PR as-is with assumption that someone more knowledgeable could help with writing tests. Also creating PR early could help fix the code quality (first time writing anything in go...).

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielboth** [comment]
Hi @sjwang90, I'm running into the issue this PR fixes too (this mainly pops up when trying to monitor for a process that doesn't exist (yet)). What is required to get this fix merged?

**Comment by sjwang90** [comment]
We still need tests before it can be reviewed. @danielboth would you be able to help @bielawb on the tests for this PR?

**Comment by danielboth** [comment]
I'm afraid my knowledge of go is not sufficient to do that at the moment @sjwang90. Is there some documentation available on how to get going / can you give some hints in the right direction?

**Comment by sspaink** [comment]
Thank you @bielawb for starting this, it seemed your pull request was stuck due to lack of tests so I took your work and extended it in this PR: https://github.com/influxdata/telegraf/pull/10535

@danielboth or @bielawb if you have time to test out the changes in the new PR it would be greatly appreciated! I will work with other reviewers to address any comments. I am going to close this PR in favor of https://github.com/influxdata/telegraf/pull/10535

**Pull request closed without merging**
