### PR TITLE
add sqs as possible input source

### PR DESCRIPTION
**Pull request by jaecktec**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

moved PR to branch, so I can work on other things
old pr: #7576
fixes [#6115]

### CODE REVIEW

**Comment by sjwang90** [comment]
Is this building off of PR #7584?

**Comment by jaecktec** [comment]
No, this came first and are two competing implementations

**Comment by jaecktec** [comment]
No, also I think the competing implementation got way better feedback than this one.

**Comment by srebhan** [comment]
Ok, but please note that the competing PR is closed as the contributor has no interest in it anymore...

**Pull request closed without merging**
