### PR TITLE
Add timeout option to IPMI sensor input plugin

### PR DESCRIPTION
**Pull request by m4ce**
Solves #2817.

### Required for all PRs:

- [x] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by danielnelson** [comment]
Looks good, can you add it to the CHANGELOG?

**Comment by m4ce** [comment]
@danielnelson, I've updated the CHANGELOG as requested.

**Comment by danielnelson** [comment]
Can you change the default to 5s as well?  Since the default interval is 10s we should keep it under that.

**Comment by m4ce** [comment]
The problem with 5s is that is just too low and users would have to often override that. If you are okay with it, I will change it back to 5s.

**Comment by danielnelson** [comment]
closes #1565

**Comment by danielnelson** [comment]
How much time do we need to query a single localhost server?  If we only need >5s for mutliple remote servers than I am comfortable requiring the user to increase the timeout.

**Comment by m4ce** [comment]
So, via the IPMI kernel interface (which is local), it takes more than 5 seconds on some of my boxes.

```shell
# time ipmitool sdr >/dev/null

real    0m8.026s
user    0m0.000s
sys     0m0.003s
```

I'd imagine over the network should be more expensive.

**Comment by danielnelson** [comment]
So maybe we should set the timeout = 20s and also add interval = 30s, similar to what we did for the cloudwatch input.

**Comment by m4ce** [comment]
@danielnelson - I've made the changes as requested. Let me know if there's anything that needs fixing.

**Pull request merged**
