### PR TITLE
feat: add bearer token support to elasticsearch output

### PR DESCRIPTION
**Pull request by toddboom**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #82333

Added a configuration to the Elasticsearch output to allow a bearer token to be passed along in the authorization header.

### CODE REVIEW

**Comment by toddboom** [comment]
Thanks, @powersj!

**Review by MyaLongmire — APPROVED** [review]

**Comment by toddboom** [comment]
Thanks, @MyaLongmire!

**Comment by toddboom** [comment]
Hey @powersj! Would it be possible to get this cherry-picked into `release-1.21` so that it can get picked up on the next release? Or are there plans for a `v1.22.0` sometime soon?

Thanks!

**Comment by MyaLongmire** [comment]
@toddboom `v1.22` should be coming out in the next week or two :)

**Pull request merged**
