### PR TITLE
minor - update function name in comment

### PR DESCRIPTION
**Pull request by sgarg7**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.

Saw a copy paste error in function name in comment, fixes that.

### CODE REVIEW

**Review by srebhan — APPROVED** [review]
Looks good. Thanks for spotting @sgarg7!

**Comment by srebhan** [comment]
@sgarg7 you need to sign the [Contributor License Agreement](https://www.influxdata.com/legal/cla/) before we can merge this PR.

**Comment by sgarg7** [comment]
@srebhan I'm checking with my employer about the CLA, most likely will sign it without any issues.

**Comment by srebhan** [comment]
@sgarg7 if you act on behalf of a company you additionally need a [Corporate CLA (CCLA)](https://www.influxdata.com/legal/ccla/)...

**Comment by sspaink** [comment]
@sgarg7 Thanks for the pr, have you had success with signing the CLA?

**Comment by srebhan** [comment]
@sgarg7 any chance you sign the CLA?

**Pull request closed without merging**
