### PR TITLE
chore(serializers.prometheus): Migrate to new-style framework

### PR DESCRIPTION
**Pull request by srebhan**
- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

This PR migrates the prometheus serializer to the new-style framework.

### CODE REVIEW

**Review by powersj — APPROVED** [review]

**Review by powersj — APPROVED** [review]

**Comment by powersj** [comment]
@srebhan sorry I didn't comment last week, I am +1 with the changes, but I am going to leave the conflict resolution to you ;) this is the last serializer I think so there is a bit of clean up required

**Comment by srebhan** [comment]
@powersj rebases. Will cleanup in a follow-up PR.

**Review by powersj — APPROVED** [review]
Thanks for wrapping this up

**Review by powersj — APPROVED** [review]
Thanks for wrapping this up

**Pull request merged**
