### PR TITLE
chore(snmp): Refactor SNMP translation and data-structures

### PR DESCRIPTION
**Pull request by Hipska**
## Summary

There are several other plugins importing `plugins/inputs/snmp`, which is not a good situation, so the `Field` and `Table` structs and the `Translator` and `Connection` interfaces were moved to `internal/snmp`.

~~Note that some test could and should be moved out of `plugins/inputs/snmp`, this might be something for #10531~~

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

1. https://github.com/influxdata/telegraf/pull/14223#discussion_r1389334200
2. https://github.com/influxdata/telegraf/pull/14223#discussion_r1475878585

### CODE REVIEW

**Review by srebhan — COMMENTED** [review]
Thanks you @Hipska for the amazing work! I just have the following requests/comments/questions:

1.  Can we please also move the netsnmp implementation to the common dir!
2. Is there a way to place at least some test-cases into the common dir?
3. Can we move this whole common thing to `plugins/common/snmp`?

Otherwise this looks really good!

**Comment by Hipska** [comment]
> 1. Can we please also move the netsnmp implementation to the common dir!

It can, however I thought we agreed that new plugins only should use the gosmi implementation, so I didn't see a need to refactor that one as wel. What do you think?

> 2. Is there a way to place at least some test-cases into the common dir?

I'll look into that, some could indeed, others use the plugin. A big rework of all the snmp related tests should be part of #10531.

> 3. Can we move this whole common thing to `plugins/common/snmp`?

I'm not comfortable doing that together with this PR as the purpose was to avoid other plugins import the `inputs/snmp` plugin.

**Comment by srebhan** [comment]
@Hipska ok, but I would really like to see netsnmp to also move to `internal` as it is kind-of unexpected to have the implementation of the interface split to two places. 

For the test-cases, I would love to see at least _some_ of the tests to move to have a minimal coverage. I agree that we should do more more testing but that can be a separate PR...

For moving to common: Which issues do you see in moving the stuff to common instead of internal? Asking out of interest if there is anything preventing this... I can also live with keeping stuff in internal for now...

**Comment by Hipska** [comment]
Moving all of internal/snmp to plugins/common/snmp involves too much stuff unrelated to the initial task and as stated, a lot of this code hasn't good test coverage. So too much possibility to break stuff unnoticed.. I would really keep that on a separate PR.

**Comment by srebhan** [comment]
Ok. So this leaves us with moving netsnmp and, if possible, at some basic / easy to move tests...

**Review by srebhan — APPROVED** [review]
Awesome. Thanks @Hipska!

**Comment by Hipska** [comment]
Sorry added some additional refactoring.

**Review by srebhan — APPROVED** [review]

**Comment by Hipska** [comment]
!retry-failed

**Review by srebhan — APPROVED** [review]

**Review by powersj — APPROVED** [review]
Thanks!

**Pull request merged**
