### PR TITLE
chore: Enables support for Windows and Darwin for golangci-lint in CI

### PR DESCRIPTION
**Pull request by zak-pawel**
This can be merged only when `golangci-lint` run for Linux/Windows/Darwin will not find any issues:
```
GOOS=linux make lint-branch
GOOS=windows make lint-branch
GOOS=darwin make lint-branch
```

Current situation:
- Linux:
  - no findings (guarded by CI)
- Windows:
  - Findings from https://github.com/influxdata/telegraf/issues/13036 need to be addressed
- Darwin:
  -  Almost all issues have been fixed here: https://github.com/influxdata/telegraf/pull/12958

Probably small rework of few plugins will be needed to avoid "false-positive" (platform specific) `unused...` findings, like these found for `GOOS=darwin make lint-branch`:
```
plugins/inputs/diskio/diskio.go:33:2       unused  field `infoCache` is unused
plugins/inputs/diskio/diskio_other.go:5:6  unused  type `diskInfoCache` is unused
plugins/inputs/ethtool/ethtool.go:43:2     unused  field `interfaceFilter` is unused
plugins/inputs/ethtool/ethtool.go:44:2     unused  field `namespaceFilter` is unused
plugins/inputs/ethtool/ethtool.go:45:2     unused  field `includeNamespaces` is unused
plugins/inputs/ethtool/ethtool.go:48:2     unused  field `command` is unused
```

This is a continuation of work previously done in https://github.com/influxdata/telegraf/pull/10782

### CODE REVIEW

**Comment by Hipska** [comment]
Shouldn't we first fix the darwin and windows linter warnings before this?

**Comment by zak-pawel** [comment]
> Shouldn't we first fix the darwin and windows linter warnings before this?

That's what I wrote in first sentence in this PR ;)



> As darwin is already fixed, maybe only enable this one and wait for windows to be fixed?

Good point! But remember of all these `unused...` findings for Darwin which are still there: https://github.com/influxdata/telegraf/pull/12958

**Comment by Hipska** [comment]
Right, maybe mark as draft until then? I don't think there is another way on GitHub to mark a dependency on another PR or issue?

**Comment by Hipska** [comment]
It’s not easy to follow the commits when they all have the same message 😅

**Comment by powersj** [comment]
@zak-pawel - what's left on this one? Did you still want to pursue this as well?

**Comment by zak-pawel** [comment]
> @zak-pawel - what's left on this one? Did you still want to pursue this as well?

@powersj Merged master with the newest fixes into this PR. For now we need to address current findings (both for darwin and windows):
```
  plugins\inputs\diskio\diskio.go:33:2          unused    field `infoCache` is unused
  plugins\inputs\diskio\diskio_other.go:5:6     unused    type `diskInfoCache` is unused
  plugins\inputs\ethtool\ethtool.go:43:2        unused    field `interfaceFilter` is unused
  plugins\inputs\ethtool\ethtool.go:44:2        unused    field `namespaceFilter` is unused
  plugins\inputs\ethtool\ethtool.go:45:2        unused    field `includeNamespaces` is unused
  plugins\inputs\ethtool\ethtool.go:48:2        unused    field `command` is unused
```

These findings were discussed here: https://github.com/influxdata/telegraf/pull/13246#discussion_r1222234901 and here: https://github.com/influxdata/telegraf/pull/13246#discussion_r1222234746.

We need to establish a common approach to address these findings. I'm also ok with someone fixing them (as I might not have much time during next 2-3 weeks).

**Comment by powersj** [comment]
replacing with #13599

**Pull request closed without merging**
