### PR TITLE
Add netstat connections plugin

### PR DESCRIPTION
**Pull request by superguillen**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by sjwang90** [comment]
Thanks for the contribution. I've converted this to a draft for now, feel feel to select "Ready for review" when it is finalized.

**Comment by superguillen** [comment]
Can you help me with the test errors?, in the details dont see the problem

**Comment by sjwang90** [comment]
@superguillen Looks like you fixed the test errors. Do you think you could clarify your use case for the PR and update anything necessary to the README?

**Comment by superguillen** [comment]
Hi, I created NETSTAT_CONECTIONS_README.md

**Comment by superguillen** [comment]
Hi, what is the next?

**Comment by sjwang90** [comment]
Thanks for the PR @superguillen. We'll get someone to review.

**Comment by superguillen** [comment]
Hi, can help me with:

#!/bin/bash --login -eo pipefail
make tidy
go mod verify
all modules verified
go mod tidy
please run go mod tidy and check in changes
make: *** [tidy] Error 1

Exited with code exit status 2
CircleCI received exit code 2

With macdeps in circleci,
Regards

**Comment by sjwang90** [comment]
@srebhan Do you have any suggestions for superguillen?

**Comment by srebhan** [comment]
@sjwang90 @superguillen well the error message says `please run go mod tidy and check in changes`. That's what is necessary. :-) Please run `go mod tidy` in the telegraf top directory (the one containing `go.mod`) and then `git add`/`git commit`.

**Comment by srebhan** [comment]
@superguillen you still need to run `make fmt` to fix the CI fails.
Furthermore, can you please explain your reasoning behind _not_ extending the existing plugin in that directory?

**Comment by superguillen** [comment]
Hi, 
The original plugin generate basic information (but low cardinality), this plugin generate higth cardinality (but is very usseful for productions problems), 
regards.

**Comment by superguillen** [comment]
What next?

**Comment by srebhan** [comment]
Hey sorry for the late response, but my day-job is keeping me busy. :-)

> The original plugin generate basic information (but low cardinality), this plugin generate higth cardinality (but is very usseful for productions problems),

What other plugins do is, the always deliver the basic information (like the original plugin) and offer a switch (or a feature-include list) to enable the extended info with high cardinality (like in your plugin). This has the advantage of not duplicating the code and mutually profit from extensions/enhancements. Can you please reconsider if you can merge with the original plugin!?

**Comment by superguillen** [comment]
Ok, I will work to merge in the original plugin,
regards,
Victor.

**Comment by srebhan** [comment]
Any update?

**Comment by powersj** [comment]
Hi,

This PR has not been touched in a while and as a result I am going to close it. We are happy to review again once someone picks this back up with the suggested changes and rebased on master.

Thanks!

**Pull request closed without merging**
