### PR TITLE
feat: add support for OpenSearch to existing ElasticSearch output plugin

### LINKED ISSUE #9414: elasticsearch output doesn't work with opensearch
### Relevant telegraf.conf:

```toml
[[outputs.elasticsearch]]
  urls = ["https://10.0.0.195:9200"]
  timeout = "5s"
  health_check_interval = "10s"
  username = "admin"
  password = "admin"
  index_name = "telegraf-%Y.%m.%d"
  manage_template = true
  template_name = "telegraf"
  overwrite_template = false
  insecure_skip_verify = true
```

### System info:

os: Ubuntu 20.04
telegraf version: 1.19
opensearch version: 1.0.0-rc1

### Steps to reproduce:

1. start telegraf with output config listed
2.  follow logs with journalctl

### Expected behavior:

no logs and documents appearing in elasticserch
### Actual behavior:
outputs 2021-06-23T05:11:31Z E! [agent] Failed to connect to [outputs.elasticsearch], retrying in 15s, error was 'Elasticsearch version not supported: 1.0.0-rc1' to the console

### PR DESCRIPTION
**Pull request by pteich**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #9414

This PR adds support for [OpenSearch](https://opensearch.org/) to the existing ElasticSearch output plugin. OpenSearch is based on ElasticSearch 7.x but it introduces its own versioning. Because of this the current version reports 1.2.3 and this breaks the version check implementation.

To make it work with OpenSearch servers this PR introduces a new config setting `opensearch = true` that circumvents the version check and internal treats the server as a major version 7 ElasticSearch (because this is needed for other internal checks).
The new config setting also enables to react to other potentially OpenSearch additions in the future.

### CODE REVIEW

**Comment by pteich** [comment]
!signed-cla

**Comment by StefanSa** [comment]
@pteich Peter,
there would be already an important pull request.
Please make sure that this new plugin also supports `data stream`, so `bulk_action` => `create`.

**Comment by pteich** [comment]
@StefanSa I'll have a look and also resolve the conflicts.

**Comment by StefanSa** [comment]
@pteich Peter,
details please look here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#docs-bulk-api-desc
```
Data streams support only the create action. To update or delete a document in a data stream, you must target the backing index containing the document. See Update or delete documents in a backing index.
```

Grüße nach Leipzig

**Comment by powersj** [comment]
The team chatted about the way we wanted to fix this and instead put up #10586.

The PR documents the method that Amazon has given to enable compatibility with Elasticsearch clients. It is best if users use this method rather than trying to set options in Telegraf itself. 

One of the reasons is we do not like to add boolean values due to potential conflicts in the future. For example, right now this PR would set the major version to 7. However, it is entirely possible that Amazon moves to Elasticsearch 8 or 9 in the future. If there are additional major version checks added in the future the boolean would have to know more about which version to use.

I appreciate that you took the time to put this up, but I am going to close it as we have landed the other PR.

Thanks

**Pull request closed without merging**
