### PR TITLE
chore: add Super Linter Github Action

### PR DESCRIPTION
**Pull request by sspaink**
Add the Super Linter Github Action: https://github.com/github/super-linter

Will only check the changed files in a pull request and by default the configuration enables all the linters and only runs them based on the changed files. Doesn't seem to do any harm have them all enabled, we can disable any we want. It does seem to check the entire changed file and not just the changes you made, therefore I updated a few unrelated lines in `README.md` and `REVIEWS.md` that the linter was complaining about.

You can test the github action locally following these steps: github/super-linter@main/docs/run-linter-locally.md

Also included a configuration file for the markdown linter called `.markdownlint.yml` that disables the line-length rule, the vscode markdownlint extension does this by default and I thought it would be good to match it.

### CODE REVIEW

**Review by MyaLongmire — APPROVED** [review]
lgtm!

**Comment by powersj** [comment]
@reimda thoughts on this one? I like the idea of lining other things, but I do not like the fact that I would need to launch a docker container just to run this locally.

**Comment by sspaink** [comment]
> @reimda thoughts on this one? I like the idea of lining other things, but I do not like the fact that I would need to launch a docker container just to run this locally.

Each linter it runs has an easier way to run it locally, like it runs golangci-lint which you can setup separately. For markdown it uses markdownlint which is used in the vscode extension. The docker approach is just there to copy the GitHub action.

**Comment by powersj** [comment]
Can we document what those are and how to run them? If we are going to block a PR on tests, I think running those should be part of `make lint` for users to test locally.

**Comment by reimda** [comment]
I agree devs should be able to easily run the new linter locally before pushing. Making docker a requirement to do that could be enough of an obstacle for some devs that it may discourage contributions. Then again, if a dev doesn't want to install docker, they can always push and let CI do the check for them.

Since this is new could we add it as a non-required check? Could we have it run but not block the PR if it doesn't pass? Then we can see if it's worth requiring devs to run it locally in docker?

**Comment by sspaink** [comment]
I can update this to just include the markdown and golangci-lint linters for now, and then just add the markdown linter to `make lint`. Just adding the two linters we know we want to run, then add the other linters in the future.

**Pull request merged**
