### PR TITLE
Added tags for monitoring readable secondaries for Azure SQL MI

### PR DESCRIPTION
**Pull request by bhsu-ms**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

Added new column - is_primary_replica in DB queries for monitoring readable secondaries.
@denzilribeiro Could you please review this PR for exposing replica role to monitor readable secondaries for MI?

### CODE REVIEW

**Review by denzilribeiro — CHANGES_REQUESTED** [review]
For simplicity can we actually have the tag as 'READ_ONLY' or READ_WRITE just return the property itself rather than returning a 0/1?
Aka  
DATABASEPROPERTYEX(DB_NAME(), 'Updateability') as replica_updateability

**Review by denzilribeiro — APPROVED** [review]
Reviewed MI related changes

**Comment by bhsu-ms** [comment]
@ssoroka / @reimda could you help merging this PR? Thanks!

**Review by denzilribeiro — APPROVED** [review]

**Comment by bhsu-ms** [comment]
@ssoroka Could you help approving this PR? Thanks!

**Review by ssoroka — APPROVED** [review]

**Pull request merged**
