### PR TITLE
fix(inputs.socket_listener): Avoid noisy logs on closed connection

### LINKED ISSUE #13043: socket_listener: silence health checks in logs
### Use Case

Right now the socket_listener input generates lots of noise due to health check probes. For example if you have a load balancer which opens a tcp socket to the input, and then immediately closes the socket without writing anything, it generates 2 logs entries (in the case of SSL):

```
Apr 06 03:56:36 myhost telegraf[21963]: 2023-04-06T03:56:36Z E! [inputs.socket_listener] Error in plugin: connection not a TCP connection (*tls.Conn)
Apr 06 03:56:36 myhost telegraf[21963]: 2023-04-06T03:56:36Z E! [inputs.socket_listener] Error in plugin: creating decoder failed: write tcp 10.0.0.10:8085->10.0.2.9:33288: write: connection reset by peer
```

When you have many clients, this gets extremely noisy and make it hard to observe the logs for meaningful information.

### Expected behavior

Silence

### Actual behavior

```
Apr 06 03:56:36 myhost telegraf[21963]: 2023-04-06T03:56:36Z E! [inputs.socket_listener] Error in plugin: connection not a TCP connection (*tls.Conn)
Apr 06 03:56:36 myhost telegraf[21963]: 2023-04-06T03:56:36Z E! [inputs.socket_listener] Error in plugin: creating decoder failed: write tcp 10.0.0.10:8085->10.0.2.9:33288: write: connection reset by peer
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by phemmer**
This suppresses several different logs that may be emitted when the connection is closed (locally or by remote) at various points.

Fixes #13043

Note this depends on #13059, otherwise the test fails (times out).

# Required for all PRs

- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

### CODE REVIEW

**Review by powersj — APPROVED** [review]
Thanks - my only concern was that we would no longer be telling the user if we hit a connection reset, but I think that is generally ok and can be hidden

**Review by srebhan — COMMENTED** [review]
Thanks for the fix @phemmer! The fix looks good to me, but I want to encourage you to extend the [`CaptureLogger` implementation](https://github.com/influxdata/telegraf/blob/master/testutil/capturelog.go) instead of rolling your own `TestLogger`. Do you think merge the two?

**Comment by phemmer** [comment]
> The fix looks good to me, but I want to encourage you to extend the [CaptureLogger implementation](https://github.com/influxdata/telegraf/blob/master/testutil/capturelog.go) instead of rolling your own TestLogger.

I'm fine with going that route, but don't really want to tackle that update. Such a change would break other tests currently using it as `Errors()` will suddenly return more results than it used to. You could have separate `Infos()`, `Warnings()`, etc. But that makes it even more complicated. Making those decisions is way outside the scope of this change. If someone else wants to do it, I'll update this PR to use it.

**Comment by srebhan** [comment]
@phemmer my idea was to leave the error path as-is and add another field (e.g. logs) that can be accesses via a `Logs()` function (or similar), just as you do in your implementation. So the goal is to _extend_ `CaptureLogger`.

**Comment by srebhan** [comment]
@phemmer any chance you look at merging the loggers?

**Comment by phemmer** [comment]
> @phemmer any chance you look at merging the loggers?

#13161

**Comment by phemmer** [comment]
closing as I don't have time to carry this. If someone else wants to pick it up, feel free

**Comment by srebhan** [comment]
Waiting for #13275...

**Comment by srebhan** [comment]
Replaced by #13288

**Pull request closed without merging**
