### PR TITLE
Add Riemann TLS output

### PR DESCRIPTION
**Pull request by mcorbin**
- Replace raidman by riemann-go-client (https://github.com/riemann/riemann-go-client) which support TLS.
- Add support for TLS

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
At a high level I'm concerned about this libraries support for timeouts, I see they have it for connect but I don't see any ability to set timeouts on send.

**Comment by mcorbin** [comment]
Thanks your for your review.

I have updated riemann-go-client to support timeout on send. I have also updated this pull request with the new version of riemann-go-client.

**Comment by danielnelson** [comment]
Would you consider adding support for `context.Context` to your library?  Currently I have only basic support for context in Telegraf but I'm looking to expand this in the future.  If we could pass in a context to the Connect and Send functions that would be ideal, as we may want to apply a timeout to a group of commands, or simply want to cancel the connection.

Another question I have is about the channel you are using in the client, what is the purpose of this? https://github.com/riemann/riemann-go-client/blob/master/tls.go#L78

Any chance we can use an already create `tls.Config` for creating the TLSClient?  This will make it easier to hook into our standard TLS handling and allow us to add new options in the future.

Finally, is there a reason why you have separate clients for TLS vs non-TLS?

**Comment by mcorbin** [comment]
> Would you consider adding support for context.Context to your library?

I will try ;)

> Another question I have is about the channel you are using in the client, what is the purpose of this? https://github.com/riemann/riemann-go-client/blob/master/tls.go#L78

For concurrency. We use a channel to be sure than only one message is write at a time. I'm new to Golang so maybe there is a more idiomatic way to do it ?

> Any chance we can use an already create tls.Config for creating the TLSClient? This will make it easier to hook into our standard TLS handling and allow us to add new options in the future.

I will try do to that.

> Finally, is there a reason why you have separate clients for TLS vs non-TLS?

Not really, i will merge the 2 clients.

Thanks you for your reviews ;)

**Comment by danielnelson** [comment]
> For concurrency. We use a channel to be sure than only one message is write at a time. I'm new to Golang so maybe there is a more idiomatic way to do it ?

I see, the Send method is meant to be thread-safe?  I think what you have works, personally I would probably just use the channel as a semaphore and then call Write directly without the goroutine.   I did something like this in the dcos input to limit the number of concurrent HTTP requests made: https://github.com/influxdata/telegraf/blob/a4870e6a6d2f1503b2feea689207bd5093c6033a/plugins/inputs/dcos/client.go#L284-L299


>>Finally, is there a reason why you have separate clients for TLS vs non-TLS?
>
>Not really, i will merge the 2 clients.

I recently have been working on adding TLS support to our zookeeper input, the main difference between the two modes was the Dial function when working with timeouts, this isn't fully tested but maybe it will be helpful:
https://github.com/influxdata/telegraf/blob/c46c3a0b6e033668d7d0438c6d6a5ee28c112e74/plugins/inputs/zookeeper/zookeeper.go#L66-L77

**Comment by mcorbin** [comment]
> I see, the Send method is meant to be thread-safe? 

Yes. And the format being protobuf, i need to do several write and read sequentially for a message.

I have started working on a refactoring (https://github.com/riemann/riemann-go-client/pull/21), i just need to add support for Context (i am reading doc about context and example code right now ;) ). 

I will update this PR once the refactoring merged.

**Pull request closed without merging**
