### PR TITLE
add kafka new consumer support

### PR DESCRIPTION
**Pull request by neonmori**
add supports of kafka 0.9+ new consumer with TLS

Some information:
Since kafka 0.9, they begin to provide 2 types of consumers, old consumers are what we have in the existing consumer plugin which I'm not sure if they have TLS support and the new consumers. What I am trying to fix is the compatibility of kafka_consumer plugin to Kafka 0.9+.
### Required for all PRs:
- [ ] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by sparrc** [comment]
@neonmori is there a chance you could set the "new" consumer to be the default, and then fallback to the "old" consumer if that one fails?

**Comment by neonmori** [comment]
We can look at the "BrokerList" option, if this one is empty, then it will be old consumer, once this is specified, we will know it's new consumer.

**Comment by sparrc** [comment]
why did you make a separate list for 0.9+ brokers? doesn't that defeat the purpose of the `new_consumer` option?

**Comment by pcallewaert** [comment]
Any update on this?

@sparrc I maybe can answer on those questions, in kafka 0.9 you do not connect anymore with zookeeper for the broker list, but with kafka itself. The new consumer is set up so clients do not need a dependency on zookeeper anymore. So zookeeper_peers is obsolete and wrong name when you use it for 0.9.

**Comment by sparrc** [comment]
that's good to know, but the code's current state is not mergable, it's going to need a significant rewrite and we should probably discuss how this should look side-by-side with the current kafka plugin in a feature request, not a PR.

**Comment by sparrc** [comment]
I'm going to close because we need to discuss this in a feature request.

The main concern is that we need to elegantly support both the "new" kafka and old kafka in an elegant way that makes sense for most users.

Not sure the current PR satisfies that, at least I don't find it very intuitive.

**Comment by burdandrei** [comment]
hey @sparrc  I'm trying to run Telegraf => Kafka 0.10 => Telegraf => influx
And without sarama cluster it's not really working.
Any news about this? i think kafka is really common buffer.
And as logtash 5 is working with new kafka, i think it's the time for telegraf to support it too.
Let me know if any help needed to make this happen.
Cheers!

**Comment by jackzampolin** [comment]
@burdandrei There is a [PR open for a new `kafka_consumer`](https://github.com/influxdata/telegraf/pull/2487). It breaks backward compatibility, and needs a little testing but we are moving forward with that implementation. If you could test it and comment on the pull it would help out!

**Comment by burdandrei** [comment]
@jackzampolin  running it now!

**Pull request closed without merging**
