### PR TITLE
Added hep protocol support as parser in telegraf

### PR DESCRIPTION
**Pull request by aqsyonas**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by lmangani** [comment]
For more backstory on the implemented protocol: [HEP](https://github.com/sipcapture/HEP) is an open encapsulation protocol extremely popular in VoIP Applications and natively supported by many platforms such as Kamailio, OpenSIPS, Asterisk, Freeswitch and others.

For more information on HEP and its enabled projects: https://github.com/sipcapture

**Comment by danielnelson** [comment]
Thanks @aqsyonas and @lmangani, would love to hear more about the specifics of how one would utilize this parser.  I'll probably want to setup a testing environment as well, any suggestions for which program I could use that, whichout too much fuss, could generate some interesting data?

**Comment by lmangani** [comment]
Hi @danielnelson thanks for your feedback! We have a `HEP` generator in NodeJS you can use to pump some data towards the socket. Find it here: https://github.com/sipcapture/hepgen.js

We're available to provide examples and assistance setting up and executing any test ;)

**Comment by aqsyonas** [comment]
@danielnelson Thanks, for the reply. I have generated some data using the parser, below stats are from influxdb. 

`time                    CLOCK   CODEC_PT        DELTA   DIR     DST_PORT        EXPECTED_PK     JITTER  MAX_DELTA       MAX_SKEW        MEAN_JITTER     MEAN_MOS        cid                     dest_ip4           dest_port       host           node_id node_pw nodename        protocol        protocol_type_field     tsec         src_ip4  
1564391681515466558     8000    9               19.983  0       51354           1512            0.017   20.024          0.172           0.005           4.032           7k3fq@127.0.0.1_b2b-1   224.9.197.178      0               testServer     2001    myHep   2001            35              35                      1564391694   55.66.77.83
1564391684007630125     8000    9               11.983  0       51354           1512            0.011   20.124          0.221           0.305           3.932           7k3fq@127.0.0.1_b2b-1   224.9.197.178      0               testServer     2001    myHep   2001            35              35                      1564391694   55.66.77.83
1564391686506494653     8000    9               19.983  0       51354           1512            0.017   20.024          0.172           0.005           4.032           7k3fq@127.0.0.1_b2b-1   224.9.197.178      0               testServer     2001    myHep   2001            35              35                      1564391694   55.66.77.83
1564391689007343462     8000    9               11.983  0       51354           1512            0.011   20.124          0.221           0.305           3.932           7k3fq@127.0.0.1_b2b-1   224.9.197.178      0               testServer     2001    myHep   2001            35              35                      1564391694   55.66.77.83
1564391691508162941     8000    9               19.983  0       51354           1512            0.017   20.024          0.172           0.005           4.032           7k3fq@127.0.0.1_b2b-1   224.9.197.178      0               testServer     2001    myHep   2001            35              35                      1564391694   55.66.77.83`

I have just selected a few stats, but Hep protocol does offer feature in-rich information regarding the calls. 

Please let me know if that helps. 
Br, Aqs.

**Comment by lmangani** [comment]
@srebhan we will shortly open a new PR for with rebased code and refer to this issue - thanks!

**Comment by adubovikov** [comment]
@srebhan sorry for delay. Here is the new one: https://github.com/influxdata/telegraf/pull/10039 
This we can close.

**Pull request closed without merging**
