### PR TITLE
Fix instance and object name in performance counters with backslashes 

### LINKED ISSUE #4499: Win_perf_counters plugin regex doesn't work for instances that have back slashes
### Relevant telegraf.conf:
```
[[inputs.win_perf_counters]]
  UseWildcardsExpansion=true 
 [[inputs.win_perf_counters.object]]
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = [
      "% Disk Read Time",
      "% Disk Write Time",
      "Disk Read Bytes/sec",
      "Disk Write Bytes/sec",
      "Disk Reads/sec",
      "Disk Writes/sec",
      "Current Disk Queue Length",
      "Avg. Disk sec/Read",
      "Avg. Disk sec/Write"
    ]
    Measurement = "win_disk"
    IncludeTotal=false
    WarnOnMissing=true
```
### System info:
Telegraf v1.7 - with changes (not affecting this problem)
Windows Server 2012 R2

### Steps to reproduce:

1. Get a system that has logicaldisk instances that are path names.
2. Run telegraf with the above config input.
3. Check output and you will see the instance and object for the path name instances are wrong.

### Expected behavior:
`\BOWSQLTST23A\LogicalDisk(E:\Data\Disk1)\Disk Reads/sec -> "instance":"E:\\Data\\Disk1" "objectname":"LogicalDisk"`

### Actual behavior:
`\BOWSQLTST23A\LogicalDisk(E:\Data\Disk1)\Disk Reads/sec -> "objectname":"Disk1)"`

### Additional info:
Here is the fix for this from my testing: https://gist.github.com/jedthe3rd/4a361cc19ac4cfd4ccf7bf7547107ead

Relevant regex tests:
https://regex101.com/r/GAnd0s/2
https://regex101.com/r/GAnd0s/3

### PR DESCRIPTION
**Pull request by vlastahajek**
closes #4499 

### Overview
replaced complex regexp marching with simple index searching
Added unit test for counterPath parsing

### Required for all PRs:
- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@jedthe3rd Could you test this fix with your setup?  [telegraf-1.8.0~9f9bd961_windows_amd64.zip](https://17236-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.8.0%7E9f9bd961_windows_amd64.zip)

**Comment by vlastahajek** [comment]
I realized that there can be even more complex counter paths, e.g. `\\host\object(d:\f\I(a)x)\counter(d:\f(d)\i)`.
I haven't found any restrictions of counter name, instance name or object name. I tested that complex path on Windows performance counters API function [PdhParseCounterPathW](https://docs.microsoft.com/en-us/windows/desktop/api/Pdh/nf-pdh-pdhparsecounterpathw) and as it was able to parse it, I find such complex path valid.
So I have created better, more bulletproof, parser. It's ~6x slower than previous, but still a lot faster than regexp.
Unit test has been a lot more extended as well.

**Comment by danielnelson** [comment]
@jedthe3rd Here is an updated build with the latest fixes for testing, if you are available to verify we can add this for 1.7.4:

- [telegraf-1.8.0~1789ce0b_windows_amd64.zip](https://17290-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.8.0%7E1789ce0b_windows_amd64.zip)

**Comment by vlastahajek** [comment]
I"m sorry for discontinuous commits. The latest one is just an improved unit test.

**Pull request merged**
