### PR TITLE
beanstalkd (new plugin)

### PR DESCRIPTION
**Pull request by irr**
### Required for all PRs:
- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by rubycut** [comment]
Will this be merged any time soon?

**Comment by sparrc** [comment]
it's unlikely, we are currently working on a system for external plugins, stay tuned

**Comment by mld** [comment]
Any updates on the new system for external plugins? Otherwise, maybe you should consider letting in new plugins again :)

**Comment by edbizarro** [comment]
+1

**Comment by edbizarro** [comment]
:/

**Comment by edbizarro** [comment]
That would be awesome, currently i had to setup another system only to monitor my tubes

**Comment by 44px** [comment]
Hi guys,

I'm also interested in this plugin so I started to work on my own implementation on last weekend =) I hope to submit a new pull request soon.

**Comment by 44px** [comment]
Here is the PR: https://github.com/influxdata/telegraf/pull/4272 :)

**Pull request closed without merging**
