### PR TITLE
refactor: Prevent import from going the wrong way

### LINKED ISSUE #12003: Update wavefront serializer to prevent import from going the wrong way
### Use Case

Our team is planning to add a field `httpconfig.HTTPClientConfig` in the Wavefront output plugin struct `Wavefront`. This addition intends to expose TLS configuration properties. The intention behind exposing these properties is to enable supplying a self-signed Certificate Authority for TLS communication. 

### Expected behavior

The `make build` call to build the `telegraf` binary succeeds. 

### Actual behavior

When we added a field `httpconfig.HTTPClientConfig` in the Wavefront output plugin struct `Wavefront`, we saw that `make build` failed with the following error:
```  imports github.com/influxdata/telegraf/config: import cycle not allowed```

### Additional info

There is already a TODO referencing this issue [here](https://github.com/suprajanarasimhan/telegraf/blob/215e8e030a34455605cff522280140eed8838df4/plugins/serializers/wavefront/wavefront.go#L10) that explains how to fix the import cycle: 

```
"github.com/influxdata/telegraf/plugins/outputs/wavefront" // TODO: this dependency is going the wrong way: Move MetricPoint into the serializer.
```

### PR DESCRIPTION
**Pull request by suprajanarasimhan**
Signed-off-by: Devon Warshaw <warshawd@vmware.com>

# Required for all PRs

- [Won't fix] Updated associated README.md. -- I didn't, since this was a refactor, rather than a change.
- [Won't fix] Wrote appropriate unit tests. -- Fixed existing tests but did not write any new ones.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #12003

<!-- Finally, include a summary of the code change itself. This
description should tell reviewers how the issues were resolved.

example: Fixed a potential dependency cycle by having Wavefront output plugin import the Wavefront serializer, rather than the other way around.

### CODE REVIEW

**Comment by suprajanarasimhan** [comment]
> 

!signed-cla

**Review by powersj — APPROVED** [review]
Thanks for taking the time to put this up! I do see your name in the list of signed CLA folks, so I think we are good.

**Comment by powersj** [comment]
!signed-cla

**Comment by suprajanarasimhan** [comment]
> Thanks for taking the time to put this up! I do see your name in the list of signed CLA folks, so I think we are good.

Hi @powersj! Thanks for looking it over and nice to meet you. 😊

**Review by MyaLongmire — APPROVED** [review]

**Comment by suprajanarasimhan** [comment]
Thank you, @MyaLongmire! =)

**Pull request merged**
