### PR TITLE
fix(inputs.sqlserver): Converted THROW to RAISERROR for 2008 compatibility

### LINKED ISSUE #12978: inputs.sqlserver: SQLServerRequests fails on SQL Server version 2008 R2 and older because of THROW statement
### Relevant telegraf.conf

```toml
[[inputs.sqlserver]]
  servers = [
      'app name=qmonitor;log=1;connection timeout=8;server=QDSRVMONITOR\SQL2008;encrypt=disable',
  ]

  database_type = "SQLServer"

  include_query = [
    'SQLServerRequests'
  ]

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```

### Logs from Telegraf

```text
2023-03-29T10:59:35Z I! Loading config file: telegraf.conf
2023-03-29T10:59:35Z I! Starting Telegraf 1.3.0-1e9319f4 (customized)
2023-03-29T10:59:35Z I! Available plugins: 12 inputs, 0 aggregators, 3 processors, 6 parsers, 5 outputs, 0 secret-stores
2023-03-29T10:59:35Z I! Loaded inputs: sqlserver
2023-03-29T10:59:35Z I! Loaded aggregators:
2023-03-29T10:59:35Z I! Loaded processors:
2023-03-29T10:59:35Z I! Loaded secretstores:
2023-03-29T10:59:35Z I! Loaded outputs: file
2023-03-29T10:59:35Z I! Tags enabled: host=QDWS01
2023-03-29T10:59:35Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"QDWS01", Flush Interval:10s
2023-03-29T10:59:35Z I! [inputs.sqlserver] Config: database_type: SQLServer , query_version:0 , azuredb: false
2023-03-29T10:59:35Z I! [inputs.sqlserver] Config: Effective Queries: []string{"SQLServerRequests"}
2023-03-29T10:59:40Z E! [inputs.sqlserver] Error in plugin: query SQLServerRequests failed for server: QDSRVMONITOR\SQL2008 and database: <empty-database-name> with Msg 102, Level 15, State 1:, Line 108, Error: mssql: Incorrect syntax near 'THROW'.
2023-03-29T10:59:42Z I! [agent] Hang on, flushing any cached metrics before shutdown
2023-03-29T10:59:42Z I! [agent] Stopping running outputs
```

### System info

Telegraf 1.26.0 on Windows 11

### Docker

_No response_

### Steps to reproduce

Run telegraf using the config supplied

### Expected behavior

Run SQLServerRequests query and gather data

### Actual behavior

Error on SQL Server 2008

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by spaghettidba**
- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [X] Pull request title or commits are in [conventional commit format]

resolves #12978

In SQLServerRequests, converted THROW to RAISERROR for 2008 compatibility

### CODE REVIEW

**Review by powersj — COMMENTED** [review]
Thanks for the PR. Do you know if this is compatible with newer versions of SQL server. From the plugin readme:

```s
## The SQL Server plugin supports the following editions/versions of SQL Server

- SQL Server
  - 2012 or newer (Plugin support aligned with the [official Microsoft SQL Server support](https://docs.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-end-of-life-overview?view=sql-server-ver15#lifecycle-dates))
  - End-of-life SQL Server versions are not guaranteed to be supported by Telegraf. Any issues with the SQL Server plugin for these EOL versions will need to be addressed by the community.
```

**Comment by spaghettidba** [comment]
Thanks for the feedback.
It is compatible with newer versions. Tested with 2019.
I know that the plugin targets supported versions only, but the hard truth is that there are countless SQL Server 2008 instances out there and writing code that works in all versions takes very limited additional effort. There are other parts of the plugin code that account for older versions.

**Review by powersj — APPROVED** [review]
ok, I think this fine if that is the case - I do think as we get further away from the 2008 and now 2012 EOL dates you may run into this more and more :\

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for the fix @spaghettidba!

**Pull request merged**
