### PR TITLE
Fix dovecot regression in #9415

### LINKED ISSUE #9415: [dovecot input plugin] tcp read i/o timeout since telegraf 1.18.3 -> 1.19.0 update
### Relevant telegraf.conf:

```toml
[[inputs.dovecot]]
        type = "global"
```

### Relevant dovecot.conf:

```
mail_plugins = $mail_plugins old_stats
auth_stats = yes
plugin {
        old_stats_refresh = 10 secs
        old_stats_track_cmds = yes
}
service old-stats {
        fifo_listener old-stats-mail {
                user = dovecot
                group = mail
                mode = 0666
        }
        inet_listener {
                address = 127.0.0.1 ::1
                port = 24242
        }
        process_min_avail=1
}
```

### System info:

OS: CentOS Linux release 7.9.2009 (Core)
Uname: Linux <hostname> 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Telegraf: telegraf-1.19.0-1.x86_64
Dovecot: dovecot23-2.3.11.3-1.gf.el7.x86_64 and dovecot23-pigeonhole-2.3.11.3-1.gf.el7.x86_64

All latest updates are installed on the OS

### Steps to reproduce:

1. Update from telegraf 1.18.3 -> 1.19.0
2. Enable the above config in telegraf and dovecot
3. watch the telegraf error log

### Expected behavior:

Version 1.19.0 to act like 1.18.3.

In version 1.18.3 the dovecot stats were read via 127.0.0.1:24242 without any error. 

### Actual behavior:

Since version 1.19.0 the error (see logs below) appears.

There was no other config/update than the update from telegraf 1.18.3 -> 1.19.0. 
A tcp connection to 127.0.0.1:24242 is still possible, as before

```
$ telnet 127.0.0.1 24242
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

```

### Additional info:

Just a note: As per #9223 (telegraf version 1.19.0) there were changes around this plugin made.

```
Jun 23 07:54:45 mail1 telegraf: 2021-06-23T05:54:45Z E! [inputs.dovecot] Error in plugin: copying message failed for dovecot server '127.0.0.1:24242': read tcp 127.0.0.1:60094->127.0.0.1:24242: i/o timeout
Jun 23 07:54:55 mail1 telegraf: 2021-06-23T05:54:55Z E! [inputs.dovecot] Error in plugin: copying message failed for dovecot server '127.0.0.1:24242': read tcp 127.0.0.1:60102->127.0.0.1:24242: i/o timeout
Jun 23 07:55:05 mail1 telegraf: 2021-06-23T05:55:05Z E! [inputs.dovecot] Error in plugin: copying message failed for dovecot server '127.0.0.1:24242': read tcp 127.0.0.1:60110->127.0.0.1:24242: i/o timeout
Jun 23 07:55:15 mail1 telegraf: 2021-06-23T05:55:15Z E! [inputs.dovecot] Error in plugin: copying message failed for dovecot server '127.0.0.1:24242': read tcp 127.0.0.1:60116->127.0.0.1:24242: i/o timeout
Jun 23 07:55:25 mail1 telegraf: 2021-06-23T05:55:25Z E! [inputs.dovecot] Error in plugin: copying message failed for dovecot server '127.0.0.1:24242': read tcp 127.0.0.1:60124->127.0.0.1:24242: i/o timeout
Jun 23 07:55:35 mail1 telegraf: 2021-06-23T05:55:35Z E! [inputs.dovecot] Error in plugin: copying message failed for dovecot server '127.0.0.1:24242': read tcp 127.0.0.1:60148->127.0.0.1:24242: i/o timeout
Jun 23 07:55:45 mail1 telegraf: 2021-06-23T05:55:45Z E! [inputs.dovecot] Error in plugin: copying message failed for dovecot server '127.0.0.1:24242': read tcp 127.0.0.1:60156->127.0.0.1:24242: i/o timeout
```

### PR DESCRIPTION
**Pull request by srebhan**
- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.

resolves #9415

This PR tries to resolve the regression above.

### CODE REVIEW

**Comment by popey** [comment]
Thanks for the PR! This appears to fix the issue for me.

Before this patch:

```
2021-06-24T16:07:16Z E! [inputs.dovecot] Error in plugin: copying message failed for dovecot server '10.55.242.189:24242': read tcp 10.55.242.1:60994->10.55.242.189:24242: i/o timeout
```

After this patch:

```
> dovecot,host=ac,server=10.55.242.189,type=global auth_cache_hits=0i,auth_cache_misses=0i,auth_db_tempfails=0i,auth_failures=0i,auth_master_successes=0i,auth_successes=0i,clock_time=0,disk_input=0i,disk_output=0i,invol_cs=0i,mail_cache_hits=0i,mail_lookup_attr=0i,mail_lookup_path=0i,mail_read_bytes=0i,mail_read_count=0i,maj_faults=0i,min_faults=0i,num_cmds=0i,num_connected_sessions=0i,num_logins=0i,read_bytes=0i,read_count=0i,sys_cpu=0,user_cpu=0,vol_cs=0i,write_bytes=0i,write_count=0i 1624546810000000000

```

**Comment by popey** [comment]
Here's the full output..

telegraf 1.18.3
```
$ ../telegraf-1.18.3/usr/bin/telegraf --debug --config etc/telegraf/telegraf.conf --test
2021-06-24T18:45:52Z I! Starting Telegraf 1.18.3
2021-06-24T18:45:52Z D! [agent] Initializing plugins
2021-06-24T18:45:52Z D! [agent] Starting service inputs
2021-06-24T18:45:57Z D! [agent] Stopping service inputs
2021-06-24T18:45:57Z D! [agent] Input channel closed
2021-06-24T18:45:57Z D! [agent] Stopped Successfully
> dovecot,host=ac,server=10.55.242.189,type=global auth_cache_hits=0i,auth_cache_misses=0i,auth_db_tempfails=0i,auth_failures=0i,auth_master_successes=0i,auth_successes=0i,clock_time=0,disk_input=0i,disk_output=0i,invol_cs=0i,mail_cache_hits=0i,mail_lookup_attr=0i,mail_lookup_path=0i,mail_read_bytes=0i,mail_read_count=0i,maj_faults=0i,min_faults=0i,num_cmds=0i,num_connected_sessions=0i,num_logins=0i,read_bytes=0i,read_count=0i,sys_cpu=0,user_cpu=0,vol_cs=0i,write_bytes=0i,write_count=0i 1624560357000000000
```

telegraf 1.19.0
```
$ usr/bin/telegraf --debug --config etc/telegraf/telegraf.conf --test
2021-06-24T18:40:00Z I! Starting Telegraf 1.19.0
2021-06-24T18:40:00Z D! [agent] Initializing plugins
2021-06-24T18:40:00Z D! [agent] Starting service inputs
2021-06-24T18:40:05Z E! [inputs.dovecot] Error in plugin: copying message failed for dovecot server '10.55.242.189:24242': read tcp 10.55.242.1:35066->10.55.242.189:24242: i/o timeout
2021-06-24T18:40:05Z D! [agent] Stopping service inputs
2021-06-24T18:40:05Z D! [agent] Input channel closed
2021-06-24T18:40:05Z D! [agent] Stopped Successfully
2021-06-24T18:40:05Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```

This PR.
```
$ ../pr9429/telegraf-1.20.0/usr/bin/telegraf --debug --config etc/telegraf/telegraf.conf --test
2021-06-24T18:40:16Z I! Starting Telegraf 
2021-06-24T18:40:16Z D! [agent] Initializing plugins
2021-06-24T18:40:16Z D! [agent] Starting service inputs
copying message failed after 5.000958463s for dovecot server '10.55.242.189:24242': read tcp 10.55.242.1:35172->10.55.242.189:24242: i/o timeout  --> is net.Error (timeout=true)2021-06-24T18:40:21Z D! [agent] Stopping service inputs
2021-06-24T18:40:21Z D! [agent] Input channel closed
2021-06-24T18:40:21Z D! [agent] Stopped Successfully
> dovecot,host=ac,server=10.55.242.189,type=global auth_cache_hits=0i,auth_cache_misses=0i,auth_db_tempfails=0i,auth_failures=0i,auth_master_successes=0i,auth_successes=0i,clock_time=0,disk_input=0i,disk_output=0i,invol_cs=0i,mail_cache_hits=0i,mail_lookup_attr=0i,mail_lookup_path=0i,mail_read_bytes=0i,mail_read_count=0i,maj_faults=0i,min_faults=0i,num_cmds=0i,num_connected_sessions=0i,num_logins=0i,read_bytes=0i,read_count=0i,sys_cpu=0,user_cpu=0,vol_cs=0i,write_bytes=0i,write_count=0i 1624560022000000000
```

**Comment by popey** [comment]
Latest update looks good.
```
$ ../pr9429v2/telegraf-1.20.0/usr/bin/telegraf --debug --config etc/telegraf/telegraf.conf --test
2021-06-24T19:50:16Z I! Starting Telegraf 
2021-06-24T19:50:16Z D! [agent] Initializing plugins
2021-06-24T19:50:16Z D! [agent] Starting service inputs
> dovecot,host=ac,server=10.55.242.189,type=global auth_cache_hits=0i,auth_cache_misses=0i,auth_db_tempfails=0i,auth_failures=0i,auth_master_successes=0i,auth_successes=0i,clock_time=0,disk_input=0i,disk_output=0i,invol_cs=0i,mail_cache_hits=0i,mail_lookup_attr=0i,mail_lookup_path=0i,mail_read_bytes=0i,mail_read_count=0i,maj_faults=0i,min_faults=0i,num_cmds=0i,num_connected_sessions=0i,num_logins=0i,read_bytes=0i,read_count=0i,sys_cpu=0,user_cpu=0,vol_cs=0i,write_bytes=0i,write_count=0i 1624564221000000000
2021-06-24T19:50:21Z D! [agent] Stopping service inputs
2021-06-24T19:50:21Z D! [agent] Input channel closed
2021-06-24T19:50:21Z D! [agent] Stopped Successfully

```

**Review by sspaink — APPROVED** [review]

**Review by reimda — APPROVED** [review]
Looks like this PR works the same as before the linter change so we should take it to fix the regression.

We should investigate whether dovecot provides a newer metric api (this is called the "old" api in dovecot docs) that is easier to use and doesn't require ignoring the timeout

**Pull request merged**
