### PR TITLE
Add tcp/udp check connection plugin

### PR DESCRIPTION
**Pull request by titilambert**
Hello ! Me again :)
An other plugin to check tcp/udp connection from telegraf agent.

### CODE REVIEW

**Comment by titilambert** [comment]
@sparrc Could you help me on this one ? I don't get what I did wrong :/
Thanks !

**Comment by titilambert** [comment]
@sparrc rebased with master, but I still don't get the error.

**Comment by sparrc** [comment]
@titilambert you might want to try basing your changes on a fresh branch, there shouldn't be 81 commits in this PR

As to the test failure, it looks like there might be invalid toml in your SampleConfig function

**Comment by sparrc** [comment]
@titilambert Could you make a new PR or rebase this one? Hard to review in it's current form, but it looks like there are some toml parse errors in your SampleConfig section.

**Pull request closed without merging**
