### PR TITLE
chore: Fix readme linter errors for input plugins E-L

### PR DESCRIPTION
**Pull request by reimda**
Use the linter in https://github.com/influxdata/telegraf/pull/10916 to clean up input plugin E-L readme markdown files.

The linter has more rules for input plugins, including rules that require sections for example output and metric format. I've fixed formatting problems, but quite a few of the plugins don't have content for the required sections. They will require some research, so there is more work to do in future PRs.

Here is the linter output. It shows which plugins lack which sections.

```
plugins/inputs/ecs/README.md:1: missing required section 'Example Output'
Fail plugins/inputs/ecs/README.md, 1 failed assertions
plugins/inputs/elasticsearch/README.md:1: missing required section 'Example Output'
Fail plugins/inputs/elasticsearch/README.md, 1 failed assertions
plugins/inputs/elasticsearch_query/README.md:1: missing required section 'Example Output'
plugins/inputs/elasticsearch_query/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/elasticsearch_query/README.md, 2 failed assertions
Pass plugins/inputs/ethtool/README.md
plugins/inputs/eventhub_consumer/README.md:1: missing required section 'Metrics'
plugins/inputs/eventhub_consumer/README.md:1: missing required section 'Example Output'
Fail plugins/inputs/eventhub_consumer/README.md, 2 failed assertions
plugins/inputs/example/README.md:1: missing required section 'Example Output'
Fail plugins/inputs/example/README.md, 1 failed assertions
plugins/inputs/exec/README.md:1: missing required section 'Metrics'
plugins/inputs/exec/README.md:1: missing required section 'Example Output'
Fail plugins/inputs/exec/README.md, 2 failed assertions
plugins/inputs/execd/README.md:1: missing required section 'Metrics'
plugins/inputs/execd/README.md:1: missing required section 'Example Output'
Fail plugins/inputs/execd/README.md, 2 failed assertions
Pass plugins/inputs/fail2ban/README.md
Pass plugins/inputs/fibaro/README.md
plugins/inputs/file/README.md:1: missing required section 'Example Output'
Fail plugins/inputs/file/README.md, 1 failed assertions
plugins/inputs/filestat/README.md:1: missing required section 'Example Output'
plugins/inputs/filestat/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/filestat/README.md, 2 failed assertions
plugins/inputs/fluentd/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/fluentd/README.md, 1 failed assertions
Pass plugins/inputs/github/README.md
plugins/inputs/gnmi/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/gnmi/README.md, 1 failed assertions
plugins/inputs/graylog/README.md:1: missing required section 'Example Output'
plugins/inputs/graylog/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/graylog/README.md, 2 failed assertions
Pass plugins/inputs/haproxy/README.md
plugins/inputs/http/README.md:1: missing required section 'Example Output'
Fail plugins/inputs/http/README.md, 1 failed assertions
plugins/inputs/http_listener_v2/README.md:1: missing required section 'Example Output'
Fail plugins/inputs/http_listener_v2/README.md, 1 failed assertions
Pass plugins/inputs/http_response/README.md
plugins/inputs/httpjson/README.md:1: missing required section 'Example Output'
plugins/inputs/httpjson/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/httpjson/README.md, 2 failed assertions
plugins/inputs/hugepages/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/hugepages/README.md, 1 failed assertions
plugins/inputs/icinga2/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/icinga2/README.md, 1 failed assertions
plugins/inputs/influxdb/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/influxdb/README.md, 1 failed assertions
plugins/inputs/influxdb_v2_listener/README.md:1: missing required section 'Example Output'
Fail plugins/inputs/influxdb_v2_listener/README.md, 1 failed assertions
plugins/inputs/intel_pmu/README.md:1: missing required section 'Example Output'
Fail plugins/inputs/intel_pmu/README.md, 1 failed assertions
plugins/inputs/intel_rdt/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/intel_rdt/README.md, 1 failed assertions
plugins/inputs/internal/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/internal/README.md, 1 failed assertions
Pass plugins/inputs/internet_speed/README.md
Pass plugins/inputs/interrupts/README.md
plugins/inputs/ipmi_sensor/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/ipmi_sensor/README.md, 1 failed assertions
plugins/inputs/iptables/README.md:36: long line in paragraph
plugins/inputs/iptables/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/iptables/README.md, 2 failed assertions
Pass plugins/inputs/ipvs/README.md
Pass plugins/inputs/jenkins/README.md
plugins/inputs/jolokia/README.md:1: missing required section 'Example Output'
plugins/inputs/jolokia/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/jolokia/README.md, 2 failed assertions
plugins/inputs/jolokia2/README.md:12: config next sibling isn't a fenced code block
plugins/inputs/jolokia2/README.md:1: missing required section 'Example Output'
plugins/inputs/jolokia2/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/jolokia2/README.md, 3 failed assertions
plugins/inputs/jti_openconfig_telemetry/README.md:1: missing required section 'Example Output'
plugins/inputs/jti_openconfig_telemetry/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/jti_openconfig_telemetry/README.md, 2 failed assertions
plugins/inputs/kafka_consumer/README.md:1: missing required section 'Example Output'
plugins/inputs/kafka_consumer/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/kafka_consumer/README.md, 2 failed assertions
plugins/inputs/kafka_consumer_legacy/README.md:1: missing required section 'Example Output'
plugins/inputs/kafka_consumer_legacy/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/kafka_consumer_legacy/README.md, 2 failed assertions
plugins/inputs/kapacitor/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/kapacitor/README.md, 1 failed assertions
plugins/inputs/kernel/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/kernel/README.md, 1 failed assertions
plugins/inputs/kernel_vmstat/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/kernel_vmstat/README.md, 1 failed assertions
Pass plugins/inputs/kibana/README.md
plugins/inputs/kinesis_consumer/README.md:1: missing required section 'Example Output'
plugins/inputs/kinesis_consumer/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/kinesis_consumer/README.md, 2 failed assertions
Pass plugins/inputs/knx_listener/README.md
Pass plugins/inputs/kube_inventory/README.md
Pass plugins/inputs/kubernetes/README.md
plugins/inputs/lanz/README.md:1: missing required section 'Example Output'
Fail plugins/inputs/lanz/README.md, 1 failed assertions
plugins/inputs/leofs/README.md:1: missing required section 'Example Output'
plugins/inputs/leofs/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/leofs/README.md, 2 failed assertions
plugins/inputs/linux_sysctl_fs/README.md:1: missing required section 'Example Output'
plugins/inputs/linux_sysctl_fs/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/linux_sysctl_fs/README.md, 2 failed assertions
plugins/inputs/logparser/README.md:1: missing required section 'Example Output'
plugins/inputs/logparser/README.md:1: missing required section 'Metrics'
Fail plugins/inputs/logparser/README.md, 2 failed assertions
Pass plugins/inputs/logstash/README.md
Pass plugins/inputs/lustre2/README.md
Pass plugins/inputs/lvm/README.md
```

### CODE REVIEW

**Comment by srebhan** [comment]
@reimda can you please fix: 
```
/github/workspace/plugins/inputs/elasticsearch_query/README.md:185:8 MD034/no-bare-urls Bare URL used [Context: "https://www.elastic.co/guide/e..."]
```

**Review by srebhan — COMMENTED** [review]
Thanks for the effort @reimda! Can you please take a look at the issues found by `markdownlint`!?

**Comment by reimda** [comment]
@srebhan I've fixed the markdownlint errors and I'm going to go ahead and merge so this doesn't get out of date again.

**Comment by Hipska** [comment]
Yeah, ignore my concern... I added it to the maintainers meeting minutes.

**Pull request merged**
