### PR TITLE
Add Filebeat input plugin

### PR DESCRIPTION
**Pull request by dmitryilyin**
Add a new Filebeat 6 Monitoring API input plugin.

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

### CODE REVIEW

**Comment by gl1ridae** [comment]
Hi! Any information regarding when it will be merged?

**Comment by Esity** [comment]
@gl1ridae what do you think about updating this to work for all beats(filebeat, packetbeat, metricbeat, etc) instead of just filebeat. They should all function pretty similar from a collection and metric perspective and it wouldn't require much for code changes

**Comment by gl1ridae** [comment]
@Esity Sounds great actually, just checked beats endpoints. I can try to figure it out and create mr.

**Comment by dmitryilyin** [comment]
@Esity Well, perhaps you're right. I've also make input for kafkabeat and it's almost identical.

I'll make a single input for "beat" instead.

**Comment by nferch** [comment]
Since this seemed pretty straightforward, started on merging the two, see https://github.com/nferch/telegraf/commit/416bb8eae172afce4a40f6847fc8191d6ff11167 . Seems to work with my Filebeat instance, don't have a Kafka instance to test it on.

What do y'all think? @gl1ridae @dmitryilyin

**Comment by sjwang90** [comment]
Closing this as we'd prefer the general #6653 Beat input plugin. Will re-open if we need to separate them (file, kafka, etc.) out. 

Please provide any feedback to PR #6653 and that will help us get it merged in.

**Pull request closed without merging**
