### PR TITLE
Add Syncthing plugin for gathering metrics

### PR DESCRIPTION
**Pull request by kradalby**
Monitor Syncthing instance, gather useful metrics :)

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by kradalby** [comment]
Anyone?

**Comment by danielnelson** [comment]
Can you take another pass over the README.md and make sure it matches the [EXAMPLE_README.md](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/EXAMPLE_README.md)

**Comment by kradalby** [comment]
Sorry, did that part a bit quick, hopefully it is better now :) please let me know if there is anything more I should change. 

I have been running it on my own system with three Syncthing instances since I opened the PR without error.

@danielnelson PTAL

**Comment by Diromns** [comment]
Looking forward to see this merged

**Comment by kradalby** [comment]
@danielnelson, let me know if you have any other changes in mind :) 

I’m have been running it since I made it, but I would like to use the upstream version rather than my own.

**Comment by kradalby** [comment]
Any update here? Should I check it against master?

**Comment by sjwang90** [comment]
Hello @kradalby! Would you be willing to submit this plugin as an [external plugin](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf? Telegraf users would be able to use the plugin sooner by having it as an external plugin since it wouldn't have to go through the typical review process. 

Here is some [information on external plugins](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) and using them with `execd`. Feel free to respond with any questions you may have.

**Comment by sjwang90** [comment]
Due to inactivity I'm going to close the issue here for now, but we'd love to see this as an external plugin.

**Pull request closed without merging**
