### PR TITLE
fix(json_v2): strange formatted comments in the README

### PR DESCRIPTION
**Pull request by irevoire**

### CODE REVIEW

**Comment by irevoire** [comment]
!signed-cla

**Review by srebhan — COMMENTED** [review]
Hey @irevoire thanks for looking into this. I fear neither the version before nor the version after your PR will work if fed to telegraf as the current TOML parser cannot parse comments in a line that also contains valid data. I.e. the line is either completely a comment or there is no comment in that line.

This being said, can you please move the comments _before_ the options to have a valid example?

**Comment by srebhan** [comment]
@irevoire any update on this PR?

**Comment by srebhan** [comment]
@irevoire any chance to work on fixing the issue in my comment?

**Pull request closed without merging**
