### PR TITLE
mqtt: Remove 'host' and 'stat' from output topic

### PR DESCRIPTION
**Pull request by sparrc**

### CODE REVIEW

**Comment by sparrc** [comment]
@shirou You wrote this output plugin, so I wanted you to review before I merge this:

1. Now that measurements have fields, I think that we don't need to split on "_"
1. The `host` topic level seemed a little unecessary to me, seems like we should just have the host in that spot each time (if it exists)
1. Why were you appending a `stat` topic level to some measurements?
1. Why the random client ID setting?

**Comment by shirou** [comment]
> 1. Now that measurements have fields, I think that we don't need to split on "_"

That is releyd on a usecase. I think there are two usecase to get system metrics.

1. want to get all information such as memory available, free, used...
2. want to get specific information such as memory available only.

If user want 1, subscribe `mem/+`. If user want 2, subscribe `mem/available`. I think this topic structure can answer these two usecases.

> 2. The host topic level seemed a little unecessary to me, seems like we should just have the host in that spot each time (if it exists)

Hmm, there are other system which have `prefix/host/<hostname>` topic structure. But I can not remember. So, if you want to remove `host` level, I agree.

> 3. Why were you appending a stat topic level to some measurements?

*level* is important on MQTT, especially using wildcard(* or +) to subscribe. To adjuest same level, I add `stat` if there are no sub type.

> 4. Why the random client ID setting?

On MQTT Specification, if other client which has same ClientId connect to the MQTT server, the previous client will be disconnected. I think user want to send from multiple telegraf, so ClientIds should be unique.

**Comment by sparrc** [comment]
thanks @shirou, I've left in the client ID setting for now then.

I'm not sure what to do about the measurement filtering on levels. Since metrics are now mostly defined as fields on a measurement, there is only one level (cpu), and then all of the fields (idle, system, etc) are within the string line-protocol representation.

One thing I've been thinking about is having an MQTT "Templating" system similar to graphite, where users can specify fields, measurements, and tags to turn into a topic, so if you had an influx metric like this:

```
cpu,cpuX=cpu0,host=foo.com usage_idle=90
```

and a template:

```
telegraf/cpuX/host/measurement/field
```

you would get an MQTT topic & payload like this:

```
telegraf/cpu0/foo.com/cpu/usage_idle 90
```

**Comment by shirou** [comment]
*Template* system in mqtt-out plugin seems very good idea. I worried about topic structure is defined by the plugin is not suite for some user. But if template system is introduced, it will be solved.
I appreciate if you would implement.

**Pull request merged**
