### PR TITLE
Allow stateful parsers

### PR DESCRIPTION
**Pull request by GeorgeMac**
closes: https://github.com/influxdata/telegraf/issues/6138

This is a work in progress.

It updates the `tail` plugin to only use the `parser.Parse` function instead of `parser.ParseLine`. This is a standard we would like to obvserve in all plugins going forward. Deprecating the ParseLine method. As per discussion in the above issue.

This brings with it other changes in the form of:

- `plugin.SetParserFunc` to be standard in place of `plugin.SetParser` allowing plugins to acknowledge when new parses are required. In the event that a parse may be stateful (e.g. csv).
- Update to `file` input plugin to call parser func per new file to be read. Rather than use same parser for each file.

TODO:

- [ ] better understand implications of stateful parsers for other parser consumers (other than just `file` and `tail`).

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Looking good, however I am starting to become nervous about how expensive creating a new parser can be.  To preserve behavior, in all plugins other than tail we would need to recreate the parser on each call to Parse(), and in ServiceInput plugins especially the `*_consumer` plugins we could be calling Parse thousands of times per second.

We ought to look closer into the performance difference and if it's going to be noticeable try to improve it.  I think we can rework the factory code in `plugins/parsers/registry.go` and get some large performance gains.

**Comment by GeorgeMac** [comment]
@danielnelson I see the concern. I am just wondering if we need to address all of it in one go.

This PR does move all plugins to `SetParserFunc`. However, the majority of them call it immediately and set the resulting parser forever. Giving most existing plugins exactly the same behavior.

The one difference (for now) being the `tail` + `file` plugins. Which now produce one parser per file they consume.

I am conerned that existing things that interact with the csv parser may break due to the slight adjustment in behavior.

**Comment by GeorgeMac** [comment]
Ahh I see one problem. SetParserFunc needs to take a `parsers.ParseFunc` which can return an error. 
Makes sense. I missed that. Will re-assess.

**Comment by srebhan** [comment]
@GeorgeMac: Any progress on this?
To solve the performance issue, we might add a `NewInstance()` function to the parser, letting the parser itself decide if it is stateful (while CSV is, JSON is not) and either return a new instance of the parser or create a singleton and return that.

**Comment by srebhan** [comment]
@GeorgeMac any news on this PR?

**Comment by powersj** [comment]
Hi,

This PR has not been touched in a while and as a result I am going to close it. We are happy to review again once someone picks this back up with the suggested changes and rebased on master.

Thanks!

**Pull request closed without merging**
