### PR TITLE
Add notes about running tests on mac and the need to install dependencies

### PR DESCRIPTION
**Pull request by jmccann**
Some notes/steps that may help others when trying to run tests for first time.

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
I'm torn on this, while this is good information it would be so much nicer if we could figure out why the tests are hanging.

**Comment by jmccann** [comment]
I'll leave it to you.  ;)

My thoughts on this though are that having the info would have saved me personally several hours of time.  The issue has been around for 5-6months so not sure how timely it will get addressed.  

Perhaps a note to #3158 could be added to remove the section I've added once the issue is fixed?

**Comment by danielnelson** [comment]
Sorry about the headache this caused, I think what we should do is add this to the test that hangs, is this enough to get tests working on Mac?:
```
if runtime.GOOS != "darwin" {
	t.Skip("Skipping due to hang on Darwin; issue #3158")
}
```

**Comment by danielnelson** [comment]
We went through the tests this summer and got everything working on Darwin.  It is probably a matter of time before they break again, since we have no CI system setup for testing, which is unfortunate but I'm not sure how to solve.

I think instead of adding this documentation, we just need to fix any test issues as they come up.

**Pull request closed without merging**
