### PR TITLE
fix(inputs.sqlserver): Suppress error on secondary replicas

### LINKED ISSUE #9530: SQLServer Plugin: Throwing Errors when HADR DB Not Readable
### Relevant telegraf.conf:
```toml
[[inputs.sqlserver]]
  servers = ["Server=xxxxxxxxxxx;Port=1433",]

  exclude_query = []

  database_type = "SQLServer"
```

### System info:
All Windows versions
Telegraf version 1.18.0

### Steps to reproduce:
Setup the sqlserver input plugin to collect data against a SQL Server instance that is hosting secondary databases in an AlwaysOn Availability group. These databases aren't configured for read-only access.

No queries are excluded from the sqlserver input plugin.

### Expected behavior:

No errors to be thrown

### Actual behavior:

The below errors are thrown as the database can't be queried:

[inputs.sqlserver] Error in plugin: Script SQLServerRequests failed: mssql: The target database, 'xxxxxxxxxx', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

[inputs.sqlserver] Error in plugin: mssql: The target database, 'xxxxxxxxxx', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

### PR DESCRIPTION
**Pull request by deweter**
- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

Resolves #9530

This PR suppresses an error which we may encounter, if we query sys.dm_exec_requests DMV against a SQL Server hosting secondary replicas.

### CODE REVIEW

**Comment by srebhan** [comment]
@deweter can you please check why `go.sum` was changed and if that's correct please run `make tidy`.

**Comment by spaghettidba** [comment]
I believe that `azuresqlmanagedqueries.go` should be changed as well, since managed instances can be part of AGs.

**Comment by deweter** [comment]
> I believe that `azuresqlmanagedqueries.go` should be changed as well, since managed instances can be part of AGs.

@spaghettidba - I changed it. Initially, I skipped it as I didn't test it, but in general I do agree that the error could appear most probably there too.

> @deweter can you please check why `go.sum` was changed and if that's correct please run `make tidy`.

@srebhan - Sorry, my mistake - I removed a change to `go.sum`

**Comment by srebhan** [comment]
@spaghettidba and @Trovalo any comments?

**Review by srebhan — APPROVED** [review]
Code-wise this looks good to me. Waiting for @Trovalo's ok on this...

**Review by Trovalo — APPROVED** [review]

**Review by powersj — APPROVED** [review]

**Pull request merged**
