### PR TITLE
Add Netflow input plugin from @tetsusat

### PR DESCRIPTION
**Pull request by shigechika**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by shigechika** [comment]
This plugin is forked from github.com/tetsusat/telegraf/tree/netflow/plugins/inputs/netflow
Please merge.

**Comment by robcowart** [comment]
I have reviewed the code for this plugin and it has a number of issues. The largest problem is that it looks like IPFIX information element definitions in `ipfix_field_table.go` are not PEN-specific. PEN-specific IEs eliminate the IE ID conflicts that plagued Netflow v9. It seems this plugin assumes that the flow records will come from Cisco (it uses this list of IEs from Cisco https://gblogs.cisco.com/jp/2017/04/deepdive-netflow/).

**Comment by dapryor** [comment]
@shigechika is there any plan to update your version of the netflow plugin and resubmit a PR? I know it has been about 2 years, but worth a shot asking ;)

**Comment by sjwang90** [comment]
@dapryor 
1. Please take a look at this PR. 
1. [Here](https://github.com/sjwang90/telegraf/tree/netflow-input/plugins/inputs/netflow) is the Netflow Plugin that was removed from #6427.
   1. We are looking to have a Netflow plugin as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) since the current plugin uses code generation. Telegraf does not do that elsewhere and it's not part of the build process. 
   1. We would love someone to champion this and try it on different devices. Every implementation we've seen is very different making it a weird protocol to work with.

**Pull request closed without merging**
