### PR TITLE
Add Runc Input

### PR DESCRIPTION
**Pull request by kevinschoon**
Hi -- 

Thank you all for building such a great tool!

I have implemented a plugin with support for collecting metrics from [runc](github.com/opencontainers/runc). It executes the `runc` binary directly and collects metrics described in the [libcontainer/cgroups](https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/stats.go) package. I choose to add [containerd/go-runc](https://github.com/containerd/go-runc) as dependency because it simplifies the collector code and provides a clean abstraction. Now that the OCI v1 [spec](https://www.opencontainers.org/blog/2017/07/19/oci-v1-0-bringing-containers-closer-to-standardization) has been finalized, and [runc](https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc3) has (nearly) reached 1.0 things should be fairly stable going forward.

Note that I have only tested this plugin on Linux.

Thank you!

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Thanks for the pull request.  To help with prioritization, can you briefly describe your usage of runc, why do you want/need this instead of the existing docker input plugin?

**Comment by kevinschoon** [comment]
@danielnelson I am building a Linux distribution on top of [linuxkit](https://github.com/linuxkit/linuxkit). Linuxkit uses runc directly at boot and indirectly via [containerd](https://github.com/containerd/containerd). I want to use Telegraf as part of the telemetry system in my OS. I have not released the project publicly yet but expect to sometime soon in the future.

The plugin could also be useful in a few other ways:
 * It's a common pattern to use runc with systemd unit files.
 * Provide monitoring for other projects that are built on top of runc (not sure how many others are using runc directly).

**Comment by russorat** [comment]
Hi @kevinschoon , have you released your project yet?

**Comment by kevinschoon** [comment]
@russorat sadly I am no longer pursuing the [project](https://github.com/mesanine/mesanine) I initially wrote this PR for. I can still imagine it would be useful for people who want to monitor `runc` directly but to be honest that is probably a small target audience. Merging this is probably not worth the additional complexity of adding it to the Telegraf codebase unless someone can benefit from it.

If this seems useful in the future please feel free to reach out and I will be happy to open up a new PR and get it merged. 

Thank you!

**Pull request closed without merging**
