### PR TITLE
Kafka consumer improvement

### PR DESCRIPTION
**Pull request by neonmori**
add supports of kafka 0.9+ new consumer with TLS
add timestamp selector to JSON parser

### Required for all PRs:

- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by sparrc** [comment]
1. Don't put two features into a single PR
2. Why does the kafka consumer need to track 0.9+ and pre-0.9 consumers? why not use the same library to connect to both? (ie, just use github.com/bsm/sarama-cluster to connect to any kafka cluster, there is no need to keep the previous functionality)
3. Aren't we already supporting kafka with TLS? Can you explain what you are fixing with your PR?

**Comment by neonmori** [comment]
1. I will make another PR
2. sarama-cluster only supports 0.9+, we need both of them to maintain the back-compatibility. You can see the reference here [sarama-consumer](https://github.com/Shopify/sarama/blob/master/consumer.go#L41).
3. Since kafka 0.9, they begin to provide 2 types of consumers, old consumers are what we have in the existing consumer plugin which I'm not sure if they have TLS support and the new consumers. What I am trying to fix is the compatibility of kafka_consumer plugin to Kafka 0.9+.

**Comment by sparrc** [comment]
OK, fair enough, but is there a way that you can dynamically determine which type of kafka cluster it is, rather than requiring a boolean flag?

**Comment by neonmori** [comment]
With the new kafka, users have to use a flag --new-consumer to explicitly specify the version of consumer they want to use. This boolean flag is actually following the official style. Users are required to be aware of the consumers they need to use.

**Comment by sparrc** [comment]
can you link to documentation for that?

**Comment by neonmori** [comment]
@sparrc 
https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/tools/ConsoleConsumer.scala
Basically there is not dynamic way to tell.

**Pull request closed without merging**
