### PR TITLE
Change the timeout from all queries to per query

### LINKED ISSUE #9377: [SQL Server Input plugin] Configurable Query Timeout
## Feature Request

Introduce configurable timeout for queries in SQL plugin to prevent telegraf queries blocking SQL server resources.

### Proposal:
There is no timeout for telegraf queries in SQL server plugin today. Telegraf could potentially trigger long running queries and cause performance issues. Introducing timeouts in queries will prevent long running queries from happening. There could be many reasons why even a simple DMV query gets blocked or executes much slower than expected, so a timeout would be a good thing in general. This timeout is configurable. If no timeout is specified for the connection string, the default timeout will be 30s. Customers can also set the timeout to some value that fits their scenario.

### Current behavior:
No timeout for SQL server plugin queries. Telegraf could have long running queries that cause performance issues.
### Desired behavior:

1. If the user does not specify query timeout value, we set the query timeout to 30s.
2. If the user specifies a different timeout value in telegraf.conf, we use that value as query timeout.

### Use case: 
Timeout could prevent telegraf from introducing long running queries causing performance issues.

I'm willing to make the change, but wanted to gather feedback before I create a PR.

### PR DESCRIPTION
**Pull request by bhsu-ms**
### Required for all PRs:

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.

resolves #9377 

As discussed in #9377. Current implementation has a timeout over all SQL queries. If there's one long running query, the rest of the other queries will be dropped due to timeout. This PR changes the timeout to per query instead, so only the long running query will be dropped.

### CODE REVIEW

**Comment by bhsu-ms** [comment]
@srebhan could you help take a look at this? Thank you!

**Review by srebhan — COMMENTED** [review]
The code looks good to me. Thanks for working on this!

Can you please additionally improve the `timeout` documentation such that it becomes clear that the timeout is _per query_ and not _per gather_? You might want to put a small comment in `sampleConfig` and `README.md`...

**Review by srebhan — APPROVED** [review]
Perfect. Thank you @bhsu-ms!

**Review by MyaLongmire — APPROVED** [review]

**Review by sspaink — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
