### PR TITLE
fix(inputs.ping): Add option to force ipv4

### PR DESCRIPTION
**Pull request by powersj**
## Summary

Similar to ipv6 option, add ipv4 option and ensure both are not true.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

fixes: #15005

### CODE REVIEW

**Comment by detobate** [comment]
Thanks, will test it out later today.

I actually was going to submit a PR doing exactly this, but got side tracked, sorry.
Only comment is that instead of raising an error if both vars are true, you could set address family to "ip" which explicitly tells Go Ping to use either address family.  
i.e.,

```
	if p.IPv4 && p.IPv6 {
		pinger.SetNetwork("ip")
	}
```
	
	
	
https://pkg.go.dev/github.com/prometheus-community/pro-bing#Pinger.SetNetwork

**Comment by powersj** [comment]
> you could set address family to "ip" which explicitly tells Go Ping to use either address family.

This appears to already be the default. However, I've updated the PR to not error.

**Review by DStrand1 — APPROVED** [review]

**Review by srebhan — APPROVED** [review]
I'm fine with merging as-is, but I really think you should error if both options are true. The comment clearly says IPvX **only** so IPV4 *only* **and** IPv6 *only* is not possible logically and is potentially pointing to a misconfiguration...

I think naming the options `ipv4_only` or `ipv6_only` would be better but that's just a matter of taste I guess...

**Comment by detobate** [comment]
I too dislike the ambiguity of the variable names, but figured renaming the existing one would break backwards compatibility and probably be a non-starter?

**Comment by powersj** [comment]
> I too dislike the ambiguity of the variable names, but figured renaming the existing one would break backwards compatibility and probably be a non-starter?

Agreed, this is why I avoided renaming anything.

**Pull request merged**
