### PR TITLE
feat(inputs.influxdb_listener): Add token based authentication

### LINKED ISSUE #9445: Telegraf to accept tokens on v1 InfluxDB input plugins
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add tokens (alongside existing username/password) to the [InfluxDB Listener v1 plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/influxdb_listener).
- Use telegraf as an aggregator in front of the Cloud 2 API with v1 capability.
- Even though v2 listener https://docs.influxdata.com/telegraf/v1.18/plugins/#influxdb_v2_listener exists,
I was hoping the `inputs.influxdb_listener` would provide similarly a “fake” v2 with `token = user:password` (just like InfluxDB 1.8) on the same port as the regular v1 API (the v2 listener *I think* would require a different port).

### Current behavior:
Telegraf InfluxDB Listener v1 input plugin only supports username/password not tokens.

### Desired behavior:
Allow for token configuration in `inputs.influxdb_listener`.
The token would just be what’s listed in compatibility API: https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/#basic-authentication

### Use case: 
Make migration experience from 1.x to 2.x more seamless. 

For example, while using the Go library (https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility)
and noticed it didn't work with Telegraf.

### PR DESCRIPTION
**Pull request by srebhan**
- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #9445

This PR adds token based authentication to the InfluxDB v1 listener to complement the authentication methods supported. This is especially relevant to get a forward compatibility with v2.x.

### CODE REVIEW

**Review by powersj — COMMENTED** [review]
@srebhan thanks for this PR and looking at this feature request.

Looking at the original request, the user seems to be asking for "token" authentication. When I think about token authentication, especially in reference to v2, I think of the generated string API tokens, not a JWT token. 

Effectively I was thinking we would have a a `token` value just like we have in the influxdb_v2 output.

Was that not your understanding?

Thanks!

**Comment by srebhan** [comment]
@powersj I talked to Geoffrey yesterday and he pointed me to the 1.8 server code. I reproduced what is there. The downside of a fixed token is that it cannot have an expiry date and token without an expiry won't work with InfluxDB 1.8...

**Comment by powersj** [comment]
That is not my understanding of reading the feature request. The background is a user is transitioning from v1 to v2 and wants that process to go more smoothly. The current behavior lists:

> Telegraf InfluxDB Listener v1 input plugin only supports username/password not tokens.

They want the v1 input plugin to support tokens which is a v2 auth mechanism. Looking further down they use [the go client library](https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility) as an example:

> Use the form username:password for an authentication token. Example: my-user:my-password. Use an empty string ("") if the server doesn't require authentication.

The JWT tokens are a legacy 1.8 auth mechanism, which is why I still think the correct item is allowing a username/password?

**Comment by srebhan** [comment]
Sorry, but isn't this what I added in line 116? What am I missing here? I just added _all_ documented auth mechanisms as per documentation, so you can use `Authentication: Basic <encoded user/password>` , `Authentication: Token <user>:<password>` **and** `Authentication: Bearer <token>`...

**Comment by powersj** [comment]
> Sorry, but isn't this what I added in line 116? What am I missing here?

If I was a user who wanted to use backwards compatibility, again I was expecting a token parameter in the sample config itself, again similar to the client libraries.

You are re-purposing the basic auth username and password configuration fields. To someone coming from v2 that is not obvious that they can use that as a token backwards comparability. At the very least you need to update the docs.

**Comment by powersj** [comment]
I've gone through this again and realized my comment may have come across a little harsh - my point is that the code is fine, rather we have not guided the user to the fact that this is even possibility.

Updating the sample config section near basic auth username/password to state that these can be set for users using compatibility mode via "username:password" is all that is needed to land this.

**Comment by srebhan** [comment]
@powersj no worries about the comment, I don't classify this as harsh, you have to try harder! ;-) Will add a comment as soon as possible to the sample-config.

**Review by powersj — APPROVED** [review]
Thank you!

**Pull request merged**
