### PR TITLE
feat: user interface guided tool to build Telegraf with a subset of plugins

### PR DESCRIPTION
**Pull request by sspaink**
This pull request introduces a new way to generate a sample config using a terminal user interface. The motivation behind introducing a user interface is that creating a TOML config is a stumbling block for new users and [using the filter flags](https://docs.influxdata.com/telegraf/v1.21/introduction/getting-started/#create-and-edit-the-configuration-file) to create a sample config isn't obvious. At the moment, this is a **draft and experimental change** that I would like to have community feedback on to see if we want to introduce it to Telegraf. Please let me know if you are interested in this change, and if you have time try out the artifacts to see if it works for you. This change was inspired by the work I did with @appletreeisyellow  during an internal influxdata hackathon, where we worked together to re-imagine the help page our work can be found [in this branch](https://github.com/influxdata/telegraf/tree/bubbletea). This pull request takes this original work further by introducing a more functional feature through re-imaging the `--sample-conifg` flag with a user interface.

The framework to make this possible is [bubbletea](https://github.com/charmbracelet/bubbletea), so here is a telegraf tiger drinking bubble tea:

tea_sipping_tiger_smaller

# A GIF walking through the UI flow

bubbletea

# General feature overview

* A new flag `--sample-config-ui`
* Introduction of [bubbletea](https://github.com/charmbracelet/bubbletea) and associated projects (e.g. bubble, lipgloss)

### Home page

The first page is a greeting page to let the user know about this utilities purpose, I thought this would be friendlier then dropping them into the plugin selection page.

<details>
<summary>Home Page Screenshot</summary>

image

</details>

### Plugin selection page

This is the most complicated page, provides tabs for each plugin type and a list of plugins associated with the type. You can filter the list, and like a grocery list select the plugins you want included in your final config.

<details>
<summary>Plugin Selection Page Screenshots</summary>

image

image

image

</details>

### Plugin Info page

From the plugin selection page you can hit `i` to get more info on a plugin, this will display the full description in case it was shortened in the selection page and also the sample config.

<details>
<summary>Plugin Info Page Screenshot</summary>

image

</details>

### Plugin Review Page before Save

From the plugin selection page you can hit `s` to generate the sample config, this page allows the user to review what has been selected and choose to go back and re-select plugins or hit `enter` to save to a file called `telegraf.conf`.

<details>
<summary>Plugin Review Page Screenshots</summary>

image

</details>

### CODE REVIEW

**Comment by Hipska** [comment]
Would love to see this as a separate binary where it can also build a minimal telegraf version based on the selected plugins.

One feature request would be the option for plugins to add additional screen/wizards so additional configuration options can be pre-filled. Use case: snmp input could ask for a table where it then would generate some sensible configuration to be able to poll that table..

**Comment by sspaink** [comment]
@Hipska I think updating this to allow building a minimal Telegraf is a great idea, I can use @srebhan (https://github.com/influxdata/telegraf/pull/8519) and @powersj  (https://github.com/powersj/telegraf-build) work to make this possible. For UI updates It think I would just require updating the `Save` page to show it can build both a Telegraf binary and a configuration, and allow the user to choose which one.

I like the feature request idea to be able to edit the config, I am thinking to avoid the scope getting too big it would be better to do it in a separate PR.

I've updated the change to be a separate binary from Telegraf called `telegraf_build`, Telegraf Tiger shows the binaries but it appears as a duplicate ATM but if you click on the second entry it will download the `telegraf_build` artifact. For the CI I am thinking only building this binary if there is a change to the files to avoid extra time for every PR.

**Comment by Hipska** [comment]
> I like the feature request idea to be able to edit the config, I am thinking to avoid the scope getting too big it would be better to do it in a separate PR.

Yeah, fine by me. But you could already keep this in mind when modelling this thing so future addition would fit nicely.

**Comment by sspaink** [comment]
I am going to close this PR for now because it has a big problem that the resulting binary size is the same as Telegraf. Also after some discussion it would be better for this to remain as a beginner utility for now that just helps generate the sample config and have the builder tool for Telegraf be purely CLI to help get it merged quickly so people can begin using it. 

In the meantime, I've moved the code to a separate repo in case anyone wants to easily get it and play with it: https://github.com/sspaink/TelegrafCompanion

**Pull request closed without merging**
