### PR TITLE
Add SignalFx output plugin

### PR DESCRIPTION
**Pull request by ewbankkit**
### Required for all PRs:
- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

For those whose love Telegraf for metrics collection but prefer to use [SignalFx](https://signalfx.com/) for storage and analysis.
May need to revisit SignalFx datapoint type once/if https://github.com/influxdata/telegraf/pull/1694 is merged.

### CODE REVIEW

**Comment by ewbankkit** [comment]
OK, need to add back **opencontainers** to `Godeps`...

**Comment by ewbankkit** [comment]
* Rebased with latest **master**
* Added support for Telegraf metric types
* Added name sanitization, similar to Prometheus output plugin

**Comment by ewbankkit** [comment]
I'll follow and integrate with the outcome of https://github.com/influxdata/telegraf/issues/1717 and https://github.com/influxdata/telegraf/issues/1718.

**Comment by nhaugo** [comment]
@ewbankkit Sorry about the delay on the merge, but it looks like you figured out the reason. We should be able to get this merged once we have the plugins checked in.

**Comment by ewbankkit** [comment]
Is an `exec` output plugin in the works: https://github.com/influxdata/telegraf/issues/544?

**Comment by sparrc** [comment]
@ewbankkit not at the moment, but we may want to prioritize that for a 1.x release to better enable external plugins.

**Comment by ewbankkit** [comment]
Addresses https://github.com/influxdata/telegraf/issues/923.

**Comment by ewbankkit** [comment]
Closing this PR as an exec output plugin seems to be the longer-term way forward.
See https://github.com/influxdata/telegraf/pull/1999.

**Comment by amoghe** [comment]
@ewbankkit any chance we could revive this and have a built-in signalfx output plugin (seeing as how the exec one never fully landed)?

If you could point out the remaining work you'd like to see as part of this PR, I'd be happy to take over and see it through to completion.

**Comment by ewbankkit** [comment]
@amoghe Please feel free to take this over.

**Pull request closed without merging**
