### PR TITLE
DNS Activity plugin

### PR DESCRIPTION
**Pull request by growse**
This is a plugin that uses libpcap (specifically the miekg/pcap wrapper) to aggregate DNS answers and errors being received by the system. The answers break down per DNS Type and aggregates the count and the number of bytes per answer. The errors break down by error type and just counts them (1 per DNS packet).

At the moment, this is only tested on Linux. It'd be interesting to think about making the packet capture more cross-platform.

Testing is a little challenging as you have to actually interact with the network and a remote DNS server to test to see if the metrics are collected as expected. This could probably be enhanced in the future by spinning up a dedicated mini DNS server and poking it over localhost.
### Required for all PRs:
- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [X] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by growse** [comment]
Looks like there's issues on testing, I'm assuming related to not having capture provisions. Not sure what the right way forward is on this, assuming that you need `CAP_NET_RAW` to capture and `CAP_NET_ADMIN` to enumerate devices.

**Comment by rlex** [comment]
is that something similar to collectd dns plugin?

**Comment by growse** [comment]
I'm not really familiar with collectd, but looks like it.

**Comment by russorat** [comment]
Closing this due to inactivity. If you are interested in this, please comment.

**Pull request closed without merging**
