### PR TITLE
Move CloudWatch rate limit to config

### PR DESCRIPTION
**Pull request by tmonk42**
### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

Reference #1670

### CODE REVIEW

**Comment by sparrc** [comment]
thanks @tmonk42, but you should also set 10 to be the default in the `init()` function.

**Comment by tmonk42** [comment]
I dug through several other input plugins and found a common pattern of adding a setDefaults or setDefaultValues function inside of Gather(). I opted to follow this pattern rather than set it in init(). I hope that is acceptable.

**Comment by sparrc** [comment]
sorry, that's not acceptable, please put it in the init() function. There's no point in calling setDefaults on every Gather when it can only be set once.

If there are other plugins doing that then they should be changed to use the init() method.

**Comment by tmonk42** [comment]
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/conntrack/conntrack.go#L40
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/dns_query/dns_query.go#L80

Looks like the Ceph input plugin was updated to move to the init() function for defaults just a few hours ago. I'll update again :) thank you!

**Comment by sparrc** [comment]
thanks @tmonk42!

**Pull request merged**
