### PR TITLE
Save docker timestamp as offset and resume from offset

### PR DESCRIPTION
**Pull request by i-prudnikov**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

This PR comes from #7068, the second part - track message timestamps in external file. This feature inspired by fluentd.

### CODE REVIEW

**Comment by i-prudnikov** [comment]
@danielnelson , Hello Daniel, could you please provide your opinion about this PR? The first check failed because of circle ci problem.

**Comment by i-prudnikov** [comment]
Since I got no replies here,  reopen with updated upstream to merge latest changes #7697

**Comment by danielnelson** [comment]
@i-prudnikov Don't worry I see you, I read every comment even if I don't reply.  I'm just super busy and haven't been able to take a look yet.

**Comment by i-prudnikov** [comment]
@danielnelson, thank you for letting me know.

**Pull request closed without merging**
