### PR TITLE
Adding new Input-Plugin for Atlassian Jira statistics over JQL

### PR DESCRIPTION
**Pull request by LukyLuke**
I am not that familiar with go, hope it conforms your needs.

This plugin is able to fetch statistics based on JQL from Atlassian Jira. For example to measure the amount of new, resolved and rejected Bugs or whatever.

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by jtsunne** [comment]
I've tested this pull request, but this code is working only with JIRA without credentials
can you add credentials for JIRA (token)?

**Comment by LukyLuke** [comment]
Sorry for the delay @jtsunne 
Thanks for testing!

I just added BasicAuthentication and Toke-Authentication - what is the same as I found out :)

**Comment by jmwaldrip** [comment]
Is there any updates on this? Would be awesome to be able to use this!

**Comment by LukyLuke** [comment]
I have no idea how to push this forward that one from the owners takes a look on here.

**Comment by danielnelson** [comment]
Sorry all, I do see this, but unfortunately it might be some time still before I will be able to find the time to review this.  In the meantime, here are links to the builds of the pull request, I hope these will help anyone who wants to test out the plugin:

- [telegraf-1.10.0~ce8bbb07-0.x86_64.rpm](https://27738-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.10.0~ce8bbb07-0.x86_64.rpm)
- [telegraf_1.10.0~ce8bbb07-0_amd64.deb](https://27738-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.10.0~ce8bbb07-0_amd64.deb)
- [telegraf-1.10.0~ce8bbb07_windows_amd64.zip](https://27738-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.10.0~ce8bbb07_windows_amd64.zip)

**Comment by zimmertr** [comment]
Excited for this to be merged in!

**Comment by Punkoivan** [comment]
Hello folks,
thanks for your great job!

Trying to run it with ubuntu and get an error:
```
2019-10-26T20:14:38Z I! Starting Telegraf 
2019-10-26T20:14:38Z I! Using config file: /etc/telegraf/telegraf.conf
panic: reflect: Elem of invalid type

goroutine 1 [running]:
reflect.(*rtype).Elem(0x20ff8e0, 0xc0003b5148, 0x199)
	/usr/local/go/src/reflect/type.go:923 +0x143
github.com/influxdata/telegraf/vendor/github.com/influxdata/toml.UnmarshalTable(0xc0000cf900, 0x202a640, 0xc0003b5130, 0xc0000a4d80, 0x0)
	/go/src/github.com/influxdata/telegraf/vendor/github.com/influxdata/toml/decode.go:183 +0x172f
github.com/influxdata/telegraf/internal/config.(*Config).addInput(0xc00040ad20, 0xc0004016e0, 0x4, 0xc0000cf900, 0x0, 0x0)
	/go/src/github.com/influxdata/telegraf/internal/config/config.go:926 +0x16a
github.com/influxdata/telegraf/internal/config.(*Config).LoadConfig(0xc00040ad20, 0x234ccd7, 0x1b, 0x3f4f728, 0x0)
	/go/src/github.com/influxdata/telegraf/internal/config/config.go:681 +0x6f3
main.runAgent(0x265ad80, 0xc0000c5180, 0x3f4f728, 0x0, 0x0, 0x3f4f728, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:122 +0x32a
main.reloadLoop(0xc0000a0180, 0x3f4f728, 0x0, 0x0, 0x3f4f728, 0x0, 0x0, 0xc00025dd58, 0x0, 0x0, ...)
	/go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:102 +0x267
main.main()
	/go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:386 +0x4ba
```

When trying to use "" across username and password and this error without quotes:

```
vagrant@ubuntu-bionic:~$ sudo telegraf --test
2019-10-26T20:17:03Z I! Starting Telegraf 
2019-10-26T20:17:03Z I! Using config file: /etc/telegraf/telegraf.conf
2019-10-26T20:17:03Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, toml: line 1382: parse error
```

Using default config with my URL, creds and jql.

If you need more debug info - please let me know.

Thanks,
Ivan

**Comment by glinton** [comment]
@Punkoivan that looks like a config file related panic, try using single brackets surrounding the `authentication` table - `[inputs.jira.authentication]` rather than two (two denote it's a slice, which it's not)

**Comment by Punkoivan** [comment]
Thanks @glinton, it works!

So:
auth must be wit a single brackets:
`[inputs.jira.authentication]`
and jql with double:
`[[inputs.jira.jql]]`

**Comment by izaakk** [comment]
Hello, any idea on when these changes can be merged? It would be awesome to be able to use this in my environment.

**Comment by sjwang90** [comment]
This plugin looks like it would be a useful plugin but may be better as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md). Would you be willing to submit this plugin as an [external plugin](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf? Telegraf users would be able to use the plugin sooner by having it as an external plugin since it wouldn't have to go through the typical review process.

**Comment by howardyoo** [comment]
Would be very happy to see if this plugin can be available to try it out!

**Comment by srebhan** [comment]
@LukyLuke are you still interested in working on this PR?

**Comment by LukyLuke** [comment]
> @LukyLuke are you still interested in working on this PR?

Due to the fact that this takes Years and not days/weeks, I moved forward to an other TSDB.
Therefore I will not push this forward, sorry...

**Comment by sjwang90** [comment]
If anyone would like to take this PR over we will accept this as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf.

Otherwise we'll look to close this PR.

**Comment by srebhan** [comment]
@LukyLuke I'm sorry this took so long and can understand that you will not continue here. If anybody wants to step up bringing this forward as internal plugin, I promise to review it in a timely manner.

**Comment by sjwang90** [comment]
Going to close this PR as there hasn't been any one willing to pick up this PR and it's not a high enough priority item for the influx team to takeover.

**Pull request closed without merging**
