### PR TITLE
Rework mqtt_consumer connect/reconnect

### LINKED ISSUE #4580: MQTT connected, not pushing data to influxdb
I have configured the following Influxdb in telegraf.conf:
```
[[outputs.influxdb]]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  ##
  ## Multiple urls can be specified as part of the same cluster,
  ## this means that only ONE of the urls will be written to each interval.
  # urls = ["udp://127.0.0.1:8089"] # UDP endpoint example
  urls = ["https://fqdn"] # required
  ## The target database for metrics (telegraf will create it if not exists).
  database = "simcom7000e_test" # required
  ## Name of existing retention policy to write to.  Empty string writes to
  ## the default retention policy.
  retention_policy = ""
  ## Write consistency (clusters only), can be: "any", "one", "quorum", "all"
  write_consistency = "any"

  ## Write timeout (for the InfluxDB client), formatted as a string.
  ## If not provided, will default to 5s. 0s means no timeout (not recommended).
  timeout = "5s"
  username = "user"
  password = "pwd"
  ## Set the user agent for HTTP POSTs (can be useful for log differentiation)
  user_agent = "telegraf-srv-ubn-services-1"
  ## Set UDP payload size, defaults to InfluxDB UDP Client default (512 bytes)
  # udp_payload = 512

  ## Optional SSL Config
  # ssl_ca = "/etc/telegraf/ca.pem"
  # ssl_cert = "/etc/telegraf/cert.pem"
  # ssl_key = "/etc/telegraf/key.pem"
  ## Use SSL but skip chain & host verification
  insecure_skip_verify = true
  namepass = ["*_simcom7000e_test"]
`
```
And the following MQTT input config in telegraf.conf
```
[[inputs.mqtt_consumer]]
  name_suffix = "_simcom7000e_test"
  data_format = "json"
  ## MQTT broker URLs to be used. The format should be scheme://host:port,
  ## schema can be tcp, ssl, or ws.
  servers = ["ssl://fqdn"]
  ## MQTT QoS, must be 0, 1, or 2
  qos = 0
  ## Connection timeout for initial connection in seconds
  connection_timeout = "30s"

  ## Topics to subscribe to
  topics = [
    "simcom7000e1",
  ]
  client_id = "telegraf"
  ## username and password to connect MQTT server.
  username = "user"
  password = "pwd"
  insecure_skip_verify = true
```

But for some reason, Telegraf is not pushing the data to Influxdb anymore. In the Telegraf logs I can see, that Telegraf connects to the MQTT broker, but no Data is sent towards Influxdb. The MQTT message looks like this:
`{"temperature":25,"airpressure":1010,"humidity":77`

The strange thing is, that it was working approximately one month ago. Maybe a bug that found to one of the latest telegraf updates?

### LINKED ISSUE #4594: MQTT input plugin disconnecting from Mosquitto
We are planning to use TICK stack on a EU funded project for collection of measurements from MQTT broker. For this purpose, we setup InfluxDB, MQTT broker (Mosquitto) and Telegraf (mqtt_consumer input plugin and InfluxDB output plugin). Telegraf connects successfully to Mosquitto, and starts collecting published metrics in JSON format. However, from time to time it disconnects from the MQTT broker. After a couple of days, it stops reconnecting after losing connection and all the metrics published to MQTT broker are lost.
In the sequel, I provide you with both Telegraf and Mosquitto logs at the moment when there is a reconnection.
 

**Telegraf log:**
2018-08-26T18:07:20Z D! Output [influxdb] buffer fullness: 73 / 10000 metrics. 
2018-08-26T18:07:20Z D! Output [influxdb] wrote batch of 73 metrics in 7.241577ms
2018-08-26T18:07:22Z E! Error in plugin [inputs.mqtt_consumer]: E! MQTT Connection lost
error: pingresp not received, disconnecting
MQTT Client will try to reconnect
2018-08-26T18:07:22Z I! MQTT Client Connected
2018-08-26T18:07:40Z D! Output [influxdb] buffer fullness: 76 / 10000 metrics. 
2018-08-26T18:07:40Z D! Output [influxdb] wrote batch of 76 metrics in 5.022393ms
**--------------------------------------------------------------------------------------------
**Mosquitto log**
1535306832: Received PINGREQ from energo2
1535306832: Sending PINGRESP to energo2
.
.
.
1535306842: Sending PUBLISH to energo2 (d0, q0, r0, m0, 'ENE-E893B/data', ... (240 bytes))
1535306842: Socket error on client energo2, disconnecting.
1535306842: New connection from ::1 on port 1883.
1535306842: Client energo2 disconnected.
1535306842: New client connected from ::1 as energo2 (c0, k60, u'user1').
1535306842: Sending CONNACK to energo2 (1, 0)
**---------------------------------------------------------------------------------------------
### Relevant telegraf.conf:
[[inputs.mqtt_consumer]]
   servers = ["tcp://localhost:1883"]
   persistent_session = true
   qos = 2
   connection_timeout = "120s"
   topics = [
      "+/data",
   ]
   name_override = "demand"
   client_id = "xxxxx"
   username = "xxxx"
   password = "xxxxxxxxx"
   data_format = "json"
   tag_keys = [
	 "measurementID",
     "measurementIndex",
     "deviceID"
   ]

### System info:
Telegraf version 1.7.3, Ubuntu 16.04, Mosquitto ver. 1.4.14

### LINKED ISSUE #4731: telegraf stops sending data to influx
I use telegraf to collect MQTT data and send the to Influx. 
In irregular intervals telegraf stops sending data. The instance is still there but seems to do nothing. When telegraf is restarted everything works again as expected. 

### System info:
Telegraf v1.7.4 (git: release-1.7 578db7ef)
Raspbian GNU/Linux 9 (stretch), Rpi 3
[trace.txt](https://github.com/influxdata/telegraf/files/2406120/trace.txt)

stack trace is attached.

### PR DESCRIPTION
**Pull request by danielnelson**
Reworks the connection lifetime for the mqtt_consumer plugin.  For now I have this marked for 1.9.0 but if we can get some help testing we can consider it for 1.8.x.

closes #4594 
closes #4580
closes #4731

Based on #4814 

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
- [telegraf-1.9.0~dcf4fb4b-0.x86_64.rpm](https://20713-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.9.0%7Edcf4fb4b-0.x86_64.rpm)
- [telegraf_1.9.0~dcf4fb4b-0_amd64.deb](https://20713-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.9.0%7Edcf4fb4b-0_amd64.deb)
- [telegraf-1.9.0~dcf4fb4b_windows_amd64.zip](https://20713-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.9.0%7Edcf4fb4b_windows_amd64.zip)

**Comment by trankennykhang** [comment]
@danielnelson sorry for slow action. It is the first time I contribute to community and just learned golang few weeks ago so I need a bit of time to check one by one carefully

Your changes is pretty good. Here is my comment:
- Three connection state will prevent the connection to establish second time completely. My change only tried to set it asap.
- Get rid of "receive" thread function to reduce the complexion
- I feel not right at the first look "opts.SetAutoReconnect(false)" but it is clear after checking further. The "SetConnectionLostHandler" will set the state back to original then the next call of "gather" function will try to establish it again.

I will test it on our IoTs project to see how it is. Thanks

**Comment by Dees7** [comment]
Please make armhf build for RaspberryPi3

**Comment by Dees7** [comment]
Please make armhf build for RaspberryPi3

**Comment by danielnelson** [comment]
- [telegraf-1.9.0~dcf4fb4b-0.armv6hl.rpm](https://20713-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.9.0%7Edcf4fb4b-0.armv6hl.rpm)
- [telegraf-1.9.0~dcf4fb4b_linux_armhf.tar.gz](https://20713-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.9.0%7Edcf4fb4b_linux_armhf.tar.gz)
- [telegraf_1.9.0~dcf4fb4b-0_armhf.deb](https://20713-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf_1.9.0%7Edcf4fb4b-0_armhf.deb)

**Comment by Dees7** [comment]
There is to output at all.
telegraftest.conf :
```
[global_tags]
[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 500
  metric_buffer_limit = 1000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = true
[[processors.converter]]
  [processors.converter.tags]
    float = ["POWER*"]
[[processors.printer]]
  order = 2
[[processors.regex]]
  order = 1
  [[processors.regex.tags]]
      key = "topic"
      pattern = ".*/(.*)/.*"
      replacement = "${1}"
      result_key = "topicname"
[[inputs.mqtt_consumer]]
  servers = ["tcp://localhost:1883"]
  qos = 0
  connection_timeout = "4s"
  topics = ["test/#"]
  persistent_session = true
  client_id = "telegraftest"
  username = "user"
  password = "pass"
  name_override = "mqttc"
  tag_keys = ["hostname","POWER","POWER1"]
  data_format = "json"
[[outputs.file]]
   files = ["stdout"]
   data_format = "graphite"
[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  database = "test"
  skip_database_creation = false
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
  username = "user"
  password = "pss"
```
/home/pi/telegraf --debug -config /etc/telegraf/telegraftest.conf
```
2018-10-11T06:51:26Z D! Attempting connection to output: influxdb
2018-10-11T06:51:26Z D! Successfully connected to output: influxdb
2018-10-11T06:51:26Z D! Attempting connection to output: file
2018-10-11T06:51:26Z D! Successfully connected to output: file
2018-10-11T06:51:26Z I! Starting Telegraf 
2018-10-11T06:51:26Z I! Loaded inputs: inputs.mqtt_consumer
2018-10-11T06:51:26Z I! Loaded aggregators: 
2018-10-11T06:51:26Z I! Loaded processors: converter regex printer
2018-10-11T06:51:26Z I! Loaded outputs: influxdb file
2018-10-11T06:51:26Z I! Tags enabled: 
2018-10-11T06:51:26Z I! Agent Config: Interval:5s, Quiet:false, Hostname:"", Flush Interval:10s 
2018-10-11T06:51:30Z I! [inputs.mqtt_consumer]: connected [tcp://localhost:1883]
2018-10-11T06:51:40Z D! Output [file] buffer fullness: 0 / 1000 metrics. 
2018-10-11T06:51:40Z D! Output [influxdb] buffer fullness: 0 / 1000 metrics. 
2018-10-11T06:51:50Z D! Output [influxdb] buffer fullness: 0 / 1000 metrics. 
2018-10-11T06:51:50Z D! Output [file] buffer fullness: 0 / 1000 metrics. 
^C2018-10-11T06:51:57Z I! Hang on, flushing any cached metrics before shutdown
2018-10-11T06:51:57Z D! Output [file] buffer fullness: 0 / 1000 metrics. 
2018-10-11T06:51:57Z D! Output [influxdb] buffer fullness: 0 / 1000 metrics. 
2018-10-11T06:51:57Z D! [inputs.mqtt_consumer]: disconnecting [tcp://localhost:1883]
2018-10-11T06:51:57Z D! [inputs.mqtt_consumer]: disconnected [tcp://localhost:1883]
```

publishing:
```
mosquitto_pub -u 'user' -P 'pass' -t 'test/sonoff/RESULT' -m '{"POWER":0,"TEMP":41.1,"hostname":"mine"}'
mosquitto_pub -u 'user' -P 'pass' -t 'test/sonoff/RESULT' -m '{"POWER":0,"TEMP":41.1,"hostname":"mine"}'
```
debug with mosquitto_sub -u 'user' -P 'pass'  -v -t 'test/#':
```
test/sonoff/RESULT {"POWER":0,"TEMP":41.1,"hostname":"mine"}                                       2018-10-11T06:50:29Z D! [inputs.mqtt_consumer]: disconnected [tcp://localhost:1883]
test/sonoff/RESULT {"POWER":0,"TEMP":41.1,"hostname":"mine"}  
```
mosquitto.log
```
Thu 11 Oct 11:51:30 +05 2018 1539240690: Sending CONNACK to telegraftest (1, 0)
Thu 11 Oct 11:51:34 +05 2018 1539240694: Sending PUBLISH to telegraftest (d0, q0, r0, m0, 'test/sonoff/RESULT', ... (41 bytes))
Thu 11 Oct 11:51:47 +05 2018 1539240707: Sending PUBLISH to telegraftest (d0, q0, r0, m0, 'test/sonoff/RESULT', ... (41 bytes))
Thu 11 Oct 11:51:57 +05 2018 1539240717: Received DISCONNECT from telegraftest
```

**Comment by danielnelson** [comment]
@Dees7 I had broken persistent sessions, restoring the behavior of subscribing once on the initial connection as we did before.  I feel like this is not completely correct but I don't see a way to check the session present flag, I'll have to ask on the paho project but for now this should generally work.

- [telegraf-1.9.0%7E2cc071d4_freebsd_amd64.tar.gz](https://20788-33258973-gh.circle-artifacts.com/0/build/freebsd/amd64/telegraf-1.9.0%7E2cc071d4_freebsd_amd64.tar.gz)
- [telegraf-1.9.0%7E2cc071d4_freebsd_i386.tar.gz](https://20788-33258973-gh.circle-artifacts.com/0/build/freebsd/i386/telegraf-1.9.0%7E2cc071d4_freebsd_i386.tar.gz)
- [telegraf-1.9.0%7E2cc071d4-0.x86_64.rpm](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.9.0%7E2cc071d4-0.x86_64.rpm)
- [telegraf-1.9.0%7E2cc071d4_linux_amd64.tar.gz](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.9.0%7E2cc071d4_linux_amd64.tar.gz)
- [telegraf_1.9.0%7E2cc071d4-0_amd64.deb](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.9.0%7E2cc071d4-0_amd64.deb)
- [telegraf-1.9.0%7E2cc071d4-0.arm64.rpm](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.9.0%7E2cc071d4-0.arm64.rpm)
- [telegraf-1.9.0%7E2cc071d4_linux_arm64.tar.gz](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf-1.9.0%7E2cc071d4_linux_arm64.tar.gz)
- [telegraf_1.9.0%7E2cc071d4-0_arm64.deb](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/arm64/telegraf_1.9.0%7E2cc071d4-0_arm64.deb)
- [telegraf-1.9.0%7E2cc071d4-0.armel.rpm](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf-1.9.0%7E2cc071d4-0.armel.rpm)
- [telegraf-1.9.0%7E2cc071d4_linux_armel.tar.gz](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf-1.9.0%7E2cc071d4_linux_armel.tar.gz)
- [telegraf_1.9.0%7E2cc071d4-0_armel.deb](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/armel/telegraf_1.9.0%7E2cc071d4-0_armel.deb)
- [telegraf-1.9.0%7E2cc071d4-0.armv6hl.rpm](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.9.0%7E2cc071d4-0.armv6hl.rpm)
- [telegraf-1.9.0%7E2cc071d4_linux_armhf.tar.gz](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf-1.9.0%7E2cc071d4_linux_armhf.tar.gz)
- [telegraf_1.9.0%7E2cc071d4-0_armhf.deb](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/armhf/telegraf_1.9.0%7E2cc071d4-0_armhf.deb)
- [telegraf-1.9.0%7E2cc071d4-0.i386.rpm](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf-1.9.0%7E2cc071d4-0.i386.rpm)
- [telegraf-1.9.0%7E2cc071d4_linux_i386.tar.gz](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf-1.9.0%7E2cc071d4_linux_i386.tar.gz)
- [telegraf_1.9.0%7E2cc071d4-0_i386.deb](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/i386/telegraf_1.9.0%7E2cc071d4-0_i386.deb)
- [telegraf-1.9.0%7E2cc071d4-0.s390x.rpm](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf-1.9.0%7E2cc071d4-0.s390x.rpm)
- [telegraf-1.9.0%7E2cc071d4_linux_s390x.tar.gz](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf-1.9.0%7E2cc071d4_linux_s390x.tar.gz)
- [telegraf_1.9.0%7E2cc071d4-0_s390x.deb](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/s390x/telegraf_1.9.0%7E2cc071d4-0_s390x.deb)
- [telegraf-1.9.0%7E2cc071d4-static_linux_amd64.tar.gz](https://20788-33258973-gh.circle-artifacts.com/0/build/linux/static_amd64/telegraf-1.9.0%7E2cc071d4-static_linux_amd64.tar.gz)
- [telegraf-1.9.0%7E2cc071d4_windows_amd64.zip](https://20788-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.9.0%7E2cc071d4_windows_amd64.zip)
- [telegraf-1.9.0%7E2cc071d4_windows_i386.zip](https://20788-33258973-gh.circle-artifacts.com/0/build/windows/i386/telegraf-1.9.0%7E2cc071d4_windows_i386.zip)

**Comment by chumbert2** [comment]
Using telegraf_1.9.0~dcf4fb4b-0_amd64.deb the problem of double connection we had with 1.8.0 and 1.8.1 is not present. MQTT messages are correctly received. (we haven't tested reconnect yet).

**Comment by Dees7** [comment]
Yes. Now  works stable (after restarting telegraf or mosquitto).

**Comment by chumbert2** [comment]
Works as expected with telegraf_1.9.0~2cc071d4-0_amd64.deb:

* messages are properly received
* no double connection
* reconnection OK

NOTE: tested with `persistent_session = false` only (AWS broker does not support persistent sessions).

**Comment by Flowm** [comment]
Works perfectly so far on a RPi3 with telegraf_1.9.0%7E2cc071d4-0_armhf.deb
Thanks a lot!

**Pull request merged**
