### PR TITLE
add kube state metrics

### PR DESCRIPTION
**Pull request by kelwang**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

### CODE REVIEW

**Comment by lpic10** [comment]
FYI currently I have kube-state-metrics running in a container and I'm reading the metrics via a prometheus input in telegraf. 

I understand this plugin will avoid running this additional binary and this would suit me a lot better, but I think you need to explain the reasoning of having this inside telegraf instead.

**Comment by puckpuck** [comment]
How is this plugin different than just using the prometheus plugin pointed to your kube-state-metrics service?

**Comment by puckpuck** [comment]
Interesting. I will certainly give this a try, comparing it to the current setup via prometheus.

**Comment by thedebugger** [comment]
We also use the prometheus plugin to pull the k8s metrics and we were thinking of improving the output schema by just running some transformations on the output of kube-state-metrics. Won't that be better than moving kube-state-metrics code inside telegraf? The downside is someone has to keep this up to date with kube-state-metrics which is managed by kubernetes community

**Comment by russorat** [comment]
i set up a single telegraf to scrape these metrics by following the default steps in the [kube-state-metrics readme](https://github.com/kubernetes/kube-state-metrics#usage) and then adding this to my telegraf config:

```
[[inputs.prometheus]]
  kubernetes_services = ["http://kube-state-metrics.kube-system:8080/metrics"]
  bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
  insecure_skip_verify = true
```

**Comment by kelwang** [comment]
Hey @russorat , I think you need to copy the real content of the token, I don't think copy the token path will work.



> i set up a single telegraf to scrape these metrics by following the default steps in the [kube-state-metrics readme](https://github.com/kubernetes/kube-state-metrics#usage) and then adding this to my telegraf config:
> 
> ```
> [[inputs.prometheus]]
>   kubernetes_services = ["http://kube-state-metrics.kube-system:8080/metrics"]
>   bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
>   insecure_skip_verify = true
> ```

**Comment by russorat** [comment]
@kelwang the path was working or more likely being ignored on my setup.

**Comment by glinton** [comment]
From what I can tell, the popular grafana kubernetes dashboards only retrieve the following stats via kube-state-metrics:

```
#### kube_statefulset
- ts: statefulset creation time
- fields:
  - metadata_generation
  - replicas
  - status_replicas
  - status_replicas_current
  - status_replicas_ready
  - status_replicas_updated
  - status_observed_generation
- tags:
  - namespace
  - name

#### kube_deployment
- ts: now
- fields:
  - status_replicas_available
  - status_replicas_unavailable
- tags:
  - namespace
  - name

#### kube_pod_container
- ts: now
- fields:
  - resource_requests_cpu_cores
  - resource_limits_cpu_cores
  - resource_requests_memory_bytes
  - resource_limits_memory_bytes
- tags:
  - namespace

#### kube_node
- ts: now
- fields:
  - status_capacity_pods
- tags:
  - os_image
```

**Comment by danielnelson** [comment]
Continued on #5110

**Pull request closed without merging**
