### PR TITLE
Azure IoT Hub / Azure Event Hub input plugin

### PR DESCRIPTION
**Pull request by R290**
As discussed in issue #5231.
Feedback on code quality or anything else is greatly appreciated.

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by eaidland** [comment]
Hi!

What's the status for this merge/release ?

**Comment by R290** [comment]
> 
> 
> Hi!
> 
> What's the status for this merge/release ?

I've been using this plugin continuously since February without any issues.
No upstream updates have been tested (latest commits are 52bd698046d60c99ca781b5ead6d5b95fd19a7f1 and https://github.com/Azure/azure-event-hubs-go/commit/aca3e9cfe138951ffb815665621095482a674ee9).

To fully enjoy this plugin the following issue needs to be fixed: https://github.com/Azure/azure-event-hubs-go/issues/95, I've not yet been able to submit a PR.

**Comment by eaidland** [comment]
We'll have to wait until it's part of the default telegraf plugins.

**Comment by R290** [comment]
Closed until `dep` has minimal support for Go Modules (https://github.com/golang/dep/pull/1963). Until then the required package `github.com/Azure/azure-event-hubs-go/v2` can not be successfully handled by `dep ensure`.

**Comment by russorat** [comment]
go modules support will be added here: https://github.com/influxdata/telegraf/pull/6118

then this PR can be reopened.

**Comment by R290** [comment]
This pull request is reopened since https://github.com/influxdata/telegraf/pull/6912 is merged.

**Comment by R290** [comment]
I don't exactly understand what happened here, I expected one commit to be included instead of 274. I'll open a new pull request and reference this one.

**Pull request closed without merging**
