### PR TITLE
Pidstat plugin

### PR DESCRIPTION
**Pull request by PetrBarborka**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Here is what I get with running go fmt:
```
(git::PetrBarborka-master) $ go fmt ./...
plugins/inputs/all/all.go
(git::PetrBarborka-master) $ git diff
diff --git a/plugins/inputs/all/all.go b/plugins/inputs/all/all.go
index 790d0133..05d81595 100644
--- a/plugins/inputs/all/all.go
+++ b/plugins/inputs/all/all.go
@@ -62,8 +62,8 @@ import (
        _ "github.com/influxdata/telegraf/plugins/inputs/openldap"
        _ "github.com/influxdata/telegraf/plugins/inputs/passenger"
        _ "github.com/influxdata/telegraf/plugins/inputs/phpfpm"
-       _ "github.com/influxdata/telegraf/plugins/inputs/ping"
        _ "github.com/influxdata/telegraf/plugins/inputs/pidstat"
+       _ "github.com/influxdata/telegraf/plugins/inputs/ping"
        _ "github.com/influxdata/telegraf/plugins/inputs/postgresql"
        _ "github.com/influxdata/telegraf/plugins/inputs/postgresql_extensible"
        _ "github.com/influxdata/telegraf/plugins/inputs/powerdns"
```

**Comment by danielnelson** [comment]
Thank you for the pull request, pidstat looks like a nice utility, but I'm concerned about the amount of overlap between this and the current procstat plugin.  We don't want to provide too many ways to do something because it can be confusing to the users.

Is there something that this plugin gathers that procstat doesn't, maybe we can address the shortcoming of procstat instead.

**Comment by PetrBarborka** [comment]
ad format: Thanks for your assistance, but I still don't understand the problem. It should be added into the "all.go", right? It is alphabetical order, right?

ad relevancy: We need some things procstat won't give us: 
1) resource percentage 
2) full name of runnig command incl. arguments ( not there atm, comming right up )
3) actual i/o data ( somehow procstat creates measurement fields for them but never sends any

**Comment by danielnelson** [comment]
What exactly do you mean by resource percentage?  Usually we prefer to output the total and current and have percentage calculated on query, which has a few advantages when aggregating.

On the full command line, there has been some discussion on https://github.com/influxdata/telegraf/issues/1873, I think concerns about potential command length it would apply here too.  However, I have no other good ideas so perhaps we just require the user to opt-in.  I'll comment more on the issue.

On the IO metrics, these require root permissions to gather.  This is problematic because we don't recommend running telegraf as root.  There may be a way to change this but I have not been able to figure out how https://github.com/influxdata/telegraf/pull/2787

**Comment by danielnelson** [comment]
Closing pull request, I think we will want to focus on improving the procstat input instead of adding support for shelling out to external utilities.

**Pull request closed without merging**
