### PR TITLE
Oauth2 support in HTTP output plugin

### PR DESCRIPTION
**Pull request by vikrant6**
Support for OAuth2 Authentication in http output plugin.
The golang client credentials librarty supports token reuse untill its expiry.

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by vikrant6** [comment]
fmt check done

**Comment by vikrant6** [comment]
dep ensure -vendor-only fixed

**Comment by vikrant6** [comment]
test

**Comment by danielnelson** [comment]
@vikrant6 Thanks for the PR.  I'll try to take a look soon, ping me when you have the tests passing on circleci or if you need help.

**Comment by vikrant6** [comment]
@danielnelson  I very new to go and might be missing something basic here. Need your help 

go vet $(go list ./... | grep -v ./plugins/parsers/influx)
plugins/outputs/http/http.go:17:2: cannot find package "golang.org/x/oauth2" in any of:
	/go/src/github.com/influxdata/telegraf/vendor/golang.org/x/oauth2 (vendor tree)
	/usr/local/go/src/golang.org/x/oauth2 (from $GOROOT)
	/go/src/golang.org/x/oauth2 (from $GOPATH)
plugins/outputs/http/http.go:18:2: cannot find package "golang.org/x/oauth2/clientcredentials" in any of:
	/go/src/github.com/influxdata/telegraf/vendor/golang.org/x/oauth2/clientcredentials (vendor tree)
	/usr/local/go/src/golang.org/x/oauth2/clientcredentials (from $GOROOT)
	/go/src/golang.org/x/oauth2/clientcredentials (from $GOPATH)

**Comment by danielnelson** [comment]
This error is due to the new dependency not being added to the lock file.  You don't want to edit it by hand though, undo your changes to Gopkg.toml and run:
```
dep ensure -add golang.org/x/oauth2@master
```

Then make sure there are no errors when you run:
```
dep check
```

**Comment by vikrant6** [comment]
@danielnelson Thanks. vet is failing for some packages (existing) Any idea how to proceed?

**Comment by vikrant6** [comment]
@danielnelson - Any pointer on how to proceed from here?

**Comment by danielnelson** [comment]
@vikrant6 Is it alright if I fix it up and push to your fork?

**Comment by vikrant6** [comment]
@danielnelson - Please go ahead. Thanks.

**Comment by danielnelson** [comment]
I fixed up the dep issue, cleaned up some whitespace changes, and switch the client over to using the oauth2.Client and added some tests.  I made some minor tweaks to the config file variable names as well.

Here is the rpm from CircleCI [telegraf-1.8.0~f6efa1a9-0.x86_64.rpm](https://17845-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.8.0%7Ef6efa1a9-0.x86_64.rpm)

**Comment by vikrant6** [comment]
@danielnelson  Thank you !

**Comment by vikrant6** [comment]
@danielnelson What's next for this to merge ? Is there a milestone identified?

**Comment by danielnelson** [comment]
We should be able to add this to 1.8.  Since I don't have a real system to do a final testing, can you let me know if everything is working?

**Comment by vikrant6** [comment]
@danielnelson Found that it no longer honors the configuration "insecure_skip_verify=true"
For self signed certs it errors out as "x509: certificate signed by unknown authority"
I can test the windows and linux version extensively here.

**Comment by danielnelson** [comment]
I think this will fix it: https://github.com/influxdata/telegraf/pull/4536/commits/c1dc2d0690c7298a829c1e49f90aa39d973b058c

Updated package: [telegraf-1.8.0~c1dc2d06-0.x86_64.rpm](https://17987-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.8.0%7Ec1dc2d06-0.x86_64.rpm)

**Pull request merged**
