### PR TITLE
Fix #7344: Add percentiles to the ping plugin

### LINKED ISSUE #7344: Add percentiles to ping plugin
## Feature Request

When measuring response times, percentiles are typically more useful than averages and standard deviations. Since the ping plugin has a native method and can get all times, percentiles can be calculated.

### PR DESCRIPTION
**Pull request by fhriley**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

### CODE REVIEW

**Comment by fhriley** [comment]
Can someone review this? It's much better than average and standard deviation: [https://imgur.com/a/4gQl9bd](https://imgur.com/a/4gQl9bd)

**Review by srebhan — APPROVED** [review]

**Comment by zak-pawel** [comment]
@fhriley Can you rebase your code? You still aiming go 1.12 and 1.13 in CI - nowadays 1.14 and 1.15 versions are tested (rebasing automatically solves this).

**Comment by fhriley** [comment]
@zak-pawel Done.

**Comment by zak-pawel** [comment]
@srebhan you review this earlier. What do you think?

**Comment by srebhan** [comment]
I think we are good to go.

**Comment by reimda** [comment]
There was some work done about a year ago to add a T-Digest aggregator to telegraf.  It would accurately estimate percentiles and work with data from any source, not just ping.  The PR hasn't had much attention for a while.  Are any of you interested in picking it up?
https://github.com/influxdata/telegraf/issues/6440
https://github.com/influxdata/telegraf/pull/6887

**Review by reimda — APPROVED** [review]

**Pull request merged**
