### PR TITLE
fix: support 1.17 & 1.16.7 Go versions

### PR DESCRIPTION
**Pull request by sspaink**
New Go version 1.17: https://golang.org/doc/devel/release#go1.17
New Go version 1.16.7: https://golang.org/doc/devel/release#go1.16
Deprecated 1.15.8

### CODE REVIEW

**Comment by sspaink** [comment]
Gross, so many files changed. There is a change with gofmt in 1.17 to help migrate to the use of `//go:build` as the build flag, which allows using logical operators. `make vet` was failing without running `go fmt ./...` first. More information in the release notes: https://tip.golang.org/doc/go1.17#gofmt

**Comment by reimda** [comment]
Let's hold off on this for telegraf 1.19.3. I'd like to understand better why `//go:build` is required now.

**Comment by srebhan** [comment]
@reimda maybe the [release notes](https://golang.org/doc/go1.17#gofmt) help. :-)

**Review by srebhan — APPROVED** [review]
LGTM.

**Comment by reimda** [comment]
More details on golang's transition plan are at https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md#transition.

As I understand it, once we start switching to go:build, we no longer support go 1.15. 1.17 will be preferred but 1.16 will be supported. 1.15 will be unsupported but might still partially work because +build lines will be kept in sync.

The next transition step will be when we switch to 1.18. At that point 1.17 will still work but 1.16 and previous won't because +build lines will be removed.

**Pull request merged**
