### PR TITLE
Add VSphere input plugin

### PR DESCRIPTION
**Pull request by mlabouardy**
### Required for all PRs:

- [x] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by mkuzmin** [comment]
This PR is a good start, but we need a bit more work to reach acceptable level of quality.

I also developed pretty the same plugin, but not going to publish alternate PR. Instead, I rebased my fixes on top of your code at https://github.com/mkuzmin/telegraf/commits/vsphere.
There was a sad story of unhealthy competition in vSphere plugins for Terraform and Packer, and I really don't want to repeat the same mistakes here. Let's join the forces, and develop the best solution together.

I'd suggest the next plan:
1) You mark this PR as **[WIP]**
2) You rebase the code to **release-1.3** branch until we finish the work. I want to use this code in production ASAP, but it should not involve changes in Telegraf core.
Squashing commits would be helpful.
3) I will post my contributions as PRs to your repository. We discuss and agree on all the changes. I'd like to have contributor permissions, so after review I'm able to merge PRs by myself.
4) We publish binary releases and involve people to test our code and provide early feedback.

**Comment by rlex** [comment]
Any chances this will be merged?

**Comment by danielnelson** [comment]
@mkuzmin @mlabouardy Have you made any progress on unifying your plugins?

**Comment by mlabouardy** [comment]
@mkuzmin I rebased the code to https://github.com/mlabouardy/telegraf/tree/release-1.3

I added you as contributor

**Comment by mkuzmin** [comment]
Thank you. I will return to this PR soon.

**Comment by huyujie** [comment]
@mlabouardy @mkuzmin when I use this vsphere plugin,output:"default datacenter resolves to multiple instances, please specify"

**Comment by ideologysec** [comment]
@huyujie export GOVC_DATACENTER="Your Datacenter Name Here"

**Comment by danielnelson** [comment]
Closing in favor of #4141

**Pull request closed without merging**
