### PR TITLE
sqlserver - Changed requests to include blocking sessions.

### PR DESCRIPTION
**Pull request by spaghettidba**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

Changed query to gather requests to also include blocking sessions. The original query started from sys.dm_exec_requests, which excludes all idle queries (which have a session but not a request).
Also fixed query text truncation of the last character.

### CODE REVIEW

**Comment by danielnelson** [comment]
Thanks for the pull request, but could you update the pr to minimize any whitespace changes?  This will make the changes to the query a bit easier to understand and improve the history of the file.

**Comment by spaghettidba** [comment]
@denzilribeiro No problem, I'll change it to a COALESCE. 

@danielnelson I certainly could reduce the number of whitespace changes, but the query is formatted in a way that makes it a bit hard to read. How do you suggest I can improve it? Should I open a second PR? Wouldn't that "clutter" the history of the file anyway? Should I avoid changing formatting at all?

**Comment by spaghettidba** [comment]
Hi! Sorry to bother. Will this PR be merged now that it's approved? Do I need to do anything else?

**Comment by Trovalo** [comment]
@ssoroka can you have a look at this?

**Comment by denzilribeiro** [comment]
> It seems like coalescing the values from two different tables into a single column has the potential to provide really weird behavior. Would it be better to report these as separate columns instead?

No that is how it should be actually. Don't merge this, I will take care of it under PR #7934  given the major change if that is ok with you and @Trovalo

**Comment by ssoroka** [comment]
Fine by me. I'll close this out, then.

**Pull request closed without merging**
