### PR TITLE
chore: Update go to v1.23.0

### LINKED ISSUE #15746: chore: support new golang version 1.23.0
There is a new golang version available. Please update Telegraf to use version '1.23.0'.

### PR DESCRIPTION
**Pull request by srebhan**
## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #15746

### CODE REVIEW

**Review by Hipska — APPROVED** [review]
Have `min` and `max` now become a reserved word or something? 😂

**Comment by srebhan** [comment]
@Hipska yes. Those are [builtin functions](https://pkg.go.dev/builtin#min) since go v1.21...

**Comment by mskonovalov** [comment]
I guess the issue may be related to https://github.com/golangci/golangci-lint/issues/4837#issuecomment-2317329924
or https://github.com/golangci/golangci-lint/issues/4908#issuecomment-2288716658

**Comment by srebhan** [comment]
@mskonovalov the issue is that the CircleCI instance runs out-of-memory unfortunately. In the past we were able to tune the garbage collection params but this doesn't seem to work this time...

**Comment by zak-pawel** [comment]
It looks like `go 1.23.0` and/or `golangci-lint 1.60.x` need more memory to complete the scan than previous versions, and tweaking `GOGC` and `GOMEMLIMIT` wasn't enough this time. 

But I found something else. When I started playing around with `GODEBUG=gctrace=1`, I discovered that `golangci-lint` uses 36 logical CPUs to perform the scan. However, the Docker / Large setup only has 4 vCPUs:
image

By default, `golangci-lint` uses as many CPUs as there are logical CPUs available. It turns out that the system is reporting the number of processors on the host, rather than the number available within the Docker executor.

Confirmation here:
image
(https://discuss.circleci.com/t/x86-vm-cpu-ram-size-mismatch/45779/6)

And here:
image
(https://app.circleci.com/pipelines/github/influxdata/telegraf/22537/workflows/43957c5b-61fa-4de1-b1b9-2ca3a29c9581/jobs/350312)

Using only as many CPUs as are actually available to the guest (4 instead of 36) speeds up the jobs (less CPU time spent in garbage collection) and reduces memory usage/makes garbage collection more efficient (with parallel linter threads, using fewer processors allows for a more efficient "stop the world" phase).

**Comment by srebhan** [comment]
This is really amazing! Thanks for hunting down and fixing the issue @zak-pawel!

**Review by Hipska — APPROVED** [review]

**Review by DStrand1 — APPROVED** [review]

**Pull request merged**
