### PR TITLE
fix(inputs.phpfpm): Add pid field to differentiate metrics

### PR DESCRIPTION
**Pull request by powersj**
## Summary

Adds the PID field to allow users to differentiate works based on this field.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

fixes: #14461

### CODE REVIEW

**Review by srebhan — APPROVED** [review]
Totally makes sense... Thanks @powersj!

**Comment by anthosz** [comment]
@powersj I guess there is a typo, the pid is not a metric but a tag

**Comment by powersj** [comment]
> @powersj @srebhan I guess there is a typo, the pid is not a metric but a tag

What do you mean? It is a field and won't be a tag.

**Comment by powersj** [comment]
As I mentioned in the [original bug report](https://github.com/influxdata/telegraf/issues/14461#issuecomment-1857979210), we do not make numeric values with wide ranges tags by default. It can lead to run-away cardinality in some outputs (e.g. influxdb v1/v2). If a user wishes to change this, and opt-in to having it as a tag, they can use the converter processor.

**Pull request merged**
