### PR TITLE
fix systemd path in order to add compatibility with SuSe

### PR DESCRIPTION
**Pull request by snahelou**
Hello

In order to respect [the official Systemd path](https://www.freedesktop.org/software/systemd/man/systemd.unit.html) (and be compatible with SLES12), you must change the systemd file path. 

It compatible with RHEL due to default symlink.

Regards

### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by danielnelson** [comment]
I believe this will not work on Debian which is still using `/lib/systemd/system`: https://manpages.debian.org/unstable/systemd/systemd.unit.5.en.html

**Comment by snahelou** [comment]
Is someone can confirm ? I can modify my PR in order to pass a parameter to `install_systemd `

**Comment by danielnelson** [comment]
Do we know how long the `/usr/lib` path has been supported by Suse and RHEL?  We wouldn't want to break the install on old versions.

**Comment by snahelou** [comment]
I don't know why but RHEL and SuSe use different packages for filesystem:
* CentOS5 (docker official): filesystem-2.4.0-3.el5.centos ( 2 real directories ) - no systemd
* CentOS6 (docker official): filesystem-2.4.30-3.el6.x86_64 ( 2 real directories ) - no systemd
* CentOS7.3 (docker official): filesystem-3.2-21.el7.x86_64 ( lib -> usr/lib )
* SLES12SP2: filesystem-13.1-11.13.x86_64 ( 2 real directories )
* OpenSuse 42.2 (docker official):  filesystem-13.1-7.2.x86_64 (2 real directories )

In Suse we can find in the changelog (filesystem-13.1-11.13.x86_64) :
```
* Mon Sep 30 2013 speilicke@suse.com
- Drop /lib/systemd and /lib/systemd/system, everything is now in
  /usr/lib/systemd...
```

And in RHEL7 we can find: 
```
* Fri Feb 03 2012 Kay Sievers <kay@redhat.com> 3-2
- enable guard against unconverted /bin, /sbin, /lib*
  directories in the filesystem

* Wed Jan 25 2012 Harald Hoyer <harald@redhat.com> 3-1
- install everything in /usr
  https://fedoraproject.org/wiki/Features/UsrMove
```

So I think the best practice is to use /usr/lib

**Comment by danielnelson** [comment]
@rossmcdonald Can you take a look?

**Comment by danielnelson** [comment]
Can you check if this will work with SLES 11 and OpenSuse 42.1?  Then we need to open tickets for influxdb, kapacitor, and chronograf.

**Comment by danielnelson** [comment]
@snahelou Can you rebase?  There might be conflicts with #2360, sorry.

**Comment by danielnelson** [comment]
I believe SLES 11 does not support systemd, so we don't need to check it.

**Comment by danielnelson** [comment]
Thank you!

**Pull request merged**
