### PR TITLE
Add support for kubernetes jobs

### LINKED ISSUE #7779: Add support for kubernetes jobs
## kubernetes Jobs

Opening a feature request kicks off a discussion.

### Proposal:

Add functionality to generate metrics derived from the state of the [job](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#job-v1-batch) resource to the [kube_inventory input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kube_inventory). This could be a new metrics like:
- kubernetes_job
   - tags:
      - job_name
      - namespace
      - selector (*varies)
   - fields
      - started
      - completed
      - failed
      - succeeded

### Current behavior:

Job metrics are not currently ingested.

### Desired behavior:

Ingest job metrics.

### Use case

By bringing in job metrics into influx, a user can:
1. Set up alerting when jobs start failing which allows users know about issues as soon as possible without having to monitor jobs.
2. See the health of jobs over time and see if there is an issue with applications or infrastructure.

### PR DESCRIPTION
**Pull request by carlosv-ukg**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

Closes #7779

### CODE REVIEW

**Comment by sspaink** [comment]
@carlosv-ukg thank you for this pr, with this recent pr #8937 the project has moved to use github.com/kubernetes/client-go in the kube-inventory plugin. Would you be able to migrate this pull request to use this new library?

**Comment by carlosv-ukg** [comment]
@sspaink I took a look at the repo and it wasn't obvious to me how I could port these changes over to github.com/kubernetes/client-go. Do you have a PR when you brought over the code-base?

**Comment by sspaink** [comment]
This is the pull request that migrated telegraf to github.com/kubernetes/client-go:  [ https://github.com/influxdata/telegraf/pull/8937 ](https://github.com/influxdata/telegraf/pull/8937)

I think this is the function you need to get the job list: https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/batch/v1/job.go#L86

Hopefully that helps?

**Comment by carlosv-ukg** [comment]
gotcha thanks! that's helpful. I'll see what I can do to port over the change 👍

**Comment by carlosv-ukg** [comment]
Closing now that the project has moved.

**Pull request closed without merging**
