### PR TITLE
Add docker input server version

### LINKED ISSUE #4029: FeatureRequest: add docker engine version to inputs.docker
Having `docker_version` as a tag in `inputs.docker` would be great.

### PR DESCRIPTION
**Pull request by danielnelson**
closes #4029

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@rdxmb Can you review?

**Comment by rdxmb** [comment]
Oh, I am not a Go-developer, so I cannot make a "real review". But, I can have a look at it, of course.

What I think about is if we need the tag really with all measurements. Having it with `docker` could be enough, I guess.

**Comment by danielnelson** [comment]
Hmm, maybe it should be a string field then, what sort of queries are you planning to use?

**Comment by rdxmb** [comment]
As mostly the strings I use are stored as tags, I did not have the idea to use a string field for that.

However, for anybody else a use-case could also be to get what engine-version is running **under a container**. For that, your PR would be the best.

My personal use case is to just check if the docker-engines are up-to-date. So for now I am very flexible about the query.

**Comment by danielnelson** [comment]
I think having it as a tag to all of the docker_* measurements will end up be the least confusing.

**Pull request merged**
