### PR TITLE
Influxdb output database routing tag

### PR DESCRIPTION
**Pull request by danielnelson**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by voiprodrigo** [comment]
Is it possible to drop the tag after routing is established?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danielnelson** [comment]
I didn't include this.

**Comment by amarbajric** [comment]
@danielnelson Is there any possibility at the moment to drop the tag that was used for dynamic routing with `database_tag`? I have tried to use `tagexclude` without success. I guess `database_tag` and `tagexclude` are not intended to work together by now?

**Comment by danielnelson** [comment]
Unfortunately, the general metric filtering options are applied before `database_tag`, so they can't be used together.  This means we will need to add a new option specifically for this :(.

**Comment by amarbajric** [comment]
Ah I see, that's what I was thinking as telegraf was simply ignoring the `tagexclude` property in the configuration. Yes I will open an issue for this feature request as I think that others also would like this specific functionality! Thank you for your fast response :)

**Comment by x70b1** [comment]
```
[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  username = "telegraf"
  password = "xxxxx"
  timeout = "5s"

  database = "Database1"
  database_tag = "influxdb_database"
  tagexclude = ["influxdb_database"]

[[inputs.exec]]
  commands = [
    "bash command.sh"
  ]

  interval = "1m"
  timeout = "20s"
  data_format = "influx"

  [inputs.exec.tags]
    influxdb_database = "Database1"

```

Sounds weird, but `tagexclude` works there for me? How is that possible?
I tested it.

**Comment by danielnelson** [comment]
Tag exclude will work to remove the tag, but then it won't be available for the `database_tag` option to use and it will just send everything to the default database `Database1`.

**Comment by x70b1** [comment]
That makes sense. Thanks for the clarification!

**Pull request merged**
