### PR TITLE
feat(inputs.sqlserver): add Azure Arc-enabled SQL MI support

### PR DESCRIPTION
**Pull request by nikosheng**
# Required for all PRs

- [X] Updated associated README.md.
- [X] Wrote appropriate unit tests.
- [X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves [#13145](https://github.com/influxdata/telegraf/issues/13145)

Add an sqlserver input plugin to support Azure Arc-enabled SQL Managed Instance. Currently, the plugin is not able to support the Azure Arc-enabled SQL MI due to engine edition checking.

### CODE REVIEW

**Comment by nikosheng** [comment]
@powersj Hi Joshua, happy to know if any follow up for this PR.

**Review by srebhan — APPROVED** [review]
Looks good code-wise. Cannot judge the SQL query part. @Trovalo any comments?

**Comment by Trovalo** [comment]
I've no knowledge of Arc-Enabled SQL Server, and I've no way of testing the queries but I trust the work of @nikosheng.
Just one question tho (for my own curiosity), if the only limit was the engine check wouldn't it suffice to just expand that rule instead of creating a whole new branch of queries? Or is there something more, like different or additional queries?

**Review by powersj — APPROVED** [review]
Thank you for taking the time to put this up!

**Review by powersj — APPROVED** [review]
Thank you for taking the time to put this up!

**Pull request merged**
