### PR TITLE
feat: add builds for riscv64

### PR DESCRIPTION
**Pull request by powersj**
Fixes: #10216

### CODE REVIEW

**Comment by popey** [comment]
LGTM in a RISCV VM. :)

```
ubuntu@ubuntu:~$ ./telegraf-1.21.0/usr/bin/telegraf --once --config telegraf-1.21.0/etc/telegraf/telegraf.conf
2021-12-15T17:11:11Z I! Starting Telegraf 1.21.0-41283e3b
2021-12-15T17:11:11Z I! Loaded inputs: cpu disk diskio kernel mem processes swap system
2021-12-15T17:11:11Z I! Loaded aggregators: 
2021-12-15T17:11:11Z I! Loaded processors: 
2021-12-15T17:11:11Z I! Loaded outputs: file
2021-12-15T17:11:11Z I! Tags enabled: host=ubuntu
2021-12-15T17:11:11Z I! [agent] Hang on, flushing any cached metrics before shutdown
kernel,host=ubuntu entropy_avail=182i,interrupts=86402i,context_switches=109191i,boot_time=1639587992i,processes_forked=975i 1639588271000000000
mem,host=ubuntu swap_total=0i,commit_limit=1001541632i,committed_as=265080832i,free=1504329728i,high_total=0i,inactive=134721536i,vmalloc_total=68719475712i,dirty=94208i,sunreclaim=37101568i,vmalloc_chunk=0i,available_percent=90.73070584049371,high_free=0i,low_total=0i,mapped=99065856i,write_back_tmp=0i,used=156336128i,buffered=16527360i,huge_pages_free=0i,huge_page_size=2097152i,low_free=0i,sreclaimable=37433344i,total=2003083264i,huge_pages_total=0i,shared=573440i,slab=74534912i,swap_free=0i,available=1817411584i,used_percent=7.804774310170663,cached=325890048i,page_tables=1413120i,swap_cached=0i,vmalloc_used=31375360i,active=222478336i,write_back=0i 1639588271000000000
system,host=ubuntu n_cpus=4i,n_users=1i,load1=0.12,load5=0.35,load15=0.17 1639588271000000000
system,host=ubuntu uptime=280i 1639588271000000000
system,host=ubuntu uptime_format=" 0:04" 1639588271000000000
disk,device=vda1,fstype=ext4,host=ubuntu,mode=rw,path=/ inodes_used=76964i,total=8662106112i,free=5786910720i,used=2858418176i,used_percent=33.063151331611294,inodes_total=1079296i,inodes_free=1002332i 1639588271000000000
disk,device=vda15,fstype=vfat,host=ubuntu,mode=rw,path=/boot/efi used=1536i,used_percent=0.0014037320556252223,inodes_total=0i,inodes_free=0i,inodes_used=0i,total=109422592i,free=109421056i 1639588271000000000
swap,host=ubuntu free=0i,used_percent=0,total=0i,used=0i 1639588271000000000
swap,host=ubuntu in=0i,out=0i 1639588271000000000
diskio,host=ubuntu,name=vda15 iops_in_progress=0i,merged_reads=664i,reads=265i,writes=2i,read_bytes=10259456i,write_bytes=1024i,write_time=1i,weighted_io_time=51i,merged_writes=0i,read_time=50i,io_time=240i 1639588271000000000
diskio,host=ubuntu,name=vda reads=5081i,writes=1067i,io_time=13452i,merged_writes=2434i,iops_in_progress=0i,merged_reads=2416i,read_bytes=141306880i,write_bytes=355709952i,read_time=4684i,write_time=2038i,weighted_io_time=7296i 1639588271000000000
diskio,host=ubuntu,name=vda1 writes=1052i,write_bytes=355667968i,read_time=3762i,merged_writes=2426i,reads=4001i,read_bytes=125647872i,write_time=2011i,io_time=12508i,weighted_io_time=5774i,iops_in_progress=0i,merged_reads=1691i 1639588271000000000
diskio,host=ubuntu,name=vda12 writes=0i,read_bytes=889856i,write_bytes=0i,write_time=0i,io_time=144i,merged_reads=61i,merged_writes=0i,reads=183i,weighted_io_time=27i,iops_in_progress=0i,read_time=27i 1639588271000000000
diskio,host=ubuntu,name=vda13 io_time=404i,merged_reads=0i,merged_writes=0i,writes=0i,read_time=279i,write_bytes=0i,write_time=0i,weighted_io_time=279i,iops_in_progress=0i,reads=224i,read_bytes=1835008i 1639588271000000000
diskio,host=ubuntu,name=vda14 reads=300i,io_time=216i,iops_in_progress=0i,merged_reads=0i,merged_writes=0i,weighted_io_time=74i,writes=0i,read_bytes=1355776i,write_bytes=0i,read_time=74i,write_time=0i 1639588271000000000
processes,host=ubuntu total_threads=135i,blocked=0i,zombies=0i,sleeping=52i,total=111i,paging=0i,stopped=0i,running=0i,unknown=0i,dead=0i,idle=59i 1639588271000000000
cpu,cpu=cpu0,host=ubuntu usage_idle=96.15384615383901,usage_nice=0,usage_iowait=0,usage_steal=0,usage_guest=0,usage_user=1.9230769230763975,usage_system=1.9230769230770808,usage_guest_nice=0,usage_irq=0,usage_softirq=0 1639588272000000000
cpu,cpu=cpu1,host=ubuntu usage_system=6.52173913043532,usage_nice=0,usage_iowait=0,usage_softirq=0,usage_user=4.347826086957395,usage_idle=89.13043478261191,usage_irq=0,usage_steal=0,usage_guest=0,usage_guest_nice=0 1639588272000000000
cpu,cpu=cpu2,host=ubuntu usage_iowait=0,usage_irq=0,usage_guest_nice=0,usage_softirq=0,usage_steal=0,usage_guest=0,usage_user=7.9999999999998295,usage_system=50,usage_idle=41.99999999999591,usage_nice=0 1639588272000000000
cpu,cpu=cpu3,host=ubuntu usage_softirq=0,usage_guest=0,usage_guest_nice=0,usage_system=2.00000000000054,usage_iowait=0,usage_irq=0,usage_steal=0,usage_user=1.9999999999998295,usage_idle=96.00000000000887,usage_nice=0 1639588272000000000
cpu,cpu=cpu-total,host=ubuntu usage_irq=0,usage_steal=0,usage_guest_nice=0,usage_user=4.040404040403917,usage_nice=0,usage_iowait=0,usage_softirq=0,usage_guest=0,usage_system=15.151515151514868,usage_idle=80.80808080807547 1639588272000000000
2021-12-15T17:11:11Z I! [agent] Stopping running outputs
ubuntu@ubuntu:~$ arch
riscv64

```

**Comment by philroche** [comment]
Testing completed on the now discontinued BeagleV board. On Fedora with an image from https://github.com/starfive-tech/Fedora_on_StarFive

```
wget https://140206-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.22.0~c3b72b1a-0.riscv64.rpm
sudo dnf --verbose install --cacheonly ./telegraf-1.22.0~c3b72b1a-0.riscv64.rpm
```

```
$ uname -a
Linux fedora-starfive 5.15.0-61.fc33.riscv64 #1 SMP Wed Nov 10 20:58:14 CST 2021 riscv64 riscv64 riscv64 GNU/Linux
$ arch
riscv64
$ /usr/bin/telegraf --version
Telegraf 1.22.0-c3b72b1a (git: pull/10262 c3b72b1a)
```

Disable influxdb output and test as per your command

```
$ sudo sed --in-place 's/\[\[outputs.influxdb]]/# [[outputs.influxdb]]/' /etc/telegraf/telegraf.conf 
$ sudo sed --in-place 's/# \[\[outputs.file]]/[[outputs.file]]/' /etc/telegraf/telegraf.conf 
$ /usr/bin/telegraf --once --config /etc/telegraf/telegraf.conf
2021-12-22T12:15:39Z I! Starting Telegraf 1.22.0-c3b72b1a
2021-12-22T12:15:40Z I! Loaded inputs: cpu disk diskio kernel mem processes swap system
2021-12-22T12:15:40Z I! Loaded aggregators: 
2021-12-22T12:15:40Z I! Loaded processors: 
2021-12-22T12:15:40Z I! Loaded outputs: file
2021-12-22T12:15:40Z I! Tags enabled: host=fedora-starfive
2021-12-22T12:15:40Z I! [agent] Hang on, flushing any cached metrics before shutdown
mem,host=fedora-starfive mapped=239972352i,swap_total=3767529472i,vmalloc_chunk=0i,inactive=688164864i,vmalloc_total=68719475712i,write_back=0i,total=7536230400i,available=7146934272i,used_percent=3.725039404315452,sunreclaim=36020224i,committed_as=954851328i,free=6247800832i,slab=86716416i,page_tables=5591040i,shared=17858560i,swap_cached=0i,write_back_tmp=0i,available_percent=94.8343388227621,buffered=60723200i,high_free=0i,active=417480704i,high_total=0i,swap_free=3767529472i,sreclaimable=50696192i,vmalloc_used=57274368i,used=280727552i,huge_pages_free=0i,huge_pages_total=0i,huge_page_size=2097152i,low_total=0i,low_free=0i,cached=946978816i,commit_limit=7535644672i,dirty=262144i 1640175340000000000
disk,device=mmcblk0p4,fstype=ext4,host=fedora-starfive,mode=rw,path=/ inodes_free=3505912i,inodes_used=337448i,total=62132891648i,free=51711635456i,used=10281607168i,used_percent=16.585044970723292,inodes_total=3843360i 1640175340000000000
disk,device=mmcblk0p3,fstype=ext4,host=fedora-starfive,mode=rw,path=/boot inodes_used=42i,total=479895552i,free=375021568i,used=89497600i,used_percent=19.266718397291196,inodes_total=125184i,inodes_free=125142i 1640175340000000000
disk,device=mmcblk0p2,fstype=vfat,host=fedora-starfive,mode=rw,path=/boot/efi used=4685824i,used_percent=3.6706078642131774,inodes_total=0i,inodes_free=0i,inodes_used=0i,total=127657984i,free=122972160i 1640175340000000000
diskio,host=fedora-starfive,name=mmcblk0 io_time=146110i,merged_writes=3234i,writes=4587i,read_time=93381i,write_bytes=463056896i,write_time=1246298i,weighted_io_time=1351635i,iops_in_progress=0i,merged_reads=9788i,reads=10156i,read_bytes=526903296i 1640175340000000000
diskio,host=fedora-starfive,name=mmcblk0p2 merged_reads=245i,read_bytes=3325952i,write_bytes=0i,write_time=0i,io_time=820i,weighted_io_time=756i,iops_in_progress=0i,merged_writes=0i,reads=120i,writes=0i,read_time=596i 1640175340000000000
diskio,host=fedora-starfive,name=mmcblk0p3 reads=91i,writes=1i,read_time=974i,write_time=1i,weighted_io_time=1064i,merged_reads=4i,read_bytes=3339264i,write_bytes=4096i,io_time=1150i,iops_in_progress=0i,merged_writes=0i 1640175340000000000
diskio,host=fedora-starfive,name=mmcblk0p4 writes=4586i,read_bytes=518890496i,write_time=1246296i,io_time=145280i,merged_writes=3234i,reads=9871i,read_time=91499i,weighted_io_time=1349504i,iops_in_progress=0i,merged_reads=9539i,write_bytes=463052800i 1640175340000000000
swap,host=fedora-starfive used_percent=0,total=3767529472i,used=0i,free=3767529472i 1640175340000000000
swap,host=fedora-starfive in=0i,out=0i 1640175340000000000
kernel,host=fedora-starfive entropy_avail=1484i,interrupts=392591i,context_switches=393791i,boot_time=1640173148i,processes_forked=1193i 1640175340000000000
system,host=fedora-starfive load1=0.09,load5=0.37,load15=0.71,n_cpus=2i,n_users=2i 1640175340000000000
system,host=fedora-starfive uptime=2192i 1640175340000000000
system,host=fedora-starfive uptime_format=" 0:36" 1640175340000000000
diskio,host=fedora-starfive,name=zram0 reads=586i,writes=1i,write_bytes=4096i,read_time=10i,io_time=100i,iops_in_progress=0i,merged_writes=0i,read_bytes=2400256i,write_time=0i,weighted_io_time=10i,merged_reads=0i 1640175340000000000
processes,host=fedora-starfive sleeping=81i,total=127i,dead=0i,total_threads=191i,idle=46i,zombies=0i,running=0i,unknown=0i,paging=0i,blocked=0i,stopped=0i 1640175340000000000
cpu,cpu=cpu0,host=fedora-starfive usage_softirq=0,usage_guest=0,usage_system=7.999999999998408,usage_nice=0,usage_irq=2.000000000001023,usage_steal=0,usage_guest_nice=0,usage_user=7.999999999992724,usage_idle=81.9999999999709,usage_iowait=0 1640175341000000000
cpu,cpu=cpu1,host=fedora-starfive usage_user=12.244897959177992,usage_system=18.367346938781488,usage_idle=69.38775510210142,usage_iowait=0,usage_softirq=0,usage_nice=0,usage_irq=0,usage_steal=0,usage_guest=0,usage_guest_nice=0 1640175341000000000
cpu,cpu=cpu-total,host=fedora-starfive usage_softirq=0.9900990099016466,usage_nice=0,usage_iowait=0,usage_irq=0.9900990099007672,usage_steal=0,usage_guest=0,usage_user=9.900990099007672,usage_system=12.87128712872123,usage_idle=75.24752475254836,usage_guest_nice=0 1640175341000000000
2021-12-22T12:15:40Z I! [agent] Stopping running outputs

```

**Comment by powersj** [comment]
@philroche thank you for trying this out!

**Review by MyaLongmire — APPROVED** [review]
Thanks for doing this Josh!

**Pull request merged**
