### PR TITLE
Geth input plugin

### PR DESCRIPTION
**Pull request by drewkerrigan**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by drewkerrigan** [comment]
Hello @glinton, any updates or questions on this?

**Comment by glinton** [comment]
It's still in my queue to be reviewed, I'll try to get to it this week

**Comment by glinton** [comment]
This has been moved to the backburner for now but I'll keep an eye on it and once the backlog of more requested/popular plugins subsides, I'll revisit.

**Comment by drewkerrigan** [comment]
@glinton thanks for the update, I'll check back every so often for updates as well.

**Comment by drewkerrigan** [comment]
Hello @glinton ! Just wanted to follow-up on this PR and let your team know that we have published an open source DC/OS framework to run Ethereum / Geth (https://github.com/iss-lab/dcos-ethereum) as well as a blog post on Medium (https://medium.com/iss-lab/ethereum-on-dc-os-d6b6bf7ddd80). If you have any other questions or concerns regarding Geth or this input plugin please feel free to reach out!

**Comment by sjwang90** [comment]
@drewkerrigan Checking in as it's been awhile. It'd would great to this as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md)t hat can be used with `execd` to run seamlessly with Telegraf?

**Comment by drewkerrigan** [comment]
@sjwang90 Thanks for reaching out! 

Re: moving this to an external plugin: that makes complete sense to me. I probably won't have time to work on this anytime soon, but you can feel free to close this PR for now and we'll work on breaking it out into its own repository in the future.

**Pull request closed without merging**
