### PR TITLE
Added readable Database Names in SQL Managed Instance #6570

### PR DESCRIPTION
**Pull request by duncanpcc**
Added readable database names in SQL Managed Instance when pulling stats from sys.os_performance_counters. 

Using dynamic SQL as column physical_database_name does not exist in earlier versions of SQL Server, also only replaced user database names as replacing system database names was creating duplicate entries conflicting with primary key in table variable. 

Tested on SQL MI, SQL 2016 and SQL 2012. 

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Thanks @duncanpcc, but could you adjust the whitespace back to match the prior version for this pull request so we can more easily see the changes?

**Comment by srebhan** [comment]
@duncanpcc thanks for submitting this PR.
Can you please rebase on the latest master and make sure that the changes are minimal, i.e. no unnecessary whitespace changes.

**Comment by srebhan** [comment]
@duncanpcc any update?

**Comment by powersj** [comment]
Hi,

This PR has not been touched in a while and as a result I am going to close it. We are happy to review again once someone picks this back up with the suggested changes and rebased on master.

Thanks!

**Pull request closed without merging**
