### PR TITLE
feat(migrations): Add migration for inputs.snmp_legacy

### PR DESCRIPTION
**Pull request by srebhan**
- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

relates to #13376

This PR adds migrations for the deprecated `inputs.snmp_legacy` plugin that requires manual intervention.

### CODE REVIEW

**Review by powersj — APPROVED** [review]

**Comment by Hipska** [comment]
Am I right that in these cases it is opted for telegraf to just silently (Inform message in log) ignore the plugin rather than preventing telegraf to start up?

**Comment by srebhan** [comment]
I don't think we should silently ignore these but instead fail early and loudly. The user can still comment the plugins...

**Comment by Hipska** [comment]
I don’t see that actually. Could you point where this fail is happening?

**Comment by srebhan** [comment]
The fail happens as we do not remove the plugin and telegraf [will (or at least should) fail on start](https://github.com/influxdata/telegraf/blob/2c5fbbc2a73e7ff2a6d8f751e3188caf8e473f7f/config/config.go#L1231) when we rollout v1.30.0 on the deprecated plugin.

**Comment by Hipska** [comment]
Okay, I think I'm starting to get it.. But not completely yet.. 😂 

So, why is this migration created if it's not possible to migrate? And did I also understand correctly that the plugin code will not get actually removed in 1.30?

**Comment by srebhan** [comment]
> So, why is this migration created if it's not possible to migrate? 
I created the migration in case someone runs the `migrate` command and expects that afterwards the config works. Those people will now (hopefully) see the message and fix the issue themselves. Otherwise they might expect that Telegraf will just work...

> And did I also understand correctly that the plugin code will not get actually removed in 1.30?
We will discuss this. One idea is to keep the code in 1.30.0 (and get an error message) and remove it in 1.30.1 for the case that some unforeseen issues appear. The (more likely) alternative is to remove the code directly in revertible PRs.

**Comment by Hipska** [comment]
Many thanks for the explanations.. I now fully understand.

**Pull request merged**
