### PR TITLE
fix(metricpass): Remove python logic compatibility

### PR DESCRIPTION
**Pull request by powersj**
fixes: #13790

### CODE REVIEW

**Comment by knollet** [comment]
this is the old affected version.
```
me@host:~/filter-bug$ telegraf -config filter-bug.conf -test
[...]
> bugreport,host=host,this=shouldn't\ !\ be\ modified and="is modified" 1692367811000000000
> bugreport,host=host,this=should\ not\ pass\ unmodified but="does pass unmodified" 1692367811000000000
```

this is the fix-artefact:
```
me@host:~/filter-bug$ bugfix/telegraf-1.28.0/usr/bin/telegraf -config filter-bug.conf -test
[...]
> bugreport,host=host,this=shouldn't\ !\ be\ modified and="is not modified" 1692367801000000000
> bugreport,host=host,this=should\ not\ pass\ unmodified but="is modified" 1692367801000000000
```

this is the old affected version.
```
me@host:~/filter-bug$ telegraf -config filter-bug2.conf -test
2023-08-18T14:14:46Z I! Loading config: filter-bug2.conf
2023-08-18T14:14:46Z E! error loading config file filter-bug2.conf: error parsing regex, ERROR: <input>:1:6: Syntax error: no viable alternative at input '.&&'
 | tags.&& == 'the name of this tag is &&'
 | .....^
ERROR: <input>:1:9: Syntax error: extraneous input '==' expecting {'[', '{', '(', '.', '-', '!', 'true', 'false', 'null', NUM_FLOAT, NUM_INT, NUM_UINT, STRING, BYTES, IDENTIFIER}
 | tags.&& == 'the name of this tag is &&'
 | ........^
```
this is the fix-artefact:
```
me@host:~/filter-bug$ bugfix/telegraf-1.28.0/usr/bin/telegraf -config filter-bug2.conf -test
[...]
> bugreport,&&=the\ name\ of\ this\ tag\ is\ &&,and=now\ for\ something\ completely\ different,host=host the="larch" 1692368092000000000

```

Looks good to me

**Review by srebhan — CHANGES_REQUESTED** [review]
This is a breaking change and should be declared as such in the Changelog! Please also note that this was an explicit request by Dave back when I added this.

This being said, I'm fine with removing this as we can get rid of another regex pitfall and will approve when the breaking change is documented in the Changelog.

**Comment by powersj** [comment]
PR updated with change log entry!

> This is a breaking change and should be declared as such in the Changelog! Please also note that this was an explicit request by Dave back when I added this.

Ah ok thanks for the history

**Review by srebhan — APPROVED** [review]
Thanks for taking care of this @powersj!

**Pull request merged**
