### PR TITLE
fix(inputs.modbus): add slave id to failing connection

### LINKED ISSUE #12021: [[inputs.modbus]] add slave_id in logs
### Use Case

I have multiple bride devices which will convert RTU to TCP.  Each bridge device is connected to 25 Modbus devices. Some of my devices are failing to send data for various reasons. My goal is to list all the devices which are failing.
From the logs, how to find the faulty ones?  at present IP is logged, I believe If slave_id is also logged we can pinpoint that failing device.
```
telegraf_1       | 2022-10-14T20:12:53+05:30 E! [inputs.modbus] Error in plugin: read tcp 172.21.0.5:42978->192.168.13.106:502: i/o timeout
telegraf_1       | 2022-10-14T20:12:53+05:30 E! [inputs.modbus] Error in plugin: read tcp 172.21.0.5:46838->192.168.13.116:502: i/o timeout
telegraf_1       | 2022-10-14T20:12:53+05:30 E! [inputs.modbus] Error in plugin: dial tcp 192.168.13.122:502: i/o timeout 
```

### Expected behavior

--

### Actual behavior

--

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by MyaLongmire**
# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #12021

### CODE REVIEW

**Review by zak-pawel — APPROVED** [review]

**Comment by powersj** [comment]
This is a helpful change, but does this also actually resolve #12021? The error message the user shows is unwrapped, and I believe it is coming from the top of `Gather()` where there is a call to `m.connect()` and an unwrapped connect error.

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks @MyaLongmire!

**Comment by MyaLongmire** [comment]
@powersj the top of the gather connecting is not due to 1 slave having issues. That would come from a gateway device having problems connecting. In that case, he should use an alias to determine which gateway he is having problems with. I asked him to test the artifacts and recommended using an alias.

**Review by powersj — APPROVED** [review]

**Comment by powersj** [comment]
Given the closure of the original bug I'm going to merge this :)

**Pull request merged**
