### PR TITLE
Convert datid to a string for backwards compatibility

### LINKED ISSUE #3622: PostgreSQL input error after upgrade to 1.5.0 - datid is integer instead of string
Since I upgraded Telegraf via apt to 1.5.0 I get an error with postgresql input:

```
Dec 27 10:39:17 vs-psql-03 telegraf[12274]: 2017-12-27T09:39:17Z I! Starting Telegraf v1.5.0
Dec 27 10:39:17 vs-psql-03 telegraf[12274]: 2017-12-27T09:39:17Z I! Loaded outputs: influxdb
Dec 27 10:39:17 vs-psql-03 telegraf[12274]: 2017-12-27T09:39:17Z I! Loaded inputs: inputs.system inputs.net inputs.nginx inputs.processes inputs.swap inputs.postgresql inputs.cpu inputs.disk inputs.diskio inputs.kernel inputs.mem inputs.redis
Dec 27 10:39:17 vs-psql-03 telegraf[12274]: 2017-12-27T09:39:17Z I! Tags enabled: environment=production host=vs-psql-03 rails_env=production role=cloud
Dec 27 10:39:17 vs-psql-03 telegraf[12274]: 2017-12-27T09:39:17Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"vs-psql-03", Flush Interval:10s
Dec 27 10:39:30 vs-psql-03 telegraf[12274]: 2017-12-27T09:39:30Z E! Field type conflict, dropping conflicted points: Response Error: Status Code [400], expected [204], [field type conflict: input field "datid" on measurement "postgresql" is type integer, already exists as type string]
```

My current `telegraf.conf` postgresql input config:

```
  [[inputs.postgresql]]
    address = "host=127.0.0.1 user=postgres sslmode=disable dbname=cloud"
    databases = ["cloud"]
```

### PR DESCRIPTION
**Pull request by danielnelson**
closes #3622

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@james-lawrence I could use some advice here if you can spare the time.  Please ignore the code here so far, it won't work.

I introduced a regression into 1.5 causing oid types to be converted to ints instead of strings, so I'm trying to undo that.  Since this also affects postgresql_extensible I would like it to apply to all oids.

It seems like to fix this I will need to pass the `row.ColumnTypes()` into `accRow()` and then use that to setup the `columnMap` and `columnVars` with the correct types.  Do you think this is the best way to go about a fix?

**Comment by james-lawrence** [comment]
@danielnelson do you know what commit caused the regression so I can take a look?

**Comment by danielnelson** [comment]
It was part of #3210, when we updated pgx.  I believe it was added in https://github.com/jackc/pgx/commit/bec9bd261b6a0e11ecde620f2f7fd8a7ea07e529, quite some time back.

**Comment by james-lawrence** [comment]
ah, so basically the driver added first class support for the type which strips the default output.

unfortunately atm there isn't a good way of doing this. once https://github.com/jackc/pgx/pull/365 is merged we should be able to configure the output for types.

**Comment by danielnelson** [comment]
Too bad, I guess I'll just whip a release note for this item then.  Thanks for the help

**Pull request closed without merging**
