### PR TITLE
Add cgroup plugin

### PR DESCRIPTION
**Pull request by vlasad**
### Required for all PRs:

- [ ] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sebito91** [comment]
:+1: from us!

**Comment by Will-Beninger** [comment]
:+1: from us! I've pulled in your changes and have already started testing the plugin.

No issues so far and would love to see it pulled into 1.0.1 beta version!

**Comment by sebito91** [comment]
Any idea when we can merge this? Waiting for v.1.0.0?

**Comment by sparrc** [comment]
Hi @sebito91, sorry for the delay but I've been very busy with work on the logparser plugin. I have been trying to concentrate on that but can hopefully get to these PRs by the middle of the week.

**Comment by Will-Beninger** [comment]
@sparrc Appreciate it! My workaround at the moment to integrate cgroups and then our own plugins is quite ugly at the moment. haha

**Comment by sparrc** [comment]
Looks good on the whole, but are the flush_scope and writeWithBatches changes still necessary considering https://github.com/influxdata/telegraf/pull/1321?

**Comment by sparrc** [comment]
@vlasad bump, is the flush_scope argument still necessary? Seems like it is a duplication of the change @Maksadbek is working on.

**Comment by vlasad** [comment]
It's not necessary already. I have removed it.

**Comment by sparrc** [comment]
Thank you @vlasad !

I hope you don't mind I made one small change: I've changed the external configuration to be "files" instead of "fields". To me "files" makes more sense, and since they were already internally called "files" I went ahead and changed it externally.

**Comment by vlasad** [comment]
It's OK. Also It's necessary rename it in the README.md .

**Pull request closed without merging**
