### PR TITLE
update nsq input plugin to be compatible with latest version 1.0.0-co…

### PR DESCRIPTION
**Pull request by Ashtonian**
More info: https://github.com/influxdata/telegraf/issues/3147 

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
Will this still work with nsq version <1.0?

**Comment by Ashtonian** [comment]
nope - how do you want to handle that ? just a version flag default to latest perhaps?

**Comment by danielnelson** [comment]
Maybe we can autodetect?  We could do an optimistic parse, try to parse in latest format then fallback to old format.

**Comment by Ashtonian** [comment]
This should work. The tests are a bit sloppy but they work- didn't want to make them interdependent and also overly complicated. Parses new version and then if the version string is empty reverts to the old.

**Comment by Ashtonian** [comment]
any update?

**Pull request merged**
