### PR TITLE
fix(inputs.knx_listener): Ignore GroupValueRead requests

### LINKED ISSUE #15006: inputs.knx_listener is writing wrong "source" tag
### Relevant telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "Âµs"), "ms", "s".
  precision = ""

  
  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false
[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  ##   ex: urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
  urls = ["http://127.0.0.1:8086"]

  ## Token for authentication.
  token = 

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "Home"

  ## Destination bucket to write into.
  bucket = "knx"









# Listener capable of handling KNX bus messages provided through a KNX-IP Interface.
[[inputs.knx_listener]]
  ## Type of KNX-IP interface.
  ## Can be either "tunnel" or "router".
  service_type = "tunnel"

  ## Address of the KNX-IP interface.
  service_address = "192.168.1.106:3671"




[[inputs.knx_listener.measurement]]
  name = "Alarm"
  dpt = "1.005"
  addresses = ["0/2/2", # Windalarm (Markise)
               "0/2/3",  # Windalarm (Raffstores)
               "0/2/4"] # Regenalarm
```

### Logs from Telegraf

```text
Actual behavior
```

### System info

Telegraf 1.19.0+

### Docker

_No response_

### Steps to reproduce

Actual behavior

### Expected behavior

GroupValue_Read messages should been ignored because there is no valid payload data

### Actual behavior

When Im using DPT 1.005
knx listener
Screenshot 2024-03-16 144056
Screenshot 2024-03-16 163431
Screenshot 2024-03-16 170011
 is writing wrong source tag in some situations.

Situation: my sensor is having PA 1.1.50.
At the same time im using ETS6 connected to my KNX-IP Interface (Gira X1) via tunneling connection, having PA 1.1.6

Now i do a "GroupValue_Read" for example on 0/2/2. my Sensor (1.1.50) is responding via GroupValue_Response with its address. But in telegraf im getting 1.1.6 as source tag, but it has to be 1.1.50 instead.

For now other DPTs dont have this problem. First time I notice this but only with DPT 1.005.

I looks like knx-go is taking the PA from the GroupValue_Read message but the correct address is in the GroupValue_Response message

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by farmio**
## Summary

Ignore KNX GroupValueRead requests as they don't contain any value. Yet DPT 1 typed requests are treated as telegrams with `0` value.

These are my first lines of Go, so please be patient with me 😬

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #15006

### CODE REVIEW

**Comment by farmio** [comment]
!signed-cla

**Comment by userwithoutpassword** [comment]
I tested som more DPTs. Yes only DPT1.xxx have this problem

**Comment by farmio** [comment]
Yes, that's because unpacking GroupValueRead data for other DPTs fail at
https://github.com/influxdata/telegraf/blob/19ac5e8081291fa4c5f179e93884a311c24e0bf3/plugins/inputs/knx_listener/knx_listener.go#L147
> [inputs.knx_listener] Unpacking data failed: given application data has invalid length

so they have never get to be forwarded anyway.

**Comment by userwithoutpassword** [comment]
> Yes, that's because unpacking GroupValueRead data for other DPTs fail at
> 
> https://github.com/influxdata/telegraf/blob/19ac5e8081291fa4c5f179e93884a311c24e0bf3/plugins/inputs/knx_listener/knx_listener.go#L147
> 
> > [inputs.knx_listener] Unpacking data failed: given application data has invalid length
> 
> so they have never get to be forwarded anyway.

Interesting

But anyway there is no need for saving GroupValue_Read Messages because there is no valid data in this messages.

**Comment by farmio** [comment]
> What did u change? Does it now ignore all Read messages?

Yes, as it says in the PR description.

**Review by srebhan — COMMENTED** [review]
@farmio thanks for your contribution! Your code looks good but I do have two comments/concerns:

1. Your current code will spam the log-file as you generate an entry every time a group-read arrives. Please change the logic to only log each address once? Some lines below you can see an example for how to do it...
2. For some applications it might be advantageous to also log DPT1.xxx events. Could we just log a fixed value if the datagram does not contain any? Like a zero value or similar?

**Comment by farmio** [comment]
@srebhan Hi 👋! 

Ad 1: Depending on the log-level, current implementation will reduce logs, as the GroupValueRead-log is `debug`, but a read request for a non-DPT-1-Telegram will produce an `error` log (see https://github.com/influxdata/telegraf/pull/15007#issuecomment-2002580088)
The example you mentioned would filter out (except for the first occurrence) read request logs for unconfigured GAs. Is this in your interest? 
Or do you want to filter all GAs? I guess we may just remove the log in that case.

Ad 2: DPT 1.x write and response telegrams are still logged like they have been before. Only the read telegrams are filtered out. I can not think of an application needing to log a read telegram as constant value (without the possibility to distinguish it from writes/responses).

**Comment by farmio** [comment]
I moved the match for the message command behind the test for the group address.
Now the GroupValueRead debug log only applies for configured (known) group addresses.
Please let me know if this is what you meant.

**Comment by srebhan** [comment]
@farmio thanks for your explanation! So just to be sure I got it right, your PR filters the group-read-**request** but not the response!?!? If this is correct, I would not log anything and just go on. Please also add a small comment to the code on why this is required...

If you really want to log a debug message, you should really only log it once for a GA as some people run Telegraf in debug mode in production environments and we would log this _every_ single time we see a group-read request otherwise.

**Comment by farmio** [comment]
You are exactly right. We ignore the read request (that doesn't carry valuable data), but still process the responses (that do carry data). And of course we still process the normal write requests.

Removed the logging and added a comment explaining why GroupValueRead requests are ignored.

**Review by srebhan — APPROVED** [review]
Awesome. Thanks a lot @farmio for the fix and your explanation!

**Review by DStrand1 — APPROVED** [review]

**Review by powersj — APPROVED** [review]

**Pull request merged**
