### PR TITLE
[WIP] Add poller mode to Telegraf

### PR DESCRIPTION
**Pull request by titilambert**
Hello !
This is the first draft of https://github.com/influxdata/telegraf/issues/765

### CODE REVIEW

**Comment by sparrc** [comment]
thanks for the work @titilambert, but it's honestly going to be a pretty long time before I'm ready to merge something that is as large a change as this. I'm also not 100% sure it should even be a part of telegraf, maybe it should be a separate binary or even a separate repo.

Also-- why is it dependent on AMQP? Can you explain that?

**Comment by titilambert** [comment]
@sparrc Thanks for your reply !

I think this PR is more about the **InfluxData** environment than just Telegraf. I don't know the roadmap of InfluxData company so maybe this PR doesn't fit with ?
BTW, I understand this is a huge change (but it's almost an addition) in Telegraf and maybe also in Telegraf philosophy. 

But, let me just explain what I have in mind:
First of all, the schema ...
telegraf-polling2
... and schema arrows explanations:

| Arrow | Details |
|---------|----------|
| Telegraf/InfluxBD | Send metrics |
| InfluxDB/Kapacitor | Stream analyse |
| Kapacitor/RabbitMQ | Create *One shot tasks* and publish them in RabbitMQ |
| Discovering/Consol-Etcd-... | Find stuff to monitor |
| Discovering/Etcd | Generate Telegraf configuration from discovering and store it in Etcd |
| Discovering/RabbitMQ | Create *Scheduled tasks* and publish them in RabbitMQ |
| RabbitMQ/Telegraf | Give *Scheduled tasks* and *One shot tasks* to Poller/Hybrid Telegraf  |
| Etcd/Telegraf | Give Configuration Standard/Hybrid Telegraf |

Some definitions
* Task: (remote) Pulling check (unique input plugin configuration) like ping/snmp/http/...
* One shot tasks: Task run only ONE time by ONE of Telegraf with poller mode enabled
* Scheduled tasks: Task run every TIME interval by ONE of Telegraf with poller mode enabled

With this schema I'm trying to get a monitoring system which can:
* Automate the configuration generation
* Schedule remote pulling checks, launch these checks (and easy scaling up/down)
* Accept pushed metrics from an agent
* Schedule recheck tasks to limit False-Positive alert

**Comment by sparrc** [comment]
@titilambert I'm not sure I want such tight coupling with a queuing system integrated directly into Telegraf. In my opinion this seems to be a bit out of scope of the Telegraf project overall.

It seems to me like your "poller" code could be it's own executable that could trigger telegraf gathers (after #862 is done).

Would that satisfy everything or am I still missing something?

**Comment by titilambert** [comment]
@sparrc I understand that polling stuff is out of scope of the Telegraf project.

> Would that satisfy everything or am I still missing something?

Yes, I guess, but I'm thinking about create a friendly fork of Telegraf, just to maintain this branch/feature. What do you think about this ? ( I will still add features to Telegraf :) )

**Comment by sparrc** [comment]
yes, that would be fine with me :smile:

**Pull request closed without merging**
