### PR TITLE
feat(outputs.elasticsearch): support data streams

### LINKED ISSUE #15051: Elasticsearch output cannot be used with data streams
### Use Case

Setup an index template and data stream in Elasticsearch. Configure Telegraf to index into Elasticsearch with the "create" optype.

### Expected behavior

Data ingests into Elasticsearch correctly.

### Actual behavior

Elasticsearch returns an error, because only the "create" operation type can be used with data streams (not the default "index" operation type).

### Additional info

https://github.com/olivere/elastic/issues/1464

>Indexing requests add documents to a data stream. These requests must use an op_type of create.

https://www.elastic.co/guide/en/elasticsearch/reference/7.17/set-up-a-data-stream.html

### PR DESCRIPTION
**Pull request by cnemo-cenic**
## Summary
This provides a basic way to use Telegraf with Elasticsearch's data streams feature [1]. Usually you will manage the template yourself. This follows support upstream in the elasticsearch client library. [2]

[1] https://www.elastic.co/guide/en/elasticsearch/reference/7.17/set-up-a-data-stream.html
[2] https://github.com/olivere/elastic/issues/1464

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #15051

### CODE REVIEW

**Comment by cnemo-cenic** [comment]
test-integration seems to show unrelated errors, the output I modified was ok:

>ok      github.com/influxdata/telegraf/plugins/outputs/elasticsearch    145.201s

**Comment by srebhan** [comment]
@cnemo-cenic please sign the CLA! Otherwise we won't be able to take your contribution...

**Comment by cnemo-cenic** [comment]
@srebhan Odd question, but is there any CLA option for companies that want the CLA to be limited to a single contribution?

**Comment by powersj** [comment]
Hi,

> @srebhan Odd question, but is there any CLA option for companies that want the CLA to be limited to a single contribution?

Unfortunately, that is not an option we provide.

**Pull request closed without merging**
