### PR TITLE
separator to separate metrics and fields

### PR DESCRIPTION
**Pull request by owlet123**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

I solved problem with data separating. The default setting separated data with "-" but some databases are set to separate with ".". So now it is optional in config file.

### CODE REVIEW

**Comment by danielnelson** [comment]
closes #2561

**Comment by xblitz** [comment]
any news on this PR ?

**Comment by danielnelson** [comment]
@owlet123 Looks good, can you rebase/merge to fix the conflicts?

**Comment by danielnelson** [comment]
@owlet123 Thanks, I'm just going to make one tweak now that it is merged to preserve backwards compatibility by setting the default value to `_`.

**Pull request merged**
