### PR TITLE
fix(outputs.mongodb): Fix the issue of data not being stored in the database

### PR DESCRIPTION
**Pull request by l-ordofLords**
去除mongodb的collection的显示创建改为在输入数据时自动创建

# Required for all PRs

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

### CODE REVIEW

**Comment by l-ordofLords** [comment]
> 非常感谢您的拉取请求！ 🤝 ✒️ 提醒一下，CLA 尚未签署，我们在合并之前需要它。有机会时请[签署 CLA](https://www.influxdata.com/legal/cla/)，然后在此处发表评论说`!signed-cla`

!signed-cla

**Comment by l-ordofLords** [comment]
!signed-cla

**Comment by l-ordofLords** [comment]
> 晉語
> 
> 此 PR 按原样删除了创建新时序集合的功能。你能提出一个错误并解释你要解决什么问题吗？

When using the CreateCollection driver method, there may be a situation where data cannot be added. I tested it using the 5.0 version of the official image provided by Mongodb, but the data did not enter Mongodb. Therefore, I removed the createTimeSeriesCollection method and its reference

this is my config

[agent]
  interval = "3s"
  flush_interval = "5s"

[global_tags]
  user="yanxinhui"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
  core_tags = false

[[processors.converter]]
  [processors.converter.tags]
    measurement = ["cpu"]

[[outputs.mongodb]]
  # connection string examples for mongodb
  dsn = "mongodb://localhost:27017"
  authentication ="NONE"

and my mongodb image is  this
  docker pull mongo:5.0

**Comment by powersj** [comment]
> there may be a situation where data cannot be added

Can you explain what these situations are or provide us with a test case we could add?

Do you have any logs to show what error you got?

**Comment by l-ordofLords** [comment]
> > 可能会出现无法添加数据的情况
> 
> 您能解释一下这些情况是什么，或者为我们提供一个可以添加的测试用例吗？
> 
> 你有任何日志来显示你得到什么错误吗？
In the above answer, I showed the configuration of my Telegraf and the Mongodb image used. If you use this configuration to start Telegraf and write data to the corresponding version of Mongodb, you can see the situation of this problem. This is my example. I have already explained this clearly above, and the corresponding version is attached to the answer.
I don't have a corresponding log because Telegraf doesn't report any errors, but Mongodb doesn't display data and cannot provide logs. I suggest you test according to my instructions and immediately discover the problem.

**Comment by l-ordofLords** [comment]
> > 可能会出现无法添加数据的情况
> 
> 您能解释一下这些情况是什么，或者为我们提供一个可以添加的测试用例吗？
> 
> 你有任何日志来显示你得到什么错误吗？



> > there may be a situation where data cannot be added
> 
> Can you explain what these situations are or provide us with a test case we could add?
> 
> Do you have any logs to show what error you got?

ni

> > there may be a situation where data cannot be added
> 
> Can you explain what these situations are or provide us with a test case we could add?
> 
> Do you have any logs to show what error you got?

I am not very good at adding test cases because the previous test cases can be used, but the previous scripts cannot add even a single line of data in the MongoDB 5.0 image. That's why I came over to submit this change. You can use the previous test cases to test whether the previous script is available.

**Comment by powersj** [comment]
I am going to close this PR. Unfortunately you have not shown what the issue is and more importantly your change will break the current behavior for existing users. Without demonstrating the issue it is impossible to know why the change is even required.

More importantly, I cannot reproduce using the following config:

```toml
[agent]
    debug = true

[[inputs.cpu]]
[[outputs.mongodb]]
    dsn = "mongodb://localhost:27017"
    authentication = "NONE"
```

And then here is an example:

```
> docker run -it --rm mongo:5
...
> ./telegraf --config config.toml
2023-11-09T03:39:15Z I! Loading config: config.toml
2023-11-09T03:39:15Z I! Starting Telegraf 1.29.0-d4449b6f brought to you by InfluxData the makers of InfluxDB
2023-11-09T03:39:15Z I! Available plugins: 241 inputs, 9 aggregators, 29 processors, 24 parsers, 60 outputs, 5 secret-stores
2023-11-09T03:39:15Z I! Loaded inputs: cpu
2023-11-09T03:39:15Z I! Loaded aggregators: 
2023-11-09T03:39:15Z I! Loaded processors: 
2023-11-09T03:39:15Z I! Loaded secretstores: 
2023-11-09T03:39:15Z I! Loaded outputs: mongodb
2023-11-09T03:39:15Z I! Tags enabled: host=x1c6
2023-11-09T03:39:15Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"x1c6", Flush Interval:10s
2023-11-09T03:39:15Z D! [agent] Initializing plugins
2023-11-09T03:39:15Z D! [agent] Connecting outputs
2023-11-09T03:39:15Z D! [agent] Attempting connection to [outputs.mongodb]
2023-11-09T03:39:16Z D! [agent] Successfully connected to outputs.mongodb
2023-11-09T03:39:16Z D! [agent] Starting service inputs
2023-11-09T03:39:26Z D! [outputs.mongodb] Buffer fullness: 0 / 10000 metrics
2023-11-09T03:39:36Z D! [outputs.mongodb] Wrote batch of 9 metrics in 55.992257ms
2023-11-09T03:39:36Z D! [outputs.mongodb] Buffer fullness: 0 / 10000 metrics
2023-11-09T03:39:46Z D! [outputs.mongodb] Wrote batch of 9 metrics in 3.721295ms
2023-11-09T03:39:46Z D! [outputs.mongodb] Buffer fullness: 0 / 10000 metrics
^C2023-11-09T03:39:47Z D! [agent] Stopping service inputs
2023-11-09T03:39:47Z D! [agent] Input channel closed
2023-11-09T03:39:47Z I! [agent] Hang on, flushing any cached metrics before shutdown
2023-11-09T03:39:47Z D! [outputs.mongodb] Buffer fullness: 0 / 10000 metrics
2023-11-09T03:39:47Z I! [agent] Stopping running outputs
2023-11-09T03:39:47Z D! [agent] Stopped Successfully
```

ok so we reported that we successfully wrote metrics, now let's check mongo:

```s
root@x1c6:/# mongo
MongoDB shell version v5.0.22
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("88221cc7-1e35-43fc-bbd2-3de974d18fa4") }
MongoDB server version: 5.0.22
================
Warning: the "mongo" shell has been superseded by "mongosh",
which delivers improved usability and compatibility.The "mongo" shell has been deprecated and will be removed in
an upcoming release.
For installation instructions, see
https://docs.mongodb.com/mongodb-shell/install/
================
---
The server generated these startup warnings when booting: 
        2023-11-09T03:33:43.396+00:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
        2023-11-09T03:33:43.396+00:00: /sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'
---
> show dbs
admin     0.000GB
config    0.000GB
local     0.000GB
telegraf  0.000GB
> use telegraf
switched to db telegraf
> show collections
cpu
system.buckets.cpu
system.views
> db.cpu.count()
18
> db.cpu.findOne()
{
	"timestamp" : ISODate("2023-11-09T03:39:30Z"),
	"tags" : {
		"cpu" : "cpu0",
		"host" : "x1c6"
	},
	"usage_system" : 1.3626834381550939,
	"usage_guest" : 0,
	"usage_irq" : 0.4192872117400439,
	"usage_steal" : 0,
	"usage_guest_nice" : 0,
	"_id" : ObjectId("654c54781a2c99e441519ba8"),
	"usage_idle" : 94.44444444444709,
	"usage_iowait" : 0.5241090146750619,
	"usage_user" : 3.03983228511553,
	"usage_softirq" : 0.2096436058700173,
	"usage_nice" : 0
}
> 
```

**Comment by l-ordofLords** [comment]
> I am going to close this PR. Unfortunately you have not shown what the issue is and more importantly your change will break the current behavior for existing users. Without demonstrating the issue it is impossible to know why the change is even required.
I tried my configuration based on your instance and did reproduce the situation. You are right, the script is fine, but why does navicat not display the corresponding collection in some cases in the database.

**Comment by l-ordofLords** [comment]
> I am going to close this PR. Unfortunately you have not shown what the issue is and more importantly your change will break the current behavior for existing users. Without demonstrating the issue it is impossible to know why the change is even required.
> 
> More importantly, I cannot reproduce using the following config:
> 
> ```toml
> [agent]
>     debug = true
> 
> [[inputs.cpu]]
> [[outputs.mongodb]]
>     dsn = "mongodb://localhost:27017"
>     authentication = "NONE"
> ```
> 
> And then here is an example:
> 
> ```
> > docker run -it --rm mongo:5
> ...
> > ./telegraf --config config.toml
> 2023-11-09T03:39:15Z I! Loading config: config.toml
> 2023-11-09T03:39:15Z I! Starting Telegraf 1.29.0-d4449b6f brought to you by InfluxData the makers of InfluxDB
> 2023-11-09T03:39:15Z I! Available plugins: 241 inputs, 9 aggregators, 29 processors, 24 parsers, 60 outputs, 5 secret-stores
> 2023-11-09T03:39:15Z I! Loaded inputs: cpu
> 2023-11-09T03:39:15Z I! Loaded aggregators: 
> 2023-11-09T03:39:15Z I! Loaded processors: 
> 2023-11-09T03:39:15Z I! Loaded secretstores: 
> 2023-11-09T03:39:15Z I! Loaded outputs: mongodb
> 2023-11-09T03:39:15Z I! Tags enabled: host=x1c6
> 2023-11-09T03:39:15Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"x1c6", Flush Interval:10s
> 2023-11-09T03:39:15Z D! [agent] Initializing plugins
> 2023-11-09T03:39:15Z D! [agent] Connecting outputs
> 2023-11-09T03:39:15Z D! [agent] Attempting connection to [outputs.mongodb]
> 2023-11-09T03:39:16Z D! [agent] Successfully connected to outputs.mongodb
> 2023-11-09T03:39:16Z D! [agent] Starting service inputs
> 2023-11-09T03:39:26Z D! [outputs.mongodb] Buffer fullness: 0 / 10000 metrics
> 2023-11-09T03:39:36Z D! [outputs.mongodb] Wrote batch of 9 metrics in 55.992257ms
> 2023-11-09T03:39:36Z D! [outputs.mongodb] Buffer fullness: 0 / 10000 metrics
> 2023-11-09T03:39:46Z D! [outputs.mongodb] Wrote batch of 9 metrics in 3.721295ms
> 2023-11-09T03:39:46Z D! [outputs.mongodb] Buffer fullness: 0 / 10000 metrics
> ^C2023-11-09T03:39:47Z D! [agent] Stopping service inputs
> 2023-11-09T03:39:47Z D! [agent] Input channel closed
> 2023-11-09T03:39:47Z I! [agent] Hang on, flushing any cached metrics before shutdown
> 2023-11-09T03:39:47Z D! [outputs.mongodb] Buffer fullness: 0 / 10000 metrics
> 2023-11-09T03:39:47Z I! [agent] Stopping running outputs
> 2023-11-09T03:39:47Z D! [agent] Stopped Successfully
> ```
> 
> ok so we reported that we successfully wrote metrics, now let's check mongo:
> 
> ```m68k
> root@x1c6:/# mongo
> MongoDB shell version v5.0.22
> connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
> Implicit session: session { "id" : UUID("88221cc7-1e35-43fc-bbd2-3de974d18fa4") }
> MongoDB server version: 5.0.22
> ================
> Warning: the "mongo" shell has been superseded by "mongosh",
> which delivers improved usability and compatibility.The "mongo" shell has been deprecated and will be removed in
> an upcoming release.
> For installation instructions, see
> https://docs.mongodb.com/mongodb-shell/install/
> ================
> ---
> The server generated these startup warnings when booting: 
>         2023-11-09T03:33:43.396+00:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
>         2023-11-09T03:33:43.396+00:00: /sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'
> ---
> > show dbs
> admin     0.000GB
> config    0.000GB
> local     0.000GB
> telegraf  0.000GB
> > use telegraf
> switched to db telegraf
> > show collections
> cpu
> system.buckets.cpu
> system.views
> > db.cpu.count()
> 18
> > db.cpu.findOne()
> {
> 	"timestamp" : ISODate("2023-11-09T03:39:30Z"),
> 	"tags" : {
> 		"cpu" : "cpu0",
> 		"host" : "x1c6"
> 	},
> 	"usage_system" : 1.3626834381550939,
> 	"usage_guest" : 0,
> 	"usage_irq" : 0.4192872117400439,
> 	"usage_steal" : 0,
> 	"usage_guest_nice" : 0,
> 	"_id" : ObjectId("654c54781a2c99e441519ba8"),
> 	"usage_idle" : 94.44444444444709,
> 	"usage_iowait" : 0.5241090146750619,
> 	"usage_user" : 3.03983228511553,
> 	"usage_softirq" : 0.2096436058700173,
> 	"usage_nice" : 0
> }
> > 
> ```

I tried my configuration based on your instance and did reproduce the situation. You are right, the script is fine, but why does navicat not display the corresponding collection in some cases in the database.

**Pull request closed without merging**
