### PR TITLE
Changing StatsD in telegraf so that it able to fetch timestamp from m…

### PR DESCRIPTION
**Pull request by souvik-ray**
…etric tags instead of using current timestamp

Testing is done....
 === Input ===
souvik@souvik-HP-ProBook-450-G2:~$ echo "user.logins,service=payroll,region=us-west,timestamp=1455600970:1|c" | nc -C -w 1 -u localhost 8125
souvik@souvik-HP-ProBook-450-G2:~$ echo "user.logins,service=payroll,region=us-west,timestamp=1455600970:1|c" | nc -C -w 1 -u localhost 8125
souvik@souvik-HP-ProBook-450-G2:~$ echo "user.logins,service=payroll,region=us-west,timestamp=1455600970:1|c" | nc -C -w 1 -u localhost 8125
^[[Asouvik@souvik-HP-ProBook-450-G2:~$ echo "user.logins,service=payroll,region=us-west,timestamp=1455600970:1|c" | nc -C -w 1 -u localhost 8125
souvik@souvik-HP-ProBook-450-G2:~$ echo "user.logins,service=payroll,region=us-west,timestamp=1455600970:1|c" | nc -C -w 1 -u localhost 8125

=== Output ===
souvik@souvik-HP-ProBook-450-G2:~/workspace/telegraph/telegraf$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.10.0
InfluxDB shell 0.10.0
> show databases
name: databases
---------------
name
_internal
telegraf

> use telegraf
Using database telegraf
> select * from user_logins
name: user_logins
-----------------
time			host				metric_type	region	service	timestamp	value
1455600970000000000	souvik-HP-ProBook-450-G2	counter		us-west	payroll	1455600970	3

### CODE REVIEW

**Comment by sparrc** [comment]
Not sure I will merge this since timestamps are not part of the statsd spec, but you'll need to write unit tests regardless.

Also, what happens when it gets multiple timestamps within the same collection interval?

The whole purpose of statsd is aggregation, so how do you aggregate multiple timestamps in the same measurement?

**Comment by souvik-ray** [comment]
The way I am using the statsd in telegraf is.
1) My service generates service logs which I write to a file.
2) A continously running daemon reads the service logs and passes the data to the statsd client (in telegraf).
The issue for relying on statsd timestamp is for somereason the daemon or statsd component is down or the backend influxdb databases is not reachable, the pending metrics will accumulate and show an incorrect timestamp of the event. The time stamp is of utmost importance to me. 

Regarding your queries about aggregation, I thought about it and any one time stamp from an aggregated metrics is good enough for this purpose because that will still give me an approximation on when that event occured in the time window.

I ll add the test cases in sometime

**Comment by sparrc** [comment]
@souvik-ray If your timestamps are of utmost importance, I'm not sure that statsd is the correct protocol for you to be using. You can write InfluxDB line-protocol directly to the database, or to a message broker and then consume it with Telegraf.

in 0.10.3 you'll also be able to consume graphite or JSON from a message broker

**Comment by sparrc** [comment]
not going to merge this unless there's significant demand for it, I'd prefer not to get too far from vanilla statsd. If timestamps are important to you, statsd is probably not the right solution.

**Pull request closed without merging**
