### PR TITLE
feat: check TLSConfig early to catch missing certificates

### PR DESCRIPTION
**Pull request by isodude**
### Required for all PRs:

- [-] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

feat: check TLSConfig early to catch missing certificates

Since outputs and inputs are started async, missing certificates will
let the process start but then fail after 15s.

Most likely missing certificates should fail hard rather than soft.

### CODE REVIEW

**Comment by powersj** [comment]
Hi - could you take a look at the test failures? Thanks!

**Comment by isodude** [comment]
> Hi - could you take a look at the test failures? Thanks!

I did look at the test case, not directly sure how I should proceed with them, but I'll figure it out.

Is the basic idea good to start with?

**Comment by powersj** [comment]
It looks like it is the same test case failing in all attempts: `TestConfig_LoadSpecialTypes` from `telegraf/config/config_test.go`

With the error:

`Error loading config file ./testdata/special_types.toml: error parsing http_listener_v2, could not load keypair /path/to/my/cert`

I would like to see two things:

1) A new test case that correctly fails early due to a missing cert file. This would test the behavior of this MP.
2) The above test case was using a fake path to a cert and key. Your MP changes the behavior to throw the error earlier. In the testdata directory let's ensure there is a fake cert and key file there so the rest of this test case continues on now with the new behavior.

**Comment by isodude** [comment]
> It looks like it is the same test case failing in all attempts: `TestConfig_LoadSpecialTypes` from `telegraf/config/config_test.go`
> 
> With the error:
> 
> `Error loading config file ./testdata/special_types.toml: error parsing http_listener_v2, could not load keypair /path/to/my/cert`
It's still not working. This is however not my fault, it seems that
```
"""
./testdata/special_types.pem
"""
```

Is not trimmed. Should we trim it inside tls-config? Or earler?

**Comment by powersj** [comment]
> Is not trimmed. Should we trim it inside tls-config? Or earlier?

Not sure I follow, my suggestion is to do what you need to get that test working again, and we can review the changes.

**Comment by isodude** [comment]
> > Is not trimmed. Should we trim it inside tls-config? Or earlier?
> 
> Not sure I follow, my suggestion is to do what you need to get that test working again, and we can review the changes.

I updated, my point being here that I need to change from multi line to single line, I can keep the triple quotes but since line breaks are kept the file will not be found if line break are kept.

**Comment by isodude** [comment]
> > > Is not trimmed. Should we trim it inside tls-config? Or earlier?
> > 
> > 
> > Not sure I follow, my suggestion is to do what you need to get that test working again, and we can review the changes.
> 
> I updated, my point being here that I need to change from multi line to single line, I can keep the triple quotes but since line breaks are kept the file will not be found if line break are kept.

I solved this I think. Everything should be in place now!

**Review by powersj — APPROVED** [review]
Thanks for cleaning up the tests!

**Review by sspaink — APPROVED** [review]

**Pull request merged**
