### PR TITLE
fix: prometheus input plugin run outside k8s cluster error

### PR DESCRIPTION
**Pull request by yahaa**
# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

[The first one](https://github.com/influxdata/telegraf/pull/9960/files#diff-dcebbfefbef8e986af6172ea7f96ab8b6d0b62aac383a7fa3f7bc1df5d06f2e0L57), when we run telegra in outside of a kubernetes cluster the line `config, err := rest.InClusterConfig()` will be always get an error.

[The second one](https://github.com/influxdata/telegraf/pull/9960/files#diff-dcebbfefbef8e986af6172ea7f96ab8b6d0b62aac383a7fa3f7bc1df5d06f2e0L50), the method of getting rest.Config instance in loadClient function will be cause kubernetes client has error materURL, and this error can be reproduced by using the following UT:
```
// add this UT into plugins/inputs/prometheus/kubernetes_test.go
func TestLoadClient(t *testing.T) {
	kubeconfig := "/path_to_your_kubeconfig"
	client, err := loadClient(kubeconfig)
	if err != nil {
		t.Errorf("got err: %v", err)
		return
	}

	watcher, err := client.CoreV1().Pods("kube-system").Watch(context.TODO(), metav1.ListOptions{
		LabelSelector: "app=debug",
	})
	if err != nil {
		t.Errorf("watch pod got err: %v", err)
		return
	}
	defer watcher.Stop()
}
```
this UT can got watch pod got err: Get "http://localhost/api/v1/namespaces/kube-system/pods?labelSelector=app%3Ddebug&watch=true": dial tcp 127.0.0.1:80: connect: connection refused error.

### CODE REVIEW

**Comment by powersj** [comment]
Hi,

Can you remind me if you filed a bug for this issue?

Also, I understand the only way to try to start monitoring a K8s cluster is if `monitor_kubernetes_pods` is set to `true`. If you set that to false, shouldn't that avoid this?

Thanks

**Comment by yahaa** [comment]
> Hi,
> 
> Can you remind me if you filed a bug for this issue?
> 
> Also, I understand the only way to try to start monitoring a K8s cluster is if `monitor_kubernetes_pods` is set to `true`. If you set that to false, shouldn't that avoid this?
> 
> Thanks

In this case such as following input config，the telegraf process is not running properly

```toml
[[inputs.prometheus]]
  monitor_kubernetes_pods = true
  kube_config = "/path/to/kubernetes.config"
```

**Comment by yahaa** [comment]
> > Hi,
> > Can you remind me if you filed a bug for this issue?
> > Also, I understand the only way to try to start monitoring a K8s cluster is if `monitor_kubernetes_pods` is set to `true`. If you set that to false, shouldn't that avoid this?
> > Thanks
> 
> In this case such as following input config，the telegraf process is not running properly
> 
> ```toml
> [[inputs.prometheus]]
>   monitor_kubernetes_pods = true
>   kube_config = "/path/to/kubernetes.config"
> ```

In my environment, telegraf is running outside the k8s cluster, so I need to specify kubeconfig to run telegraf, and then I get an error.

After analyzing the prometheus input plugin code, I found that the problem occurs in the following two points:

1. https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/kubernetes.go#L59 always try to run inCluster mode.
2. https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/kubernetes.go#L52 using this way to get kubeconfig will cause this k8s client watch pod error (`watch pod got err: Get "http://localhost/api/v1/namespaces/kube-system/pods?labelSelector=app%3Ddebug&watch=true": dial tcp 127.0.0.1:80: connect: connection refused error.`)

**Comment by yahaa** [comment]
Hi @powersj would you please help me to review this pr once again?

**Review by powersj — APPROVED** [review]

**Pull request merged**
