### PR TITLE
chore(deps): Bump github.com/influxdata/influxdb-observability libraries from 0.3.3 to 0.3.15

### PR DESCRIPTION
**Pull request by povilasv**
# Required for all PRs

Update otel2influx libraries so that we can support delta temporality in statsd plugin
REF:  https://github.com/influxdata/telegraf/issues/12507

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

### CODE REVIEW

**Review by powersj — APPROVED** [review]
Thanks for diving this effort! can you confirm that the PR works as you expect as well?

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks for the update @povilasv!

**Comment by srebhan** [comment]
@powersj assigning the PR back to you in case you want to wait for feedback...

**Comment by srebhan** [comment]
Thanks @povilasv! I guess that counts as feedback... ;-)

**Pull request merged**
