### PR TITLE
provide basic auth capabilities to elasticsearch plugin

### PR DESCRIPTION
**Pull request by Crapworks**
### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

PR #1970 was closed because there were two different issues in it and it should be split. Since we are also using Shield and need basic authentication for the plugin to work, I extracted the relevant parts and made a new PR.

Regards,
Christian

### CODE REVIEW

**Comment by phemmer** [comment]
What about putting the credentials in the URL instead of separate parameters?
All the official clients support the scheme, while only some of them support user/pass as separate parameters, and the parameters vary at that, thus URL might be considered more standard.
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html
https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_security.html

Just a thought. :-)

**Comment by somnair** [comment]
Thanks @Crapworks for creating a new PR . @phemmer nice idea . i can give that a try :)

**Comment by Crapworks** [comment]
@phemmer that acutally works! Haven't thought about that. In this case, there should just be a comment that is mentioning that possibility in the config. Wan't me to create a new PR for that?

**Comment by sparrc** [comment]
sure, or just update this PR with a force push

**Comment by Crapworks** [comment]
@sparrc Done

**Comment by sparrc** [comment]
closed by efb64a0

**Pull request closed without merging**
