### PR TITLE
feat: Quality as a tag workaround

### LINKED ISSUE #9405: [inputs.opcua] Quality should be a tag and not a field
## Feature Request

Regarding the opcua input plugin:

### Proposal:

In my opionon quality should be a tag and not a field based on the [InfluxDB schema design and data layout]( https://docs.influxdata.com/influxdb/v1.8/concepts/schema_and_data_layout/#encode-meta-data-in-tags).

### Current behavior:

Quality is a field

### Desired behavior:

Quality should be a tag

### Use case: 

Filtering for good quality data

### PR DESCRIPTION
**Pull request by R290**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #9405

A set of workarounds for the opcua input plugin were introduced in #10384. Adding a workaround for quality as a tag instead of a field ensures backwards compatibility. I did not add a specific unit test since quality as a field was also not tested in the original.

### CODE REVIEW

**Comment by powersj** [comment]
@reimda thoughts on adding this as a boolean?

**Comment by R290** [comment]
@reimda see https://github.com/influxdata/telegraf/issues/9405#issuecomment-967314832 on why the converter plugin will probably not suffice. I'm not filtering as much on quality as I thought I would so I'm also happy to leave this open.

**Comment by powersj** [comment]
@R290,

Looking at older PRs right now and came across this. Looking at your comments in #9405, it isn't immediately apparent to me why you wouldn't use the converter plugin? You would then have two unique metrics in your example.

**Comment by R290** [comment]
Closed due to no longer being needed.

**Pull request closed without merging**
