### PR TITLE
feat(inputs.jenkins): add option for node labels as tag

### PR DESCRIPTION
**Pull request by powersj**
fixes: #13626

### CODE REVIEW

**Comment by 1tft** [comment]
Thank you for that ultra fast PR. Will test it detailed with our Jenkins servers next week. Still found a typo issue: lables != labels

**Review by srebhan — APPROVED** [review]
Looks good to me. Thanks @powersj!

**Comment by srebhan** [comment]
Reassigning to you @powersj in case you want to wait for the testing...

**Comment by 1tft** [comment]
@powersj FYI: Installed latest build and found no issues. Thanks!

**Pull request merged**
