### PR TITLE
chore(linters): Enable `preferDecodeRune` and `preferFprint` checkers for gocritic

### PR DESCRIPTION
**Pull request by zak-pawel**
resolves https://github.com/influxdata/telegraf/issues/14406 (preferDecodeRune)
resolves https://github.com/influxdata/telegraf/issues/14407 (preferFprint)

### CODE REVIEW

**Review by Hipska — APPROVED** [review]

**Comment by srebhan** [comment]
@zak-pawel the `fmt.Fprintf` changes assume that this function does not return an error and I wonder why you can make that assumption!? `fmt.Fprintf` writes to an `io.Writer` which _can_ return an error, e.g. if it is a network connection which is closed or a file and the disk is full, can't it?

**Comment by zak-pawel** [comment]
@srebhan You're right, I got carried away a bit. Where mistakes should be dealt with, I allowed them to be dealt with again.

**Review by srebhan — APPROVED** [review]
Thanks for the update and all your work @zak-pawel!

**Review by powersj — APPROVED** [review]

**Comment by powersj** [comment]
@zak-pawel please resolve conflicts

**Comment by zak-pawel** [comment]
@powersj Done.

**Pull request merged**
