### PR TITLE
New Output Plugin: AMQP 1.0 (e.g. Azure ServiceBus)

### PR DESCRIPTION
**Pull request by phires**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

This PR adds AMQP1.0 as output plugin. Can be used with e.g. Azure ServiceBus.
This replaces my old PR #4327

### CODE REVIEW

**Comment by sjwang90** [comment]
Hi @phires, it's been awhile but I was wondering if you'd be willing to submit this output plugin as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf? Telegraf users would be able to use the plugin sooner by having it as an external plugin since it wouldn't have to go through the typical review process.

**Comment by phires** [comment]
Hi, I'll look into this, doesn't look too hard!

**Comment by srebhan** [comment]
@phires if you rebase this code I can give it a review...

**Comment by srebhan** [comment]
@phires any news on this?

**Comment by phires** [comment]
Sadly I had not yet time to look into this :(

**Comment by sjwang90** [comment]
Going to close this PR for now as the interest for an AMQP output has waned. If anyone is interesting in picking this up and submitting it as an external plugin please feel free to do so.

**Pull request closed without merging**
