### PR TITLE
Fix uint64 value parse issue in mysql plugin

### PR DESCRIPTION
**Pull request by gangseok514**
Solve https://github.com/influxdata/telegraf/issues/4331

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by gangseok514** [comment]
@danielnelson Hello, Could you review this PR?

**Comment by glinton** [comment]
This change would break some existing stacks. For example, you cannot change a value type in influx so any new metrics, properly parsed, would get dropped if the value in question was already stored as a float64.

**Comment by danielnelson** [comment]
With this implementation the field will vary it's type depending on the value, which will cause problems even if we ignore what the current type is.  Perhaps we can find a better method for assigning types than this fallback list.  We should check what type the database driver believes these fields are, does it differentiate between int64, uint64 and float64?

**Comment by gangseok514** [comment]
I understand what you concern. But I couldn't find other problems except @glinton's example.
Anyway, I faced a critical issue related to this.
I'm using fluentd and telegraf sends metric to fluentd. Fluentd cannot parse the value(Bignum too big to convert to unsigned long long) because of this issue.
I had to drop the field manually but the values can be useful for some users.

As you know, mariadb has this value as default in some configuration variables. https://mariadb.com/kb/en/library/server-system-variables/#max_join_size

I think telegraf is the best metric agent. so I'm using it with influxdb very well in my k8s clusters.

But now I need to customize telegraf for this. I hope to contribute this
Thanks

**Comment by danielnelson** [comment]
> Fluentd cannot parse the value(Bignum too big to convert to unsigned long long) because of this issue.

This seems like it might be an independent issue, how are you sending metrics from Telegraf to fluentd?

**Comment by danielnelson** [comment]
So you are using the socket_writer + `data_format = "json"`?

JSON has arbitrary length and precision numbers, not float/int, I think the `.0` is left out if it not needed.  Here are the details of the float to number encoding: https://golang.org/src/encoding/json/encode.go?s=6456:6499#L537

You may want to capture the JSON output from Telegraf and let the fluentd team know about it, to me it sounds like an issue for them to take a look at.

**Comment by srebhan** [comment]
@gangseok514: The mysql-driver supports ColumnTypeScanType() to derive the actual type from the DB/scheme-definition. It includes information about signedness of the column. Instead of guessing the types, we should use this information to parse the value.
So I agree with the other guys that this is not the right fix.

**Comment by sjwang90** [comment]
Closing this issue. If anyone is interesting in fixing this based off the above discussion feel free to submit a PR.
> The mysql-driver supports ColumnTypeScanType() to derive the actual type from the DB/scheme-definition. It includes information about signedness of the column. Instead of guessing the types, we should use this information to parse the value.

**Pull request closed without merging**
