### PR TITLE
feat: support ingesting multi-measures to timestream

### PR DESCRIPTION
**Pull request by zhihaoli**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

Feature: support ingesting multi-measures to timestream

The feature controlled using the use_multi_measure_records field which is set to false by default for backward compatibility.

### CODE REVIEW

**Comment by sjwang90** [comment]
Since this a breaking change we suggest to see if there's any way to have these changes be backwards compatible until we have a Telegraf 2.0 and can deprecate the old behavior. 

With other plugins that have wanted to implemented behavior changes, if you use the old configuration, it sets to old behavior. If you generate a new sample config it will set the setting to the new value to select new behavior. Similar to the `metric_version = 2` in the [Prometheus Input plugin](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/README.md).

@reimda chime in with anything you have to add

**Comment by zhihaoli** [comment]
@sjwang90 thanks for the suggestion, we are looking into it. By the way, what is the current timeline for Telegraf 2.0?

**Comment by sjwang90** [comment]
@zhihaoli we're currently scoping it out but we'd hope for something later this year. We'll want to make sure any major/breaking updates you and the timestream need are included.

**Comment by zhihaoli** [comment]
Closing in favor of new PR: https://github.com/influxdata/telegraf/pull/10952

**Pull request closed without merging**
