### PR TITLE
Jitter for Input plugin Ping

### PR DESCRIPTION
**Pull request by alekseyp**
### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sparrc** [comment]
I think calling `standard_deviation_ms` would be more clear

**Comment by alekseyp** [comment]
@sparrc updated.

**Comment by alekseyp** [comment]
@sparrc , any idea if it will be part of 1.2.0?
Of if there anything else needs to be done?

**Comment by sparrc** [comment]
yes I think we can get it in for 1.2

**Pull request merged**
