### PR TITLE
Win perf plugin doc proof read

### PR DESCRIPTION
**Pull request by vlastahajek**
Proofread of windows performance counter plugin readme and sample config description from our tech writer

- [X] Signed [CLA](https://influxdata.com/community/cla/).

### CODE REVIEW

**Comment by danielnelson** [comment]
Merged as f217d12de52bff56d6e43e4e36bd1993935f69e0 but I didn't take the UseWildcardExpansion section.

**Comment by vlastahajek** [comment]
Ok, what was wrong with it? The proofreading was done on the branch for  PR #4265, where UseWildcardExpansion section was introduced, but he didn't manage to do it in the time before PR was merged..

**Comment by danielnelson** [comment]
Nothing major, I just felt it was a little too choppy and didn't read well.

**Comment by vlastahajek** [comment]
It's no problem to reformat the text to paragraphs,  if as would like it better. There are, imho, good corrections to my original text with lame English expressions

**Pull request closed without merging**
