### PR TITLE
docs(inputs.opcua): typing error

### PR DESCRIPTION
**Pull request by Giu-seppe**
Simple typing error in an example

### CODE REVIEW

**Review by powersj — APPROVED** [review]
Thanks for taking the time to put up a PR with a fix!

**Review by MyaLongmire — APPROVED** [review]

**Comment by MyaLongmire** [comment]
@Giu-seppe please sign the CLA so we can get this merged :)

**Comment by Giu-seppe** [comment]
I don't know how to do it 
I'm really a newbie with GitHub :')

**Comment by powersj** [comment]
> I don't know how to do it I'm really a newbie with GitHub :')

If you click on this link: https://www.influxdata.com/legal/cla/ and scroll to the bottom there is a form to file out. Let us know once you have done that please.

**Comment by Giu-seppe** [comment]
Done

**Comment by powersj** [comment]
!signed-cla

**Comment by powersj** [comment]
Thanks for the PR!

**Pull request merged**
