### PR TITLE
feat(inputs.sflow): Add default source tag

### PR DESCRIPTION
**Pull request by Hipska**
# Required for all PRs

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

Related to #8011 and #4413

Add the source tag to standardise the sflow input.

### CODE REVIEW

**Comment by srebhan** [comment]
@Hipska while I love the PR, the issue is that you double the cardinality (at least for InfluxDB) users with this change. Can you please add an option to switch between the existing tag and the new `source` tag!

**Comment by Hipska** [comment]
I did follow [METRIC_FORMAT_CHANGES](https://github.com/influxdata/telegraf/blob/master/docs/developers/METRIC_FORMAT_CHANGES.md) doc, it is not considered to be unsafe (whose need such an option).

**Comment by powersj** [comment]
> it is not considered to be unsafe (whose need such an option).

While adding a tag is not specifically listed as "unsafe" it is listed as "be careful with 
cardinality". The addition of this tag is not strictly necessary. In order to prevent issues who may already be at a limit of cardinality for whatever reason, then it should follow the unsafe change guidelines: 

> If your change has the potential to seriously affect existing users, the change must be opt-in.

**Comment by powersj** [comment]
@Hipska same question here -do you want to make it a doc change to suggest using "source" or close this?

**Comment by Hipska** [comment]
Well, if the idea is to deprecate this plugin, then its best to just close this PR I guess..

**Pull request closed without merging**
