### PR TITLE
Add Protocol Buffers output data format

### PR DESCRIPTION
**Pull request by dialogbox**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

In addition to the current output data formats, I added a new binary output data format `protobuf`.

### Purporse:

To define protobuf messages and add output data format to support it.

### Current behavior:

Only text based output is supported.

### Desired behavior:

New format `protobuf` generates Protocol Buffers encoded metrics with/without byte length prefix depends on setting.

### Use case:

Even the text based formats are easy to use, these are not the most efficient to parse and process. Protocol Buffers can be used to define language-neutral, platform-neutral binary data encoding and the result can be easily encoded, decoded with many built-in safety checks.

### CODE REVIEW

**Comment by phemmer** [comment]
> Even the text based formats are easy to use, these are not the most efficient to parse and process. Protocol Buffers can be used to define language-neutral, platform-neutral binary data encoding and the result can be easily encoded, decoded with many built-in safety checks.

If this is the goal, what about using msgpack? InfluxDB already supports generating it (https://github.com/influxdata/influxdb/blob/1a920c5c420d2e7afcfb3e8781fb8dfbe557fcf9/services/httpd/response_writer.go#L196), so it wouldn't be a completely new format.

*I'm not a project maintainer, just throwing out some ideas for discussion :-)*

**Comment by dialogbox** [comment]
@phemmer msgpack could be a good another output data format. Why couldn't we support the both data format 'protobuf' and 'msgpack'?

**Comment by phemmer** [comment]
Well I was thinking the difficulty with implementing protobuf is that we're making up a new format, one currently not implemented anywhere else. Meaning it's going to need a lot of very thorough review to make sure it's not going to need breaking changes in the future. Or if InfluxDB adds protobuf, we might end up with competing protocol formats.
So in a nutshell not saying it shouldn't be implemented, just that there's likely to be a much lower barrier for getting msgpack support.

**Comment by dialogbox** [comment]
@phemmer I totally agree. The only reason why it was protobuf is I didn't know about msgpack and the already defined format in InfluxDB's code base.
In parallel with this PR, I will study msgpack and will try to implement it as the other output data format of telegraf. I will open new PR if it is prepared.

BTW, thank you for the great feedback. Since this was the my first github PR ever, your feedback is the first feedback to me!

**Comment by dialogbox** [comment]
@phemmer I opened another PR #3427 for msgpack. Thank you for the suggestion.

**Comment by danielnelson** [comment]
Thanks for the pull request, the code is very good, but I feel that this has similar issues to our JSON output.  While the output is encoded in the output format, there is no control over the output schema so it does not integrate well with existing code.  The msgpack version has the same issue.

So, I'm not sure if it is something we are ready to add yet.  Can you explain how you concretely plan to use this data format?

**Comment by dialogbox** [comment]
> While the output is encoded in the output format, there is no control over the output schema so it does not integrate well with existing code.

I agree. I don't expect some one can use the output directly.

My original intent was sends output to a centralized pipeline (i.e. Kafka) and multi-use metrics in many platforms. In this scenario, consumers(a.k.a forwarders) of the pipeline have to deserialize the metrics, so the data format of the metrics is matter.

JSON output could be the easiest format for this because every platform can parse it by default. So it's perfect for small systems. However it requires too high overhead in terms of size and parsing cost. Influx line protocol provides reasonable space efficiency but parsing it is not easy (of inefficient) in some platform.

**Comment by srebhan** [comment]
@dialogbox are you still interested in this PR? If so I please rebase the code and I will review. It looks quite nice on a first glance...

**Comment by srebhan** [comment]
@dialogbox so we are continuing with this one? :-)

**Comment by dialogbox** [comment]
@srebhan Yes. Let me try after the lunar new year. Happy new year.

**Comment by srebhan** [comment]
@dialogbox I hope you had a smooth transition into the new year. Any time to work on this?

**Comment by dialogbox** [comment]
@srebhan Hi. I'm still working on it but it might take some time. And I deleted the original PR branch so I will create a new PR once it is ready.

**Pull request closed without merging**
