### PR TITLE
kafka sasl-mechanism auth support

### PR DESCRIPTION
**Pull request by ssoroka**

### CODE REVIEW

**Comment by ssoroka** [comment]
waiting for some confirmation that this works

**Comment by luisgf** [comment]
I'm really interested in this feature. any plans to merge?

**Comment by ssoroka** [comment]
Absolutely. I'd love it if you could try it out and provide feedback.

You can grab the build at one of these to try it out
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1-0.aarch64.rpm
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1-0.armel.rpm
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1-0.armv6hl.rpm
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1-0.i386.rpm
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1-0.s390x.rpm
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1-0.x86_64.rpm
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_darwin_amd64.tar.gz
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_freebsd_amd64.tar.gz
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_freebsd_i386.tar.gz
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_linux_amd64.tar.gz
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_linux_arm64.tar.gz
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_linux_armel.tar.gz
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_linux_armhf.tar.gz
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_linux_i386.tar.gz
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_linux_mips.tar.gz
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_linux_mipsel.tar.gz
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_linux_s390x.tar.gz
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_static_linux_amd64.tar.gz
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_windows_amd64.zip
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Ef45cc9e1_windows_i386.zip
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Ef45cc9e1-0_amd64.deb
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Ef45cc9e1-0_arm64.deb
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Ef45cc9e1-0_armel.deb
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Ef45cc9e1-0_armhf.deb
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Ef45cc9e1-0_i386.deb
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Ef45cc9e1-0_mips.deb
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Ef45cc9e1-0_mipsel.deb
https://67812-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Ef45cc9e1-0_s390x.deb

**Comment by luisgf** [comment]
Hello @ssoroka 

Installed telegraf-1.17.0%7Ef45cc9e1-0.x86_64.rpm.

Here the snippet of kafka output section:

```
[[outputs.kafka]]
  brokers = ["localhost:9092"]
  topic = "metrics"
  sasl_username = "telegraf"
  sasl_password = "telegraf"
  sasl_mechanism = "SCRAM-SHA-512"
  routing_tag = "host"
  client_id = "Telegraf"
```

Telegraf doesn't start. Seems that sasl_mechanism is not recognised.

```
[root@server user]# telegraf --test
2020-10-27T16:40:55Z I! Starting Telegraf 
2020-10-27T16:40:55Z I! Using config file: /etc/telegraf/telegraf.conf
2020-10-27T16:40:55Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.conf: Error parsing kafka array, line 20: field corresponding to `sasl_mechanism' is not defined in kafka.Kafka
```

**Comment by ssoroka** [comment]
k, I'll investigate and respond shortly

**Comment by ssoroka** [comment]
so I had only added it for the inputs.kafka_consumer, but I'm adding it now to the outputs.kafka.. but I realize I also missed a bunch of stuff. will add this shortly.

**Review by reimda — APPROVED** [review]
Looks great.  Let's merge as soon as we get a successful test

**Comment by ssoroka** [comment]
@luisgf 
Here's the updated packages for you to test.
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3-0.aarch64.rpm
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3-0.armel.rpm
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3-0.armv6hl.rpm
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3-0.i386.rpm
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3-0.s390x.rpm
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3-0.x86_64.rpm
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_darwin_amd64.tar.gz
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_freebsd_amd64.tar.gz
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_freebsd_i386.tar.gz
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_linux_amd64.tar.gz
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_linux_arm64.tar.gz
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_linux_armel.tar.gz
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_linux_armhf.tar.gz
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_linux_i386.tar.gz
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_linux_mips.tar.gz
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_linux_mipsel.tar.gz
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_linux_s390x.tar.gz
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_static_linux_amd64.tar.gz
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_windows_amd64.zip
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.17.0%7Eb02f2cc3_windows_i386.zip
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Eb02f2cc3-0_amd64.deb
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Eb02f2cc3-0_arm64.deb
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Eb02f2cc3-0_armel.deb
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Eb02f2cc3-0_armhf.deb
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Eb02f2cc3-0_i386.deb
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Eb02f2cc3-0_mips.deb
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Eb02f2cc3-0_mipsel.deb
https://67924-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.17.0%7Eb02f2cc3-0_s390x.deb

**Comment by luisgf** [comment]
Hello @ssoroka works! I'm connected to my kafka brokers using SCRAM-SHA-512 authentication.

**Comment by Neustradamus** [comment]
@ssoroka: Thanks a lot for all about SCRAM.

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Comment by douglasawh** [comment]
GSSAPI is still listed as experimental? Why is that the case?

**Pull request merged**
