### PR TITLE
HAproxy admin socket filename globbing

### PR DESCRIPTION
**Pull request by weshmashian**
When dealing with multiple instances of HAproxy (or just multiple admin sockets) on a single server, it might be useful to just add wildcard match in configuration file, server=["/var/run/haproxy*.sock"] for example.

With proper naming and socket locations telegraf could send out stats without manual intervention. The only thing not tested is if telegraf client needs to be reloaded to pick up (or forget) sockets as they appear/disappear.

### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sparrc** [comment]
Looks good but you'll need to write some tests for this, as well as documenting this behavior: see https://github.com/influxdata/telegraf/blob/master/plugins/inputs/haproxy/haproxy_test.go#L174 for how the current socket test looks.

**Comment by weshmashian** [comment]
Thanks for the suggestions. I took the opportunity to rework the tests a bit and updated docs in sample config to reflect the behavior of the plugin.

**Comment by sparrc** [comment]
great, thanks, any chance you could write a README for the plugin as well? 😬 🙏

see the general input example here: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/EXAMPLE_README.md

**Comment by weshmashian** [comment]
Sure, I'll whip something up and add it to this lot.

**Comment by weshmashian** [comment]
Rebased to current master branch. Is there anything holding this off? Readme is rather short as the plugin is simple in terms of options and operation.

**Pull request closed without merging**
