### PR TITLE
plugins/inputs/statsd: enforce minimum allowed_pending_messages

### PR DESCRIPTION
**Pull request by arussellsaw**
### Required for all PRs:

- [x] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by arussellsaw** [comment]
will update with CHANGELOG.md

**Comment by arussellsaw** [comment]
or would this be better off in config parsing?

**Comment by arussellsaw** [comment]
this pr isn't necessarily required, as this line will catch it before the 0 division. https://github.com/influxdata/telegraf/blob/master/plugins/inputs/statsd/statsd.go#L301 

so maybe i should just close this :(

**Comment by sparrc** [comment]
oh, right, looks like the zero division doesn't exist anymore, so setting to 0 is OK because I guess it would just create an unbuffered channel instead of allowing some packets to queue up.

**Comment by arussellsaw** [comment]
if anyone sets a negative value you could still panic, but they deserve that!

**Pull request closed without merging**
