### PR TITLE
Fix snmp tools output parsing when they contain Windows eols

### LINKED ISSUE #3263: SNMP Table input fails on Windows
## Bug report

SNMP Table input fails on Windows.

### Relevant telegraf.conf:
````
[[inputs.snmp]]
  agents = [ "10.20.254.10:161" ]
  version = 1
  community = "public"
  name = "Switches"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true
  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EXPRESSION-MIB::sysUpTimeInstance"	
  
  [[inputs.snmp.table]]
    name = "iface"
	inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifTable"
	# Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true
````
### System info:

Telegraf v1.4 on Windows 2012R2

### Steps to reproduce:

1. Install net-snmp 5.7 for Windows
2. Use the CONFIG EXAMPLES from the SNMP plugin as above

### Expected behavior:
SNMP Table info is collected and sent to InfluxDB

### Actual behavior:
SNMP plugin fails to collect table data

### Additional info:

Log file contains the following error:
````
2017-09-25T04:41:40Z E! Error in plugin [inputs.snmp]: initializing table iface: getting table columns: exit status 1: IF-MIB::ifTable
````

I believe the error is occurring on line 876 of snmp.go file. My understanding is that it is running the command:
````
snmptable -Ch -Cl -c public 127.0.0.1 IF-MIB::ifTable
````

When I run that command from the command line, it returns the table columns and I checked the exit code which is 0.

### Use case: [Why is this important (helps with prioritizing requests)]
Pretty important for Windows sysadmins to use TICK to collect SNMP data in an office environment

### PR DESCRIPTION
**Pull request by danielnelson**
closes #3263

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
@pstatho @RubenN Could you test out this build?

https://8665-33258973-gh.circle-artifacts.com/0/tmp/circle-artifacts.gpwmL3M/build/windows/amd64/telegraf-1.5.0%257Ef0a8a55_windows_amd64.zip

**Comment by pstatho** [comment]
I'm getting a timeout, with the following in the log file:
2017-10-27T01:41:00Z E! Error in plugin [inputs.snmp]: took longer to collect than collection interval (10s)
I'm just using the example for the documentation and it continue works with regular SNMP fields

**Comment by danielnelson** [comment]
The timeout is potentially normal, depends on how fast the remote agent responds.  Does it ever finish a collection or is it completely stuck?

> I'm just using the example for the documentation and it continue works with regular SNMP fields

I don't quite understand what you meant here.

**Comment by pstatho** [comment]
My telegraf.conf has the following (as in the example documentation):
```
[[inputs.snmp]]
  agents = [ "192.168.16.252:161" ]
  version = 1
  community = "public"
  name = "snmp.switch"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true
  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EXPRESSION-MIB::sysUpTimeInstance"
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifTable"
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true
```
So regular fields like hostname and uptime return, but anything table related does not return any data.
When I run
```
>telegraf.exe --config telegraf.conf --test|find "snmp.switch"
```
The output is:
```
> snmp.switch,host=MY-HOST-01,hostname=MY-SWITCH-01,agent_host=192.168.16.252 uptime=1618717056i 1509069658000000000
```
and then it hangs/timesout for 10secs with no further output.

When I run it via the Windows service the log file has the error message I mentioned earlier.

**Comment by RubenN** [comment]
I can confirm that it's working fine for me!

**Comment by danielnelson** [comment]
@pstatho Can you try this build with `--debug` enabled, I added some temporary logging that hopefully will help us figure out the issue.

https://8695-33258973-gh.circle-artifacts.com/0/tmp/circle-artifacts.j68kVkX/build/windows/amd64/telegraf-1.5.0%257E1238cf3_windows_amd64.zip

**Comment by pstatho** [comment]
Here is the log output:
https://gist.github.com/pstatho/5f5cdb2661b60d5fddd75bc25581f0bd

The command line output is still the same, only the hostname of the switch and uptime are returned, after about 30 seconds.

**Comment by danielnelson** [comment]
@pstatho From the output it looks like the parsing is working, maybe this timeout is unrelated.  Any chance your hardware allows you to use `version = 2`, this will enable bulk walks.

Also can you try running this and record the execution time:
```
snmpwalk -v1 -c public 127.0.0.1:161 IF-MIB::ifTable
```

**Comment by pstatho** [comment]
Running against 127.0.0.1 returns:
Timeout: No Response from 127.0.0.1:161

Running the command against my 26-port switch returns in 12 seconds when I pipe the output to a file to remove and rendering/scrolling delays on the console. When I run it against my 50-port switch it takes 22 seconds (almost double the time). I've tried both v1 and v2c and the time to execute the snmpwalk is the same.

**Comment by danielnelson** [comment]
That's pretty slow but I suspect we won't be able to improve upon the time it takes snmpwalk to do the same operation.  I think you will have to increase the interval to approx double the collection time.
```toml
[[inputs.snmp]]
  interval = "1m"
```

@phemmer I don't have much experience with snmp on real hardware, is this typical performance?

**Comment by phemmer** [comment]
Not for me no. I can run the given config against one of our 48 port switches and it completes in about 5s with version 2c, and about 24s on version 1.

Note that doing `snmpwalk -v2c ...` is expected to give the same timing as `snmpwalk -v1 ...`. To take advantage of bulk walk using the net-snmp CLI utils, you need to use `snmpbulkwalk -v2c ...`

**Comment by pstatho** [comment]
@phemmer ah yes you are correct. When I use `snmpbulkwalk -v2c` it takes about 2 seconds.  So does the snmp plugin for telegraf use the bulk command when the version is 2 or higher?

Regardless, when I change my telegraf config to use version 2, I still don't get table output when I test it. I tried with the first patch version and teh second debug version as well.

**Comment by danielnelson** [comment]
Yes it does switch to bulkwalk with version 2 and higher, of course we are using the gosnmp library for this functionality, not the snmpbulkwalk command.

I added printing of gosnmp log messages to this branch. It is very verbose, so you must set `debug = true` on the plugin in addition to running with the `--debug` flag.  Could you try this out and report back the output?

**Comment by pstatho** [comment]
Finally had some time to try out the latest build. It seems to run in a continuous loop when I execute it from the command line. There was nothing outputted in the console. 
I believe I captured a complete cycle in this [gist](https://gist.github.com/pstatho/4c9c9a07140a5a5085d95d73705dc656).

**Comment by danielnelson** [comment]
Are you running it with `--test`?

**Comment by pstatho** [comment]
@danielnelson I tried it again and it is outputting to the console. I must have forgotten the --test as you correctly pointed out. 
Also to confirm using SNMP version 2 in the config, it returns within a few 1-2 seconds as expected. Looking forward to the official release. Thanks!

**Pull request merged**
