### PR TITLE
Nfsclient input: (Reopen of PR 1491)

### PR DESCRIPTION
**Pull request by RasmusWernerLarsen**
### Required for all PRs:
- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [X] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by RasmusWernerLarsen** [comment]
I've made a few changes to LuizOz initial plugin:

1: I've removed the Iostat option. The only reason for having the Iostat option was avoiding a very minor duplication of metrics, when used with the Fullstat option. But fullstat returns hundreds of metrics where Iostat just returns 8, and those 8 are still slightly different from what is returned by fullstat. After the change the iostat metrics are always returned.

2: I've renamed the plugin from nfs to nfsclient. Perhaps nfsmountstats might be even better, but atleast it makes it clear that we aren't returning nfs server stats.

3: I've attempted to improve the documentation. I think it still needs some improvements... In particular I need to dig through the kernel source code to determine exactly what the metrics represent... I think I know, but honestly it includes a bit of guesswork.


Also, I see the test is failing now. Will get that fixed.

**Comment by RasmusWernerLarsen** [comment]
The nfsclient module tests are passing now.

**Comment by RasmusWernerLarsen** [comment]
I believe the metric documentation is good now. I'm out of ideas for things to improve.

**Comment by tpaimpar** [comment]
Hello, may I ask you when, or what is needed to do, to have this plugin merged  ?

**Comment by danielnelson** [comment]
We are working on improvements to the plugin system #1717 and trying to complete this work before we merge new plugins.

**Comment by paultowers** [comment]
Any updates on when this will be merged?

**Comment by 4picht** [comment]
@danielnelson It's now nearly a year since your comment. Any news? #1717 seems to be rather quiet for half a year now ...

**Comment by danielnelson** [comment]
@RasmusWernerLarsen can you fixup the conflict and I'll review for 1.7?  You can scrap the changes to the CHANGELOG as I usually just add them myself to avoid conflicts.

**Comment by gallart** [comment]
Any one can update this PR or should we open a new one?

**Comment by danielnelson** [comment]
Closing in favor of the updated version of this plugin in #4615

**Pull request closed without merging**
