### PR TITLE
chore: enable linting of shell scripts

### PR DESCRIPTION
**Pull request by sspaink**
resolve: https://github.com/influxdata/telegraf/issues/9716

also bumped the version to the latest.

### CODE REVIEW

**Comment by powersj** [comment]
Can you push a change to a `.sh` under scripts to show that this works?

**Comment by sspaink** [comment]
@powersj it is now correctly failing, let me know what you think and I can undo the shell script changes so we can merge it.

**Comment by powersj** [comment]
> @powersj it is now correctly failing, let me know what you think and I can undo the shell script changes so we can merge it.

Looks good - it is a little confusing that there are two failures in the GitHub actions one for "--> Linted: BASH" and the other for "Lint Code Base / Lint Code Base (pull_request) Failing after 1m"

**Comment by sspaink** [comment]
Agreed, it isn't the most clear but I believe the same happens with the markdown linter. It might just be a super linter quirk.

**Comment by powersj** [comment]
> Agreed, it isn't the most clear but I believe the same happens with the markdown linter. It might just be a super linter quirk.

ok! once the CI passes, I'm +1 :)

**Review by powersj — APPROVED** [review]

**Pull request merged**
