### PR TITLE
Release 1.12 cloudwatch filter

### PR DESCRIPTION
**Pull request by hflamboauto1**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by hflamboauto1** [comment]
relates to https://github.com/influxdata/telegraf/issues/4046

**Comment by danielnelson** [comment]
You should be able to use the `tagdrop` option to achieve the same result:
```toml
[[inputs.cloudwatch]]
  period = "1m"
  interval = "5m"

  [[inputs.cloudwatch.metrics]]
    names = ["Latency"]

    [[inputs.cloudwatch.metrics.dimensions]]
      name = "LoadBalancerName"
      value = "*"

    [[inputs.cloudwatch.metrics.dimensions]]
      name = "AvailabilityZone"
      value = "*"

  [[inputs.cloudwatch.tagdrop]]
    LoadBalancerName = ["example"]
```

Give this a shot and let me know how it goes.

**Comment by hflamboauto1** [comment]
@danielnelson 

Thanks for your thoughts and working example. 

Yes that's right, it could be done like that if the number of LoadBalancerName(s) to drop is small.  It becomes impractical (on my particular case at least) as I have a "huge" AWS Account with a considerable amount of LoadBalancers to be excluded. 

Imagine having to specify 20 or 30 or even more LoadBalancerName(s) tags to drop explicitly by specifying exact names! That becomes not very handy specially in dynamic environments.

With the way you propose  then I guess that would no need for tag drop at all and just register to the exactly LoadBalancerName(s) of interest in similar fashion, but again this becomes impractical for same previous reasons as I have lets say 30 that can be of interested and another 20 of non interest for a particular domain ... like  qa | prod | staging | test ...  or whatever.

Maybe there's another option or I misunderstood something that would allow me to achieve that with ease but did not found and some kind of filtering options based on LoadBalancerName match help a lot and it solves issue in my case.

**Comment by danielnelson** [comment]
You can use globs/wildcards in all of the filtering options, we don't have regular expression support right now, but in my experience globs are usually enough to get the job done for hostnames.  We use [github.com/gobwas/glob](https://github.com/gobwas/glob) syntax.
```
  [[inputs.cloudwatch.tagdrop]]
    LoadBalancerName = ["prod.*", "staging.*"]
```

**Comment by hflamboauto1** [comment]
Lovely .. I think I can go with that .. shameless completely missed that. A big thanks.

**Pull request closed without merging**
