### PR TITLE
Postgresql database blacklist configuration option

### PR DESCRIPTION
**Pull request by mediocretes**
Basically every postgres includes the postgres, template0, and template1 database.  The stats for these are usually very boring, and being able to filter them out without knowing the name of all the databases on the server up front would be great.  This change adds "ignored_databases", a list of databases to ignore.  Any databases not in the list will get full stats as usual.

### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [N/A] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sparrc** [comment]
this looks good to me, thanks @mediocretes, please put your change in the changelog under 1.1 and I will merge

**Comment by mediocretes** [comment]
@sparrc I have added this PR to the changelog

**Comment by mediocretes** [comment]
@sparrc I have added this PR to the changelog

**Comment by mediocretes** [comment]
@sparrc I have added this PR to the changelog

**Pull request merged**
