### PR TITLE
Add missing Elasticsearch cluster & index health stats

### PR DESCRIPTION
**Pull request by aegixx**
Add missing Elasticsearch cluster health stats:
delayed_unassigned_shards, number_of_pending_tasks, number_of_in_flight_fetch, task_max_waiting_in_queue_millis, active_shards_percent_as_number

Also, included all stats from the /_stats endpoint.

### Required for all PRs:

- [x] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sparrc** [comment]
@aegixx why did you close and re-open? is this ready to review?

**Comment by aegixx** [comment]
@sparrc I added a new endpoint (/_stats) in addition to the missing stats from _cluster/health that I had before.  (Didn't appear my new commits were picked up by the original PR)

Ready for review!

**Comment by sparrc** [comment]
if you push or force-push to the same branch it should get picked up

but please just ping us to let us know what you're doing so that we can keep track of the milestones easier :)

**Comment by aegixx** [comment]
Work should be complete on this one -- Just adding some more global statistics to Elasticsearch for better health dashboards.

**Comment by aegixx** [comment]
CI failure seems unrelated to the changes

**Comment by lpic10** [comment]
Hi @aegixx , few comments:

First, I find the measurement names `elasticsearch_indicesstats` and `elasticsearch_indicesstats_indices` does not quite look good. 

Then, it seems (by looking at the code, I didn't test this yet), you are storing the data returned on `_shards`. That information is not really important in this context and is returned on every request to Elasticsearch (just to say how many shards actually answered the request).

Another thing is that inside the `_all` response you have exactly the same fields as for each individual indice (with the data aggregated from all indices), thus I think it could use the same measurement as the indices themselves (maybe with "_all" as index tag name). In the same way, each indice (and _all as well) have fields for `primaries` and `total` information, and that could be a tag value instead of part of the field name. This way you could have just one measurement like `elasticsearch_index_stats` or `elasticsearch_indices_stats` that looks way better.

Maybe as future evolution and for an even more detailed ES indices monitoring, you could add segment monitoring by requesting "_segments" endpoint.

**Comment by aegixx** [comment]
I'm completely new to Go and Telegraf in-general, so I'll need some more specific input on what kinds of changes need to be made.  Thank you for the input!

I may also be delayed in making changes due to some travel upcoming.  So if I need to hand this off in some way, please let me know.

**Comment by danielnelson** [comment]
@lpic10 @aegixx I think we should close this and focus on #2518.

@aegixx can you look over that PR and see if it will fulfill your needs?

**Pull request closed without merging**
