### PR TITLE
Devo output plugin

### PR DESCRIPTION
**Pull request by ansfan**
The Devo output plugin allows for messages to be sent directly to Devo or a Devo Relay. Devo tags can be set by using input tags and messages can be serialized using any existing serializer.
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

### CODE REVIEW

**Comment by ansfan** [comment]
Any update on getting the review process rolling and advancing this process? Is there anything I can help with to get this pushed through?

**Comment by billybco** [comment]
I can confirm this plugin is working for me. Any updates on when this will be merged?

**Comment by sjwang90** [comment]
Thanks for the PR! I think this is an excellent candidate for an external plugin. You can find the docs on how how to convert it [here](https://github.com/influxdata/telegraf/tree/master/plugins/common/shim#telegraf-execd-go-shim), and once that's done please open a pull request to get it added to the [list of external plugins](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md).

Let me know if you have any questions. I'm going to close the issue here for now, but we'd love to see this as an external plugin.

**Comment by srebhan** [comment]
@ansfan how should we proceed here? Are you going to make this an external plugin?

**Pull request closed without merging**
