### PR TITLE
feat(questdb): QuestDB output plugin

### PR DESCRIPTION
**Pull request by jerrinot**
- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

The plugin is based on SocketWriter and at this point, it's only adding authentication support, removing unnecessary configuration options and adding an integration test.

The code is a literal copy'n'paste from the Socker Writer output with the changes described above.

### CODE REVIEW

**Comment by jerrinot** [comment]
due latest failures are caused by Google Infra issue: https://github.com/golang/go/issues/63684

**Comment by srebhan** [comment]
@jerrinot can you please sign the CLA so we can do a review!?

**Comment by jerrinot** [comment]
!signed-cla

**Comment by srebhan** [comment]
@jerrinot any update on using the upstream library?

**Comment by powersj** [comment]
Happy to see this get updated to the upstream library at a later date. Happy to see a new PR or let us know if you push an update and we can re-open.

Thanks!

**Pull request closed without merging**
