### PR TITLE
Ebookbug ipmi lowercase change

### PR DESCRIPTION
**Pull request by sparrc**

### CODE REVIEW

**Comment by sparrc** [comment]
hi @ebookbug, could you take a look at this? I have made some changes to add unit tests, to add a "units" tag, to convert everything to lowercase, and to convert spaces to "_"

can you let me know what you think of doing this? I thought it might make it easier and more consistent to query in the db?

**Comment by sparrc** [comment]
Would also be OK with me if we only translated " " to "_", we don't need to do the lower casing if you'd rather not

**Comment by ebookbug** [comment]
Tansform to lower case is ok.
I think it will be better to take the unit (for example rpm,watt) to be a field.

**Comment by sparrc** [comment]
Can you explain why you would prefer units as a field instead of a tag?

**Comment by ebookbug** [comment]
This is no need to index the unit

**Comment by sparrc** [comment]
@ebookbug I see your point...it certainly seems like it makes more sense as a field for influxdb. There are other outputs though where it makes more sense as a tag (graphite, opentsdb, prometheus, etc.)

how would you feel if the schema design actually looked more like this (would this be too difficult to query?):

```
ipmi_sensor,server=10.20.2.203 ambient_temp_degrees_c=20,ambient_temp_status=1,altitude_feet=80, altitude_status=1, ....
```

**Comment by sparrc** [comment]
One other thing to consider-- if `units` is a tag that doesn't change for that particular sensor name, then it doesn't change the cardinality, and thus there is no penalty to indexing it.

So I'm leaning towards leaving it as-is, as a tag

**Comment by ebookbug** [comment]
Different manufacture‘s server maybe have different metrics.
So,it's not a good idea to write all the metric in one line.

But in next build,we can seperate the measurement ipmi_sensor to some sub measurements ,such as ipmi_temp,ipmi_fan_speed,ipmi_voltage ....

**Comment by ebookbug** [comment]
It's a common issue to discuss where to place the unit
I think the unit(rpm,watt) and counter type(gauge,count) should be designed in the schema when using influxdb,not stored in the tags nor the fields

**Pull request merged**
