### PR TITLE
Update net response

### PR DESCRIPTION
**Pull request by morfien101**
Deprecating result_type as a field value in favor of result_text as a tag value.
Adding a field value called result_code which is an int in the fields.
Updating tests to reflect changes.
Adding new tests to test other sections of the code.
Updating the README.me file to reflect the changes.

### Required for all PRs:

- [ x ] Signed [CLA](https://influxdata.com/community/cla/).
- [ x ] Associated README.md updated.
- [ x ] Has appropriate unit tests.

### CODE REVIEW

**Comment by morfien101** [comment]
@danielnelson Is there any word on when this will be released ? We are waiting on the release to push it out into our estate.

**Comment by danielnelson** [comment]
We could add the `result_code` field for 1.5, but I'd like to have more discussion and consensus with respect to adding the tag.

**Comment by tzz** [comment]
This would be great for Prometheus users.

**Comment by danielnelson** [comment]
I followed this pull request up with some minor changes to match style with http_response and dns_query plugins: https://github.com/influxdata/telegraf/commit/fa04e539ff4a477f90146cb855be7ff93cec64c9

**Pull request merged**
