### PR TITLE
feat: use new Influx Line Protocol Parser

### LINKED ISSUE #9474: Support the new Influx Line Protocol Parser
## Feature Request

@rogpeppe has written a new Influx Line Protocol Parser that is more semantically correct and significantly faster, supporting zero-allocation parsing. We should upgrade to it.

Updated parser can be found here https://pkg.go.dev/github.com/influxdata/line-protocol/v2/influxdata

### Proposal:

upgrade to the faster parser

### Current behavior:

Current parser does unnecessary memory allocations, causing a performance hit compared to the new parser. 
image (1)

### Desired behavior:

Upgrade to the new parser

### Use case: 

memory allocations are expensive and slow. No need to do unnecessary ones.

### PR DESCRIPTION
**Pull request by powersj**
Replaces the Influx Line Protocol parser with the new, zero-allocation parser found here. The only downside to the new parser is that we cannot get the current buffer when using the stream parser variant, so the messages will be slightly less descriptive when an error is encountered.

Blocked by https://github.com/influxdata/line-protocol/issues/50
Previous PR #9685
Resolves #9474
Authored-by: Alex Krantz <alex@krantz.dev>

### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

### CODE REVIEW

**Comment by srebhan** [comment]
@powersj any update on the problem of panicing?

**Comment by oplehto** [comment]
@powersj It looks like https://github.com/influxdata/line-protocol/pull/51 has resolved the issue. 

I built a version of Telegraf that incorporates that PR and have not been able to crash it.

**Comment by powersj** [comment]
@oplehto thanks for confirming! I will get this PR updated with the latest parser code and we can let it bake a bit more.

**Review by srebhan — APPROVED** [review]
Looks good to me. Excellent work @akrantz01 and @powersj! @oplehto can you please confirm that this PR does not panic anymore?

**Comment by oplehto** [comment]
> Looks good to me. Excellent work @akrantz01 and @powersj! @oplehto can you please confirm that this PR does not panic anymore?

I've had this running for a while now ingesting a very large amount of various metrics data and can confirm that I have not seen  any issues anymore.

**Comment by sjwang90** [comment]
We're planning on this new parser ~a month to bake in cloud. We'll check in on merging this in to Telegraf mid January 2022.

**Comment by popey** [comment]
Now we're into mid-Jan, we should re-visit this PR.
Are we confident this has been exercised enough elsewhere to land in Telegraf?

**Comment by sjwang90** [comment]
There have not been any issues with this new parser in InfluxDB Cloud. This will get added on our list to get reviewed and merged soon. Since this is new parser is a major feature implementation it won't officially be included until our next minor release in a couple months. However, once merged, you can use it and test with our nightlies.

**Review by srebhan — APPROVED** [review]
LGTM.

**Review by srebhan — APPROVED** [review]

**Comment by powersj** [comment]
Hi,

Thanks to everyone for providing feedback on this feature. After talking through this change as a team, we decided to merge the feature as a flag of the parser. This means users can enable the use of the new parser backend by adding a new parser config option, "influx_parser_type" as shown below:

```toml
    data_format = "influx"
    influx_parser_type = "upstream"
```

The "upstream" value will enable the use of the new faster more memory efficient parser, while "internal", which is the default setting, will remain with the existing parser. This allows users to opt-in to the new parser and allow us to collect more confidence in ensuring existing configurations will not suddenly break. Our plan is to switch the default parser type in a future release.

The change was merged in as a part of https://github.com/influxdata/telegraf/pull/10749 and is now in master. Tonight's nightlies should have the change included them, and next weeks v1.22.0 release will be the first release with the new features. As such I am closing this PR.

Thanks again!

**Pull request closed without merging**
