### PR TITLE
Add column measurement_db_type to output of all queries

### PR DESCRIPTION
**Pull request by IgorKuchmienko**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

This column is used to distinguish between outputs of queries that have the same value in column [measurement], such as sqlAzureDBResourceStats and sqlAzureMIResourceStats.

### CODE REVIEW

**Review by denzilribeiro — APPROVED** [review]
Looks fine to me.  @Trovalo  - any objections to this

**Review by denzilribeiro — COMMENTED** [review]
Realized that DatabaseType won't always exist if someone isn't using it in the config file ( aka are using the older V2/V1 queries). May have to check if it is configured in conf file.

**Comment by Trovalo** [comment]
@denzilribeiro I see no problem in adding this.
Personally, I'll leave the V2 queries as they are and add the column only on the new ones. If we want to provide that info also for old query we can easily use SERVERPORPERTY('EngineEdition') to identify the correct value

**Comment by denzilribeiro** [comment]
> Personally, I'll leave the V2 queries as they are and add the column only on the new ones. If we want to provide that info also for old query we can easily use SERVERPORPERTY('EngineEdition') to identify the correct value

But where it was being added was when results were being sent , appending a tag to all result sets which won't be conditional at this point.

**Comment by Trovalo** [comment]
Sorry I didn't notice that, in any case it's fine to me.
The other option is to add the info in the query itself as a static tag (like the measurement), I have no preference, both methods are fine to me.

If we choose this way, adding a check to ensure that there is a valid value seems reasonable to me, otherwise we could end up with an empty tag, which is not that handy to query

**Comment by IgorKuchmienko** [comment]
I added a check to ensure that the new column is only added when DatabaseType is not empty.

**Review by Trovalo — APPROVED** [review]
Looks fine to me, @denzilribeiro anything else to add?

**Review by denzilribeiro — APPROVED** [review]
Looks good to me

**Comment by IgorKuchmienko** [comment]
Looks like there is nothing else to be done here. @ssoroka can you please merge it?

**Review by ssoroka — APPROVED** [review]

**Pull request merged**
