### PR TITLE
fail2ban: Runs on all *nix platforms

### PR DESCRIPTION
**Pull request by rickard-von-essen**

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
These arbitrary build constraints are a bit annoying. I'll start a hunt... 🔫

**Comment by danielnelson** [comment]
Great, I'll merge all of these as soon as I get the tests to pass.  I sort of started working on these in #3099 with the goal of getting tests working on Mac, but I only have a Linux system so its been hard to test.

**Comment by rickard-von-essen** [comment]
> with the goal of getting tests working on Mac, but I only have a Linux system so its been hard to test.

Yes it's a pain to get things working on all platform, especially when they are proprietary.

**Comment by xuebaba1115** [comment]
I added fail2ban after the test is ok
```
 dev@debian:/etc/telegraf$ sudo telegraf --config telegraf.conf --input-filter fail2ban --test
 Plugin: inputs.fail2ban, Collection 1
> fail2ban,jail=sshd,host=debian failed=0i,banned=0i 1503565774000000000
> fail2ban,jail=tomcat,host=debian failed=1i,banned=0i 1503565774000000000`
```

Restart telegraf service
And did not collect fail2ban data
There is no fail2ban data in my database

```
> show measurements
name: measurements
name
----
cpu
disk
diskio
kernel
mem
processes
swap
system
tomcat_connector
tomcat_jvm_memory
tomcat_jvm_memorypool
```

**Pull request merged**
