### PR TITLE
fix: Update Consul Header Token

### PR DESCRIPTION
**Pull request by bear359**
### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

Updated Consul Header token as the previous code was not passing the Consul token correctly and was blocking Consul client metrics from being sent to Telegraf.

### CODE REVIEW

**Comment by bear359** [comment]
!signed-cla

**Comment by powersj** [comment]
@efbar thoughts? I can try looking at docs tomorrow

**Comment by efbar** [comment]
@powersj I think @bear359 is right regarding the token setting that I've mixed up. There are two way of adding the token header (same way as [Vault](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/vault/vault.go#L93), but with Consul substring, [here](https://www.consul.io/api-docs#authentication) the docs):

1. `X-Consul-Token: <consul token>`
or
2. `Authorization: Bearer <consul token>` 

First option is definitely better.

I'm not sure about `AddHeader` in place of `SetHeader` in the sense that it doesn't replace any headers associated with the key like the latter does.

**Comment by bear359** [comment]
@efbar @powersj If there is anything I can do to assist with getting this merged, please let me know. This is blocking any integration that uses telegraf's `consul_agent` plugin and our managed cloud offering, HCP Consul.

**Review by powersj — APPROVED** [review]

**Review by MyaLongmire — APPROVED** [review]

**Comment by powersj** [comment]
@bear359 this will go in our next bug fix release next week. Till then you should be able to grab it from a nightly as of tomorrow

**Comment by bear359** [comment]
@powersj appreciate the expediency on that! Many thanks!

**Pull request merged**
