### PR TITLE
fix: update toml tag to match sample config / readme

### LINKED ISSUE #9829: Small nuance
https://github.com/influxdata/telegraf/blob/f489cff3eadd150123c894121fe45424b0828f38/plugins/outputs/loki/loki.go#L60

Hi, guys!
I found one nuance

`http_headers` doesnt work
but `headers` - works ok

### PR DESCRIPTION
**Pull request by helenosheaa**
resolves #9829

### CODE REVIEW

**Review by MyaLongmire — APPROVED** [review]

**Review by srebhan — APPROVED** [review]
Looks good to me.

**Review by powersj — COMMENTED** [review]
My only concern is if folks are using "headers" already, they will have breakage in the next version. Instead, should the documentation get updated to show "headers" as the correct value?

**Comment by helenosheaa** [comment]
@powersj yeah I was sort of torn between which is less disruptive. The `http_headers` key is what was in the readme and in the sample config so anyone who figured out they needed to use `headers` instead would have had to go looking in the plugin code for it.

Considering the plugin has only been around since 1.18 I thought making it match the spec would be ok. However happy to change the readme instead, thoughts?

**Review by powersj — APPROVED** [review]
It sounds like merging this as-is makes sense, as we have not received an issue about this till now.

**Pull request merged**
