### PR TITLE
Additional output plugin: AMQP 1.0

### PR DESCRIPTION
**Pull request by phires**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

This is a basic, first version of an AMQP1.0 output plugin, which allows to send metric data to e.g. Microsoft Azure ServiceBus or EventHub.

### CODE REVIEW

**Comment by dapaxx** [comment]
Sadly I have no clue on how to fix the merge conflict on godeps. 
New dependency is pack.ag/amqp for AMQP1.0

**Comment by glinton** [comment]
@phires You can remove it from your copy `git rm Godeps` and commit/push.

**Comment by eaidland** [comment]
What's the status for this plugin?

**Comment by R290** [comment]
The package [pack.ag/amqp](https://github.com/vcabbage/amqp) is no longer in active development, see issue https://github.com/vcabbage/amqp/issues/205. Maybe consider switching to the active Azure fork? https://github.com/Azure/go-amqp

**Comment by phires** [comment]
I completly forgot about this PR :(
I've recreated the change and will put up a new PR for AMPQ1.0.

**Pull request closed without merging**
