### PR TITLE
Add new output plugin httpjson

### PR DESCRIPTION
**Pull request by opan**
### Required for all PRs:

- [v] Signed [CLA](https://influxdata.com/community/cla/).
- [v] Associated README.md updated.
- [v] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
We recently added the [http output](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/http) which will be included in 1.7.0.  I believe it covers the same ground as this pull request, can you take a look at it to see if it fulfills you needs?

**Comment by opan** [comment]
Thank you for the response! Okay, it looks like the one I created. But only it is missing one feature, I need to able to send an additional data.

My version have one more options, I called it `data`, we can add as many params we need to be sent to the targeted API.

I think I will take a look at the source code and see if I am able to made a PR and adding this feature.

**Comment by opan** [comment]
And btw, when version 1.7.0 will be released? Because I need to use it soon. At least for monday.

**Comment by danielnelson** [comment]
I'm going to close this pull request, but let me know if using HTTP headers will work for your use case.

**Pull request closed without merging**
