### PR TITLE
Added new output plugin for new Librato API that supports tagging. 

### PR DESCRIPTION
**Pull request by stefanhorning**
In addition to the existing Librato plugin to keep it for the old API.

Still WIP.

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by stefanhorning** [comment]
Will reopen when done

**Comment by danielnelson** [comment]
Thanks for the pull request.  Do you think it would be possible to have this feature be a new option on the current librato plugin, instead of an entirely new plugin?

**Comment by stefanhorning** [comment]
My first consideration was to extend the existing plugin as well. After looking at the code however it looked more sensible to me to open up a seperate plugin. As the code was closely modelled around the JSON body being sent to the old API. Also the paradigm of message sending has shifted slightly.

However as I am new to go and relatively new to telegraf I am open for suggestions on how to approach this better.

Another thing I am not to happy with yet, is the naming of the plugin. As Librato has a new version of their API but technically still call it v1 in their endpoint, so I refrained from calling it just librato_v2, as that would be confusing. On the other hand lbrato_with_tags is far from an elegant name. So I am open for ideas there too.

Alos I just did some more testing against librato and it seems there is issues when running this plugin for a while things stop showing up on Librato. So I am still investigating and improving this for now. Once I consider it stable I will let you know and then we can think on how to merge this into telegraf best...

**Comment by danielnelson** [comment]
The options are very similar between the two, so I wouldn't create a new plugin.  I would just have a option called `use_tagged_metrics = false`.  We can then put the current implementation of Connect and Write into a ClassicClient struct and then your new code can go into a TaggedClient struct.  If you have a Client interface you can pick the implementation during the initial Connect call to the plugin.

One more thing, perhaps we should steer users away from adding a prefix?  I find it is much better to let tags provide namespacing and now that Librato has support for tags is prefixing still required?

**Comment by stefanhorning** [comment]
Thanks for your feedback, I will see what I can do.

**Comment by danielnelson** [comment]
@stefanhorning Can you let me know why you closed this pull request?

**Comment by stefanhorning** [comment]
To my understanding it was decided not in include this plugin in it's current form and instead extend the existing librato plugin instead. So I don't see a reason to keep this PR open as won't be merged anyways.

**Comment by morph027** [comment]
Just stumpled upon this ... are there still plans to extend the existing legacy plugin?

**Comment by danielnelson** [comment]
So far as I know it is not being worked on by anyone right now, but we would accept a pull request.

**Comment by morph027** [comment]
Okay, thanks for the info...Let's see if i can do the changes myself without creating a code mess.

**Pull request closed without merging**
