### PR TITLE
fix: sync on init to run it once for safety

### PR DESCRIPTION
**Pull request by MyaLongmire**
### Required for all PRs:

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

added once.Do on init as it is getting called multiple times and only needs to be called once

### CODE REVIEW

**Review by Hipska — COMMENTED** [review]
Is the mutex still needed in that case?

See my use case with 2k `inputs.snmp` instances, they each need to wait for the previous one to finish walking the paths and loading all mibs with gosmi...

**Review by reimda — APPROVED** [review]

**Comment by Hipska** [comment]
@reimda @MyaLongmire can I have a response please?

**Comment by reimda** [comment]
@Hipska It's not clear whether the gosmi.AppendPath() function is threadsafe, so the mutex is still needed. How is the performance in your case with the mutex?

**Comment by Hipska** [comment]
Not tested yet, but I can’t imagine it will be good or fast to walk `/usr/share/snmp/mibs` recursively 2000 times after each other …

**Pull request merged**
