### PR TITLE
Update gopsutil

### LINKED ISSUE #6103: [linux] inputs.mem: SlabReclaimable and SlabUnreclaim
## Feature Request

On linux slab is subdivided into two: SReclaimable and SUnreclaim.
It is interesting to know these two values.

### Proposal:

Add SReclaimable and SUnreclaim values in addition to Slab to inputs.mem

### Use case:
SReclaimable can be freed with /proc/sys/vm/drop_caches.

### PR DESCRIPTION
**Pull request by danielnelson**
closes #6103

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by adrianlzt** [comment]
This PR updates ``Gopkg.lock`` but does not update ``Gopkg.toml``.
Is that an error?

Currently in master:

Gopkg.toml
```
[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.18.12"
```

Gopkg.lock
```
[[projects]]
  digest = "1:55dcddb2ba6ab25098ee6b96f176f39305f1fde7ea3d138e7e10bb64a5bf45be"
  name = "github.com/shirou/gopsutil"
  packages = [
    "cpu",
    "disk",
    "host",
    "internal/common",
    "load",
    "mem",
    "net",
    "process",
  ]
  pruneopts = ""
  revision = "e4ec7b275ada47ca32799106c2dba142d96aaf93"
  version = "v2.19.8"
```

**Comment by adrianlzt** [comment]
An important change also coming with this update is a change in disk device names in [this commit](https://github.com/shirou/gopsutil/commit/d7405fd87376efc3079c865d3b9977a12ee193f6).

Previously:
```
> disk,device=mapper/vg00-lvusr,path=/usr ...
```

After the new gopsutil version:
```
> disk,device=dm-2,path=/usr
```

**Comment by danielnelson** [comment]
> This PR updates Gopkg.lock but does not update Gopkg.toml.
Is that an error?

In this case yes, we need to update the toml to the version of gopsutil that has the SUnreclaim field.  I'm fixing this in #6716.

> An important change also coming with this update is a change in disk device names in this commit.

Thanks for the heads up, I'm still looking into this but we may want to use `func (s *DiskIO) diskName(devName string)` like code to deal with this.

**Comment by danielnelson** [comment]
I think since the disk device name change was included in 1.12.0 and we are getting ready to release 1.13, it will be best at this point to not attempt to work around the change anymore.

**Pull request merged**
