### PR TITLE
fix(inputs.sysstat): fix tmpfile fd leak

### PR DESCRIPTION
**Pull request by shizhx**
# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

### CODE REVIEW

**Comment by shizhx** [comment]
!signed-cla

**Review by powersj — APPROVED** [review]
@shizhx is there a corresponding issue? Was there a specific platform you were seeing this on?

**Comment by shizhx** [comment]
> @shizhx is there a corresponding issue? Was there a specific platform you were seeing this on?

in Linux, sometimes our "fd leak detector" get follow report:
image

**Review by srebhan — APPROVED** [review]
Thanks for the fix @shizhx!

**Pull request merged**
