### PR TITLE
Fixes #9177 - Specify wanted ipmi metrics

### LINKED ISSUE #9177: Make it possible to gather specific IPMI sensor data
### Proposal:
I'd like to see it be possible to gather specific IPMI sensor data (by using https://github.com/influxdata/telegraf/tree/master/plugins/inputs/ipmi_sensor). At the moment it collects all sensor data. In collectd this option is possible

### Current behavior:
The ipmi_sensor input plugin collects all sensor data.

### Desired behavior:
The ipmi_sensor input plugin is able to collect specific sensor data if specified.

### Use case: 
For our use case we collect just the inlet and exhaust temperatures of our servers and CPUs. We do not require other data.

### PR DESCRIPTION
**Pull request by Rubueno**
This change makes it possible to store specific ipmi metrics to the
ouptut.

### Required for all PRs:

- [x] Updated associated README.md.
- [ ] Wrote appropriate unit tests.

resolves #9177

Added an option to specify which ipmi metrics one wishes to collect and store. Similar to collectd's ipmi plugin: https://collectd.org/wiki/index.php/Plugin:IPMI

### CODE REVIEW

**Comment by Rubueno** [comment]
!signed-cla

**Comment by Rubueno** [comment]
This is my first ever written bit of Golang. I'm not sure how to properly manipulate the tests.

**Review by Jagularr — COMMENTED** [review]
This looks like sound logic, but I believe you can already accomplish this (matching on specific tag values) with `tagpass`. With the following config line under the input you could filter only on the tags that you specify:

```
tagpass = { name = ["tag1", "tag2"] }
```

**Comment by Rubueno** [comment]
@Jagularr Thank you for your comment. I will look into this on Monday when I get back to the office. I'll report back!

**Comment by Rubueno** [comment]
@Jagularr You're absolutely correct. `tagpass` is the way to go.

**Pull request closed without merging**
