### PR TITLE
Add SIGHUP support to reload telegraf config

### PR DESCRIPTION
**Pull request by titilambert**

### CODE REVIEW

**Comment by sparrc** [comment]
cool, thanks @titilambert :+1:

**Comment by xin-t** [comment]
hi,titilambert  @titilambert .I have some problems about this.when I use tail input plugin to collect logs metrics ,start is well ,but  after one hour or two 2 hour.The telegraf process is still there, but it cannot collect logs : )..and the telegrafa log is:
nohup: ignoring input
2018-04-19T12:19:02Z I! Database creation failed: Response Error: Status Code [405], expected [200], [<nil>]
2018-04-19T12:19:02Z I! Starting Telegraf v1.5.2
2018-04-19T12:19:02Z I! Loaded outputs: influxdb
2018-04-19T12:19:02Z I! Loaded inputs: inputs.tail
2018-04-19T12:19:02Z I! Tags enabled: host=subscribe101
2018-04-19T12:19:02Z I! Agent Config: Interval:1s, Quiet:false, Hostname:"subs101", Flush Interval:10s 
2018-04-19T14:30:50Z I! Reloading Telegraf config
2018-04-19T14:30:50Z I! Hang on, flushing any cached metrics before shutdown
2018-04-19T14:30:50Z I! Database creation failed: Response Error: Status Code [405], expected [200], [<nil>]
2018-04-19T14:30:50Z I! Starting Telegraf v1.5.2
2018-04-19T14:30:50Z I! Loaded outputs: influxdb
2018-04-19T14:30:50Z I! Loaded inputs: inputs.tail
2018-04-19T14:30:50Z I! Tags enabled: host=subs101
2018-04-19T14:30:50Z I! Agent Config: Interval:1s, Quiet:false, Hostname:"subs101", Flush Interval:10s 

.....my start telegraf way is:
nohup telegraf --config telegraf.config > out.log 2>&1 &

    that is all . thanks
    P.S. sorry for my poor english ~:)

**Comment by danielnelson** [comment]
@xin-t I don't think this related to the SIGHUP code, have you tried `watch_method = "poll"` on the tail plugin?  If this doesn't help you can open an issue on the [InfluxData Community](https://community.influxdata.com) site.

**Comment by xin-t** [comment]
thx,I try this way now.

**Pull request closed without merging**
