### PR TITLE
add ability to read redis from a socket

### PR DESCRIPTION
**Pull request by mmckinst**

### CODE REVIEW

**Comment by mmckinst** [comment]
I'll figure out why the tests are failing.

**Comment by mmckinst** [comment]
redis test is passing, but now its failing on aerospike which is unrelated to this change.

**Comment by sparrc** [comment]
yes it appears something has happened with the latest aerospike docker image, I'll fix it shortly

**Comment by sparrc** [comment]
please rebase your changes and re-push, the aerospike test should no longer fail

**Comment by mmckinst** [comment]
@sparrc tests passing now

**Pull request merged**
