### PR TITLE
Update grok package to support for field names containing '-' and '.'

### PR DESCRIPTION
**Pull request by HongChenTW**
related: #4003

Currently grok package seems no longer maintained, the latest commit merged the support for field names containing '-' and '.', maybe we can update to this commit.

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Review by ssoroka — APPROVED** [review]

**Comment by HongChenTW** [comment]
I've added a test but it failed at `test-go-1.14` stage, but I've passed with `go version go1.14.10 darwin/amd64` in my local computer, not sure why it failed at circleci.

**Review by srebhan — APPROVED** [review]
There are again updates for the grok package in November, so there is hope. Your looks good.

**Comment by ssoroka** [comment]
needed to revert this until the upstream issue is fixed

**Comment by HongChenTW** [comment]
sure, didn't expected that, thanks for the notice

**Comment by srebhan** [comment]
@HongChenTW no worries, nobody knew... :-) Need to wait until https://github.com/vjeantet/grok/pull/32 is merged and then update grok to this version...

**Comment by sjwang90** [comment]
Has this been re-committed? vjeantet/grok#32 was merged a few days after

**Pull request merged**
