### PR TITLE
fix(parsers): Linter issues

### PR DESCRIPTION
**Pull request by srebhan**
This PR fixes all remaining linter issues in `plugins/parsers`.

### CODE REVIEW

**Comment by zak-pawel** [comment]
@srebhan I didn't find any linter issues in `json_v2` package on `master` branch. Can you elaborate on your not-so-easy-to-review changes in this package? Why are they included in this PR?

**Comment by srebhan** [comment]
@zak-pawel this is what I see on master
```shell
 ~/Development/InfluxData/telegraf > make lint | grep -E '^plugins/parsers' | sort
WARN [linters context] bodyclose is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters context] nilerr is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters context] sqlclosecheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649. 
make: *** [Makefile:182: lint] Error 1
plugins/parsers/json_v2/parser_test.go:6:2                   staticcheck  SA1019: package io/ioutil is deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. 
plugins/parsers/wavefront/element.go:190:3                   revive       unhandled-error: Unhandled error in call to function p.writeBuf.WriteString
plugins/parsers/wavefront/element.go:211:3                   revive       unhandled-error: Unhandled error in call to function p.writeBuf.WriteString
plugins/parsers/wavefront/element.go:55:3                    revive       unhandled-error: Unhandled error in call to function p.writeBuf.WriteString
plugins/parsers/wavefront/element.go:60:3                    revive       unhandled-error: Unhandled error in call to function p.writeBuf.WriteString
plugins/parsers/wavefront/element.go:93:3                    revive       unhandled-error: Unhandled error in call to function p.writeBuf.WriteString
```

my version is `golangci-lint has version v1.46.2`...

**Comment by srebhan** [comment]
@zak-pawel do you want me to "fix" the issue the "straightforward" minimal way and do the rework in a separate PR?

**Comment by zak-pawel** [comment]
@srebhan Interesting... 
image

Nevertheless, I'm ok with keeping these changes here as long as you write few sentences about what have you done :)

**Comment by srebhan** [comment]
I think it's better to do the json_v2 cleanup in an own PR. Will change...

**Review by zak-pawel — APPROVED** [review]

**Review by sspaink — APPROVED** [review]

**Pull request merged**
