### PR TITLE
Add the Timestream Output Plugin 

### PR DESCRIPTION
**Pull request by piotrwest**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

-------------------------------------------------

This is continuation of https://github.com/influxdata/telegraf/pull/8211 using a different source branch, to apply all necessary changes, without editing aws:telegraf_v1.15.3_with_Timestream branch.

-------------------------------------------------
We have created a new Telegraf output plugin that is able to write metrics to [Amazon Timestream](https://aws.amazon.com/timestream/). Please see the details in README.md file.

### CODE REVIEW

**Comment by piotrwest** [comment]
Thank you @ssoroka for looking at this. I have applied your remarks, continuing https://github.com/influxdata/telegraf/pull/8211 .

**Comment by ssoroka** [comment]
Looks good. Looks like the build is failing in 1.14 due to `make fmt` mismatch.

**Comment by piotrwest** [comment]
Great! Quick question regarding `make fmt` mismatch - is it something I should fix? If so, can you give me guidance how to do that? If not, when we can expect this pull request to be merged?

**Comment by reimda** [comment]
Hi @piotrwest, the telegraf CI build checks your code to make sure it has been formatted correctly.  It does this to keep the code indentation, spacing, etc looking the same independent of who wrote it.

The makefile has a target that will reformat the code for you so it passes the format check.  You just need to check out your pr branch, run "make fmt", commit the files that it modified, and push to your pr branch.  Once that's done CI will run again and the format check should pass.

**Comment by piotrwest** [comment]
Thank you @reimda for the explanation. I've fixed formatting issues. The code is ready to be merged in now.

**Pull request merged**
