### PR TITLE
Re-Subscribe onConnect (or re-connect)

### PR DESCRIPTION
**Pull request by chaton78**
Refer to (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718028)

> If CleanSession is set to 0, the Server MUST resume communications with the Client based on state from the current Session (as identified by the Client identifier).
[...]
>If CleanSession is set to 1, the Client and Server MUST discard any previous Session and start a new one.
[..]
>The Session state in the Server consists of:
>·         The existence of a Session, even if the rest of the Session state is empty.
>·         The Client’s subscriptions.
>·         QoS 1 and QoS 2 messages which have been sent to the Client, but have not been completely acknowledged.
>·         QoS 1 and QoS 2 messages pending transmission to the Client.
>·         QoS 2 messages which have been received from the Client, but have not been completely acknowledged.
>·         Optionally, QoS 0 messages pending transmission to the Client. 

This means that if you set Clean Session (persistent  session to false)... on Re-Connect, agent must re-subscribe to receive the message again.

Left todo:

- Let say that persistent session is set to true and broker is restarted, how does it work? Broker persists session and recover?

### CODE REVIEW

**Comment by sparrc** [comment]
awesome, thanks @chaton78, I had thought that setting `opts.SetAutoReconnect(true)` was enough, but I guess not

**Comment by chaton78** [comment]
with cleanSession =false and autoReconnect = true, it should be enough... With clean session = false, in case of disconnect, you 2 choices... stop gathering or re-subscribe. I've implemented the resubscribe.

**Comment by sparrc** [comment]
thanks @chaton78, is this ready to go?

**Comment by chaton78** [comment]
I've been running this version April 13th... without any hiccups. This is
the only test I did (other than the unit test)

**Comment by sparrc** [comment]
okay, I think that's enough to get it into master, it certainly can't hurt to add a reconnect handler

**Pull request closed without merging**
