### PR TITLE
switch postgresql plugin driver - fixes poor handling of system column types.

### PR DESCRIPTION
**Pull request by james-lawrence**
currently lib/pq doesn't handle name and oid types consistently making adding custom queries for other tables difficult. switching the driver resolves the issue.

I also just copied the helper code from lib/pq it was a dependency whose logic I didn't wish to change for this pr.

### CODE REVIEW

**Comment by james-lawrence** [comment]
i'll fx the tests this weekend.

**Comment by sparrc** [comment]
@menardorama could you review?

**Comment by james-lawrence** [comment]
Just fyi, might be able to get away with just the pq driver, seems they fixed at least one of the datatypes that was a blocker.

**Comment by james-lawrence** [comment]
I just havent had the time to check

**Comment by sparrc** [comment]
@james-lawrence I would strongly prefer to keep the pq driver, does it only require updating the dependency?

**Comment by james-lawrence** [comment]
Depends. Not sure, assuming updating the dependency does resolve all the unsupported types then could remove some of the utility functions i had to add both for postgresql and the tests. But we'd want to keep the removal of the special cased columns.

**Comment by james-lawrence** [comment]
Willing to check next weekend.

**Comment by sparrc** [comment]
OK, I'm going to close the PR for the time being then while keeping the `pq` library is reviewed

**Comment by james-lawrence** [comment]
did some investigating this morning.

so libpq still doesn't handle datname properly. (its still returning a byte array instead of a string) but it does properly handle the column if you cast it in the query via 
eg)
with libpq:
```
SELECT datid, datname::text, numbackends, xact_commit, xact_rollback, blks_read, blks_hit, tup_returned, tup_fetched, tup_inserted, tup_updated, tup_deleted, conflicts, temp_files, temp_bytes, deadlocks, blk_read_time, blk_write_time FROM pg_stat_database
```
with pgx:
```
SELECT * FROM pg_stat_database
```
pgx just handles datname and other special postgresql typed columns correctly which makes for a much nicer experience on the end user side.

I think its worth using this branch.

**Comment by sparrc** [comment]
@james-lawrence is this is a bug in the `pq` library? Have you looked into submitting a PR to fix this behavior in the `pq` library?

**Comment by james-lawrence** [comment]
I consider it a bug unsure if the maintainers of pq will. I'm not interested in putting in the time with pq to see if it will get fixed, in the past I've had trouble getting them to make changes that could impact end users codes. changing the type for particular columns would fall into that category.

**Comment by james-lawrence** [comment]
examples of pq unwilling to change returned types:
https://github.com/lib/pq/pull/300

**Pull request closed without merging**
