### PR TITLE
procstat input plugin added MemoryPercent and increased time.Duration(0) to 3 seconds

### PR DESCRIPTION
**Pull request by adityacs**
### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by sparrc** [comment]
dupe of #2458?

**Comment by adityacs** [comment]
yes. Building again. Close this

**Comment by adityacs** [comment]
close this pr. I am rolling back to time.Duration(0)

**Comment by adityacs** [comment]
creating one more PR

**Pull request closed without merging**
