### PR TITLE
[WIP] Time-based limits of metrics

### LINKED ISSUE #4578: Time-based limits of metrics
## Feature Request

The `metric_buffer_limit` setting in Telegraf is not very helpful when I want to control the ability to only send time-based limits of metrics.

For example, instead of a buffer_limit of `5000`, I would like my Telegraf agent(s) to keep only 30 minutes worth of data in its buffer. 

The number of metrics in the buffer is useless when I don’t know how many lines are output, pending on the number of input plugins enabled. This is especially the case with docker hosts that can have `1` to `100` docker containers, which requires a larger `metric_buffer_limit`.

### PR DESCRIPTION
**Pull request by Jaeyo**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

close #4578

### CODE REVIEW

**Comment by Jaeyo** [comment]
@glinton i have written ttl-based buffer that can resolve #4578, but i have no idea with configuration with this buffer. related configuration is `metric_batch_size` and `metric_buffer_limit`. can you suggest the right configuration with this ttl-buffer?

**Comment by glinton** [comment]
I'm not extremely familiar with the differences between `batch_size` and `buffer_limit`, but I would imagine `buffer_ttl` ...maybe? I'm going to divert to @danielnelson for the final say on config design though

**Comment by srebhan** [comment]
@Jaeyo are you still interested in this?

**Comment by srebhan** [comment]
@Jaeyo do you want to proceed with this PR?

**Comment by Jaeyo** [comment]
@srebhan sorry for late response. Im busy for now so it's hard to proceed this.

**Comment by srebhan** [comment]
@Jaeyo no worries. Do you think you might get to it in the future? If so can you give me some time frame?

**Comment by Jaeyo** [comment]
@srebhan If you are interested in this pr, you can proceed.

**Comment by srebhan** [comment]
@Jaeyo unfortunately my time currently does not permit to take-over this PR. I just want to make sure someone is still caring for this. If you cannot continue here, I would like to ask the community to take over or let the Influx people decide on how to continue... 

Do you see any chance to work on this in the foreseeable future?

**Comment by Jaeyo** [comment]
@srebhan no, it seems hard for a while. It'll be great if there's someone who can take over this pr.

**Comment by srebhan** [comment]
@Jaeyo no worries, will set the corresponding flag and see what happens...

**Comment by srebhan** [comment]
Anyone willing to take over this PR?

**Comment by sjwang90** [comment]
Closing this PR due to inactivity. If someone is interested on taking this work back up, please feel free to re-open the PR and take over the code.

**Pull request closed without merging**
