### PR TITLE
Add mosquitto input

### PR DESCRIPTION
**Pull request by sonytricoire**
### Required for all PRs:

- [X ] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests.

Hi ! 
This is my first contribution in both telegraf & go, so please be indulgent.
I'm of course opened to critics and improvements so please do not hesitate to fix, rework, etc.

Thanks

### CODE REVIEW

**Comment by danielnelson** [comment]
Hi @sonytricoire, thanks for the pull request, but have you tried the [mqtt_consumer](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mqtt_consumer) input?

**Comment by sonytricoire** [comment]
Hello !

Of course I have, I first tried to use MQTT_consumer...
MQTT_consumer retrieves already structured data points from MQTT topics (in
various formats), I consider that it is an MQTT to HTTP adapter (more or
less).

The Mosquitto input gather raw data from Mosquitto broker (and no other
MQTT broker), create the appropriate structured data point. It's like a
input plugin gathering data from a software component to send it to
InfluxDB; MySQL_input plugin functionnaly do the same job.
Of course because Mosquitto provides internal metrics through MQTT topics,
I reused the MQTT client implementation from MQTT_Consumer.



2018-06-12 20:59 GMT+02:00 Daniel Nelson <notifications@github.com>:

**Comment by danielnelson** [comment]
Got it, sounds good, I'll take a closer look as soon as is possible.

**Comment by sjwang90** [comment]
Hi @sonytricoire, due to the lack of interest for a mosquitto specific plugin (most of our users are able to use `inputs.mqtt_consumer`, this would be best suited as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md).  Would you be willing to submit this plugin as an [external plugin](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf? Telegraf users would also be able to use the plugin sooner by having it as an external plugin since it wouldn't have to go through the typical review process. 

Feel free to respond with any questions you may have.

**Pull request closed without merging**
