### PR TITLE
Update soniah/gosnmp

### LINKED ISSUE #7130: SNMP Trap Inform
## Feature Request
As requested in #6918 an additional Feature request to start the discussion on SNMP Inform traps.

In SNMPv2 and SNMPv3 the InformRequest was added, this to send a reply once a SNMP Trap is received. The reply is sent as an acknowledgement of the received trap, to stop traps from being sent.

### Proposal:
Add inform support to SNMP-Traps
http://www.net-snmp.org/tutorial/tutorial-5/commands/snmptrap-v3.html

### Current behavior:
In our capture of traffic we see the traffic arriving but the inform is not presented in the exposed metrics of telegraf,

# Below an SNMP traps without and with inform request:
07:49:44.829779 IP nlrott99-gm5120.testlab.net.43613 > rott99-app2002.snmptrap: C="xxxxxxxx" V2Trap(173) system.sysUpTime.0=9528 S:1.1.4.1.0=E:26866.1.1.11 E:26866.1.2.17="GigaVUE-OS" E:26866.1.2.1=3 E:26866.1.2.2="Fan Status Change" E:26866.1.2.19="1" E:26866.1.2.20=1

# This below inform trap is received but dropped by the collector and no response is sent
07:49:17.911719 IP nlrott99-bs2010.testlab.net.32795 > rott99-app2002.snmptrap: C="xxxxxxx" Inform(57) system.sysUpTime.0=120308 S:1.1.4.1.0=E:15694.2.8.6

### Desired behavior:
SNMP Inform should be accepted and sent a reply message, this to not get overloaded by inform traps. 

### Use case: 
Traps of devices ares now not processed, in addition we want to use SNMPv3 because of security requirements.

### PR DESCRIPTION
**Pull request by danielnelson**
Includes support for INFORM.

closes #7130

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

### CODE REVIEW

**Comment by RemcoAA** [comment]
Hi,

what is the status of this request?

We have tested the INFORM traps with the latest version and I can confirm the traps are being processed by Telegraf, but in the tcpdumps I don't see a reply to the INFORM trap. This is resulting in the device sending the trap multiple times.

**Comment by srebhan** [comment]
@RemcoAA there are multiple tests-cases failing with the change. The problem can be reproduced locally and is not there with v.1.25.0. These test-cases need to be fixed before this can go any further! The failures are:
```
--- FAIL: TestReceiveTrap (18.08s)
    --- FAIL: TestReceiveTrap/v3_coldStart_authShaNoPriv (2.02s)
        snmp_trap_test.go:1312: timed out waiting for trap to be received
    --- FAIL: TestReceiveTrap/v3_coldStart_authShaNoPriv#01 (2.00s)
        snmp_trap_test.go:1312: timed out waiting for trap to be received
    --- FAIL: TestReceiveTrap/v3_coldStart_authMD5NoPriv (2.02s)
        snmp_trap_test.go:1312: timed out waiting for trap to be received
    --- FAIL: TestReceiveTrap/v3_coldStart_authSHAPrivAES (2.02s)
        snmp_trap_test.go:1312: timed out waiting for trap to be received
    --- FAIL: TestReceiveTrap/v3_coldStart_authSHAPrivDES (2.00s)
        snmp_trap_test.go:1312: timed out waiting for trap to be received
    --- FAIL: TestReceiveTrap/v3_coldStart_authSHAPrivAES192 (2.02s)
        snmp_trap_test.go:1312: timed out waiting for trap to be received
    --- FAIL: TestReceiveTrap/v3_coldStart_authSHAPrivAES192C (2.00s)
        snmp_trap_test.go:1312: timed out waiting for trap to be received
    --- FAIL: TestReceiveTrap/v3_coldStart_authSHAPrivAES256 (2.00s)
        snmp_trap_test.go:1312: timed out waiting for trap to be received
    --- FAIL: TestReceiveTrap/v3_coldStart_authSHAPrivAES256C (2.00s)
        snmp_trap_test.go:1312: timed out waiting for trap to be received
```

**Comment by srebhan** [comment]
@RemcoAA do you see a change to pick this up or anyone else?

**Comment by reimda** [comment]
#8588 upgraded the gosnmp library and switched to the new home on github at gosnmp/gosnmp.

**Pull request closed without merging**
