### PR TITLE
init.sh: prevent potential infinite loop

### PR DESCRIPTION
**Pull request by sajoupa**
### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

Hi,

The init.sh file which is used in packages, has a potential infinite loop. This should prevent it.

--
Laurent

### CODE REVIEW

**Comment by danielnelson** [comment]
On side effect of this change is that reload will now fail if it takes more than 30s for Telegraf to shutdown. 
Can you explain the issue that this was causing in more depth?

**Comment by sajoupa** [comment]
No specific issue that I encountered, just thought it'd be safer to make sure that an infinite loop couldn't happen.
I picked 30s because from my experience it's more than enough for telegraf to shutdown, but it could be higher.

**Comment by adrianlzt** [comment]
I don't have any measurements, but I would say that 30s could be not enough.

It could be safer to wait some time, then do a kill -9 and check that it have stopped

**Comment by danielnelson** [comment]
I don't think we should make this change.  The user running the script `invoke-rc.d telegraf stop` can always ctrl-c the script to stop waiting and I think we should leave `kill -9` to the admin since I would hate to kill the process while it is successfully shutting down, losing all the metrics.

**Pull request closed without merging**
