### PR TITLE
fix: customizable cloudwatch batch size when querying aws

### PR DESCRIPTION
**Pull request by powersj**
Fixes: #10842

### CODE REVIEW

**Review by Hipska — COMMENTED** [review]
Why is this approach used rather than just configuring `metric_batch_size` for the plugin?

**Comment by powersj** [comment]
> Why is this approach used rather than just configuring metric_batch_size for the plugin?

This is an input, not an output. This batch size is specific to how the plugin gathers data to avoid a limit in AWS.

**Comment by Hipska** [comment]
Oh, didn’t notice that.

**Comment by reimda** [comment]
Is there a way to determine a good batch size automatically? Maybe we calculate how big a request will be, and ask cloudwatch what the max batch is, then have our code determine how many requests can fit in a batch?

Adding a setting gives the user a way to fix the problem, but requires them to think more than maybe they should have to.

**Comment by powersj** [comment]
> Is there a way to determine a good batch size automatically?

AWS's [GetMetricData](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html) docs reference a limit of 500 metrics in a single request. This explains the currently hard-coded value of 500. Presumably, this is why we have not seen this issue before. 

The error the user received was a 413: `RequestEntityTooLarge: Request size 639468 exceeded 614400 bytes`. The message was 25,068 bytes too large.

I do not see any payload limit on the [CloudWatch service quotes page](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html). I also did not see any other reference to a 413 or too large error in that document or their docs on [common errors](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CommonErrors.html).

In the code, during [Gather](https://github.com/influxdata/telegraf/blob/89b8663c1450d0eefdf9db4e4a0a5d87bda71b9c/plugins/inputs/cloudwatch/cloudwatch.go#L249) we split the queries into batches and then launch goroutines for each batch. It is not clear to me how we could check that we would avoid the 413 error before the goroutines. 

@reimda, thoughts?

**Comment by Hipska** [comment]
I'm wondering if this error actually comes from AWS or some in between proxy?

**Comment by reimda** [comment]
If there's no way to know the byte limit, maybe we should watch for 413 errors and handle them afterward by splitting the batch in half and trying again?

**Comment by reimda** [comment]
Maybe there is a documented api limit, just not a quota limit. The cloudwatch docs are not the easiest to sift through, but I would expect there to be something about this kind of limit there somewhere.

**Comment by powersj** [comment]
I have continued to go through the web docs, as well as [CloudWatch API Reference](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/acw-api.pdf) and [CloudWatch User Guide](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/acw-ug.pdf) with no references to limits.

I have pushed another commit that tries the splitting method, but I think I prefer the user setting over this. The original bug report shows this occurring on every single request. This means the user will always be making 2x the requests. This does seem to be a one-off issue, and having a setting that tunes this makes more sense over something that introduces more complexity that is not easily tested either.

@reimda, that said, I'd like to close this one way or another, so please let me know which way you want to go with this.

**Comment by reimda** [comment]
> I have continued to go through the web docs, as well as [CloudWatch API Reference](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/acw-api.pdf) and [CloudWatch User Guide](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/acw-ug.pdf) with no references to limits.
> 
> I have pushed another commit that tries the splitting method, but I think I prefer the user setting over this. The original bug report shows this occurring on every single request. This means the user will always be making 3x the requests. This does seem to be a one-off issue, and having a setting that tunes this makes more sense over something that introduces more complexity that is not easily tested either.
> 
> @reimda, that said, I'd like to close this one way or another, so please let me know which way you want to go with this.

It looks like there's no way to tune the batch size automatically so a setting is the next best thing. Would it be useful to have both the splitting and a user setting? That way if the setting is too low they will get splitting instead of failures, but if/when they notice the 3x requests they can increase the setting?

It does seem like this is a relatively rare situation. I'm also ok with a setting and no splitting if that's what you prefer.

**Review by Hipska — APPROVED** [review]

**Pull request merged**
