### PR TITLE
Add Graphite line protocol listen, command and tail plugins support...

### PR DESCRIPTION
**Pull request by henrypfhu**
Add three new plugins to support Graphite line protocol:

1. execline input plugin to support shell command which generate graphite line protocol text contents. This plugin will compatible with nagois/sensue shell command plugins which can generate graphite mertics.
2. graphite input service plugin to use TCP or UDP listen port to accept graphite line protocol text inputs. This plugin should be compatible with graphite mertic collectors.
3. tail input service plugin to tail the files to process graphite line protocol texts generated by other graphite metrics generators.

### CODE REVIEW

**Comment by sparrc** [comment]
@henrypfhu you'll need to separate the plugins into separate PRs, and also some general comments:

1. execline graphite parsing should be integrated into the existing `exec` plugin.
1. You should not have the same code in 3 places, break graphite parsing into it's own package, put it somewhere like `internal/encoding/graphite`
1. the "graphite listener" is going to have to wait for now, ideally this would be integrated into #481.
1. In general I would like to standardize the JSON/graphite/line-protocol parsing (there will be other formats coming). If you could start this with an internal graphite encoding package, that would be great. I don't think that graphite needs to have it's own plugins just because it's a different encoding. Instead, I think that "generic" type plugins (such as `exec` and a `udp listen` plugin) can have the option for users to switch between encodings.

**Comment by sofixa** [comment]
If i might weigh in - i too think it would be a good idea to have a "type" or "format" parameter to the generic exec(and why not http) input plugins, which will default to json, but will also allow xml, graphite, nagios and what not.

**Comment by sparrc** [comment]
@sofixa influx line-protocol and json will be supported in 0.10.2, see #617

**Comment by henrypfhu** [comment]
According to @sparrc suggestion, I combined the graphite feature into the exec plugin, and refactor the parser module into internal/encoding directory....

**Pull request closed without merging**
