### PR TITLE
[WIP] Release 0.3.0

### PR DESCRIPTION
**Pull request by sparrc**
TODO

- [x] Support per-plugin tags
- [x] Support measurement prefix/suffix
- [x] Backend support for field name pass/drop
- [x] Refactor system plugin unit tests into separate files
- [x] Remove internal parallelizing in plugins:
    - [x] httpjson
    - [x] exec
    - [x] jolokia
    - [x] postgresql
    - [x] procstat
    - [x] rabbitmq
    - [x] twemproxy
- [x] Rename plugins -> inputs (maybe)

Aggregate plugin measurements:

- [x] All system plugins
- [x] aerospike
- [x] apache
- [x] bcache
- [x] disque
- [x] elasticsearch
- [x] exec
- [x] haproxy
- [x] httpjson
- [x] jolokia
- [x] kafka_consumer
- [x] leofs
- [x] lustre2
- [x] mailchimp
- [x] memcached
- [x] mongodb
- [x] mysql
- [x] nginx
- [x] phpfpm
- [x] ping
- [x] postgresql
- [x] procstat
- [x] prometheus
- [x] puppetagent
- [x] rabbitmq
- [x] redis
- [x] rethinkdb
- [x] statsd
- [x] trig
- [x] twemproxy
- [x] zfs
- [x] zookeeper

Output Compatability (some outputs assume a "value" key in each measurement)

- [x] amon
- [x] amqp
- [x] datadog
- [x] influxdb
- [x] kafka
- [x] kinesis
- [x] librato
- [x] mqtt
- [x] nsq
- [x] opentsdb
- [x] prometheus_client
- [x] riemann

Unit Tests:

- [x] config
- [x] internal
- [x] main
- [x] aerospike
- [x] apache
- [x] bcache
- [x] disque
- [x] elasticsearch
- [x] exec
- [x] haproxy
- [x] httpjson
- [x] jolokia
- [x] kafka_consumer
- [x] leofs
- [x] lustre2
- [x] mailchimp
- [x] memcached
- [x] mongodb
- [x] mysql
- [x] nginx
- [x] phpfpm
- [x] ping
- [x] postgresql
- [x] procstat
- [x] prometheus
- [x] puppetagent
- [x] rabbitmq
- [x] redis
- [x] rethinkdb
- [x] statsd
- [x] system
- [x] trig
- [x] twemproxy
- [x] zfs
- [x] zookeeper

Output unit tests:

- [x] amon
- [x] amqp
- [x] datadog
- [x] influxdb
- [x] kafka
- [x] kinesis
- [x] librato
- [x] mqtt
- [x] nsq
- [x] opentsdb
- [x] prometheus_client
- [x] riemann

### CODE REVIEW

**Comment by titilambert** [comment]
@sparrc 
Just a question: Why are you wondering about : Rename plugins -> inputs (maybe) ?
I just thought that inputs could be "config inputs" like etcd or zookeeper ?

**Comment by sparrc** [comment]
@titilambert because "plugins" is too generic, since there are also "output plugins" now, and probably there will be "aggregator plugins" soon too

**Comment by titilambert** [comment]
@sparrc oh :) this is cool :) what about collectors ?

**Comment by lexmag** [comment]
:+1: for "plugins" –> "inputs" renaming.

**Comment by pauldix** [comment]
omg, so much here. But looks good. +1

**Comment by sparrc** [comment]
closing in favor of #498

**Pull request closed without merging**
