### PR TITLE
Add custom docker image info to nvidia plugin

### LINKED ISSUE #8531: Add a new Telegraf:cuda Docker image to run the Nvidia-smi input plugin
### Proposal:

Running the Nvidia-smi plugin from the Docker Telegraf image.
I propose to add a new build to the list of the officially available Telegraf images based on nvidia/cuda, by specifiying clearly in the README that the Telegraf:cuda Docker image is required to run the Nvidia-smi plugin.

### Current behavior:

Nvidia-smi cannot be executed inside the Docker container as it does not include cuda.

### Desired behavior:

Make it possible to run the Nvidia-smi plugin in Docker.

### PR DESCRIPTION
**Pull request by helenosheaa**
resolves #8531
Add context on how to use nvidia plugin with a custom nvidia/cuda docker image

### CODE REVIEW

**Comment by ssoroka** [comment]
I'm not sure that this is the only method, it's probably possible to use volume mount binding to inject the required binary without rebuilding the docker container.

**Comment by helenosheaa** [comment]
@ssoroka Ok I've added about mount binding as an alternative option in there also with a link to the relevant docker page.

**Review by Jagularr — APPROVED** [review]

**Review by ssoroka — APPROVED** [review]
this is probably correct. bwahaha

**Comment by BlueskyFR** [comment]
May I make my own PR instead of this one with more detailed information?
I would like to add a Dockerfile example instead of a simple note at the end.

**Comment by helenosheaa** [comment]
@BlueskyFR if you have a docker example you can add to the plugin folder we'd be happy to review a PR for it. I think it's also worth keeping this change to the README.

**Pull request merged**
