### PR TITLE
fix(outputs.redistimeseries): Handle string fields correctly

### LINKED ISSUE #14058: Redis Timeseries' TS.ADD only accepts numeric values.
### Relevant telegraf.conf

```toml
[[outputs.redistimeseries]]
  ## The address of the RedisTimeSeries server.
  address = "127.0.0.1:6379"
```

### Logs from Telegraf

```text
ERROR:
 Error writing to outputs.redistimeseries: adding sample failed: ERR TSDB: invalid value
```

### System info

Telegraf 1.27.3 , Docker version 23.0.1,

### Docker

_No response_

### Steps to reproduce

1.telegraf outputs to redistimeseries
2. docker image for redis-stack
docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest
3. example metric .
saTable,agent_host=172.16.30.244,host=localhost.net,index=1,saRowId=1 saError=167968771i,saSerialNumber="0",saVer="49.50",saStatus=0i,saMac="00:0l:d3:01:d7:38", 1696489223000000000
...

### Expected behavior

String and integer should store in redistimeseries.

### Actual behavior

 it seems like Redis Timeseries' TS.ADD only accepts numeric values. In your example metric all fields except saMac can be converted or represented by numeric values. Some by accident like saVer or saSerialNumber which are strings but contain "numeric-like" values.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by srebhan**
- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #14058

Redis Timeseries do only support numeric field values. Currently, we bluntly send the values to Redis irrespective of their type and receive errors on string fields that convert non-numeric characters. This error then aborts the write and in turn to a retry which will only retrigger the error.

This PR adds a `convert_string_fields` option which by default tries to convert string-fields to numeric values succeeding if they e.g. contain `"3.14"` or `"0"` but failing on any non-convertible values like `"3.1.2"` or `"foo"`. In the former case the value is sent to Redis while in the latter (failing) case the field is dropped but sending is continued. This resembles the current behavior as close as possible.
When setting the option to `false` all string fields are dropped and no attempt is made to safe them.

In the course of the PR, we also update the redis client to v9 allowing support for timeseries commands and adding unit tests including a "testcases" framework.

### CODE REVIEW

**Comment by Hipska** [comment]
> This PR adds a `convert_string_fields` option which by default tries to convert string-fields to numeric values succeeding if they e.g. contain `"3.14"` or `"0"` but failing on any non-convertible values like `"3.1.2"` or `"foo"`. In the former case the value is sent to Redis while in the latter (failing) case the field is dropped but sending is continued. This resembles the current behavior as close as possible. When setting the option to `false` all string fields are dropped and no attempt is made to safe them.

Well, that's a great idea. There are some other outputs that also don't support strings which could benefit from this. A lot of them are just simply dropping any string, regardless of it's value.

**Comment by srebhan** [comment]
@Hipska feel free to reuse the code!

**Comment by Hipska** [comment]
Maybe I should list these on a new Issue?


- https://github.com/influxdata/telegraf/blob/0c1e21398e08a82e8ab53b49d2c226f04b517c12/plugins/serializers/graphite/graphite.go#L157-L158
- https://github.com/influxdata/telegraf/blob/0c1e21398e08a82e8ab53b49d2c226f04b517c12/plugins/serializers/prometheus/convert.go#L158-L159
- https://github.com/influxdata/telegraf/blob/0c1e21398e08a82e8ab53b49d2c226f04b517c12/plugins/serializers/wavefront/wavefront.go#L126-L128
- https://github.com/influxdata/telegraf/blob/0c1e21398e08a82e8ab53b49d2c226f04b517c12/plugins/serializers/splunkmetric/splunkmetric.go#L193-L195
- https://github.com/influxdata/telegraf/blob/0c1e21398e08a82e8ab53b49d2c226f04b517c12/plugins/serializers/carbon2/carbon2.go#L71-L73
- https://github.com/influxdata/telegraf/blob/0c1e21398e08a82e8ab53b49d2c226f04b517c12/plugins/outputs/groundwork/groundwork.go#L285-L288
- https://github.com/influxdata/telegraf/blob/0c1e21398e08a82e8ab53b49d2c226f04b517c12/plugins/outputs/datadog/datadog.go#L213-L214

And probably many more..

**Review by powersj — APPROVED** [review]
I am a little concerned about the additional logging during field handling. This might reveal some new "issues" to end-users that are rather verbose. However, this handling is the correct change.

**Comment by powersj** [comment]
I've rebased on master to resolve the conflicts

**Pull request merged**
