### PR TITLE
Khurramcheema/new jenkins plugin 1

### PR DESCRIPTION
**Pull request by khurramcheema**
# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

### CODE REVIEW

**Review by amarkotasky — APPROVED** [review]
LGTM

**Review by powersj — CHANGES_REQUESTED** [review]
Hi,

Need to ask you to do a few things:

1) please file an issue descrbriing why you want to add a new plugin
2) ensure all tests pass, looks like you will need to add the new github.com/bndr/gojenkins to the list of dependencies
3) remove the cloudwatch changes from this PR or create a second PR for those

Once those are done we can give this a review.

Thanks

**Comment by srebhan** [comment]
@khurramcheema let me add, please also argument why you need another plugin instead of adding your feature to `inputs.jenkins`.

**Review by amarkotasky — APPROVED** [review]
LGTM

**Comment by srebhan** [comment]
!signed-cla

**Comment by srebhan** [comment]
@khurramcheema closing this PR for now. Please address the comments by @powersj and myself and feel free to reopen afterwards.

**Pull request closed without merging**
