### PR TITLE
Enhance the documentation with telegraf process run as root 

### PR DESCRIPTION
**Pull request by djsly**
This is needed for specific procstat metrics

### Required for all PRs:

- [ ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] README.md updated (if adding a new plugin)

### CODE REVIEW

**Comment by danielnelson** [comment]
I think it is possible to get the field without root, I mentioned it recently on #517.  However, I couldn't figure out how to get it working, can you take a look?

**Comment by djsly** [comment]
Should we document for now the limitation on those two specific fields until a better solution is found to avoid people from debugging to come to the same conclusion (thats what occured to me here :) )? 

Unfortunately, I don't have time right now to look at the PTrace solution; but I could spend time eventually to dig more.

**Comment by danielnelson** [comment]
I'd like to document the limitation, but I'm somewhat unsure of suggesting running as root.

**Comment by djsly** [comment]
yeah makes sense.. I tried playing around with user access before but couldn't get around it in the amount of time I spent. 

the *io* and *memory* files access is set to 600 so I wasn't sure what more could be done.

**Comment by danielnelson** [comment]
Lets go with this for now.

**Comment by djsly** [comment]
Thanks Daniel, FYI, I tried over two weekend ago to play around with user
access and the PTRACE bit and what not.. I couldnt get it to work :(

**Pull request merged**
