### PR TITLE
WIP: enable global and user queries in dovecot plugin

### PR DESCRIPTION
**Pull request by mrannanj**
This adds support for global and user queries on the dovecot plugin. It breaks the configuration format.

This is WIP so posted in hopes of comments on the approach.

### CODE REVIEW

**Comment by mikif70** [comment]
a new possible configuration:

  servers = ["localhost:24242"]
  level = domain || user || ip

  if domain
    filter = [] ## array of domains, could be a regex

 if ip
   filter = [] ## array of IP/network

  if ip
    filter = [] ## array of users, could be a regex

the parameter filter should be mandatory

**Comment by mrannanj** [comment]
We want to support getting global stats too, so filter isn't always needed.

**Comment by mikif70** [comment]
yes, I forgotten the global level ;-)

**Comment by mrannanj** [comment]
But are you suggesting that we leave out filtering in the Telegraf plugin, so that filtering is done only on Dovecot's side? I don't mind.

**Comment by mikif70** [comment]
Yes, I think is better to receive only the necessary data from the network; at most you could done more queries.

**Comment by mrannanj** [comment]
Ah, more queries could be an option as well.

**Comment by mrannanj** [comment]
Never done go development before, so not sure how to run the CI checks locally. I think I added the support for multiple queries, but not tested well.

**Comment by sparrc** [comment]
@mrannanj you should be able to run `go test ./plugins/inputs/dovecot/...` from the root directory of the repo, looks like some of those unit tests are failing

**Pull request closed without merging**
