### PR TITLE
elasticsearch output: test to show a bug handling NaN

### PR DESCRIPTION
**Pull request by adrianlzt**
Elasticsearch output is not able to handle "NaN" values, which are valid
values (at least generated by inputs prometheus)

This new test shows how output breaks if it receives a NaN value.

NaN values are valid, at least contemplated in the [prometheus tests](https://github.com/influxdata/telegraf/blob/c66ccee46f47717c399ccc0348d17c95d11f477d/plugins/inputs/prometheus/prometheus_test.go#L190).

I don't provide a fix because I am not sure how this wants to be handled.

### CODE REVIEW

**Comment by adrianlzt** [comment]
json serializer [ignores](https://github.com/influxdata/telegraf/blob/master/plugins/serializers/json/json.go#L65) math.NaN and Inf and values.
```
			// JSON does not support these special values
			if math.IsNaN(fv) || math.IsInf(fv, 0) {
```

**Comment by adrianlzt** [comment]
Workaround, drop NaN values.
```
[[processors.starlark]]
  source = '''
load("logging.star", "log")

def apply(metric):
    for k, v in metric.fields.items():
        if type(v) == "float" and str(v) == "NaN":
            metric.fields.pop(k)
            log.warn("Dropped NaN value: metric {} field {}".format(metric.name, k))

    return metric
'''
```

**Comment by adrianlzt** [comment]
Test are passing because test avoided in the ``short`` mode.

The result of the test:
```
➜ go test -v -run TestConnectAndWriteMetricWithNaNValue
=== RUN   TestConnectAndWriteMetricWithNaNValue
2021/04/29 20:11:09 I! Elasticsearch version: 7.1.1
2021/04/29 20:11:09 D! Elasticsearch template telegraf created or updated
    elasticsearch_test.go:67: 
                Error Trace:    elasticsearch_test.go:67
                Error:          Received unexpected error:
                                Error sending bulk request to Elasticsearch: json: unsupported value: NaN
                Test:           TestConnectAndWriteMetricWithNaNValue
--- FAIL: TestConnectAndWriteMetricWithNaNValue (0.13s)
FAIL
exit status 1
FAIL    github.com/influxdata/telegraf/plugins/outputs/elasticsearch    0.133s
```

**Comment by adrianlzt** [comment]
I don't have a fix, sorry

**Comment by srebhan** [comment]
@adrianlzt can you please check if #10196 fixes your issue!?

**Comment by srebhan** [comment]
Ok bugfix is in. Closing this PR... Thanks for your contribution @adrianlzt!

**Pull request closed without merging**
