### PR TITLE
chore(deps): Bump golangci-lint from v1.62.0 to v1.62.2

### PR DESCRIPTION
**Pull request by zak-pawel**
## Summary

- `golangci-lint` bumped to `v1.62.2`
- `revive:max-public-structs` reenabled (following issue has been fixed and released in `revive` and `golangci-lint`: https://github.com/mgechev/revive/issues/1103

- New findings addressed:
```
internal/content_coding.go:1:1                  revive  max-public-structs: you have exceeded the maximum number (5) of public struct declarations
metric.go:1:1                                   revive  max-public-structs: you have exceeded the maximum number (5) of public struct declarations
plugins/common/jolokia2/client.go:1:1           revive  max-public-structs: you have exceeded the maximum number (5) of public struct declarations
plugins/common/opcua/input/input_client.go:1:1  revive  max-public-structs: you have exceeded the maximum number (5) of public struct declarations
```

## Checklist

- [x] No AI generated code was used in this PR

### CODE REVIEW

**Review by srebhan — CHANGES_REQUESTED** [review]
I don't think we should unexport the concrete encoders/decoders! They are helpful if you _know_ the encoding!

**Comment by zak-pawel** [comment]
> I don't think we should unexport the concrete encoders/decoders! They are helpful if you _know_ the encoding!

@srebhan
All these encoders/decoders are available by using `NewStreamContentDecoder`, `NewContentEncoder`, `NewContentDecoder`.

**Comment by srebhan** [comment]
Yes but if I **know** I want the gzip decoder, why should I need to do the indirection? I don't see any value in this! Furthermore, the PR is about bumping the linter and you are changing code which is not related to the bump. So please leave the encoding as is.

**Comment by zak-pawel** [comment]
> So please leave the encoding as is.

@srebhan Changed.

**Review by srebhan — COMMENTED** [review]
Can we please move the change of the encoding/decoding things to a separate PR!? The title does not suggest those changes...

**Comment by zak-pawel** [comment]
> The title does not suggest those changes...

@srebhan 
But the PR description definitely suggests it 😎 Just in case, it's about addressing new findings for
```
internal/content_coding.go:1:1                  revive  max-public-structs: you have exceeded the maximum number (5) of public struct declarations
```

Usually, what we did was that if the bumped `golangci-lint` started detecting new findings, we fixed them in the same PR. Clean and tidy.

Here are excellent examples:

- https://github.com/influxdata/telegraf/pull/13838
- https://github.com/influxdata/telegraf/pull/15473

**Comment by srebhan** [comment]
@zak-pawel I'm a bit puzzled. We agreed on limiting the export stuff to the plugin directories only. So why does it warn for something in `internal` now? And why didn't it previously?

**Comment by zak-pawel** [comment]
> @zak-pawel I'm a bit puzzled. We agreed on limiting the export stuff to the plugin directories only.

@srebhan Yes! You're right, I totally forgot about that.

> So why does it warn for something in `internal` now? And why didn't it previously?

Because the message format that we have excluded so far has been changed from `you have exceeded the maximum number of public struct declarations` to `you have exceeded the maximum number (5) of public struct declarations`. I corrected our filter.

**Review by srebhan — APPROVED** [review]
Thanks @zak-pawel!

**Review by DStrand1 — APPROVED** [review]

**Pull request merged**
