### PR TITLE
SQL Server plugin: add availabity group feature

### PR DESCRIPTION
**Pull request by mikedavem**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

Issue #6834

### CODE REVIEW

**Comment by danielnelson** [comment]
@denzilribeiro Can you review?

**Comment by mikedavem** [comment]
> @denzilribeiro Can you review?

Hi @denzilribeiro  / @danielnelson 

Did you get a chance to review it ? :)

Regards

**Comment by denzilribeiro** [comment]
Sorry for the delay  - some of these DMV's are only in SQL 14 later ( which is fine ) but you may be better off doing a version check given am not sure if telegraf being used against older versions. For example sys.dm_hadr_cluster. Also should exclude collecting if it Azure versions as it won't be relevant and all the SQL Server queries are still run. Same with the other HADR DMV's..

**Comment by mikedavem** [comment]
@denzilribeiro 

Thanks for considering my PR :) Yes, it does make sense to check the version in this case so I added it to the AG queries. I just committed the new changes. If I'm not wrong after checking on documentation, all AG DMVs used here are available since SQL 12.

**Comment by mikedavem** [comment]
@denzilribeiro . Do you think we can consider this PR in a future version? :) Many thanks for your feedback

**Comment by denzilribeiro** [comment]
@mikedavem  I looked at some of this briefly
- Why would you need things like log send queue size etc  - Aka they are already being collected in the perfmon collector so why collect them again?

https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/monitor-performance-for-always-on-availability-groups?view=sql-server-ver15

Also I am still not seeing a check for SERVERPROPERTY('EngineEdition') to exclude Azure.
The other concern I have is some of the information being collected is really AG config and State config. If the idea is to put alerts on say a status change of AG, Telegraf is not a right place, alerts should happen on a state change/error, not via a polling mechanism every n seconds which is what the telegraf collector is.

What is end goal of this The config collection - How would you use this info?

**Comment by mikedavem** [comment]
@denzilribeiro 

Thanks for the feedback and I can fix different issues accordingly. 

**Why would you need things like log send queue size etc - Aka they are already being collected in the perfmon collector so why collect them again?**

You're right and it is a duplicate from existing counters in Telegraf. I can fix it.

**Also I am still not seeing a check for SERVERPROPERTY('EngineEdition') to exclude Azure.**

I can fix it as well. Thanks

**What is end goal of this The config collection - How would you use this info?**

My intention is not to trigger alerts for AG state changes. There is already another place for it in my case :). In fact, I would like to get the same kind of information as we can have with sqlServerPropertiesV2 as the SQL instance version, edition, environment type (physical, virtual etc ...), last restart time, nb of databases and their states (online, in recovery etc ...).

With existing metrics and "state information" provided by sqlServerPropertiesV2, we already created this kind of dashboard (summary dashboard for all environments and detailed dashboard per instance)

image

Currently there exists metrics for AGs we already extract and consume through our dashboards like but there is no real information about underlying AG infrastructure like nb of replicas (and corresponding states),  nb of AG (and corresponding states), nb of high available DBs (and corresponding states), which instance is primary or secondary which may be useful to have for extend our system observability. 

Probably I may rewrite the queries to fit better with the telegraf "mindset" like you did with sqlServerPropertiesV2 ? Let me know what do you think about it?

**Comment by denzilribeiro** [comment]
@mikedavem  my apologies never got back to this slipped through the cracks. There have been many changes done, can you check https://github.com/influxdata/telegraf/pull/8379 and see if it addresses your needs too?

**Comment by mikedavem** [comment]
No worries @danielnelson . 
I just made a proposal to add info of the top-level AG state in the replica level query.
Of course we can define / compute the state of the AG itself with sub-level states (AG replicas or AG databases) but having directly the info could make the life easier with dash boarding stuff. 
Anyway, I'm glad to see queries from #8379 including to a next release of this plugin :)

**Comment by sjwang90** [comment]
Should we close this now that #8379 is merged or is there additional information in this PR?

**Comment by srebhan** [comment]
@mikedavem any answer to @sjwang90's question? Can we close this PR?

**Comment by dba-leshop** [comment]
That's ok for me. We can lose this PR

**Pull request closed without merging**
