### PR TITLE
input plugin for collect meminfo data

### PR DESCRIPTION
**Pull request by shrug42**
### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

### CODE REVIEW

**Comment by danielnelson** [comment]
The mem plugin already reads /proc/meminfo, but doesn't current return all the fields.  Could you open an issue on gopsutil to see if they would accept a pull request parsing the extra fields in `mem.VirtualMemory()`?  We could then hook up the extra fields in the mem plugin.

https://github.com/shirou/gopsutil/blob/master/mem/mem_linux.go#L18

**Comment by shrug42** [comment]
Sure, let me try a PR on their side.

**Comment by shrug42** [comment]
I will follow up with them (https://github.com/shirou/gopsutil/issues/539)
I will give you another PR if it succeeds.

**Comment by danielnelson** [comment]
@shrug42 I see your PR to gopsutil went through, are you still working on this plugin?

**Comment by shrug42** [comment]
Sorry, I was waiting for the gosputil realese to come through to upgrade the version in telegraf.
And I got busy.
will resume this.

**Comment by shrug42** [comment]
I will close this PR in favor of https://github.com/influxdata/telegraf/pull/4546

**Pull request closed without merging**
