### PR TITLE
docs(inputs.memcached): Correct typo in README.md

### PR DESCRIPTION
**Pull request by tolsadus**
## Summary
 There's a typo in the documentation that I've reading for days

## Checklist

- [X] No AI generated code was used in this PR

### CODE REVIEW

**Comment by tolsadus** [comment]
!signed-cla

**Comment by srebhan** [comment]
!signed-cla

**Comment by srebhan** [comment]
@tolsadus would love to include this PR, can you please sign the CLA!?!?!?

**Comment by tolsadus** [comment]
!signed-cla

**Review by powersj — APPROVED** [review]

**Review by srebhan — APPROVED** [review]
Thanks for the fix @tolsadus!

**Pull request merged**
