### PR TITLE
fix(parsers.csv): don't change configured csv_skip_rows & csv_header_row_count between gathers

### PR DESCRIPTION
**Pull request by sspaink**
resolve: https://github.com/influxdata/telegraf/issues/10366

The configured value `csv_header_row_count` & `csv_skip_rows` were being de-incremented between gathers, so while it worked the first time calling gather again would cause errors trying to convert the string headers into types. Also added a test similar to the one found in the json_v2 parser to confirm this fixes it. We can add more csv testdata in the future.

### CODE REVIEW

**Review by powersj — APPROVED** [review]
Thank you!

**Comment by sspaink** [comment]
Marking this as a draft because evidently more tests depended on this bad behavior then I thought that I need to work through.

**Comment by srebhan** [comment]
NO NO NO NO NO! :-) This code is there by intention!

Imagine you read a CSV file in a line-wise fashion with `SkipRowCount > 0` e.g. `SkipRowCount = 5`). For each line you call `Parse()` or `ParseLine()`.
With the current code, the first 5 rows are consumed by the parser _without_ any further processing as (the stateful) `SkipRowCount` is `5..4..3..2..1`. Now in the 6th row the usual processing will take place as the necessary number of rows were skipped.
With your new code the `skipRowCount` will _always_ be 5 for _each_ of your calls to `Parse()`, so you will _never_ reach the code that will actually parse the data as it thinks we still need to skip some more rows.

That's the issue of CSV being a stateful parser. Now we could declare a new class of stateful parsers having a `Reset()` function, but no matter what you do, the parser needs to be _stateful_ for each input (e.g. each file) and thus you cannot reuse that parser between the inputs.

**Comment by sspaink** [comment]
haha Well thank goodness there were tests to stop me from making the change, although according to the issue https://github.com/influxdata/telegraf/issues/10366 it seems the parser was able to be re-used with the http and file plugins in v1.20.4 so it seems there is a regression? Having a separate stateful parser does make sense, because it seems the parser needs to support both somehow.

**Comment by srebhan** [comment]
Yeah the problem was that 1.20.4 was not stateful but did not work when reading files linewise.. ;-D So you can decide which use-case to break. :-) Jokes aside. The best thing would be to use `ParserFunc` to be called everytime you want to drop the state as it constructs a new parser. *OR* we add the concept of a `StatefulParser` which is
```golang
type StatefulParser interface {
    Clone() telegraf.StatefulParser
    Reset()
}
```
To make the plugin aware of stateful parsing. In your case you will want to call `Reset()` when reading the file the second time. In the linewise-reading case you want to skip the `Reset()` and call `Clone()` (or `Copy()`) for each input data...

I think currently it's only `csv` suffering from being stateful though...

**Comment by sspaink** [comment]
Closing this because it isn't the right solution.

**Pull request closed without merging**
