### PR TITLE
Added support for gosensors plugin

### PR DESCRIPTION
**Pull request by md14454**
This change addresses #168 

The implementation is very basic and intended to be worked upon. I am open to feedback as to the best approach for field names and tags. For now this is a working example.

### CODE REVIEW

**Comment by sparrc** [comment]
Awesome, thanks for adding this, is there any possibility of a unit test? I know this is a fairly special case, so it's OK if the answer is "no"

**Comment by sparrc** [comment]
please also add this to the README.md and CHANGELOG.md files

**Comment by sparrc** [comment]
please add `// +build linux` at the top of this file, and any other OS that is supported

**Comment by md14454** [comment]
I've edited the README and CHANGELOG. I also changed the build to only Linux.

I'm not sure how I would add a unit test, but I'll certainly look into it.

I'm not sure if it may be worth adding that the sensors command has to be run by root from the cli first. Also, do you have a preference on how the field names should be displayed?

**Comment by lGuillaume124** [comment]
Hi,
I'm using Telegraf on Ubuntu and I just upgraded to 0.10.3 (from the official repo) to use this input, but it doesn't seem to be available. Am I doing something wrong?

```sh
$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +37.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:         +34.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:         +34.0°C  (high = +100.0°C, crit = +100.0°C)
```

```sh
$ tail -n 3 telegraf.d/inputs_system.conf
# Read metrics about sensors
[[inputs.sensors]]
  sensors = [ "coretemp-isa-0000" ]
```

```sh
$ telegraf -test -config telegraf.conf -config-directory telegraf.d -filter sensors
2016/02/20 15:20:03 Undefined but requested input: sensors
```
Thanks for your help.

**Comment by md14454** [comment]
@lGuillaume124 
Hi,

Try changing
`"coretemp-isa-0000"`
to
`"coretemp-isa-0000:*"`

or, if you would like to just log all sensors then you don't need
`sensors = [`
at all and you can comment it out, or delete it.

Hope that helps.

**Comment by sparrc** [comment]
@lGuillaume124 

sensors is currently only available if you're building from source, I'll update the readme to indicate that

**Comment by penguinpowernz** [comment]
> sensors is currently only available if you're building from source

@sparrc why is this? Is there a guide somewhere on how to enable this when you are building from source?

**Comment by sparrc** [comment]
this plugin has extensive libsensors dependencies, and I haven't found a way to compile this plugin into telegraf as an optional dependency.

You could also just use the `ipmi_sensor` plugin, which also queries libsensors, but as a separate package.

**Comment by penguinpowernz** [comment]
So does that mean you just need to make sure you install lm_sensors etc before compiling?

**Comment by sparrc** [comment]
you need to do something like `-tags sensors`

**Comment by penguinpowernz** [comment]
thanks :)

**Pull request closed without merging**
