### PR TITLE
fix(inputs.sqlserver): set lower deadlock priority

### LINKED ISSUE #10908: telegraf for windows - [inputs.sqlserver] Set deadlock priority to LOW
Hello,
I use telegraf 1.22.0 for windows.
I have few deadlock.

When I trace telegraf's queries, I see  all queries dont use SET DEADLOCK_PRIORITY -10
Only queries SQLServerPerformanceCounters and SQLServerDatabaseIO do "SET DEADLOCK_PRIORITY -10"

Personnally, iI use queries SQLServerRequests, SQLServerVolumeSpace, SQLServerCpu, SQLServerProperties, SQLServerMemoryClerks and it make deadlocks.

### PR DESCRIPTION
**Pull request by buffalovagabond**
resolves #10908

### CODE REVIEW

**Comment by MyaLongmire** [comment]
@buffalovagabond Thank you for this pr!

It seems the `test-go-linux` test is failing. Can you please run `make docs` and then push the updated README?

**Comment by buffalovagabond** [comment]
@powersj I just rebased my branch on master.
Thanks for fixing the docs.

**Review by MyaLongmire — APPROVED** [review]
Thank you for this fix!

**Comment by a-venger** [comment]
@MyaLongmire @powersj 
Hi
Sorry for bothering you.

Any reason why this was done for V2 queries but not for the newer one database_type = "SQLServer"?

**Comment by a-venger** [comment]
> > Any reason why this was done for V2 queries but not for the newer one database_type = "SQLServer"?
> 
> Happy to see a PR for the queries in sqlserverqueries.go as well.

https://github.com/influxdata/telegraf/pull/11549

**Pull request merged**
