### PR TITLE
docs: Typo

### PR DESCRIPTION
**Pull request by dg-nvm**
# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

### CODE REVIEW

**Comment by dg-nvm** [comment]
I hereby grant you InfluxData a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute this contribution and such derivative works.

**Comment by srebhan** [comment]
@dg-nvm you need to sign the [CLA](https://www.influxdata.com/legal/cla/) your text in the PR will not suffice I fear. As soon as you signed it, please let me know!

**Review by srebhan — APPROVED** [review]
Looks good to me. Waiting for the CLA for further steps...

**Comment by dg-nvm** [comment]
@srebhan that's not gonna happen, sorry :)

**Comment by srebhan** [comment]
Well IANAL, but the CLA only covers your contributions...

**Pull request closed without merging**
